wandb/wandb

.gitignore, README.md, docs/index.md, docs/usage.md, setup.cfg, setup.py, tests/api_mocks.py, tests/test_api.py, tests/test_cli.py, tests/test_config.py, wandb/__init__.py, wandb/api.py, wandb/cli.py, wandb/config.py, wandb/sync.py
So much code @shawnlewis @lukas
=> First pass on config

docs/index.md, docs/usage.md, tests/api_mocks.py, tests/test_api.py, tests/test_cli.py, tests/test_sync.py, wandb/__init__.py, wandb/api.py, wandb/cli.py, wandb/results.py, wandb/sync.py
@shawnlewis lot's of cleanup.  A few comments inline for the interesting ones.
=> bucket => run, remove file commands, no more pipe :(

.vscode/settings.json, tests/test_api.py, tests/test_sync.py, wandb/__init__.py, wandb/api.py, wandb/cli.py, wandb/history.py, wandb/run.py, wandb/sync.py, wandb/util.py
- wandb.sync automatically creates wandb/run-<run_id>
- by default we sync any files that go into that directory
- wandb.sync returns a Run object that has:
.dir: path to the run directory
.config: wandb Config for this run
.history: wandb History for this run
.summary: wandb Summary for this run
=> Create run dir, wandb.sync returns Run object.

wandb/__init__.py, wandb/api.py, wandb/cli.py
Reverts wandb/client#92. Oops. I didn't mean to merge that into master.
=> Revert "Added some grid search code."

setup.py, wandb/jsonlfile.py, wandb/stats.py, wandb/sync.py, wandb/wandb_run.py
@shawnlewis, @adrianbg figured you guys should do a quick pass on this code.  I'm hoping to push this before the openai meeting.
=> Added stats reporter thread

wandb/__init__.py, wandb/board/app/graphql/schema.py, wandb/board/app/models/files.py, wandb/board/ui/src/components/RunFeed.js, wandb/board/ui/src/components/vis/LinePlot.js, wandb/board/ui/src/containers/Runs.js, wandb/cli.py, wandb/git_repo.py, wandb/meta.py, wandb/run_manager.py, wandb/stats.py, wandb/summary.py, wandb/wandb_run.py
=> Initial work for metadata hotness

.wandb.sample, pytest.ini, requirements_dev.txt, tests/fixtures/train.py, tests/test_cli.py, tests/test_run_modes.py, tests/utils.py, wandb/__init__.py, wandb/api.py, wandb/board/app/graphql/schema.py, wandb/board/app/models/files.py, wandb/board/ui/src/components/RunViewer.js, wandb/internal_cli.py, wandb/keras.py, wandb/run_manager.py, wandb/wandb_run.py
@shawnlewis @adrianbg let me know what you think of the changes.  The socket stuff is a little hairy...
* Adds process communication through a socket in headless mode.  
* Copied `WandbKerasCallback` to `wandb.keras.Callback`
* Added `wandb.init(config={})`
* Fixed exitcodes
* Better errors / logs
=> Socket communication for headless and many other goodies

wandb/board/ui/src/components/RunSummary.js
Making the upper navigation look less weird
Before:
After:
=> Fixing weird git link issue #140

setup.cfg, setup.py, tests/test_summary.py, wandb/__init__.py, wandb/api.py, wandb/board/app/models/files.py, wandb/history.py, wandb/run_manager.py, wandb/summary.py, wandb/wandb_run.py
@lukas, can you try checking out this branch and doing a run or two?  
@shawnlewis @adrianbg low hanging performance fruit
=> Throttle log updates, summary hits upsert, handle media types

wandb/keras/__init__.py
=> Better handing of val data

wandb/keras/__init__.py
Since TF includes Keras, there's no need to install it as a separate package.
=> Support Keras via TensorFlow

.circleci/config.yml
Lol, we actually want this. It's partial cache restore: https://circleci.com/docs/2.0/caching/#restoring-cache
=> Revert "remove double cache keys in circleCI config"

.circleci/config.yml, requirements_dev.txt, tests/test_data_types.py, wandb/__init__.py, wandb/data_types.py
Client support for audio files!
To upload a file, you can do wandb.Audio(np_array, sample_rate=sample_rate, caption=caption).  
Or I can send you a test script if you want.
=> wandb.Audio

tests/api_mocks.py, tests/test_internal_api.py, tests/test_public_api.py, wandb/apis/public.py
BAM, now you can call `run.files` or `run.file("name")` and download it with `.download()`
=> New file api

tests/test_torch.py, wandb/wandb_torch.py
=> Fixes a case Adrian found where a tensor is frozen

CHANGELOG.md, tests/api_mocks.py, tests/conftest.py, tests/test_run_manager.py, tests/test_wandb.py, wandb/__init__.py, wandb/apis/internal.py, wandb/env.py, wandb/history.py, wandb/keras/__init__.py, wandb/run_manager.py, wandb/wandb_run.py
Fixes steps not being restored on resume, adds a test, and new wandb.init logic.
=> Add new resume functionality, fix old step logic

wandb/agent.py
This adds an `exit` command to the sweep agent. This will allow the server to tell agents to exit when a sweep has finished or been cancelled.
=> agent: add exit command

.circleci/config.yml, install-ml.py, tests/api_mocks.py, tests/conftest.py, tests/test_run_manager.py, tests/test_wandb.py, wandb/__init__.py, wandb/data_types.py, wandb/history.py, wandb/jupyter.py, wandb/run_manager.py, wandb/tensorboard/__init__.py, wandb/wandb_run.py
I still need to fix a couple tests but this fixes Jupyter.  @adrianbg I found a couple bugs in FileTailer, comments inline.  My approach for fixing resuming is questionable but I didn't have any better ideas.  Suggestions welcome.
=> Lots and lots of gnarley fixes / hacktown

wandb/agent.py, wandb/env.py, wandb/util.py
Addresses these issues: 
https://github.com/wandb/core/issues/1207
https://github.com/wandb/core/issues/1246
=> Add agent env vars for SIGKILL and report interval

CHANGELOG.md, tests/api_mocks.py, tests/test_public_api.py, wandb/apis/internal.py, wandb/apis/public.py
This addresses the public API opening too many connections and not retrying.
=> Fixes for retrying

wandb/wandb_torch.py
regression which demonstrates fix:
https://app.wandb.ai/jeffr/regression/groups/20190509-0.7.3-fix_pytorch-histo-0.4-7e0dcedd-wr23vz?workspace=user-jeffr
=> Detect when histc isnt available for cuda tensors more broadly

tests/test_config.py, wandb/wandb_config.py
for https://github.com/wandb/core/issues/1763
=> Automatically record the W&B version in Config

wandb/apis/public.py, wandb/summary.py
For https://github.com/wandb/core/issues/2212.
Also fix lots of instances of Run.name that should have been Run.id because I renamed it.
=> HTTPSummary: always commit in .update()

setup.py
=> remove explicit pyyaml dependancy as it is causing some users issues

CHANGELOG.md, tests/test_history.py, wandb/cli.py, wandb/data_types.py, wandb/util.py
We were converting numpy arrays in nested json to wandb histograms.
=> This casts all np.arrays in plotly json to lists 

wandb/util.py
Fix not including it in the list of synced files at the end of a run.
=> diff.patch is a W&B file

wandb/__init__.py, wandb/apis/internal.py, wandb/internal_cli.py, wandb/run_manager.py
Creates a polling thread in run_manager that checks for a requested stop. Also creates a method in apis/internal.py to check for said stop.
=> Add corresponding stop button functionality to CLI.

requirements_dev.txt, tests/test_xgboost.py, wandb/__init__.py, wandb/xgboost/__init__.py
This is a super simple callback that makes it easy to track xgboost models.
=> Initial xgboost callback

wandb/dataframes.py
the mnist example uses number labels, which we want to support. This PR uses string formatting to handle strings or number labels. (`str` + `int` throws a `TypeError` in python)
=> Support numeric labels

wandb/cli.py
Missed a path when protecting anoymode behind an environment variable.
The path was:
wandb login
control-c
prompt for anonymode
=> make sure we dont prompt for anonymode if not enabled

.gitignore, conftest.py, tests/test_run_manager.py, wandb/file_pusher.py
Bundles up files less than 1MB into one tar file every 15 seconds.
Paired with https://github.com/wandb/core/pull/2494 on the server.
=> Batch uploading in the client

tests/test_summary.py, wandb/__init__.py, wandb/run_manager.py, wandb/summary.py, wandb/wandb_config.py, wandb/wandb_run.py
=> Start jupyter agent for config and summary

wandb/wandb_controller.py
=> fix issue where sweeps are broken with py27

conftest.py, tests/test_run_manager.py, tests/utils.py, wandb/apis/internal.py, wandb/run_manager.py, wandb/wandb_run.py
This is for our spell partnership, hits their internal api and associates a spell url to our run when we see SPELL_RUN_URL in the environment.
=> Added spell support

wandb/magic_impl.py
=> always look for both keras and tfkeras

edgeml_tests/test_tensorflow2.py, wandb/data_types.py
The frontend needs to know the format to use for sprites.
=> Add image format

wandb/apis/internal.py, wandb/wandb_config.py
=> Actually persist spell config

.vscode/settings.json, wandb/tensorflow/__init__.py
Use tf.estimator.SessionRunHook in tf>=1.14, and tf.train.SessionRunHook otherwise.
=> Fix WandbHook in tf2

wandb/__init__.py
=> Fix async log thread cleanup

wandb/summary.py
**This change is untested. I believe it's close to finished but you should make sure.**
Because of its lazy loading, HTTPSummary previously only showed items in
repr(), that had already been accessed by the user. This change makes it
always use the set of keys in the underlying JSON dict. It uses the
placeholder '...' for h5 objects that haven't been loaded yet because
they may be extremely large.
https://github.com/wandb/core/issues/2705
=> Fix repr(), .keys(), and .items() for HTTPSummary

wandb/__init__.py
WB-1112 #close #comment fix restore when calling twice
=> fix restore issue

wandb/__init__.py
=> fix restore path

wandb/apis/public.py
WB-1167 # close # comment "filter internal keys"
=> remove internal keys from public run.config

wandb/data_types.py, wandb/history.py
Was seeing a race where the underlying dict changed.  This copies the dict and creates a new object during creation.
=> Fixed change size error

wandb/streaming_log.py
Fixing for HuggingFace transformers. Their progress bars currently look like this in the web app:
```
Iteration:   0%|                                                                                                                   | 0/115 [00:00<?, ?it/s]
Iteration:   1%|▉                                                                                                          | 1/115 [00:02<04:11,  2.21s/it]
Iteration:   2%|█▊                                                                                                         | 2/115 [00:04<03:56,  2.09s/it]
Iteration:   3%|██▊                                                                                                        | 3/115 [00:05<03:45,  2.01s/it]
Iteration:   3%|███▋ …
```
=> Fix TQDM progress bars

wandb/tensorboard/watcher.py
=> fix tensorboard import issue

wandb/apis/internal.py, wandb/cli.py, wandb/util.py, wandb/wandb_agent.py, wandb/wandb_run.py
wandb agent
wandb sweep
- will now handle entities and projects more consistently with the rest of the product
- will prompt for login if not logged in already
Requires gorilla push for full functionality but will not break with old gorilla:
https://github.com/wandb/core/pull/3735
=> Clean up wandb sweep and wandb agent commands

wandb/lightgbm/__init__.py
Made 2 tiny fixes as per the comments on this [PR](https://github.com/wandb/client/pull/718).
- Removed print statement
- Added clarifying comment
=> Made a tiny fix to the LightGBM PR

wandb/tensorflow/__init__.py
=> Fix summary iterator import for TF 2 compatibility

wandb/apis/public.py
Was accidentally removed as part of #720
=> public: add back historyKeys field to run query

wandb/__init__.py
=> Add attribute error to io mirroring

wandb/wandb_controller.py
WB-1534 #comment Fix local controller regression
=> Fix local controller regression not handling pending state

wandb/wandb_agent.py
bools are ints in python, awesome.
=> python agent was always flapping

.circleci/config.yml, docs/markdown/data_types.md, install-ml.py, tests/test_summary.py, tests/test_torch.py, tests/utils.py, wandb/data_types.py, wandb/util.py
This was causing the bugs with plotly rendering.  Hoping this can go out with the next release.
=> Handle numpy arrays in lists

docs/markdown/fastai.md, wandb/util.py
eager tensors are tf tensors so we were doing the wrong thing.  @cvphelps found this in going through our examples.
=> Switch order of tf checking

wandb/sweeps/bayes_search.py
The old link was down.
[https://www.iro.umontreal.ca/~bengioy/cifar/NCAP2014-summerschool/slides/Ryan_adams_140814_bayesopt_ncap.pdf]
The new link points to an updated version of the paper.
[https://arxiv.org/pdf/1206.2944.pdf]
As discussed with Lukas
=> Updated bayes search reference.

wandb/__init__.py, wandb/wandb_config.py
https://wandb.atlassian.net/browse/WB-1638
=> add config exclude/include option

docs/markdown/cli.md, wandb/cli.py
Just auto populates the username field when first signing up.
=> Add username to local launch

docs/markdown/cli.md, docs/markdown/data_types.md, docs/markdown/fastai.md, docs/markdown/keras.md, docs/markdown/wandb_api.md, wandb/tensorboard/__init__.py
Fixes https://wandb.atlassian.net/browse/WB-1781
=> New tensorflow passes string instead of bytes

.github/workflows/docs.yaml, tests/test_wandb_run.py, wandb/cli.py, wandb/wandb_controller.py, wandb/wandb_run.py
WB-1779 #comment Fix url quote issues
=> Fix url quote issues

standalone_tests/sweep_check.py
This is a script I have been using, it belongs in standalone tests
=> Add standalone sweep checker

wandb/meta.py
=> Remove ResourceWarning

wandb/summary.py
=> Fix ResourceWarning

wandb/run_manager.py
=> Fix more ResourceWarnings

wandb/summary.py
I haven't tried to achieve `ResourceWarning` at this line of code but it seems to be possible as the error is the same as in other places.
=> Fix possible ResourceWarning

docs/generate.py, docs/google_parser.py, docs/markdown/cli.md, docs/markdown/data_types.md, docs/markdown/keras.md, docs/markdown/wandb_api.md, wandb/data_types.py
This is a quick and hacky way to get the dataframe content out of the docs.
=> Attempt to fix docs

docs/markdown/data_types.md, standalone_tests/image_masks.py, tests/test_data_types.py, wandb/data_types.py, wandb/wandb_config.py
This adds default class labels for semantic segmentation. 
Requested by boris for his fastai callback
=> [Enhancement] Default class labels for semantic segmentation

README.md, tests/test_sklearn.py, wandb/sklearn/__init__.py
On the back of the #992, here is my implementation that detected `coef_` and returns feature importance list to W&B.
I ran it against my own model creation setup and it's working as hypothesised:
I have added some basic tests and happy to discuss my implementation rationale.
This is awesome, as many `scikit-learn` models that support `coef_` will start to work (https://scikit-learn.org/stable/search.html?q=coef_). I haven't tested it with all but going by scikit learn's standard attributes this could be the case.
=> Extend plot feature importances functionality

tests/test_sklearn.py, wandb/meta.py, wandb/sklearn/__init__.py
Was seeing this in some instances when using custom run directories.
=> Better code saving logic

wandb/jupyter.py, wandb/run_manager.py
We were hanging for upto 30 seconds in jupyter if the timer thread hadn't finished.  This also fixes #1008.
=> Cancel thread, handle funky ipython session

README.md
Added links to slack & twitter community to readme.
=> Add links to twitter/slack community

tests/test_keras.py, wandb/keras/__init__.py
Added WandbClassificationCallback for confusion matrix and confusion examples logging.
Not sure how to deal with imports and dependencies here.
Suggestions are welcome, tests needs to be done.
=> [WIP] Keras - WandbClassificationCallback

requirements_dev.txt
=> requirements_dev: Indicate tensorboardX>=1.5

wandb/ray/__init__.py
Reported by user at:
https://wb-forum.slack.com/archives/CL4V2QE59/p1592080064287400
=> Ignore callbacks in ray config (not serializable)

docs/markdown/data_types.md, standalone_tests/image_masks.py, wandb/data_types.py
=> Revert "[Bugfix] Add support for non uint8 types for segmentation masks"

wandb/__init__.py
User wanted better wandb.log docstrings so I added a bunch of examples and explanation.
=> Improved wandb.log docstring

wandb/__init__.py, wandb/wandb_config.py, wandb/wandb_run.py
Added more docstrings and made existing ones conform to google style.
=> more docstrings

docs/markdown/wandb_api.md, standalone_tests/artifact_load.py, standalone_tests/artifact_load_large.sh, standalone_tests/artifact_load_small.sh, wandb/apis/public.py
A load test for artifacts. Designed to test deletion and GC once available. Those features aren't yet enabled.
=> Add artifact standalone load test

wandb/__init__.py
Context: https://wandb.atlassian.net/browse/WB-2750
=> Change default histogram log frequency to once every 1000 steps

wandb/data_types.py
=> Fix mask type bug: Issue #1178

wandb/artifacts.py
This line got dropped in a merge, bringing it back. Issue reported by forum user who can't reupload a deleted artifact.
=> Fix deleted artifact handling

wandb/sklearn/__init__.py
y_probas is not being used and this call fails for classifiers without predict_proba()
=> y_probas not being used

wandb/sklearn/__init__.py
https://wandb.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=WB&selectedIssue=WB-2849&assignee=5d913828ede9300dd30b7589
=> [WB-2849] Fix sklearn

tests/test_public_api.py, wandb/apis/public.py
Also snuck in some public api fixes.
=> get_path, download root

wandb/sweeps/base.py, wandb/sweeps/bayes_search.py, wandb/sweeps/params.py, wandb/sweeps/test_bayes_search.py, wandb/sweeps/test_grid_search.py, wandb/sweeps/test_random_search.py, wandb/sweeps/util.py
This has the latest code including adrian's nan fixes
and reverts formatting changes.
=> Resync from anaconda sweeps

tests/test_notebooks.py, wandb/lib/ipython.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
=> Much better display in jupyter / colab

wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
Basic fixes for demo tomorrow AM.
=> No double output, round floats

standalone_tests/sweep_check.py
This takes a while to run but it will generate a nice project with stopped runs:
```
./sweep_check.py -t grid_hyper --grid_hyper_delay 30
```
=> Fix sweep test to allow delay to test hyperband against qa or prod

wandb/integration/tensorboard/monkeypatch.py
https://github.com/pytorch/pytorch/blob/90400f48fcebb2fdbc808d2ab14d639f1e6bcf33/torch/utils/tensorboard/writer.py
Line 18:
from tensorboard.summary.writer.event_file_writer import EventFileWriter
Because of this we should patch both the cached version in torch.utils.tensorboard.writer and the original location
=> [WB-3518] Enhance/tensorboard sync

wandb/sdk/wandb_login.py, wandb/sdk/wandb_setup.py, wandb/sdk_py27/wandb_login.py, wandb/sdk_py27/wandb_setup.py, wandb/wandb_agent.py, wandb/wandb_controller.py
This fixes jupyter sweeps in 0.10.3..... not sure how many of these problems were introduced after 0.10.2 but it fixes most login related issues.
=> [WB-3500] Fix jupyter and python login sweep stuff

wandb/cli/cli.py
i think there is another bug about the same thing.  but wanted this to go into 0.10.3
=> [WB-3469] fix sweep project/entity and some login stuff

wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_settings.py
minimal change to fix breakage.
=> [WB-3531] fix broken allow_val_change

wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_settings.py
https://wandb.atlassian.net/browse/WB-3437
=> wrap instead of redirect on windows

wandb/lib/redirect.py
Fixes https://sentry.io/organizations/weights-biases/issues/1876857687/?environment=production&project=5288891&referrer=alert_email
=> Unbuffered stream wrapper fix

wandb/lib/redirect.py
=> [CLI-459] console redirect uninstall fix

wandb/integration/sagemaker/auth.py, wandb/lib/apikey.py, wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
I broke sagemaker in 0.10.2 when i restructured how login works (sagemaker has no tests)
Tested with:
https://github.com/wandb/examples/tree/master/examples/pytorch/pytorch-cifar10-sagemaker
=> [WB-3562, WB-3546] fix sagemaker login

wandb/cli/cli.py, wandb/sync/sync.py
https://wandb.atlassian.net/browse/WB-3482
=> [WB-3482] Improve wandb sync output

setup.cfg, setup.py, wandb/__init__.py
This reverts commit 381cfdd15f7ada8456fdbb0878d97409dd19d523.
=> Revert "bump dev version (#1307)"

standalone_tests/grpc_client.py, standalone_tests/grpc_server.sh, standalone_tests/grpc_server_test.sh, standalone_tests/offline_sync_test.sh, standalone_tests/offline_sync_train.py, wandb/server/grpc_server.py, wandb/sync/sync.py
Add tests:
https://github.com/wandb/wandb-testing/commit/cc2e598cdc935d08486038c031f06c502a118862
=> [CLI-487] Fix grpc and wandb sync regressions from 0.10.6

standalone_tests/resume-empty.py, tox.ini, wandb/internal/sender.py, wandb/proto/wandb_internal.proto, wandb/proto/wandb_internal_pb2.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
added it to the resume ResumeRecord structure..
it should really be in ResumeResult... but we already stuck other stuff in there like starting_step, we can clean it up carefully in the future.
New test:
https://github.com/wandb/wandb-testing/commit/2dd71e4b7d12c9b28a9d45584a0448a16b10a4ac
=> [CLI-460] fix resume on empty runs

setup.cfg, setup.py, tools/bumpversion-tool.py, tox.ini, wandb/__init__.py
bumpversion is officially a dead project... but here is a hack to make using it less painful
=> Add bumpversion tool for tox cuz bumpversion doesnt understand dev releases

wandb/util.py
Detect fastai tensors.
Fix #1378
=> fix: detect fastai tensor

tests/utils/mock_server.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py, wandb/sweeps/config/cfg.py
Fixes #1504 
It doesn't fix the vendored in code.
=> [CLI-542] Fix deprecation warnings in Python 3.8

wandb/data_types.py, wandb/errors/term.py, wandb/sdk/wandb_setup.py, wandb/sdk_py27/wandb_setup.py
https://wandb.atlassian.net/browse/WB-3908
=> [WB-3908] logging.warn() has been deprecated for a while

wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_run.py
https://wb-forum.slack.com/archives/CL4V2QE59/p1607650987452200
=> Don't try to display widgets on terminal

wandb/integration/tensorboard/monkeypatch.py
Was helping a customer and noticed we aren't patching the tensorboardx summary writer 🙃 .  Regression should be able to assert this.
=> Add support for tboardx

wandb/data_types.py
=> Upped artifact table row limit to 200,000

standalone_tests/artifact_object_reference_test.py, tests/wandb_artifacts_test.py, wandb/data_types.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
Properly handle converting numpy and pandas values as well as transform Nans into Nones
=> [WB-4209]: Properly transform numpy/pandas values in tables for artifacts

wandb/integration/sagemaker/config.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_settings.py
To disable sagemaker:
1) env var
```shell
WANDB_SAGEMAKER_DISABLE=true
```
2) global settings object
```python
wandb.setup(wandb.Settings(sagemaker_disable=True))
```
3) wandb.init() settings object
```python
wandb.init(settings=wandb.Settings(sagemaker_disable=True))
```
=> [WB-3926] Add sagemaker disable

tests/wandb_settings_test.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_settings.py
Changes:
- Added functionality which calls `_preprocess_[SETTINGS]` function if it exists (similar to validate) before setting settings
- Used this to remove slashes from right side of URLs
- added tests
=> [WB-4221] CLI now has ability to preprocess settings and uses this to strip slashes from URL

.circleci/config.yml, requirements_dev.txt, tox.ini
Jira: https://wandb.atlassian.net/browse/WB-4250
=> [WB-4250] Taking off our coveralls, codecov time

mypy.ini, tests/test_sender.py, tests/wandb_artifacts_test.py, wandb/sdk/interface/interface.py, wandb/sdk/lib/redirect.py, wandb/sdk/wandb_run.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/interface/interface.py, wandb/sdk_py27/lib/redirect.py, wandb/sdk_py27/wandb_run.py, wandb/sdk_py27/wandb_settings.py
Left some fun for dsviz, artifact and alerts engineers.
TODO:
=> [WB-4308] Add type annotations to wandb_run.py

mypy.ini, wandb/sdk/internal/handler.py, wandb/sdk/internal/settings_static.py, wandb/sdk/internal/stats.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk_py27/internal/handler.py, wandb/sdk_py27/internal/settings_static.py, wandb/sdk_py27/internal/stats.py, wandb/sdk_py27/internal/tb_watcher.py
https://wandb.atlassian.net/browse/WB-4342
Description
-----------
Types for internal/stats and internal/tb_watcher
Testing
-------
mypy
=> [WB-4242]: types tb_watcher stats

tests/test_library_public.py
https://wandb.atlassian.net/browse/WB-4449
Description
-----------
Checks public symbols at top level of wandb package and in the Run and Config objects.
If new things interfaces are added, this test should be updated and we should scrutinize the change to make sure it makes sense to add this symbol
Still todo, clean up some old symbols, Do this for other objects?  Created a separate ticket for this: https://wandb.atlassian.net/browse/WB-4452
Testing
-------
pytest
=> [WB-4449] test toplevel library symbols and Run, Config object

wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
https://wandb.atlassian.net/browse/CLI-517
https://github.com/wandb/client/issues/1447
Description
-----------
Closes debug log file when run finishes
Testing
-------
Checked open files after run.
=> [CLI-517] Close debug log on finish

wandb/server/grpc_server.py
Description
-----------
Fix bug found in regression
Testing
-------
run standalone test grpc_server_test.py
=> Fix grpc-server

.circleci/config.yml, .gitignore, pyproject.toml, tox.ini, wandb/proto/wandb_internal.proto
https://wandb.atlassian.net/browse/WB-4550
Description
-----------
Makes sure that .proto files are correctly generated in circleci
Testing
-------
circleci passes.  Changed proto without generating files and it fails.
=> [WB-4550] Add proto check: make sure proto is generated correctly

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-4511
Description
-----------
Changelog
Testing
-------
None
=> [WB-4511] changelog 0.10.18

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-4512
Description
-----------
Testing
-------
Regression tests
=> [WB-4512] changelog 0.10.19

.coveragerc, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
Description
-----------
Use string literal type to be more safe for pythons which do not support it.
Alternate solution to: https://github.com/wandb/client/pull/1820
Testing
-------
circleci
TODO:
=> Handle py 3.6.[01] lack of NoReturn

wandb/sdk/internal/tpu.py, wandb/sdk_py27/internal/tpu.py
Tagnetially related to:
https://wandb.atlassian.net/browse/WB-4277
Description
-----------
A colab we were testing had issues with multiprocessing.
Testing
-------
=> Handle type error in colab

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-4513
Description
-----------
bump changelog
Testing
-------
Regression tests passing (with only known issues)
=> [WB-4513] changelog 0.10.20

CONTRIBUTING.md
https://wandb.atlassian.net/browse/WB-4362
Description
-----------
- Adds section talking about test points
- updates code coverage section to be up-to-date with current checks
Testing
-------
It is a document, no testing
=> [WB-4362] add more to test docs

wandb/sdk/interface/interface.py, wandb/sdk/wandb_config.py, wandb/sdk_py27/interface/interface.py, wandb/sdk_py27/wandb_config.py, wandb/util.py
https://wandb.atlassian.net/browse/WB-4813
Description
-----------
Sanitize artifact metadata.
Testing
-------
Manual tests ongoing
=> [WB-4813]: sanitize artifact metadata

standalone_tests/all_media_types.py
https://wandb.atlassian.net/browse/WB-4631
Description
-----------
Remove dataframes from summary in standalone test
Testing
-------
regression test
=> [WB-4631] Fix/test dataframe removal

wandb/apis/public.py
https://wandb.atlassian.net/browse/WB-4351
Description
-----------
Fixes the runs doc to clarify the regex syntax, plus fixes some minor stuff with the docs.
=> [WB-4351] clarify run filtering regex syntax

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-4647
Description
-----------
update changelog
Testing
-------
Local and cloud regressions:
Results:
```
Failed runs:
0: wandb-examples-raytune-pytorch:init:py36,pt
1: wandb-examples-raytune-pytorch:init:py36,ptn
2: wandb-wandb-examples-gym-monitor:init:py36
```
Failures map to these known issues:
- https://wandb.atlassian.net/browse/WB-3588
- https://wandb.atlassian.net/browse/WB-4897
=> [WB-4647] changelog 0.10.22

wandb/sdk/data_types.py, wandb/sdk_py27/data_types.py
Description
-----------
Testing
-------
=> Added key sanitation to run table artifacts

tests/wandb_integration_test.py
Description
-----------
Testing
-------
=> Improve Policy Test

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-4649
Description
-----------
Update changelog for release
Testing
-------
Regressions were run, results:
```
Failed runs:
0: wandb-examples-raytune-pytorch:init:py36,pt
1: wandb-examples-raytune-pytorch:init:py36,ptn
```
=> [WB-4649] Changelog 0.10.24

tests/test_metric_full.py, tests/test_metric_internal.py, tests/test_metric_user.py, tox.ini, wandb/__init__.py, wandb/sdk/lib/module.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_metric.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/lib/module.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_metric.py, wandb/sdk_py27/wandb_run.py
https://wandb.atlassian.net/browse/WB-4543
Description
-----------
- Enables define metric
- Turns on step_sync by default
Testing
-------
unittests
=> [WB-4543] Enable define_metric

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-5244
Description
-----------
Changelog
Testing
-------
Not needed
=> [WB-5244] Changelog 0.10.25

wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
https://wandb.atlassian.net/browse/WB-4969
Description
-----------
Moves sagemaker telemetry to give it run context.
Testing
-------
Tested using regression set up.
=> [WB-4969] Fix CLI sagemaker telemetry

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-5245
Description
-----------
Testing
-------
Regression run (5 failures :( - but non-critical)
=> [WB-5245] changelog 0.10.26

wandb/sdk/internal/meta.py, wandb/sdk/lib/filenames.py, wandb/sdk_py27/internal/meta.py, wandb/sdk_py27/lib/filenames.py
Description
-----------
This PR adds the feature of saving conda's environment configuration. See #2070 for more details.
Testing
-------
Check out this run: https://wandb.ai/costa-huang/cleanRL/runs/36rkd91h/files/conda-environment.yaml
=> #2070 save conda's environment.yaml.

tests/conftest.py, tests/test_logging.py, wandb/filesync/dir_watcher.py, wandb/filesync/upload_job.py, wandb/sdk/internal/file_pusher.py, wandb/sdk/internal/internal.py, wandb/sdk_py27/internal/file_pusher.py, wandb/sdk_py27/internal/internal.py
Fixes #2075 
https://wandb.atlassian.net/browse/CLI-837
Description
-----------
We shouldn't be removing handlers added by 3rd party libs to the root logger, instead should just stop propagating wandb logs to the root.
Testing
-------
Unit test.
=> [CLI-837] Logging fix for hydra

wandb/data_types.py
https://wandb.atlassian.net/browse/WB-5399
Description
-----------
Removes assertion that stops tables from having dots in the name. This causes regression for users and can be overcome in the UI
Testing
-------
=> [WB-5399] Removed assertion

wandb/sdk/internal/handler.py, wandb/sdk/internal/sender.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/internal/handler.py, wandb/sdk_py27/internal/sender.py, wandb/sdk_py27/wandb_run.py
Description
-----------
- lowers polling interval to every 5 seconds (ideally we would keep this at 1 but we will do that later after more internal work)
- avoids logging network poll requests
Testing
-------
manually
=> reduce verbose logging with rate limit checks

wandb/sdk/lib/retry.py, wandb/sdk_py27/lib/retry.py
Description
-----------
Checks for retry_callback before using it.
Testing
-------
By killing local while logging a large video
=> check for retry_callback more

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-5248
Description
-----------
Testing
-------
regression is running
=> [WB-5248] Changelog 0.10.29

package_readme.md
Description
-----------
Update the package readme which is shown at:
https://pypi.org/project/wandb/
Note, there are other things we might want to change in this file.  At one point this was very similar to README.md. 
The difference is package_readme.md can not have any relative code links.  If we want to go back to one file and have pypi show the same info, someone can do that with a later PR.
Testing
-------
None
=> Update package readme

tox.ini
Tests were flaky with 4 in parallel, 3 seems better. 
Description
-----------
pytest 3 in parallel
Testing
-------
unittests
=> pytest parallelism 3 (instead of 4)

wandb/wandb_torch.py
https://wandb.atlassian.net/browse/CLI-886
Description
-----------
fix #2157 
Removes dependency on `register_full_backward_hook` or `register_backward_hook` which can have unexpected effects and created issues in Pytorch 1.8, even when using noop's.
Testing
-------
I tested it manually on a local example.
=> feat: remove backward hook in watch method

tests/utils/mock_server.py, tests/wandb_artifacts_test.py, wandb/sdk/data_types.py, wandb/sdk_py27/data_types.py
Description
-----------
Added sha to media payloads
Testing
-------
=> Added sha to media payloads

mypy.ini, tests/test_file_stream.py, tests/utils/mock_server.py, wandb/sdk/internal/file_stream.py, wandb/sdk_py27/internal/file_stream.py
Description
-----------
handles json parsing issues
Testing
-------
very little
=> [WB-5300] Improve network robustness

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-5465
Description
-----------
Changelog 0.10.30
Testing
-------
Regression tests run, known failures.
=> [WB-5465] Update changelog 0.10.30

wandb/data_types.py
https://wandb.atlassian.net/browse/WB-5566
https://wandb.atlassian.net/browse/DOCS-22
Description
-----------
Makes docs better
Testing
-------
=> Improved Tables PyDocs

wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
Description
-----------
Improves the confusing assertion with a message that is indicative of what is actually happening.
Testing
-------
=> Improve Comm Error Message

wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
https://wandb.atlassian.net/browse/WB-3771
Description
-----------
Testing
-------
=> [WB-3771] Updated docs regarding wandb.finish in child

.circleci/config.yml, .codecov.yml, tox.ini
Description
-----------
Add windows testing coverage to codecov
note: this is a bit hacky in tox.ini to handle the slashes, since we use bash we want forward slashes, but tox insists on giving us backslashes so for now the paths are hardcoded for circle.
Testing
-------
Ran in circle, passes
=> Add windows to codecov

tests/conftest.py, tests/test_public_api.py, tests/utils/mock_server.py, tests/wandb_artifacts_test.py
https://wandb.atlassian.net/browse/WB-5654
Description
-----------
- Cherry picked @vanpelt's better fix to py39 issue with our storage urls having two slashes
- Improved artifact test to check something and clean it up
- improved artifact test to handle cleanup of run object (our auto cleanup is busted)
Testing
-------
unit tests passed at least once, might still have flake. but it should be better.
=> [WB-5654] Fix up flaky tests

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
https://wandb.atlassian.net/browse/WB-5631
Description
-----------
Release 0.10.31
Testing
-------
- regression tests were run
- manual colab testing
=> [WB-5631] Release/wandb 0.10.31

SECURITY.md, wandb/data_types.py, wandb/sdk/data_types.py, wandb/sdk_py27/data_types.py
Depends on https://github.com/wandb/core/pull/7055
Description
-----------
allows `run.log` to support partition and join tables
Testing
-------
=> Make it possible to log partition and join tables directly

wandb/apis/public.py
Description
-----------
Testing
-------
=> Removed Duplicate Dependencies

wandb/wandb_torch.py
Co-authored-by: Jeff Raubitschek <jeff@wandb.com>
Description
-----------
Testing
-------
=> fix: check watch non-empty list (#2194)

tests/wandb_run_test.py, wandb/util.py
https://wandb.atlassian.net/browse/CLI-941
Description
-----------
This PR fixes an infinite loop in wandb.log caused by undefined json encoding behavior for numpy types with precision greater than native python types.
Fixes #2255 
Testing
-------
Added a unit test
=> [CLI-941] fix floating point issue

tests/test_label_full.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
https://wandb.atlassian.net/browse/WB-5669
Description
-----------
small tweaks
Testing
-------
unittests
=> [WB-5669] Feature/label improvements

tests/utils/mock_server.py, tests/wandb_artifacts_test.py, wandb/data_types.py, wandb/sdk/data_types.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/data_types.py, wandb/sdk_py27/wandb_artifacts.py
Description
-----------
same as https://github.com/wandb/client/pull/2264, just bumped to 20
Testing
-------
=> Reduce Collisions

README.md
Description
-----------
Update README with PyTorch Lightning Integration
Testing
-------
N/A: Documentation
=> Update README with PyTorch Lightning Integration

wandb/wandb_torch.py
https://wandb.atlassian.net/browse/CLI-939
Description
-----------
Fixes #2251 
Testing
-------
Manual examples
=> [CLI-939] fix(watch): remove hooks only after processing all

wandb/wandb_torch.py
Merge: https://github.com/wandb/client/pull/2271
=> [CLI-939] fix(watch): remove hooks only after processing all (#2271)

wandb/apis/public.py
Description
-----------
Fixes a bug where publicly fetched run logged artifacts are instantiated with the incorrect name.
Testing
-------
=> Fixes Artifact Construction from Public Runs

tox.ini, wandb/sdk/integration_utils/data_logging.py, wandb/sdk_py27/integration_utils/data_logging.py
Description
-----------
Uses the new doc linter to cleanup integration_utils
Testing
-------
=> Added doc linter to integration_utils

wandb/sdk/lib/filenames.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/lib/filenames.py, wandb/sdk_py27/wandb_run.py
Description
-----------
log_code wasn't excluding wandb_dirs named with ".wandb"
Testing
-------
Manual
=> Fix up log_code() exclude fn to handle .wandb dir

tests/test_launch.py, wandb/cli/cli.py, wandb/errors/__init__.py, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/__init__.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/__init__.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/runner/loader.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py, wandb/sdk_py27/internal/internal_api.py
https://wandb.atlassian.net/browse/WB-5745
Description
-----------
Adds better error messages for several api calls, shows the docker steps while building the docker container.
Testing
-------
Tested by breaking stuff on purpose along launch and launch-agent workflows
=> [WB-5745]: Launch - better error handling and UX

standalone_tests/all_media_types.py
Description
-----------
Testing
-------
=> attempt to fix media types test in pytoch

wandb/apis/public.py
https://wandb.atlassian.net/browse/WB-5774
Description
-----------
This PR exposes the sweep state via the public API.
Testing
-------
Manually.
=> [WB-5774] expose sweep state via public API

.flake8-base
Description
-----------
Fix some new flake errors
Testing
-------
=> update flake for some reason

tests/integrations/test_torch.py, wandb/sdk/wandb_run.py, wandb/sdk/wandb_watch.py, wandb/sdk_py27/wandb_run.py, wandb/sdk_py27/wandb_watch.py
Description
-----------
This disables logging graph by default due to issues saving the model in some instances.
Testing
-------
Manually
=> fix(watch): disable logging graph by default

CHANGELOG.md, setup.cfg, setup.py, tests/test_data_types.py, tests/wandb_artifacts_test.py, wandb/__init__.py, wandb/sdk/data_types.py, wandb/sdk/internal/internal_api.py, wandb/sdk_py27/data_types.py, wandb/sdk_py27/internal/internal_api.py
=> Release/wandb 0.11.0

setup.cfg, setup.py, wandb/__init__.py
=> Bump version: 0.11.0 → 0.11.1.dev1

CHANGELOG.md
Description
-----------
Fix incorrect changelog entry for  `Stable-Baselines3`
Testing
-------
Not needed
Release Notes
-------
=> Fix SB3 changelog entry

.github/pull_request_template.md, .github/workflows/auto-rel-notes.yml
Description
-----------
Add @davidwallacejackson's wandb/auto-release-notes action 
Testing
-------
Release notes
--------------
=> add github action auto-release-notes

tests/launch/test_launch_cli.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/utils.py
https://wandb.atlassian.net/browse/WB-5896
Description
-----------
remove block on/add test for github url support, fix lack of default entrypoint from the last refactor, improve messaging a little
Testing
-------
added test
=> [WB-5896] remove block on github urls

tools/telemetry-tool.py
Description
-----------
Generate new analytics record and table ids for "label" feature.
Label feature documented at:
https://paper.dropbox.com/doc/Labeling-examplesreposframeworks--BO2OchT37CNH__espALt7XBtAg-wSxbYSY5m3ZqmO5HjdIhP
Testing
-------
Not tested, but used to generate the analytics PR:
https://github.com/wandb/analytics/pull/620
Release Notes
-------------
=> Add label output for telem tool

tests/launch/test_launch_cli.py
Description
-----------
fixes a broken test, i'll wait for the chardet fix to hit circle in case anything else still doesn't work that i can't see
Testing
-------
Release Notes
-------------
=> fix github entrypoint test

functional_tests/sb3-integration.py, functional_tests/script-fail.py, functional_tests/with-finish.py, functional_tests/without-finish.py, functional_tests/without-finish.yea, tox.ini
https://wandb.atlassian.net/browse/WB-6114
Description
-----------
update to yea 0.4 assert format
bump to yea-wandb 0.4.1
yea-wandb changes: https://github.com/wandb/yea-wandb/pull/6
Testing
-------
unittests pass
Release Notes
-------------
=> [WB-6114] Update yea format to preferred 0.4 format

tests/test_offline_sync.py
https://wandb.atlassian.net/browse/WB-6112
Description
-----------
Mark a flaky test flaky for all platforms
Testing
-------
unittests
Release Notes
-------------
=> mark sync test flaky

.codecov.yml, tests/launch/test_launch.py, tests/launch/test_launch_cli.py, wandb/apis/internal.py, wandb/cli/cli.py, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/launch.py, wandb/sdk/launch/runner/abstract.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py, wandb/sdk_py27/internal/internal_api.py
Description
-----------
- Adds doc strings to launch stuff
- changes git regex
- adds a section to covercircle specific to launch
- removes unused create_run_queue api method
Testing
-------
Release Notes
-------------
=> Launch - Fix up/ add more doc strings

wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
Description
-----------
Adds Molecule Support to Tables/Weave
Testing
-------
Release Notes
-------------
- Feature: Tables now support Molecule data type.
=> Added Molecule Support to Tables/Weave

tools/setup_dev_environment.sh
This PR updates the `setup_dev_environment.sh` script to install the version of tox that matches what is specified as a requirement in `requirements_dev.txt`
Release Notes
-------------
=> bump version of tox in setup_dev_environment.sh to match what is in requirements_dev.txt

CHANGELOG.md, MANIFEST.in, setup.cfg, setup.py, wandb/__init__.py, wandb/util.py, wandb/wandb_controller.py
Description
-----------
Updates changelog and bumpversion
Testing
-------
unittests
Release Notes
-------------
NO  RELEASE NOTES
=> Release 0.11.1

wandb/old/summary.py
Description
-----------
Removes broken code. There is a full fix here, but needs to be refactored: https://github.com/wandb/client/pull/2394. This path deletion is safe as it does not work today and is just causing bugs.
Testing
-------
Release Notes
-------------
=> Remove Broken Summary Deserialization

.circleci/config.yml, requirements_dev.txt, tools/setup_dev_environment.sh, tox.ini
Description
-----------
Fix broken circle/tox testing
Testing
-------
unittests pass now
Release Notes
-------------
=> Pin tox, remove pydoc-markdown to fix depends prob

tests/launch/test_launch.py, wandb/sdk/internal/internal_api.py
Description
-----------
Testing
-------
It is a test
Release Notes
-------------
=> Launch - another test

tests/test_logging.py
https://wandb.atlassian.net/browse/WB-6348
Description
-----------
This PR is just a quick a dirty hack to avoid the issue where logging test fails, when running it locally.
The proper solution will require deeper investigation, as it part of a greater trend of a set of tests. 
Testing
-------
Release Notes
-------------
=> [WB-6348] Quick hack to fix flaky logging test

requirements.txt
Description
-----------
Unpin urllib as latest version has fix, and pinning seems to cause problems when other packages have conflicting requirements.
Testing
-------
unittests (soon regression test)
Release Notes
-------------
=> unpin urllib3

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-6231
Description
-----------
Changelog
Testing
-------
None
Release Notes
-------------
=> [WB-6231] Changelog 0.12.0

setup.cfg, setup.py, wandb/__init__.py
https://wandb.atlassian.net/browse/WB-6231
Description
-----------
Release 0.12.0
Testing
-------
Unittests, Regressions, Manual testing
Release Notes
-------------
=> [WB-6231] Release 0.12.0

ARCHITECTURE.md
https://wandb.atlassian.net/browse/WB-4549
Description
-----------
Document run.log()
Testing
-------
Not needed
Release Notes
-------------
=> [WB-4549] Add run.log(), run.finish() to architecture.md

.codecov.yml, wandb/sdk/wandb_run.py
https://wandb.atlassian.net/browse/WB-6364
Description
-----------
Adds coverage annotations! (required - i think - re-enabling circleci github checks integration) .
Now your PRs will annotations like this sprinkled in with your PR code review views:
Also note that you have a github check for each circleci pipeline now:
Testing
-------
I added uncovered code and tested.
Release Notes
-------------
=> [WB-6364] Add codecov coverage annotations

tox.ini
Description
-----------
Yea 0.7.1:
- Adds artifact emulator, supports basic manifest and file support, Create and Query ops.
- Adds debug mode `yea --debug test.py`
Testing
-------
Existing tests pass, in development tests pass.
Release Notes
-------------
=> Testing: Update yea 0.7.1

tests/utils/artifact_emu.py, tox.ini
Description
-----------
Fix artifact emulator typo.
Update yea with same fix.
Testing
-------
Release Notes
-------------
=> Fix typo/bug in artifact emu (artifactfiles)

.codecov.yml, .flake8-docstrings, tox.ini, wandb/apis/public.py, wandb/cli/cli.py, wandb/errors/__init__.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/launch.py, wandb/sdk/launch/runner/abstract.py, wandb/sdk/launch/runner/loader.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py, wandb/util.py
Description
-----------
Handles some of Jeffs comments.
- fixes a spacing issue
- adds launch stuff to docstring checker
- reformats doc strings
- fixes a comment, and a covercircle setting
Testing
-------
Release Notes
-------------
=> Launch comments round 2

wandb/integration/sb3/sb3.py
This PR makes SB3's integration compatible with sweep. See https://wandb.ai/costa-huang/sb3-sweep/sweeps/yxjkl1dk?workspace=user-costa-huang
Make SB3's integration compatible with sweep
=> WB-6238 # make sb3 integration work with sweep

tests/test_public_api.py, tests/utils/mock_server.py, tests/wandb_controller_test.py, wandb/apis/public.py, wandb/sdk/launch/agent/agent.py
Description
-----------
- modifies time between polling from 30 s to 10 s
- adds test for wait_until_finished and for QueuedJob wait_until_running
Testing
-------
Release Notes
-------------
=> [Launch]: Round 3 comments

.circleci/config.yml, tests/fixtures/requirements.txt
Description
-----------
Updates installed branch in certain tests using requirements.txt in test/fixtures
Testing
-------
Using existing tests
Release Notes
-------------
=> change installed branch

tox.ini
Description
-----------
Testing
-------
Release Notes
-------------
=> bump yea version to 0.7.5

.circleci/config.yml, .codecov.yml, .coveragerc, functional_tests/keras/tf_1_15.yea, functional_tests/keras/tf_2_1.yea, functional_tests/keras/tf_2_5.yea, functional_tests/keras/tf_2_6.yea, tox.ini
Description
-----------
shard functional tests
Testing
-------
circle
Release Notes
-------------
=> Shard functional tests

README.md
Description
-----------
Updates the resource links in the README for all materials with shortlinks and sends users to the new community forum instead of the Slack.
Testing
-------
Rendered the page and clicked through on all the links.
Release Notes
-------------
=> Updates links in README to shortlinks

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-6553
Description
-----------
Testing
-------
None needed
Release Notes
-------------
=> [WB-6553] changelog 0.12.2

tox.ini
Description
-----------
Use pinned sweep_engine (not latest)
Testing
-------
circle should pass 🤞 
Release Notes
-------------
=> Use pinned sweep_engine (not latest)

functional_tests/code-save/code-save-disabled.yea, functional_tests/code-save/code-save-enabled.yea, functional_tests/code-save/code-save.py, functional_tests/code-save/log-code/fake-lib.py, functional_tests/code-save/log-code/log-code.py, functional_tests/code-save/log-code/log-code.yea, functional_tests/code-save/log-code/subdir/another-lib.py, tests/utils/mock_server.py, tox.ini
Description
-----------
Changes in client:
- Sync mock_serve
- update yea-wandb
- Add code saving tests
yea-wandb==0.7.12: (Thanks @vwrj)
- new function `count_regex`
- new operator `contains_regex`
yea-wandb==0.7.13:
- Add: [output][stdout]
- Add: [output][stdin]
- Fix: [m] and [t] when there is no data
- Fix bug preventing windows from running (likely more issues)
yea-wandb==0.7.14:
- Add: [run_id] to run object
- Add new function :fn:concat 
yea-wandb==0.7.15:
- Add: [git] to run object (has commit and remote)
Sample data:
```
$ yea --debug run functional_tests/code-save/log-code/log-code.py 
{ ':wandb:artifacts': {'source-17e0oca3': {'num': 1, 'type': 'code'}},
':wandb:runs': [ { 'config': {},
'config_wandb': { 'cli_version': '0.12.3.dev1',
'code_path': …
```
=> Update mock server to yea-wandb 0.7.15

wandb/sdk/wandb_login.py
Description
-----------
This PR fixes #2688   to make the api key prompt retry forever if the user continues to provide a malformed API key, addressing @raubitsj 's comment. 
Testing
-------
Manually
Release Notes
-------------
Makes api key prompting retry indefinitely on malformed input
=> make api key prompt retry forever

CHANGELOG.md
https://wandb.atlassian.net/browse/WB-6554
Description
-----------
Changelog update for 0.12.3
Testing
-------
Testing/Release notes:
https://paper.dropbox.com/doc/Client-release-0.12.3--BTX8QI~HRf2SPgIQMRYpvxHnAg-TkmWo4WHmVNL1HdmOV4We
Release Notes
-------------
=> [WB-6554] changelog 0.12.3

wandb/apis/public.py
[https://wandb.atlassian.net/browse/WB-6616](https://wandb.atlassian.net/browse/WB-6616)
Description
-----------
Fixes really silly issue
Testing
-------
Release Notes
-------------
=> [WB-6616] Bad error message 

wandb/sdk/internal/sender.py
https://wandb.atlassian.net/browse/WB-6801
https://github.com/wandb/client/issues/2701
Description
-----------
Fixes an issue, where we try to query the server in offline mode to check the local version.
Testing
-------
In the future this should be tested in yea: wandb/yea-wandb#9
Release Notes
-------------
Fix local warning message in offline mode
=> [WB-6801] Local tries to sync in offline mode

CHANGELOG.md
Fixes WB-6555
Description
-----------
Changelog
Testing
-------
None
Release Notes
-------------
=> [WB-6555] Changelog 0.12.4

functional_tests/metaflow/wandb-foreach-flow.yea
Temporarily disable test for: WB-6922
Description
-----------
Marks test as skip
Testing
-------
Not
Release Notes
-------------
=> [WB-6922] temporarily disable metaflow test

tools/telemetry-tool.py
Description
-----------
Lets keep underscore vars private
Testing
-------
Generated: https://github.com/wandb/analytics/pull/762
Release Notes
-------------
=> Skip private fields when generating analytics csvs

tests/integrations/test_torch.py, wandb/wandb_torch.py
WB-6700
Description
-----------
Temporary revert of the fix for WB-6700 while we work out compatibility issues with older torch
Testing
-------
Release Notes
-------------
=> Revert "[WB-6700] safer but less complete fix for excess gpu memory

wandb/proto/wandb_telemetry.proto, wandb/sdk/wandb_settings.py
Description
-----------
Testing
-------
Release Notes
-------------
`NO RELEASE NOTES
=> minor clean ups

wandb/apis/public.py, wandb/sdk/internal/file_stream.py
remove dataclasses dep
Description
-----------
remove dataclasses dep
Testing
-------
tox
Release Notes
-------------
=> remove dataclasses dep

.circleci/config.yml, .codecov.yml, .coveragerc, functional_tests/keras/tf_2_6.yea, tox.ini
Description
-----------
- Add explicit test shard for tf26 (we were using base before which has moved on to tf27+)
- Fix up some miscounts in .codecov
- Add some missing .coverage entries
Testing
-------
This is a test
=> Add explicit tf26 testing to yea

functional_tests/debug/01-debuglog-stderr.py, wandb/sdk/lib/debug_log.py, wandb/sdk/wandb_run.py
Improves WB-6879
Description
-----------
This change will show a bit more information about the messages (decode requests etc)
Testing
-------
Ran it a few times (there is a yea test that covers the codepaths too)
Checklist
-------
=> [WB-6879] Improve debug_log and name a couple threads

.circleci/config.yml, .codecov.yml, functional_tests/mp/15-simple-noml.py, functional_tests/mp/15-simple-noml.yea, wandb/sdk/backend/backend.py, wandb/sdk/service/server.py
Description
-----------
This is a shard to test that things work with limited (or no) extra packages installed.
Testing
-------
circle
=> Add noml shard to circleci

.circleci/config.yml, functional_tests/keras/keras_logged_params_names_tf_2_5.yea, functional_tests/keras/keras_logged_params_names_tf_2_6.yea
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Fix Imports in some `keras` tests and bump circle ci cache version

CHANGELOG.md
Description
-----------
Changelog.   Auto generated and manually tweaked.
Testing
-------
Regression tests are passing with service off.   With service on, there are a few failure but they have been triaged.
Checklist
-------
=> Changelog 0.12.8

CHANGELOG.md
Description
-----------
Update changelog date and remove reverted PR
Testing
-------
None
=> Update 0.12.8 changelog

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Release 0.12.8
Testing
-------
Regression tests.  manual tests, jupyter tests oh my
=> Bump version: 0.12.8.dev1 → 0.12.8

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Prep for opening up branch again
Testing
-------
None
Checklist
-------
=> Bump version: 0.12.8 → 0.12.9.dev1

CHANGELOG.md
Description
-----------
Testing
-------
None
=> Changelog 0.12.9

functional_tests/lightning/train-ddp.py, functional_tests/lightning/train-ddp.yea
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
What does the PR do? Fix PL test
Testing
-------
Checklist
-------
=> Temporary fix for failing PL test

tox.ini
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Update yea/yea-wandb 0.7.31

tests/utils/artifact_emu.py, tests/utils/mock_server.py, tox.ini
Description
-----------
Pull out the mock_server changes for the graphql change PR:
https://github.com/wandb/client/pull/3123
Modify a few parameters to support existing client gql requests in addition to future ones modified by the above mentioned PR.
Testing
-------
Checklist
-------
=> Update mock-server for graphql changes

CHANGELOG.md
Description
-----------
Changelog for 0.12.10
Testing
-------
Testing still in progress for release
=> Changelog 0.12.10

tools/telemetry-tool.py
Description
-----------
Adds issues telemetry reporting to analytics.
Updates path for dbt table descriptions
Testing
-------
Generated a PR for analytics.
https://github.com/wandb/analytics/pull/890
Checklist
-------
=> Update telemetry tool for issues table

.flake8-base, .github/workflows/contributing.yml, functional_tests/keras/keras_logged_params_names_tf_2_5.yea, functional_tests/keras/keras_logged_params_names_tf_2_6.yea, functional_tests/keras/keras_nonnumeric_tf_2_5.yea, functional_tests/keras/keras_nonnumeric_tf_2_6.yea, mypy.ini, tests/test_meta.py, tests/test_util.py, tests/wandb_artifacts_test.py, wandb/env.py, wandb/sdk/interface/interface.py, wandb/sdk/interface/interface_shared.py, wandb/sdk/launch/utils.py, wandb/sdk/lib/timed_input.py, wandb/sdk/service/server.py, wandb/util.py
Description
-----------
This PR improves test coverage and adds type annotations to `wandb/util.py`.
Additionally:
- Run `.github/workflows/contributing.yml` only on commits to master
- Tag several keras tests on yea more specifically
- Mark `test_artifact_incremental_internal` in `tests/wandb_artifacts_test.py` xfail as it has been flaking a lot, causing us to burn a ton of credits on Circle. 
Testing
-------
Implemented a few dozen new tests for `util.py`.
=> Improve test coverage and add type annotations to util.py

tests/utils/mock_server.py, tests/wandb_verify_test.py, tox.ini, wandb/sdk/verify/verify.py
Description
-----------
Improve test coverage in `wandb.verify`, which wasn't previously tested.
Testing
-------
Added tests for `wandb.verify.verify`
=> Improve test coverage in wandb.verify

docs/dev/wandb-service-user.md
Description
-----------
Updates the wandb-service user document and adds the wandb logo 
Testing
-------
markdown... no need for review
Checklist
-------
=> [WB-4318] Fix up the service user doc

wandb/sdk/wandb_sweep.py
Description
-----------
Fix a docstring in wandb_sweep.py
=> Fix a docstring in wandb_sweep.py

wandb/sdk/lib/printer.py, wandb/sdk/wandb_run.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Fix abort key combo function call in footer

CONTRIBUTING.md
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Add some text to point to the regression test repository to help run regression tests.
Testing
-------
Readme, no need for tests.
Checklist
-------
=> Minor description of regression tests in contributing file

functional_tests/core/05-log-media.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Add functional test for media logging

functional_tests/tensorflow/01-tensorflow-log.py, functional_tests/tensorflow/01-tensorflow-log.yea, functional_tests/tensorflow/02-tensorflow-hook.py, functional_tests/tensorflow/02-tensorflow-hook.yea
Description
-----------
creates a copy of functional test for tf 
Testing
-------
This is a test
Checklist
-------
=> Add TF functional tests

CHANGELOG.md
Description
-----------
Just a changelog
Testing
-------
No testing
Checklist
-------
=> Changelog 0.12.11

tests/utils/mock_server.py, tox.ini
Description
-----------
Update to use the latest yea-wandb
This has been reviewed at:
https://github.com/wandb/yea-wandb/pull/47
Testing
-------
unittests
=> sync with yea-wandb (live mockserver)

.flake8-base, functional_tests/fastai/01-v1.py, functional_tests/fastai/01-v1.yea, functional_tests/sacred/01-regression.py, functional_tests/sacred/01-regression.yea, mypy.ini, wandb/integration/fastai/__init__.py, wandb/sdk/data_types/image.py
Description
-----------
These integrations are untested, fixing that. 
Testing
-------
Wrote basic yea tests.
=> Yea test for sacred and fastai v1 integrations

tests/utils/artifact_emu.py, tests/utils/mock_server.py, tox.ini
https://wandb.atlassian.net/browse/WB-8597
Description
-----------
Added gql endpoints to artifact_emu.py and mock_server.py in yea-wandb, need to propagate these changes to client. 
Testing
-------
n/a
Checklist
-------
=> sync changes from new yea-wandb

wandb/cli/cli.py, wandb/docker/__init__.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/runner/abstract.py, wandb/sdk/launch/runner/aws.py, wandb/sdk/launch/runner/gcp_vertex.py, wandb/sdk/launch/runner/kubernetes.py, wandb/sdk/launch/runner/loader.py, wandb/util.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Kubernetes integration

wandb/deploys/launch-agent.yaml, wandb/deploys/launch-config.yaml, wandb/sdk/launch/runner/kubernetes.py
Description
-----------
Add pod security policies to the launch-agent deployment and fix minor issues with agent yaml
Testing
-------
Deployed the new namespace (with pod security admission webhook) and was able to create the launch agent and create a user job.
=> add security policy and make launch agent compliant

wandb/deploys/launch-config.yaml, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/runner/kubernetes.py, wandb/sdk/launch/templates/_wandb_bootstrap.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> [Launch]: Kubernetes fix image hanging forever

tests/fixtures/launch/launch_vertex_config.json, tests/tests_launch/test_launch_docker.py, tests/tests_launch/test_launch_gcp.py, wandb/docker/__init__.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/runner/aws.py, wandb/sdk/launch/runner/gcp_vertex.py, wandb/sdk/launch/runner/kubernetes.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> move entrypoint out of dockerfile, fix k8s context handling

functional_tests/doctest/plot-line-series-double.yea, functional_tests/doctest/plot-line-series-single.yea, tests/test_plot.py, wandb/plot/line_series.py
Fixes WB-8790
Fixes #NNNN
Description
-----------
Fixes line_series plot of strings
Testing
-------
testing different inputs to see that it actually works
Checklist
-------
=> [WB-8790] Fix line_series to plot array of strings

wandb/sdk/launch/runner/kubernetes.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix context issue

wandb/sdk/launch/runner/kubernetes.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> remove env vars from kubernetes

wandb/sdk/wandb_config.py
Description
-----------
Fixes the world's tiniest typo in the docstring of the Config class.
Testing
-------
This PR only changes documentation, so code is still the same.
=> fix typo in Config docstring

functional_tests/lightning/0-strategy-ddp.py, functional_tests/lightning/0-strategy-ddp.yea, functional_tests/lightning/1-strategy-ddp-spawn.py, functional_tests/lightning/1-strategy-ddp-spawn.yea
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
uses the latest release version of PL and remove logic that is going to go away in the next release
Testing
-------
Checklist
-------
=> Fix PL tests to use newest release

CHANGELOG.md
Description
-----------
Lightly edited automatically generated changelog
Testing
-------
None
=> Changelog 0.12.12

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
bump to dev version
=> Bump version: 0.12.12 → 0.12.13.dev1

functional_tests/login/03-login-cloud-local-key.py, functional_tests/login/03-login-cloud-local-key.yea, tests/wandb_settings_test.py, wandb/sdk/wandb_settings.py
Description
-----------
This PR reverts https://github.com/wandb/client/pull/3384 to address a regression introduced in there.
A more thorough fix is being worked on in https://github.com/wandb/client/pull/3484.
Testing
-------
Tested against local.
=> Revert #3384

functional_tests/login/03-login-cloud-local-key.py
Description
-----------
Fix accidental linting issues in `functional_tests/login/03-login-cloud-local-key.py`.
Testing
-------
N/A
=> Fix linting

CHANGELOG.md
Description
-----------
Edited changelog (proper bugfix description).
Testing
-------
N/A
=> Changelog 0.12.13

setup.cfg, setup.py, wandb/__init__.py
=> Bump version: 0.12.13 → 0.12.14.dev1

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Changelog
Testing
-------
Regression run
Checklist
-------
=> Changelog 0.12.14

wandb/sdk/internal/internal_api.py
Description
-----------
Bring back history step logging
Testing
-------
It was tested before and will be tested again.
Checklist
-------
=> Reenable history step logging in artifacts

wandb/cli/cli.py
Fixes WB-9113
Fixes #NNNN
Description
-----------
This PR remove the check for outdated local docker image (since there is a banner in the app itself)
Testing
-------
Checklist
-------
=> [WB-9113] remove upgrade check

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Testing
-------
Checklist
-------
=> Update 0.12.16 dev

setup.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Be explicit about us being py3+ only in setup.py

.github/pull_request_template.md, .github/release.yml
Description
-----------
Improve changelog generation, and get rid of unneeded ticket in PR title
Testing
-------
Not tested
Checklist
-------
=> Add cleanup section to GH changelog

CHANGELOG.md
Description
-----------
Add changelog
Testing
-------
Not tested
Checklist
-------
=> Changelog 0.12.16

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Release branch for 0.12.16
Testing
-------
See internal testing.
Checklist
-------
=> Bump version: 0.12.16.dev1 → 0.12.16

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Open up 0.12.17 dev cycle
Testing
-------
None
=> Bump version: 0.12.16 → 0.12.17.dev1

.github/CODEOWNERS
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Rename wandb/sdk to wandb/sdk-team

wandb/sdk/wandb_manager.py, wandb/trigger.py
Fixes WB-9385
Description
-----------
This PR adds the finish trigger to service to support magic 
Testing
-------
It was tested in #3459 (since service is on by default) and the magic test pass with this fix
Checklist
-------
=> [WB-9385] Adds support for magic with service

wandb/filesync/dir_watcher.py
Description
-----------
What does the PR do? 
Quick fix for broken test
Testing
-------
Test will start working again
Checklist
-------
=> Hot Fix to the broken test_live_policy_file_upload test

wandb/integration/sb3/sb3.py
Description
-----------
Improve parameter naming in `sb3` integration from https://github.com/wandb/client/pull/3643.
Testing
-------
Checklist
-------
=> Improve parameter naming in sb3 integration

tests/test_mp_full.py, tests/wandb_run_test.py, tests/wandb_test.py
Description
-----------
Skips test if service is on... since these test only valid in the non-service case
Testing
-------
Checklist
-------
=> skip if service is on

tests/utils/mock_server.py, tox.ini
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Update yea-wandb to 0.7.53

wandb/integration/keras/keras.py, wandb/sdk/data_types/image.py
Fixes DOCS-349
Fixes DOCS-313
Description
-----------
Update to reference docs for our Keras `WandbCallback` and `wandb.Image`.
=> Updates to Reference Docs

wandb/docker/__init__.py
Description
-----------
I messed up, this should make it actually work.  We were mocking this out in the tests, but I hadn't manually tested it...
Testing
-------
Checklist
-------
=> Fix busted docker inspect command

wandb/sdk/launch/agent/agent.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> add runner config skeelton

wandb/cli/cli.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/deploys/launch-agent.yaml, wandb/sdk/launch/launch.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> parse runners config

wandb/sdk/internal/internal_api.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> add new mutations and query to internal api

CHANGELOG.md
Description
-----------
Changelog
Testing
-------
Not needed
=> Update changelog for 0.12.18

hackweek/launch-agent.yaml, wandb/apis/internal.py, wandb/cli/cli.py, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/deploys/launch-agent.yaml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> add launch agent job selector

setup.cfg, setup.py, wandb/__init__.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Bump version to 0.12.19dev

hackweek/launch-agent.yaml, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/launch.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Finishes connecting the default queue job config and runspec config so we can pop runs, merge dicts and run the jobs
Testing
-------
Checklist
-------
=> summerhack launch: Fix agent code to properly handle received queue configs

wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/builder/docker.py, wandb/sdk/launch/builder/kaniko.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
WAY BETTER CAHCING
Testing
-------
IT WASNT
Checklist
-------
=> fix a bunch of stuff

hackweek/launch-agent.yaml, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/launch.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> add resource awareness and report to server

hackweek/k8s/launch-agent.yaml, hackweek/k8s/launch-config.yaml, hackweek/local-agent.yaml, wandb/sdk/launch/builder/kaniko.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> kaniko tolerations

wandb/sdk/internal/internal_api.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/builder/build.py, wandb/sdk/launch/runner/kubernetes.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> taints and tolerations and submittedby in popped rqis

wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> quick fixes

hackweek/local-agent.yaml, wandb/sdk/launch/agent/agent.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix agent project and stuff

wandb/sdk/launch/builder/kaniko.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix builder

CHANGELOG.md
https://github.com/wandb/client/pull/3709
=> Add changelog link to PR 3709

.flake8-base, wandb/apis/public.py
Description
-----------
Fix flake8 B006 errors in public API
Testing
-------
CI!
Checklist
-------
=> Fix flake8 B006 errors in public API

functional_tests/imports/01-batch1-requirements.txt, functional_tests/imports/01-batch1.py
Description
-----------
"Address" dependency conflict in `functional_tests.imports.imports1`.
The problem is with `allennlp`'s dependencies that currently don't resolve, tried a bunch to fix it, but it was becoming way too tedious, so I commented it out for now. Added a todo to uncomment once they fix it.
Testing
-------
On the CI.
Checklist
-------
=> Fix dependency conflict in `functional_tests.imports.imports1`

wandb/sdk/wandb_artifacts.py
Description
-----------
Fixes a critical regression in reference artifacts when trying to add folders. The previous code fixes an issue where if there if a virtual folder (0-byte filer with content type `x-folder`), we correctly handle it. However, the fix broke the canonical path where if there is no file present, we now error with a uncaught 404 which is very bad.
Testing
-------
- We have an integration test that exercises this case, I'll make sure that runs and passes.
- I've manually repro-ed the bug and tested that it works for no folders and a fake folder created via the s3 UI
=> fix regression in s3 reference upload for folders

.circleci/config.yml
Description
-----------
Fix some standalone stuff in circle config + beef up machines on circle.
Testing
-------
Checklist
-------
=> Fix some standalone stuff + beef up machines on circle

setup.cfg, setup.py, wandb/__init__.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Bump version: 0.13.0rc4.dev1 → 0.13.0rc5.dev1

tests/standalone_tests/artifact_tests.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Note, this test still fails if run with yea, this is for the regression suite.
Testing
-------
Checklist
-------
=> Quick fix standalone artifacts test

README.md, setup.cfg, setup.py, tests/conftest.py, wandb/__init__.py
Description
-----------
Revert the service on by default change (This will be reverted back after the upcoming release)
Testing
-------
Running the test suite should be enough to make sure we have any regression
=> revert service on by default and update version

.flake8-base, CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Bump to 0.13.0.dev2

wandb/wandb_agent.py
Description
-----------
Issues a teardown on the wandb service between agent executions.
Testing
-------
manual testing but we might be able to run wandb/sweeps testing on this.
Checklist
-------
=> Fix sweep agent with service

tests/unit_tests/test_dtypes.py, wandb/sdk/data_types/_dtypes.py, wandb/util.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix(weave): Fix empty type equals invalid type and how artifact dictionaries are handled

.git-blame-ignore-revs
Description
-----------
Add blame ignore file (see https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/)
Generated by looking at the top 50 commits by number of files changed:
```shell
% git log  | grep -E ^commit | awk '{print $2}' | xargs -n 1 ./show-patch.sh
% cat show-patch.sh                                                                                                                                               (add-blame-ignore)client
lines=`git show $1 | diffstat | tail -1 | awk '{print $1}'`
echo $lines $1
```
Testing
-------
Untested
=> Add blame ignore

tests/functional_tests/t0_main/keras/keras_flops_functional_tf_2_6.yea, tests/functional_tests/t0_main/keras/keras_flops_sequential_tf_2_6.yea
Description
-----------
Fix keras flops tests
Testing
-------
CI.
Checklist
-------
=> Fix keras flops tests

tests/functional_tests/t0_main/imports/02-batch2-requirements.txt
Description
-----------
Fix breakage in using `flair` with the latest `conllu`
Testing
-------
circleci
=> Untested fix for flair/conllu breakage

wandb/integration/keras/keras.py
Description
-----------
Sanitizes artifact name. 
Testing
-------
Checklist
-------
=> feat(modelreg): KerasCallback model artifact saving -- sanitize artifact name

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
bumps version
Testing
-------
N/A
=> bumps master version to 0.13.0rc6dev1

tests/unit_tests/test_public_api.py, wandb/apis/public.py
Fixes WB-9316
Description
-----------
Adds the Sweep State property in Public API.
Testing
-------
How was this PR tested? Locally
Checklist
-------
=> Sweep State in Public API

.circleci/config.yml, tox.ini
Description
-----------
Pin pyupgrade version so we dont end up breaking the build..  We can add a test in nightly or some other cadence to unpin this (and maybe with some other code cleanup things, like black, flake etc)
Testing
-------
Not tested
=> Pin pyupgrade version

.circleci/config.yml, .github/ISSUE_TEMPLATE/app-bug.yml, .github/ISSUE_TEMPLATE/client-bug.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/workflows/check-mocks-synced-with-yea-wandb.yml, .github/workflows/nightly-darglint.yml, ARCHITECTURE.md, CHANGELOG.md, README.md, docs/dev/diagrams.md, docs/dev/service-artifact.md, docs/dev/wandb-service-user.md, package_readme.md, pydoc-markdown.yml, tests/functional_tests/t0_main/kfp/wandb_probe.py, tests/standalone_tests/artifact_table_load.py, tests/standalone_tests/shards/gke_cpu/Dockerfile, tests/standalone_tests/shards/gke_gpu/Dockerfile, tests/unit_tests/test_redir.py, tests/utils/parse_metrics.py, tools/diff_cli_files.sh, tools/telemetry-tool.py, tools/tracelog-tool.py, wandb/integration/metaflow/metaflow.py, wandb/integration/prodigy/prodigy.py, wandb/sdk/data_types/video.py, wandb/sdk/service/service.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> `client -> wandb`: address remaining renaming-related issues

wandb/sdk/service/service.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Adds _internal_proc initialization in Service

tests/unit_tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py
=> Revert "Ensures `metadata` passed to `Artifact()` is a legal dict"

CHANGELOG.md
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Adds CHANGELOG for release 0.13.0

tests/functional_tests/t0_main/lightning/t0_strategy_ddp.py, tests/functional_tests/t0_main/lightning/t1_strategy_ddp_spawn.py, tests/functional_tests/t0_main/lightning/train_gpu_ddp.py, tests/functional_tests/t0_main/lightning/train_tpu_ddp.py
Description
-----------
Fixes the PL tests to use the updated api in the Trainer class
Testing
-------
Test that were failing should pass
Checklist
-------
=> Fixes PL tests to use the new api

tests/unit_tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py
Reverts wandb/wandb#4039
So meta!!
=> Revert "Revert "Ensures `metadata` passed to `Artifact()` is a legal dict""

tests/unit_tests/wandb_run_test.py, wandb/sdk/wandb_run.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Prevent run.log() from mutating passed in arguments

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> 0.13.2.dev1

tests/functional_tests/t0_main/imports/05-batch5.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Hotfix for 05-batch5.py

.circleci/config.yml
Description
-----------
Update docker-cli-buildx version accidentally overwritten in #4066.
Testing
-------
Checklist
-------
=> Fix accidental overwrite in config.yml

tests/unit_tests/conftest.py
Description
-----------
This PR teardown `service` by the end of the test instead of the beginning
Testing
-------
Gate
=> Moves  service teardown to the end of test

tox.ini
Description
-----------
Oops.. accidentally checked in dev yea/yea-wandb.. this moves to the latest release version yea-wandb==0.8.9
Testing
-------
circleci
=> Fix yea-wandb dev release -> release

setup.py
Description
-----------
Fixes minor link name in the setup file
Testing
-------
No need
=> follow up clean of client->wandb rename

.circleci/config.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> Update docker buildx

wandb/sdk/internal/internal_api.py
Description
-----------
Increase the time for artifact commit
Testing
-------
Manually
=> Add additional time for artifact commit

wandb/cli/cli.py
Description
-----------
- Fixes a typo in wandb enabled message
- Adds a clarification that wandb disabled can be used when running wandb offline in response to some user's confusion
Testing
-------
=> Fixes some small typos in cli output

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Update to the latest version
Testing
-------
Circle
=> Update to 0.13.3.dev1

.circleci/config.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Realized that I forgot to add that, see https://app.circleci.com/pipelines/github/wandb/wandb/15169/workflows/88cbfad3-17d1-48ad-8852-1d7666e146c5/jobs/279240
Testing
-------
Checklist
-------
=> Post slack notification on nightly Win/GPU tests failure

wandb/sync/sync.py
Description
-----------
Fix log string (variable was not included)
Testing
-------
=> Fix variable inclusion in log string

wandb/data_types.py
Description
-----------
Fixes deserialization of tables created with numeric columns
Testing
-------
Checklist
-------
=> fix(tables): Deserialization of numeric columns

.github/workflows/codeql-analysis.yml
Description
-----------
This PR adds code analysis/scanning with `codeql` offered by GH, creates a new GitHub Action `codeql-analysis.yml`.
Testing
-------
Checklist
-------
=> Adds code analysis/scanning with `codeql`

wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/launch.py
[Fixes WB-10906](https://wandb.atlassian.net/browse/WB-10906)
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> bugfix(launch): cast agent config max_jobs to int

.github/pull_request_template.md, .github/workflows/pr.yml, CONTRIBUTING.md
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
- Add a GH Action to validate PR titles to ensure compliance with Conventional Commits guidelines.
TODOs:
Testing
-------
Checklist
-------
=> ci(sdk): validate PR titles to ensure compliance with Conventional Commits guidelines

wandb/apis/public.py
Fixes https://github.com/wandb/wandb/issues/4308
Description
-----------
Fixes example display name attribute in publicApi.runs()
Testing
-------
Checklist
-------
=> docs(public-api): fix example filter for display name

wandb/apis/public.py
=> Revert "docs(public-api): fix example filter for display name"

tests/standalone_tests/artifact_object_reference_test.py
Description
-----------
Fix test
Testing
-------
Tested with regression suite:
```
./do-cloud-regression.sh --cli_branch  fix-artifact-ref-test-assets --spec wandb-standalone-artifact-references:init:py37 tests/main/
```
Checklist
-------
=> test(artifacts): fix artifact ref test asset directory

.github/release.yml
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): use the gear emoji to denote Dev changes in the changelog/release notes

CHANGELOG.md
Description
-----------
changelog for 0.13.4 release
Testing
-------
Checklist
-------
=> chore(sdk): add changelog for 0.13.4 release

.circleci/config.yml, CONTRIBUTING.md, README.md, package_readme.md, wandb/integration/prodigy/prodigy.py
Description
-----------
Update a few files to reference the new default branch: `main`
Mainly focuses on updates to documentation and doc-strings.
Testing
-------
CircleCI
Checklist
-------
=> chore(sdk): rename default branch to `main`

.gitattributes
Description
-----------
Fix mistake update linguist attribute in https://github.com/wandb/wandb/pull/4354
Testing
-------
Tested at:
https://github.com/wandb/wandb/pull/4398
=> style(sdk): fix gitattribute for protobuf generated files

tests/unit_tests/test_public_api.py, tests/unit_tests/test_wandb_sweep.py, wandb/apis/public.py
=> revert(sweeps): add `expected_run_count` property to Sweep's public api

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
bump to 0.13.6dev1 and changelog
Testing
-------
circle
=> build(sdk): bump SDK version to latest dev version

tests/functional_tests/t0_main/sklearn/t2_fix_error_cond_feature_importances.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(sdk): update t2_fix_error_cond_feature_importances to install scikit-learn

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
What's in a name?
Testing
-------
Checklist
-------
=> chore(sdk): bump version to 0.13.7.dev1; update changelog

.circleci/config.yml, tools/cloud-tool.py
Description
-----------
- the gke-gcloud-auth-plugin was removed from the OSS kubectl in v1.26, and the setup we had was picking up a wrong kubectl installed into the system -- cleaned this up. 
- 
Testing
-------
[How was this PR tested?](https://app.circleci.com/pipelines/github/wandb/wandb/17285/workflows/49e5d16f-2d6a-4922-83a3-7949abef8dc2)
Checklist
-------
=> chore(sdk): enhance nightly cloud testing process

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
- Bump sdk version to 0.13.8.dev1.
- Update changelog.
Testing
-------
Checklist
-------
=> chore(sdk): bump sdk version to 0.13.8.dev1

wandb/cli/cli.py
Updates help text to actually reflect the truth.
=> chore(sweeps): typo in docs

tests/unit_tests/test_internal_api.py
Description
-----------
Exactly what it says on the tin!
=> test(sdk): add tests for Api.upload_file_retry

tests/unit_tests/artifacts/test_wandb_artifacts.py, tests/unit_tests/artifacts/test_wandb_artifacts_cache.py
Just add some test cases that cover code that wasn't previously tested.
=> test(artifacts): improve storage handler test coverage

tests/functional_tests/t0_main/imports/03-batch3-requirements.txt, tests/functional_tests/t0_main/imports/03-batch3.py, tests/functional_tests/t0_main/imports/04-batch4-requirements.txt, tests/functional_tests/t0_main/imports/04-batch4.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Pics or didn't happen:
Checklist
-------
=> test(integrations): fix import tests

wandb/apis/public.py
Description
-----------
Fixes format issue for #4564 due to premature merge.
Testing
-------
This is just a style change no need to test, only see that the lint passes
Checklist
-------
=> style(public-api): format public file with proper formating

tests/unit_tests/conftest.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(sdk): address fixture server move from port 9003 to 9010 in local-testcontainer

tests/unit_tests/conftest.py, tests/unit_tests/test_file_stream_internal.py
Description
-----------
This PR generalizes the injection logic for testing allowing to specify an injection pattern.
Testing
-------
Checklist
-------
=> feat(sdk): add generalized response injection pattern for tests

wandb/sdk/internal/flow_control.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(sdk): temporary lower network buffer for testing

tests/unit_tests_old/tests_s_nb/test_notebooks.py, wandb/sdk/wandb_run.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
... that was accidentally disabled.
Testing
-------
Checklist
-------
=> chore(sdk): put the Tracking run with... message back in

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
minor fix to bump to the correct version 
Testing
-------
Checklist
-------
=> chore(sdk): bump version 0.13.8.dev -> 0.13.9.dev

wandb/sdk/internal/system/assets/trainium.py
Description
-----------
We need to be extra careful as [neuron tools](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/index.html) could be pre-installed on some systems in AWS that do not have the hardware.
Testing
-------
On AWS:
Checklist
-------
=> fix(sdk): exercise extra caution when checking if AWS Trainium is available in the system

wandb/util.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix(sdk): restore 'util.generate_id' for legacy / user code

CHANGELOG.md, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
This PR bump version to dev and updates the latest changelog
Testing
-------
Checklist
-------
=> chore(sdk): post release 0.13.9 - bump version and update changelog

tests/unit_tests/test_internal_api.py, tests/unit_tests/test_require_helpers.py, tests/unit_tests/test_wandb.py, tools/check-protobuf-version-compatibility.py, tools/circleci-tool.py, wandb/apis/public.py, wandb/apis/reports/_helpers.py, wandb/apis/reports/report.py, wandb/cli/cli.py, wandb/docker/auth.py, wandb/integration/tensorboard/log.py, wandb/sdk/internal/sender.py, wandb/sdk/lib/_wburls_generate.py, wandb/sdk/lib/config_util.py, wandb/sdk/lib/preinit.py, wandb/sdk/lib/printer.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_config.py, wandb/sdk/wandb_require_helpers.py, wandb/sdk/wandb_run.py, wandb/sdk/wandb_settings.py, wandb/util.py
Description
-----------
This PR fixes flake8-bugbear error B028 and ignores (for now until we fix our error codes) B017
Testing
-------
Should pass code-check
Checklist
-------
=> chore(sdk): fix flake8-bugbear B028 and ignore B017

tests/pytest_tests/system_tests/conftest.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(sdk): address fixture server move from port 9010 to 9015 in local-testcontainer

tests/functional_tests/t0_main/lightning/t0_strategy_ddp.yea
Description
-----------
Fix broken lightning test
Testing
-------
The test (0.lightning.0), that used to break, need to pass.
Checklist
-------
=> test(sdk): fix broken lightning test

tests/functional_tests/t0_main/lightning/train_gpu_ddp.yea
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(integrations): fix train_gpu_ddp test

.github/CODEOWNERS
Description
-----------
enforce codeowners for the test_libary test
Testing
-------
not tested
=> chore(sdk): fix codeowners after test restructure

tests/functional_tests/t0_main/imports/09-batch9-requirements.txt, tests/functional_tests/t0_main/imports/12-batch12-requirements.txt
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> test(integrations): fix several import tests

wandb/sdk/internal/sender.py
[Fixes WB-12207](https://wandb.atlassian.net/browse/WB-12207)
Fixes #NNNN
Description
-----------
- adds the alias tag to a job artifact when it is logged
Testing
-------
Checklist
-------
=> fix(launch): Fix issue where job artifacts are being logged without latest alias

tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_cache.py, wandb/sdk/interface/artifacts.py, wandb/sdk/wandb_settings.py
=> revert(artifacts): revert "allow setting artifact cache dir in wandb.init(...)"

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
bump version to 0.13.11.dev1
Testing
-------
circleci
=> chore(sdk): open up 0.13.11 development

CHANGELOG.md
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): Update CHANGELOG.md for 0.13.10

wandb/integration/sacred/__init__.py
Description
-----------
Fix new rule added by bugbear (B028). See [here](https://github.com/PyCQA/flake8-bugbear#list-of-warnings) for more details.
Testing
-------
Lint checks should pass after this fix
Checklist
-------
=> style(sdk): fix bugbear B028 add stacklevel

.github/workflows/release.yml
Description
-----------
Fix an issue in release.yml
Testing
-------
Checklist
-------
=> ci(sdk): update auto-release workflow

.github/workflows/bump-version.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> ci(sdk): more tweaks to the auto-release workflow

.github/workflows/bump-version.yml
Description
-----------
minor fixes to bump version workflow
Testing
-------
Checklist
-------
=> ci(sdk): fix bump version workflow

.github/workflows/bump-version.yml
Description
-----------
replace with commitizen action (trying to debug wrong change log)
Testing
-------
Checklist
-------
=> ci(sdk): use the commitizen action

tox.ini, wandb/integration/tensorboard/monkeypatch.py
Description
-----------
This PR unpins mypy this seems to solve an issue with requests new typing stub, that was causing issues.
Testing
-------
if the code-check passes it means it is fixed!
Checklist
-------
=> chore(sdk): unpin mypy to fix new request typing

wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/runner/aws.py, wandb/sdk/launch/runner/gcp_vertex.py, wandb/sdk/launch/runner/kubernetes.py, wandb/sdk/launch/runner/local_container.py
Fixes [WB-12345](https://wandb.atlassian.net/browse/WB-12345?atlOrigin=eyJpIjoiOTc1Y2EwNDU1MTIzNDE5NmI3MzIwNDllOGMxMWUyN2QiLCJwIjoiaiJ9) (nice)
Description
-----------
Add extra logging statements to make debugging easier in the future.
Testing
-------
N/A
[WB-12345]: https://wandb.atlassian.net/browse/WB-12345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): More detailed logging in runners

CONTRIBUTING.md
Description
-----------
adding r to your in line 74 of CONTRIBUTING.md
``` 3.  Develop you(r) contribution. ```
Testing
-------
N/A - documentation
Checklist
-------
=> fix(sdk): fix a typo in `CONTRIBUTING.md`

.gitignore
Description
-----------
Ignore the data that wandb dumps in the current working directory if run.
Checklist
-------
=> chore(sdk): Ignore wandb run data

tests/pytest_tests/system_tests/conftest.py
Description
-----------
When running pytest system tests with `--wandb-debug`, logging into the app has been broken due to a recent refactor of how the internal auth works with the user fixture in local. This PR addresses it.
Testing
-------
Meta! Tested manually and locally,
Checklist
-------
=> test(sdk): fix admin user creation and setting up passwords for ui for --wandb-debug

.github/workflows/codeql-analysis.yml
Description
-----------
Adds codeql scanning on pull request.
Testing
-------
Tested internally in private repo. 
Checklist
-------
=> chore(sdk): Add codeql scanning on PR for python changes

wandb/cli/cli.py, wandb/sdk/launch/builder/build.py
=> chore(sweeps): cast num_workers as string in sweep command

tests/functional_tests/t0_main/imports/01-batch1.py, tests/functional_tests/t0_main/kfp/kfp-pipeline-helper.py, tests/functional_tests/t0_main/kfp/kfp-pipeline-sklearn.py, tests/functional_tests/t0_main/magic/t1_mnist_convnet.py, tests/pytest_tests/unit_tests/test_data_types.py, tests/pytest_tests/unit_tests/test_metaflow.py, tests/pytest_tests/unit_tests/test_require_helpers.py, tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_tpu.py, tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_trainium.py, wandb/apis/public.py, wandb/cli/cli.py, wandb/integration/kfp/kfp_patch.py, wandb/integration/tensorboard/log.py, wandb/jupyter.py, wandb/sdk/internal/datastore.py, wandb/sdk/internal/system/assets/gpu_apple.py, wandb/sdk/internal/system/system_info.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/launch/runner/kubernetes.py, wandb/sdk/launch/utils.py, wandb/sdk/lib/redirect.py, wandb/sdk/service/service.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_helper.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py, wandb/util.py
Description
-----------
Testing
-------
Checklist
-------
=> style(sdk): remove unused #noqa directives

.github/release.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
What does the PR do? What's in a name?
Testing
-------
Checklist
-------
=> ci(sdk): clean up auto-generated release notes by removing the dev section

CHANGELOG.md, pyproject.toml, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): bump version to 0.13.12.dev1 and update CHANGELOG.md

tests/pytest_tests/system_tests/tests_launch/test_launch_cli.py, tests/pytest_tests/unit_tests_old/tests_launch/test_launch_cli.py, wandb/cli/cli.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> fix(launch): Hide unsupported CLI options from launch

CHANGELOG.md, pyproject.toml, setup.cfg, setup.py, wandb/__init__.py
Description
-----------
What does the PR do? What's in the name!
Testing
-------
Checklist
-------
=> chore(sdk): bump version to 0.14.1.dev1 and update CHANGELOG.md

.vscode/settings.json
Description
-----------
Undo the changes from #4945 to `.vscode/settings.json`, since they broke @kptkin's workflow (and maybe other people's as well).
Checklist
-------
=> chore(sdk): revert .vscode/settings.json changes

.pre-commit-config.yaml, tests/standalone_tests/artifact_references.py, tox.ini
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): pin ruff to 0.0.258

tests/standalone_tests/artifact_references.py, tox.ini, wandb/sdk/internal/handler.py, wandb/sdk/internal/system/assets/interfaces.py
Description
-----------
Add more guardrails around the SM when things should be shutting down.
Testing
-------
Checklist
-------
=> fix(sdk): shut down system monitor in handler.finish

tests/pytest_tests/unit_tests/test_datastore.py, tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py, tests/pytest_tests/unit_tests/test_wandb_settings.py, tests/standalone_tests/artifact_load.py, wandb/analytics/sentry.py, wandb/sdk/lib/git.py
Description
-----------
Missed another `.parent` in the previous sentry-related PR, sry about that!
Testing
-------
Checklist
-------
=> fix(sdk): fix bug in deciding prod vs dev sentry env

CHANGELOG.md, pyproject.toml, setup.cfg, setup.py, wandb/__init__.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): bump to 0.14.2.dev1

.github/pull_request_template.md
Description
-----------
adds the copilot summary and poem to the PR template
Testing
-------
N/A
Checklist
-------
=> chore(sdk): add copilot to the PR summary template

wandb/integration/langchain/util.py, wandb/integration/langchain/wandb_tracer.py, wandb/sdk/data_types/trace_tree.py
=> chore(integrations): Update docs for LangChain integration

tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py, tests/pytest_tests/system_tests/test_sweep/test_sweep_utils.py, tests/pytest_tests/system_tests/tests_launch/test_launch_sweep_cli.py, wandb/cli/cli.py, wandb/sdk/launch/sweeps/utils.py
=> Revert "chore(launch): sweep scheduler uses better arg passing"

tests/pytest_tests/unit_tests/test_saved_model.py
Fixes WB-13717
Removed unnecessary mock.
CI
=> test(artifacts): Artifacts: remove unnecessary mock

wandb/sdk/internal/handler.py
=> revert(sdk): update summary for changed keys only

tests/pytest_tests/unit_tests/test_lib/test_paths.py, wandb/sdk/lib/paths.py
=> revert(sdk): handle uri schemes in LogicalPath

wandb/sdk/artifacts/artifact.py
Fixes WB-14061
We avoid adding the same `WBValue` object to an artifact multiple times by keeping a map from `id(obj)` to its `ArtifactManifestEntry`. `id(obj)` is the memory address of the object, which means it's only unique as long as the object is not garbage collected. To prevent garbage collection, we need to keep a reference to the object as well.
Note that this is going back to what we did before https://github.com/wandb/wandb/pull/5454.
TBD
=> fix(artifacts): store a reference when storing memory address

wandb/sdk/artifacts/artifact.py
Fixes WB-13943
- added missing docstrings, undocumented exceptions
- fixed examples, applied black formatting
- removed types from docstrings, since they duplicate the information that is already present in type annotations
- reordered sections to be consistent: description, Arguments, Returns, Raises, Examples
- removed Returns from properties, since it duplicates information from the description
- fixed description of add, get_path
n/a
=> docs(artifacts): update docs

wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Docs: https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html
n/a
=> docs(artifacts): fix comment about total retry time

tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py
Fixes the sweep test suite sorry!
=> chore(sweeps): tests move name -> id

wandb/sdk/launch/agent/agent.py
followup for [WB-14150](https://wandb.atlassian.net/browse/WB-14150)
[WB-14150]: https://wandb.atlassian.net/browse/WB-14150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(sweeps): paused is not a terminal state

tests/pytest_tests/system_tests/test_launch/test_launch_cli.py, tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py, tests/pytest_tests/unit_tests_old/tests_launch/test_kaniko_build.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/agent/job_status_tracker.py, wandb/sdk/launch/builder/build.py, wandb/sdk/launch/runner/abstract.py, wandb/sdk/launch/runner/kubernetes_runner.py
=> revert(launch): revert job re-queuing implementation on pod disconnect

wandb/apis/reports/_panels.py
https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1692834637560349
=> fix(sdk): reports api - fix media_keys json path

wandb/sdk/artifacts/storage_handlers/gcs_handler.py
Fixes WB-15985
- removed a check whether versioning is enabled on the bucket. Even if versioning is disabled, objects still have a version assigned and specifying it is perfectly valid. More importantly, the check was incorrectly cached.
- fixed a case where a non-existent version was specified. Before, we used the current version. After, we raise an error.
Before:
After:
=> fix(artifacts): remove versioning enabled check in GCS reference handler

tests/pytest_tests/system_tests/test_launch/test_job_status_tracker.py
Description
-----------
https://wandb.atlassian.net/browse/WB-16154
Fixes Launch test flake (maybe)
Improve a system test for the job status tracker.  Add an assertion for the run configuration in `test_job_status_tracker.py`.
=> chore(launch): improve launch test flake

.github/CODEOWNERS
Made @wandb/mlw-team own artifacts code.
n/a
=> chore(artifacts): make @wandb/mlw-team own artifacts code

nexus/README.md
Fixes WB-15031
Updated Artifacts status in Nexus readme.
n/a
=> chore(artifacts): update Nexus readme

.circleci/config.yml, tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> test(core): enable system tests of system monitor

wandb/sdk/launch/create_job.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): improve error message for git repo missing requirements.txt

wandb/sdk/launch/sweeps/scheduler.py
Description
-----------
- Fixes WB-16674
Testing
-------
=> feat(launch): Sweeps on Launch honors selected job priority for sweep runs

.vscode/settings.json, core/internal/debounce/debounce_test.go, core/internal/watcher/event.go, core/internal/watcher/registry.go, core/internal/watcher/watcher.go, core/internal/watcher/watcher_test.go, core/scripts/pre-commit-hooks/run-go-unit-tests.sh, tests/pytest_tests/system_tests/test_core/test_sync_tb.py
Description
-----------
- Fixes #NNNN
Implement basic Tensorboard sync feature in wandb-core: tfevent files will now be synced to the run so that a TB tab will be available in the FE.
Testing
-------
TODO: add unit tests
=> test(core): add tests for watcher

core/pkg/server/sender.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(core): add send cancel request to sender

core/pkg/monitor/memory.go
Description
-----------
- Fixes WB-16810
- Fixes #NNNN
Handle errors properly when monitoring memory consumption.
Testing
-------
=> fix(core): check errors in memory monitoring

tests/pytest_tests/system_tests/test_core/test_sync_tb.py, wandb/integration/ultralytics/bbox_utils.py, wandb/integration/ultralytics/callback.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(integrations): fix linting in ultralytics integration

core/internal/filetransfer/file_transfer_manager.go, core/pkg/artifacts/manifest.go, core/pkg/server/sender.go, tests/pytest_tests/system_tests/test_artifacts/test_model_workflows.py, wandb/sdk/artifacts/artifact.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(core): download artifacts with wandb-core without an active run

core/internal/watcher/watcher_test.go, tox.ini
Description
-----------
- Fixes #NNNN
Testing
-------
=> test(sdk): fix code-check and a test in watcher_test.go

.bumpversion.wandb.cfg, CHANGELOG.md, wandb/__init__.py
Description
-----------
This PR adds the latest release notes and bumps the sdk version
Testing
-------
=> chore(sdk): merge dev branch into main
