.github/workflows/release-sdk.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> ci(sdk): increase wait time to make sure we get the latest version

wandb/sdk/launch/agent/config.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): warn of extra fields in environment block instead of erroring

core/pkg/server/store.go, core/pkg/server/store_test.go
Description
-----------
Minor clean up of the header ser/deser for store 
Testing
-------
=> refactor(core): redo header to be more idiomatic

wandb/sdk/launch/agent2/job_set.py, wandb/sdk/launch/queue_driver/abstract.py, wandb/sdk/launch/queue_driver/standard_queue_driver.py, wandb/sdk/launch/utils.py
Description
-----------
- Fixes [WB-17035](https://wandb.atlassian.net/browse/WB-17035)
Testing
-------
[WB-17035]: https://wandb.atlassian.net/browse/WB-17035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Queue driver

wandb/sdk/data_types/video.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(media): lint main

wandb/sdk/launch/queue_driver/abstract.py, wandb/sdk/launch/queue_driver/passthrough.py, wandb/sdk/launch/queue_driver/standard_queue_driver.py
Description
-----------
-Implements part of [WB-17041](https://wandb.atlassian.net/browse/WB-17041)
Implements the LA2.0 passthrough queue driver, which is a thin wrapper around the internal API queue driver methods. 
[WB-17041]: https://wandb.atlassian.net/browse/WB-17041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(launch): passthrough queue driver

wandb/sdk/launch/agent2/job_set.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> Fix wait_for_update

wandb/sdk/launch/agent2/__init__.py, wandb/sdk/launch/agent2/agent.py, wandb/sdk/launch/agent2/builder.py, wandb/sdk/launch/agent2/controller.py, wandb/sdk/launch/agent2/controllers/k8s.py, wandb/sdk/launch/agent2/controllers/local_process.py, wandb/sdk/launch/agent2/job_set.py, wandb/sdk/launch/agent2/registry.py, wandb/sdk/launch/agent2/runner.py
Description
-----------
- Fixes #NNNN
This PR adds some baseline functionality for the kubernetes controller. I also ran `ruff` on this which made a bunch of changes, that's the bulk of the PR. `controllers/k8s.py` is almost exactly the same as `controllers/local-process.py` 
Testing
-------
=> add baseline functionality for k8s controller

wandb/sdk/launch/agent2/__init__.py, wandb/sdk/launch/agent2/agent.py, wandb/sdk/launch/agent2/controllers/__init__.py, wandb/sdk/launch/agent2/controllers/local_container.py, wandb/sdk/launch/agent2/controllers/local_process.py, wandb/sdk/launch/agent2/job_set.py, wandb/sdk/launch/queue_driver/passthrough.py, wandb/sdk/launch/utils.py
Description
-----------
- Fixes [WB-17039](https://wandb.atlassian.net/browse/WB-17039)
Add a "local Docker container" launch controller and fix some bugs in the local process controller
Testing
-------
Was able to run a job from a docker queue
[WB-17039]: https://wandb.atlassian.net/browse/WB-17039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add local container launch controller

noxfile.py
Description
-----------
Adds a "proto-go" option to noxfile.py to build protos for Go.
Testing
-------
N/A
=> refactor(sdk): Add "proto-go" to noxfile.py

core/README.md, wandb/sdk/lib/_wburls_generated.py, wandb/sdk/lib/wburls.py, wandb/sdk/service/service.py
Description
-----------
Print a message when using wandb-core.
Testing
-------
=> chore(core): print a message when using wandb-core

wandb/cli/cli.py
Description
-----------
seperated -> separated
Testing
-------
=> fix(cli): typo in cli.py

noxfile.py
Description
-----------
minor type fix for the proto generation function in the noxfile.py
=> chore(sdk): fix a nox function missing a session argument

client/Cargo.lock
Description
-----------
minor clean up
=> chore(core): fix pre-commit clippy

.circleci/config.yml, noxfile.py, tox.ini
Description
-----------
Orb documented at https://circleci.com/developer/orbs/orb/codecov/codecov
Testing
-------
Wait to see codecov results on this PR.
=> chore(sdk): Use codecov's CircleCI orb instead of custom nox session

wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/builder/build.py
Description
-----------
-[ Fixes WB-17646](https://wandb.atlassian.net/browse/WB-17646)
- Fixes #NNNN
Fixes the enterypoint when a user provided a Dockefile.wandb 
Testing
-------
=> fix(launch): Fix entrypoint specification when using a Dockerfile.wandb

.circleci/config.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): Fix launch CI image

.bumpversion.wandb.cfg, .github/pull_request_template.md, .github/release.yml, .github/workflows/release-core.yml, CHANGELOG.md, wandb/__init__.py
Description
-----------
What does the PR do? Include a concise description of the PR contents
Update the version to the new dev version + minor clean up
=> chore(sdk): bump to dev version (0.16.5.dev1)

pyproject.toml
Description
-----------
minor clean up of the pytest output
Testing
-------
N/A
=> chore(sdk): make output log more readable

tests/pytest_tests/unit_tests/test_reports/test_reports.py, wandb/apis/reports/v2/interface.py, wandb/apis/reports/v2/internal.py
Description
-----------
Adds better annotations so polyfactory will generate the correct fixtures
Testing
-------
Unit tests
=> chore(sdk): Fix flaky report test

core/internal/runconfig/runconfig_test.go
Description
-----------
Testing
-------
=> test(launch): test that FilterTree does not mutate original data

core/internal/watcher/watcher.go
Description
-----------
Flake: https://app.circleci.com/pipelines/github/wandb/wandb/31847/workflows/dd1c93b8-5b16-43c2-bd4f-7ec814f0a184/jobs/1061205?invite=true#step-102-78
My best guess is that this happens because a non-Create event gets processed first. I don't know what that event could be, but I updated the code to synchronously the given handler before registering it.
Testing
-------
Existing unit tests.
=> chore(sdk): Try fixing watcher.go flakes

tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
Description
-----------
Disable launch test that keeps flaking, will be re-enabled when fixed
Testing
-------
=> chore(sdk): disable flaky luanch test

tests/pytest_tests/system_tests/test_importers/test_wandb/test_wandb.py
Description
-----------
Temporarily, disable flaky importer test until it is fixed. 
Testing
-------
=> chore(sdk): disable flaky importer test

core/internal/runfiles/runfiles_test.go, core/internal/runfiles/uploader.go
Description
-----------
Implements file uploading in the new runfiles package. Doesn't implement 'live' mode or send FileTransferInfoRequests yet.
Testing
-------
Unit tests only. Not yet wired up to the rest of the program.
=> chore(core): Implement runfiles uploading

wandb/sdk/internal/file_stream.py
Add new environment variable to debug filestream issues when we exceed the 10MB limit. This is meant to be a temporary solution and we will remove the debug logic in a future release.
To use, set: `WANDB_DEBUG_FILESTREAM_LOG=true`, this will print the following message only once when we encounter an error.
```
wandb: ERROR Summary data exceeds maximum size of 10.4MB. Dropping it.
wandb: ERROR Step: 4 | ['0: 2.86102 MB', '_timestamp: 0.00002 MB', '_runtime: 0.00002 MB', '_step: 0.00000 MB', '1: 2.86102 MB', '2: 2.86102 MB', '3: 2.86102 MB', '4: 2.86102 MB']
```
=> chore(sdk): add temporary debugging logic for filestream size issues

core/internal/runconfig/runconfig.go, core/pkg/observability/printer.go
Description
-----------
Testing
-------
=> chore(core): minor clean up

MANIFEST.in
Description
-----------
Realized that we don't have these files anymore
Testing
-------
N/A
=> chore(sdk): remove deleted files from manifest

core/api/graphql/query_run_stop_status.graphql, core/internal/gql/gql_gen.go, core/pkg/server/handler.go, core/pkg/server/sender.go
Description
-----------
- Fixes WB-18087
Testing
-------
=> feat(core): add support for stop status

pyproject.toml
https://github.com/ijl/orjson/issues/468
=> chore(sdk): Skip orjson version 3.10.0

pyproject.toml, requirements_build.txt
Issue is fixed: https://github.com/ijl/orjson/issues/468
=> chore(sdk): Revert orjson constraint

wandb/sdk/launch/runner/kubernetes_monitor.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): make KubernetesMonitor error more verbose

core/internal/runfiles/uploader.go, core/pkg/server/handler.go, core/pkg/server/sender.go, tests/pytest_tests/system_tests/test_core/test_wandb_save.py
There were two issues:
1. I forgot to call UploadRemaining()
2. I was calling Finish() in the Handler, but it is blocking
=> fix(core): Fix run.save() end behavior in Nexus

.circleci/config.yml, wandb/sdk/lib/run_moment.py
Description
-----------
This fixes an issue where we using typing that is not supported in python 3.7
Testing
-------
=> chore(sdk): fix py37 failures

wandb/sdk/launch/sweeps/scheduler.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): Fix polling sleep falsey check

core/pkg/server/connection.go
Description
-----------
- Fixes WB-18101
Temporary fix until we redo our close path for connections and streams. 
Testing
-------
=> fix(core): hack work around to deal with implicit shut down

CHANGELOG.md, tests/pytest_tests/unit_tests/test_wandb_save.py, wandb/sdk/wandb_run.py
=> fix(sdk): Correctly handle run.save() for files in the run directory

CHANGELOG.md, tests/pytest_tests/system_tests/test_core/test_footer.py, wandb/sdk/wandb_run.py
Description
-----------
Adds a link to the project in the footer.
Testing
-------
Updated existing tests
=> fix(sdk): add project link to the footer

pyproject.toml, tests/ruff.toml, tools/ruff.toml
Description
-----------
New version ruff update the config fields, just updating our pyproject.toml with the new format.
Testing
-------
=> chore(sdk): update ruff config files

CHANGELOG.md
```
git diff origin/release-0.16.5..main -- CHANGELOG.md
```
=> chore(core): Fix incorrect changelog entries

.bumpversion.wandb.cfg, CHANGELOG.md, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.16.7.dev1

wandb/sdk/launch/agent2/agent.py, wandb/sdk/launch/agent2/controller.py, wandb/sdk/launch/agent2/controllers/k8s.py, wandb/sdk/launch/agent2/controllers/local_container.py, wandb/sdk/launch/agent2/controllers/util.py, wandb/sdk/launch/agent2/jobset.py, wandb/sdk/launch/queue_driver/abstract.py, wandb/sdk/launch/queue_driver/passthrough.py, wandb/sdk/launch/queue_driver/standard_queue_driver.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): Add Job type, fix typing issues, and have k8s manager use queue driver

core/internal/filetransfer/file_transfer_default.go
Description
-----------
minor clean up
Testing
-------
=> fix(core): fix a minor bug when accessing a nil object

core/internal/execbin/execbin.go, core/internal/shared/shared.go, core/pkg/artifacts/linker.go, core/pkg/artifacts/saver.go, core/pkg/filestream/loop_process.go, core/pkg/launch/config.go, core/pkg/launch/config_files.go, core/pkg/monitor/cpu.go, core/pkg/monitor/memory.go, core/pkg/monitor/monitor.go, core/pkg/observability/printer.go, core/pkg/observability/util.go, core/pkg/server/handler.go, core/pkg/server/sender.go, core/pkg/server/stream.go, core/pkg/server/stream_init.go, core/pkg/server/sync.go, core/pkg/server/writer.go
Description
-----------
Following some of the GoLand suggestions.
Testing
-------
=> chore(sdk): minor go code clean up

tests/functional_tests/t0_main/mp/13-synctb-gradienttape.yea
Description
-----------
skip test that fails on nexus until we fix tensorboard
Testing
-------
=> chore(sdk): skip tensorboard test that fails on core

core/internal/runresume/resume_test.go, core/internal/runresume/runresume.go, core/pkg/server/resume.go, core/pkg/server/sender.go
Description
-----------
- Fixes WB-17243
Testing
-------
=> fix(core): harden resume logic to better handle nil responses

core/internal/filetransfer/file_transfer_stats.go, core/pkg/server/handler.go, wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-17202 and WB-18262
Fix file upload progress reporting by correctly mark file transfer as completed.
Testing
-------
=> fix(core): fix file upload progress reportnig

tests/pytest_tests/unit_tests/test_launch/test_controller/test_local_process.py, wandb/sdk/launch/agent2/controllers/local_process.py
Description
-----------
- Fixes [WB-18025](https://wandb.atlassian.net/browse/WB-18025)
Testing
-------
[WB-18025]: https://wandb.atlassian.net/browse/WB-18025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add unit tests for local process controller

.bumpversion.core.cfg, core/README.md, core/internal/version/version.go, core/wandb_core/__init__.py, noxfile.py, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump wandb-core version to 0.17.0.b12.dev1

tests/pytest_tests/unit_tests/test_launch/test_controller/test_base.py, wandb/sdk/launch/agent/job_status_tracker.py, wandb/sdk/launch/agent2/controllers/base.py, wandb/sdk/launch/agent2/controllers/k8s.py, wandb/sdk/launch/agent2/controllers/local_process.py, wandb/sdk/launch/queue_driver/standard_queue_driver.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> agent2: Handle failing run queue items

core/hatch.py
Description
-----------
makes `subprocess.check_call` happy by only passing strings instead of Pathlib objects.
Testing
-------
=> build(sdk): fix minor issue with build on windows

.circleci/config.yml
Description
-----------
Minor fixes
Testing
-------
=> chore(sdk): fix go on windows and go version

.circleci/config.yml, CONTRIBUTING.md, noxfile.py, pyproject.toml, tox.ini, wandb/sdk/launch/registry/google_artifact_registry.py
Description
-----------
Testing
-------
=> chore(sdk): move all code checks to use noxfile

.circleci/config.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> ci(sdk): fetch and store latest local-testcontainer on GCP

core/pkg/server/sender.go
Description
-----------
In check for stop status if the response is nil or any part of it is nil, we were doing nil pointer de-reference and getting a panic. This change just check to make sure we don't access a nil pointer.
Testing
-------
=> fix(sdk): stop status nil pointer dereference check

noxfile.py
Description
-----------
Pass missing env variables for windows in nox
Testing
-------
=> ci(sdk): pass missing env variables in nox for unit_tests sessions

CHANGELOG.md, wandb/sdk/wandb_run.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(sdk): return empty summary for finished runs

.circleci/config.yml
Description
-----------
enable nexus unit-tests on windows
Testing
-------
=> ci(sdk): enable nexus unit-tests on windows

tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
Description
-----------
Skip tests that fail on windows for async
Testing
-------
=> ci(sdk): skip tests launch tests that fail on windows

tox.ini
Description
---
Removes a little bit of code from tox.ini which got fully migrated to noxfile.py.
=> chore(sdk): Remove "notebooks" factor from tox.ini

core/internal/timer/timer.go, core/pkg/server/handler.go
Description
-----------
Moves the timer implementation into a separate package
Testing
-------
=> refactor(core): move timer to separate package

core/pkg/server/handler.go, core/pkg/server/handler_test.go, core/pkg/server/history_test.go, core/pkg/server/sender.go, core/pkg/server/sender_test.go, core/pkg/server/stream.go, core/pkg/server/writer.go
Description
-----------
Minor clean up, replace options with params.
Testing
-------
=> refactor(core): use params instead of opts in stream

wandb/apis/public/runs.py
Reorder checks in Run.log_artifact to read more easily
ghstack-source-id: e7c0383f6fc45ccd1a8f59e36dc4cbab0b19a9ee
Pull Request resolved: https://github.com/wandb/wandb/pull/7425
=> refactor(artifacts): reorder checks in Run.log_artifact to read more easily

core/pkg/server/handler.go, core/pkg/server/sender.go, core/pkg/server/sender_test.go, core/pkg/server/stream.go
Description
-----------
minor clean up and unification of forward and respond functions 
Testing
-------
=> refactor(core): minor clean up of the forward and response functions

.circleci/config.yml
Description
---
See https://github.com/codecov/codecov-circleci-orb/issues/185.
=> ci(sdk): Re-enable codecov validation, use workaround

.github/workflows/release-sdk.yml
Description
-----------
- Fixes #NNNN
Added a comment about the magically-looking GHA bot credentials in the sdk release action
Testing
-------
=> chore(sdk): add a comment about GHA bot credentials in sdk release action

noxfile.py, tests/pytest_tests/system_tests/test_core/test_metric_full.py, wandb/sdk/lib/proto_util.py, wandb/sdk/wandb_run.py
Description
-----------
- Fixes #NNNN
Previously, we were using <key> and json-dumping the nested keys into <json_val>.
Testing
-------
=> fix(sdk): correctly handle nested keys in summary

noxfile.py
Description
-----------
- Fixes WB-16166
unpin ipython version
Testing
-------
=> ci(sdk): skip broken version instead of pinning

tests/pytest_tests/unit_tests/test_util.py, wandb/util.py
=> fix(sdk): Fix wandb/util.py json_friendly() mutating its argument

.circleci/config.yml, CONTRIBUTING.md, noxfile.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): explicitly configure nox to use uv by default

.circleci/config.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> ci(sdk): install uv for the store-local-testcontainer job in circle

tests/standalone_tests/large_artifact_benchmark.py
Description
-----------
Updates the benchmark script to use the 0.17.x mode of using `wandb.require("core")` instead of installing `wandb_core`
Testing
-------
manually
=> chore(artifacts): update the artifact benchmark to use `wandb.require('core')`

core/internal/filetransfer/file_transfer_stats.go
Description
---
It was a typo all along :)
=> fix(core): Fix file stats tracking

wandb/sdk/internal/job_builder.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): remove trailing ')' from job version name

.circleci/config.yml
Description
-----------
- Fixes #NNNN
We run these tests on Circle's xlarge machines that come with 8 vcpus https://circleci.com/docs/configuration-reference/#x86. Overloading them usually has bad consequencies.
Testing
-------
=> ci(sdk): reduce parallelism in ci

core/internal/runsummary/runsummary.go
Description
-----------
RunSummary is shared between handler and sender, so needed to add a lock.
Fixes: https://app.circleci.com/pipelines/github/wandb/wandb/34242/workflows/f50ced21-f238-40aa-9edf-af7d51ed52a1/jobs/1166481?invite=true#step-105-21902_70
Testing
-------
=> fix(core): add mutex to RunSummary object

core/pkg/launch/job_builder.go, core/pkg/launch/job_builder_test.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): correct malformed inputs section in wandb-job.json if saving inputs to metadata

tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py, wandb/sdk/launch/builder/build.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): look in the right place for `requirements.frozen.txt`

tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py, wandb/sdk/launch/_project_spec.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(sweeps): unbork launch specs with placeholder uris for sweep schedulers

tests/pytest_tests/unit_tests/test_lib/test_hashutil.py
Description
---
I've been seeing occasional mysterious test failures in CI. I don't know if there's anything wrong with the code, but using `open(...).write(...)` is a little suspicious.
=> refactor(sdk): Use open() in context manager in test_hashutil.py

core/pkg/observability/logging.go
Description
---
I think there are few other unused methods in here, but they're used in tests.
=> refactor(core): Delete unused logging methods

core/internal/apitest/apitest.go, core/pkg/filestream/filestream_test.go
Description
---
Rewrites it a bit to make it easier to add new tests. All the tests are the same, except I added some stronger assertions in "batches and sends".
=> refactor(core): Rewrite filestream_test.go

.pre-commit-config.yaml, experimental/client-go/go.mod, experimental/client-go/go.sum
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): move experimental code to a dedicated directory

tests/pytest_tests/system_tests/test_launch/test_launch_manage.py, wandb/sdk/launch/__init__.py, wandb/sdk/launch/inputs/manage.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> feat(launch): job input management sdk

wandb/cli/cli.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): don't pass resource as python runtime to `wandb launch -u`

wandb/sdk/internal/job_builder.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): allow empty program_relpath in job builder

.bumpversion.wandb.cfg, core/internal/version/version.go, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.17.1.dev1

.github/workflows/release-sdk.yml
Description
-----------
For now let's make draft to be able to manually fix it
Testing
-------
=> ci(sdk): make release notes draft for now until we resolve it

core/pkg/server/handler.go, core/pkg/server/sender.go
Description
-----------
Minor fix to make sure we upload the output log file
Testing
-------
=> fix(core): upload output file at the end of the run

CHANGELOG.md
Description
-----------
Accidentally omitted this when bumping version.
Testing
-------
=> chore(sdk): update changelog for 0.17.0

.github/workflows/check-pr-title.yml
Description
-----------
Testing
-------
=> chore(sdk): add deps scope to conventional commit config

core/pkg/monitor/gpu_nvidia.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): fix linting for new gonvml

CONTRIBUTING.md
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): fix wandb logo in contributing.md

CONTRIBUTING.md
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): update linting instructions in contributing.md

wandb/sdk/launch/inputs/internal.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(launch): create non-existing subdirs of tmpdir for config file inputs

wandb/sdk/launch/sweeps/scheduler.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): Prevent scheduler from crashing if keys missing from scheduler overrides block

wandb/sdk/launch/create_job.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> refactor(launch): Warn instead of erroring if entrypoint is not a file

wandb/sdk/wandb_login.py
Description
---
Cleans up `_WandbLogin` in `wandb_login.py` slightly, adding docs and type annotations and removing some unused code.
=> refactor(sdk): Delete unused code & add docs in wandb_login

wandb/apis/importers/wandb.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): Importers: Add support for multiple log files

wandb/cli/cli.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): unhide the `--uri` option of `wandb launch`

CHANGELOG.md
Fixes typo in changelog introduced by #7711
=> chore(sdk): fix typo in CHANGELOG.md

CHANGELOG.md
Description
-----------
This updates the Changelog and mentions the new package
Testing
-------
=> chore(sdk): Add release notes for Workspace API

wandb/sdk/wandb_run.py
Description
---
:)
Fixes WB-18689.
Testing
---
Locally modified core to print messages and ran a simple script with `run.log()` and `time.sleep()`.
=> fix(core): Fix internal message polling

core/internal/api/ratelimittracker.go
Description
---
Update some variable names and comments. Pulled out of a different PR that I decided not to send out in favor of an alternative approach.
=> refactor(core): Update comments in ratelimittracker.go

CHANGELOG.md
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): fix minor issues in changelog

.bumpversion.wandb.cfg, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.17.2.dev1

wandb/sdk/wandb_run.py
Description
-----------
This PR remove dead code that was removed a while back.
Testing
-------
=> chore(sdk): minor clean up remove dead code

.github/CODEOWNERS, wandb/__init__.py
Description
-----------
🚜
Testing
-------
=> chore(sdk): 🚜 enable wandb-core by default in dev versions

tools/bench/_load_profiles.py, tools/bench/bench.py
Description
---
* Change to sentence-case
* Improve wording
=> chore(core): Improve core/README.md

tests/pytest_tests/unit_tests/test_util.py, wandb/util.py
Description
-----------
- Fixes WB-19256
JSONify enum.Enum's as e.name.
Testing
-------
=> fix(sdk): jsonify enum.Enum's as e.name

CHANGELOG.md, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py, tests/pytest_tests/system_tests/test_core/test_cli_full.py, tests/pytest_tests/unit_tests/test_dtypes.py, wandb/sdk/data_types/_dtypes.py, wandb/sdk/data_types/object_3d.py
Description
-----------
- Fixes WB-19320
- Fixes #7812
Numpy removed a number of data types in version 2.0 that were explicitly mentioned in our code in a few places.
Testing
-------
=> fix(sdk): fix issues with numpy 2.0 support

.bumpversion.wandb.cfg, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.17.3.dev1

wandb/sdk/launch/_launch_add.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> docs(launch): do not use stuff that looks like html tags in docstring

.github/workflows/generate-docodile-documentation.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> docs(sdk): Update generate-docodile-documentation.yml

CHANGELOG.md, core/go.mod, core/go.sum, core/vendor/github.com/vektah/gqlparser/v2/ast/decode.go, core/vendor/github.com/vektah/gqlparser/v2/ast/path.go, core/vendor/github.com/vektah/gqlparser/v2/formatter/formatter.go, core/vendor/github.com/vektah/gqlparser/v2/lexer/lexer.go, core/vendor/github.com/vektah/gqlparser/v2/parser/parser.go, core/vendor/github.com/vektah/gqlparser/v2/parser/query.go, core/vendor/github.com/vektah/gqlparser/v2/parser/schema.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/fields_on_correct_type.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/known_directives.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/no_unused_fragments.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/overlapping_fields_can_be_merged.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/possible_fragment_spreads.go, core/vendor/github.com/vektah/gqlparser/v2/validator/rules/values_of_correct_type.go, core/vendor/github.com/vektah/gqlparser/v2/validator/schema.go, core/vendor/github.com/vektah/gqlparser/v2/validator/schema_test.yml, core/vendor/github.com/vektah/gqlparser/v2/validator/vars.go, core/vendor/github.com/vektah/gqlparser/v2/validator/walk.go, core/vendor/modules.txt
Description
-----------
- Fixes #7818
Upgrades `github.com/vektah/gqlparser/v2` from 2.5.11 to 2.5.16 to address a remote DoS vulnerability
Testing
-------
=> security(deps): bump github.com/vektah/gqlparser/v2 from 2.5.11 to 2.5.16

.circleci/config.yml
Description
-----------
- Fixes #NNNN
Fixes legacy test build steps to prevent them from always failing
Testing
-------
=> chore(launch): Fix launch legacy tests

.bumpversion.go.cfg, .circleci/config.yml, CONTRIBUTING.md, core/go.mod, experimental/client-go/go.mod
Description
-----------
Bump go version from 1.22.3->1.22.4
Testing
-------
=> chore(core): bump go version

core/internal/filestream/collectorstate.go
Description
---
Fixes a bug introduced in my last PR (not yet released) where I forgot to remove `s.EventsLines = nil` from `PrepRequest`. I'm going to refactor this file soon.
=> fix(core): Avoid dropping system metrics lines

.bumpversion.wandb.cfg, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.17.4.dev1

core/pkg/server/tokenizer.go
Description
---
Explicitly avoid integer overflow on 32-bit systems.
It seems the only way this condition can realistically happen is with data corruption. For it to happen in practice, there would have to be a proto containing 2GB of data. But on a 32-bit system, with only 4GB (or less) of addressable virtual memory, we'd probably run into an OOM before reaching this point.
=> refactor(core): Prevent integer overflows in tokenizer

core/README.md
Description
-----------
- Fixes #NNNN
Testing
-------
=> docs(core): Update README.md

wandb/sdk/lib/credentials.py
Description
-----------
Follow up to #7734 fixing a minor issue with windows path resolve
Testing
-------
=> fix(sdk): Resolve correct file path for windows

core/pkg/server/handler.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(core): do not send a message to sentry on out-of-order step logs

core/internal/sentry_ext/client.go, core/internal/sentry_ext/client_test.go
Description
-----------
Follow up on #7868 addressing this comment: https://github.com/wandb/wandb/pull/7868#discussion_r1661381110
Testing
-------
=> chore(core): fix file name for the frame handling logic

.bumpversion.wandb.cfg, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
Testing
-------
=> chore(sdk): bump version to dev 0.17.4->0.17.5.dev1

.bumpversion.go.cfg, .circleci/config.yml, CONTRIBUTING.md, core/go.mod, core/internal/filestream/filestreamimpl.go, experimental/client-go/go.mod, noxfile.py, tools/get-go-version.py
Description
-----------
Now just run `nox -s bump-go-version`
Testing
-------
=> chore(sdk): bump go version and add automation

core/pkg/monitor/monitor.go
Description
-----------
* removes a potential block on the aggregate queue
* cleans up control flow
Testing
-------
=> refactor(core): clean up SystemMonitor::Monitor

core/pkg/server/stream.go
Description
-----------
Fix an unfortunate miss in https://github.com/wandb/wandb/pull/7719
Testing
-------
=> fix(core): fix panic capture with sentry

.bumpversion.wandb.cfg
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): Update .bumpversion.wandb.cfg for core readme

CHANGELOG.md
Description
-----------
- Fixes #NNNN
I forgot to update the changelog for https://github.com/wandb/wandb/pull/6941 so adding it here
Testing
-------
=> chore(artifacts): update changelog with link artifact change

wandb/sdk/wandb_run.py
Description
---
Reorganizes the function that shows the "X MB of Y MB uploaded". I was looking at this function because I was considering adding to it.
Testing
---
```bash
truncate -s 10M big_file.txt
```
```python
import wandb
with wandb.init() as run:
run.save("big_file.txt")
```
=> refactor(sdk): Clean up file upload stats footer

core/README.md, core/internal/data_types/data_types_test.go, core/internal/filestream/filestreamimpl.go, core/internal/gqlmock/gqlmock.go, core/internal/gqlmock/remarshall.go, core/pkg/artifacts/builder.go, core/pkg/artifacts/builder_test.go, core/pkg/artifacts/manifest.go, core/pkg/launch/job_builder.go, core/pkg/launch/job_builder_test.go, core/pkg/monitor/gpu_amd_test.go, core/pkg/observability/logging_test.go, core/pkg/utils/files.go, experimental/client-go/pkg/gowandb/run.go, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py, wandb/sdk/artifacts/artifact.py
Description
-----------
Per offline discussion, this PR suggests an SDK system test for `Artifact(..., incremental=True)`.  It is intended to stack on top of -- and merge into, if appropriate -- #7939.
The expected behavior of `incremental=True` is adapted from the description in #2029.
Testing
-------
PR is a test
=> test(artifacts): Add SDK test for artifact incremental mode

.codecov.yml
Description
---
Modifies and cleans up codecov `ignore` settings.
=> chore(sdk): Ignore core/vendor/* in codecov

tools/bench/bench.md
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): Update bench.md

wandb/sdk/wandb_run.py
Description
---
Forward $HOME in Nox tests so that `nox -s system_tests` can use Docker when running locally rather than in CI.
=> chore(sdk): Forward HOME env variable in nox tests

tests/pytest_tests/unit_tests/test_step_upload.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(sdk): fix tests broken by internal_api.Api._extra_http_headers

.github/workflows/release-sdk.yml
Description
-----------
Testing
-------
=> chore(core): update cibuildwheel to 2.19.2

.bumpversion.wandb.cfg, wandb/sdk/lib/tracelog.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): update bumpversion config

.github/workflows/release-sdk.yml, apple_stats/Package.swift
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): set min MacOS to 10.14 for mac wheel

.bumpversion.wandb.cfg, core/README.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
Testing
-------
=> chore(sdk): bump version to 0.17.6.dev1

core/internal/filestream/filestream.go, core/internal/filestreamtest/filestreamtest.go, core/internal/runresume/runresume.go, core/internal/settings/settings.go, core/pkg/server/sender.go
Description
-----------
Pass the start time to file stream to correctly stream system metric events
Testing
-------
=> fix(core): fix resume system metrics relative time

tools/inspect-tool.py
Description
-----------
add pause functionality for the reader 
Testing
-------
=> chore(sdk): add pause in inspect tool

core/internal/filestream/filestream.go, core/internal/filestream/updatestats.go, core/internal/filestreamtest/filestreamtest.go, core/internal/settings/settings.go, core/pkg/server/sender.go
Description
-----------
Fix for the hack solution in #7996
Testing
-------
=> refactor(core): refactor starttime value update in the file stream stats collector

core/README.md
Description
-----------
Testing
-------
=> docs(sdk): organized core/README.md for better readability 

wandb/sdk/wandb_login.py
Description
-----------
https://wandb.atlassian.net/browse/DOCS-913
Point out that Anon mode = None means the same thing as Anon mode = "never". See customer confusion in Jira ticket.
Testing
-------
=> docs(sdk): Added default behavious or anon mode when you log in

core/pkg/server/sender.go
Description
-----------
- Fixes WB-18908
Query to get the server information is best effort so we can ignore it when it fails, and no need to capture telemetry for it.
Testing
-------
=> chore(core): remove capture from server info errors

core/pkg/server/responder.go
Description
-----------
- Fixes WB-19933
This PR fixes a potential race condition in the dispatcher
Testing
-------
=> chore(core): fix race condition in the dispacther

core/internal/api/logging.go
Description
---
Correctly print the request URL, and upgrade to INFO level since there shouldn't be a lot of these and they're great for debugging.
=> refactor(core): Better api/logging.go debug messages

wandb/apis/public/jobs.py, wandb/sdk/launch/_project_spec.py
=> chore(launch): read base_image from job into LaunchProject

tests/pytest_tests/unit_tests/test_launch/test_runner/test_local_container.py, wandb/apis/public/jobs.py, wandb/sdk/launch/_launch.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/runner/local_container.py, wandb/sdk/launch/utils.py
=> chore(launch): support base image jobs in docker runner

core/internal/filestream/updatehistory.go, core/internal/filestream/updatestats.go, core/internal/filestream/updatesummary.go
Description
---
Logs memory addresses of strings that are sometimes affected by memory corruption.
=> chore(core): Log some string memory addresses

tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py, tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/runner/kubernetes_runner.py
=> chore(launch): support base image jobs in k8s runner

.bumpversion.wandb.cfg, .github/workflows/release-sdk.yml, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py
Description
-----------
Bump version to 0.17.7.dev1 and rm a temp hack in release GHA.
Testing
-------
=> chore(sdk): bump version to 0.17.7.dev1

.vscode/settings.json, tests/pytest_tests/unit_tests/test_mode_disabled.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py
Description
-----------
Ensure that all public attributes and methods of the Run object are available in disabled mode.
Testing
-------
=> fix(sdk): fix behavior of Run in disabled mode

.github/workflows/release-sdk.yml, nvidia_gpu_stats/Cargo.lock, nvidia_gpu_stats/Cargo.toml, nvidia_gpu_stats/src/gpu_nvidia.rs, nvidia_gpu_stats/src/main.rs, nvidia_gpu_stats/src/metrics.rs
Description
-----------
- Fixes WB-20333
In this PR:
- Report errors encountered by nvidia_gpu_stats to [Sentry](https://weights-biases.sentry.io/projects/sdk-rust/?issuesType=all&project=4506068829470720).
- Refactor nvidia_gpu_stats to make it more modular.
Testing
-------
- linux vms in gcp with and without gpus.
=> feat(core): add sentry to nvidia_gpu_stats

.bumpversion.wandb.cfg
Description
-----------
Follow-up on https://github.com/wandb/wandb/pull/8122 (fixes a bug there)
Testing
-------
=> chore(sdk): bump version in stubs

.github/workflows/release-sdk.yml
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump timeout in release action

core/internal/runfiles/uploader.go
Description
---
Improves error messages to assist with debugging cases where methods are called after Finish().
=> refactor(core): Better X-after-Finish errors in runfiles

.bumpversion.wandb.cfg, CHANGELOG.md, core/internal/version/version.go, wandb/__init__.py, wandb/__init__.pyi, wandb/__init__.template.pyi
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(sdk): bump version to 0.17.8.dev1

CHANGELOG.md
Description
-----------
Fix a typo in changelog.
Testing
-------
=> chore(sdk): Update CHANGELOG.md

hatch.toml
Description
-----------
Include stub file `__init__.pyi` in the distribution.
Testing
-------
=> chore(sdk): include stub file in the distribution

pyproject.toml
Description
---
We've been using `ruff`.
=> chore(sdk): Remove unused pyproject.toml tool.black section

core/api/graphql/mutation_rewind_run.graphql, core/api/graphql/mutation_run.graphql, core/api/graphql/query_run_resume_status.graphql, core/internal/gql/gql_gen.go, core/internal/runbranch/fork.go, core/internal/runbranch/fork_test.go, core/internal/runbranch/processresponse.go, core/internal/runbranch/resume.go, core/internal/runbranch/resume_test.go, core/internal/runbranch/rewind.go, core/internal/runbranch/rewind_test.go, core/internal/runbranch/state.go, core/internal/runbranch/utils.go, core/pkg/server/sender.go
Description
-----------
- Fixes WB-19497
This PR ports the `rewind` and `fork` logic introduced to the python code in the following PRs:
- rewind(resume_from) #7711, #7751
- fork(`fork_from`) #7078, #7217
Testing
-------
=> feat(core): add support for rewind and fork in core

wandb/sdk/wandb_settings.py
Description
-----------
Testing
-------
=> fix(sdk): prevent using the same run id in fork_from

core/pkg/server/sender.go, core/pkg/server/sender_test.go, tests/pytest_tests/unit_tests/test_lib/test_run_messages.py, wandb/sdk/internal/handler.py, wandb/sdk/service/streams.py, wandb/sdk/wandb_run.py
Description
-----------
Testing
-------
=> fix(core): move version check to the footer

README.md
Removes "free" from README
Description
-----------
Removes the term "free" from the README.
Testing
-------
=> docs(chore): Remove "free" from README page

package_readme.md
Description
-----------
Ticket: https://wandb.atlassian.net/browse/DOCS-936
Testing
-------
=> docs(sdk): Update package_readme.md for PyPi

README.md, package_readme.md
Description
-----------
Adds run.finish() to package readme files.
Testing
-------
=> docs(sdk): add run.finish() to readme.md

core/README.md
Description
-----------
Testing
-------
=> chore(core): update the feature support status

core/README.md
Description
-----------
Testing
-------
=> chore(core): update core/README.md

tests/functional_tests/debug/t2_tracelog_logger.py, tests/functional_tests/jobs/job_repo_end_to_end.yea, tests/functional_tests/mp/05-pool-nofinish.yea, tests/functional_tests/mp/13-synctb-gradienttape.yea, tests/functional_tests/save/save-dir.py, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py, tests/pytest_tests/system_tests/test_core/test_cli_full.py, tests/pytest_tests/system_tests/test_core/test_file_stream_internal.py, tests/pytest_tests/system_tests/test_core/test_footer.py, tests/pytest_tests/system_tests/test_core/test_metric_full.py, tests/pytest_tests/system_tests/test_core/test_redir_full.py, tests/pytest_tests/system_tests/test_core/test_sender.py, tests/pytest_tests/system_tests/test_core/test_system_info.py, tests/pytest_tests/system_tests/test_core/test_wandb_integration.py, tests/pytest_tests/system_tests/test_launch/test_job.py, tests/pytest_tests/system_tests/test_launch/test_launch_add.py, tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
Description
-----------
Testing
-------
=> test(core): enable skipped `wandb-core` tests

tests/pytest_tests/system_tests/test_core/test_metric_full.py
Description
-----------
Testing
-------
=> test(core): fix some define metric tests

tests/pytest_tests/unit_tests/test_launch/test_inputs/test_internal.py
Description
-----------
Testing
-------
=> chore(launch): skip test_handle_config_file_input_pydantic on windows

noxfile.py, pyproject.toml, tests/pytest_tests/conftest.py, tests/pytest_tests/system_tests/test_core/test_metric_full.py, tests/pytest_tests/system_tests/test_core/test_wandb_tensorflow.py, tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py, tests/standalone_tests/mitm_tests/t2_fs_inject.yea
Description
-----------
Testing
-------
=> chore(sdk): rename marker and do some minor clean up

wandb/__init__.pyi, wandb/__init__.template.pyi
Description
-----------
- Fixes https://github.com/wandb/wandb/issues/8217
This PR adds a type stub to `__init__.template.pyi` and generates a new version of `__init__.pyi`
Testing
-------
Tested by running below after the change:
```
echo "from wandb import login" > test.py
pyright test.py
0 errors, 0 warnings, 0 informations
```
=> fix(cli): Generate type stub for login

core/pkg/server/handler.go
Description
---
Instead of using `handlePartialHistoryRequest` with specific values to trigger a flush, call the method called "flushPartialHistory".
=> refactor(core): Flush partial history neatly in handler

core/pkg/monitor/trainium.go
Description
-----------
...to prevent writing an unnecessary config file to disk.
Testing
-------
=> chore(core): add an early availability check for neuron-monitor for aws trainium

core/pkg/server/handler.go
Description
---
These records were unused and do not need to be handled.
=> refactor(core): Remove handleFooter/handleFinal

.github/workflows/codeql-analysis.yml
Description
-----------
Testing
-------
=> ci(sdk): bump action version in CodeQL analysis

.github/workflows/pre-commit.yml
Description
-----------
Testing
-------
=> ci(sdk): update pre-commit github action

wandb/__init__.py, wandb/__init__.pyi, wandb/__init__.template.pyi
Description
-----------
Fixes #8248.
Add missing stubs for finish and log/use_artifact functions.
Testing
-------
=> fix(sdk): add missing stubs for finish and log/use_artifact

.github/workflows/check-pr-title.yml, CONTRIBUTING.md
Description
-----------
Testing
-------
=> chore(sdk): update the cc types and scopes for simplicity

pyproject.toml, tests/system_tests/conftest.py, tests/system_tests/relay.py, tests/system_tests/test_artifacts/test_misc2.py, tests/system_tests/test_core/test_file_stream.py
Description
-----------
- Fixes #5423
Testing
-------
=> chore(sdk): move relay server under tests

core/pkg/server/handler.go
Description
---
Moves the FLUSH_STATS and FLUSH_PARTIAL_HISTORY steps to `handleExit` before forwarding the Exit record. Note that the Sender does not do anything in the BEGIN/FLUSH_RUN/FLUSH_STATS/FLUSH_PARTIAL_HISTORY stages, nor does it do anything special in `sendExit`, so this does not reorder operations.
I had to update `handler_test` as the test cases rely on the Defer record.
=> refactor(sdk): move some Handler 'defer' work

.github/dependabot.yaml, .github/dependabot.yml
Description
-----------
add reviewers + github actions to the code that needs to be 
Testing
-------
=> chore(sdk): update dependabot configuration

core/internal/tensorboard/tensorboard.go
Description
---
Updates the wandb-core TensorBoard integration to use the same logic as Python for computing a namespace, in that it uses an empty namespace if the TB root directory cannot be inferred.
I don't know which behavior is better, but for now we should aim for parity.
=> fix(sdk): use empty TB namespace if no root dir available

core/internal/runconsolelogs/linefile.go
Description
---
File writes happen asynchronously and errors may be reported in `file.Close()`, so if `file.Close()` returns an error, the method can't guarantee it fulfilled its contract.
=> chore(sdk): report file Close() error for output.log

.github/workflows/release-sdk.yml
Description
-----------
Testing
-------
=> chore: turn release note step to draft for now

core/pkg/monitor/noop_linux.go, core/pkg/monitor/noop_windows.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore: add GPUNvidia to noop_windows.go in system monitor

wandb/cli/cli.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore: disable core in cli

pyproject.toml
Description
-----------
Issue with `protobuf==5.28.0` on windows, see this issue for more details: https://github.com/protocolbuffers/protobuf/issues/18045
Testing
-------
=> chore: skip broken protobuf version 5.28.0

tests/system_tests/test_core/test_wandb_run.py, wandb/sdk/service/streams.py, wandb/sdk/wandb_run.py
Description
-----------
remove footers version checks
Testing
-------
=> chore: remove check version

wandb/data_types.py, wandb/sdk/data_types/audio.py
Description
-----------
Testing
-------
=> chore: move audio class to a separate module 

wandb/data_types.py, wandb/sdk/data_types/bokeh.py
Description
-----------
Testing
-------
=> chore: move bokeh to a separate module 

tools/diff_cli_files.sh
Description
-----------
Testing
-------
=> chore: remove unused script

core/api/graphql/generate-graphql.sh, core/api/graphql/generate.go, core/generate.go
Description
-----------
move graphql generation logic closer to source
Testing
-------
=> chore: move graphql generate script closer to source

core/pkg/monitor/noop_freebsd.go
Description
-----------
- Fixes #8371.
Testing
-------
=> fix: add dummy implementations for gpuapple and gpunvidia for freebsd

core/pkg/monitor/noop_freebsd.go
Description
-----------
Fixes #8371. Hopefully this time :)
Testing
-------
=> fix: add dummy implementations for gpuamd and trainium for freebsd

tests/conftest.py, wandb/env.py, wandb/sdk/service/service.py
Description
-----------
- Fixes WB-20901
Testing
-------
=> fix: avoid reporting sentry events

.gitignore, wandb/sdk/service/service.py
Description
-----------
Testing
-------
=> chore: remove unused reference related to yea

CHANGELOG.md
Description
-----------
Testing
-------
=> chore: update changelog regarding sentry fix

core/pkg/artifacts/builder_test.go, core/pkg/launch/job_builder_test.go
Description
-----------
Testing
-------
=> chore: remove print messages from tests

CHANGELOG.md
Description
-----------
Fix merge conflict https://github.com/wandb/wandb/pull/8362/commits/a7956d4fa0ff0e71ae77c27e5bf693932767e63a#r1761588601
Testing
-------
=> chore(sdk): fix merge conflict in CHANGELOG.md from #8362

.github/workflows/release-sdk.yml
=> revert: "chore(deps): bump actions/download-artifact from 3 to 4 in /.github/workflows"

.github/workflows/release-sdk.yml
=> revert: "chore(deps): bump actions/upload-artifact from 3 to 4 in /.github/workflows"

.github/workflows/release-sdk.yml
=> revert: "chore(deps): bump docker/setup-qemu-action from 2 to 3 in /.github/workflows"

apple_stats/Package.swift
Description
-----------
Testing
-------
=> chore: bump minimal version of the apple stats

.github/workflows/release-sdk.yml
Description
-----------
Testing
-------
=> chore: update min targe macos version

core/README.md
Description
-----------
Testing
-------
=> chore: fix minor issues in the core readme

core/pkg/monitor/openmetrics.go, core/pkg/monitor/trainium.go
Description
-----------
Testing
-------
=> chore: fix monitor logging and build issues

wandb/util.py
Description
-----------
- Fixes WB-20848
Testing
-------
=> fix: make working set packages safe in case of a missing distribution

core/README.md
Description
-----------
Testing
-------
=> chore: update core readme

noxfile.py
Description
-----------
Testing
-------
=> chore: script location as it been moved 

CONTRIBUTING.md
Description
-----------
Testing
-------
=> chore: update the contributing doc

tests/system_tests/test_system_metrics/test_system_monitor.py
Description
-----------
Testing
-------
=> chore: use new arguments in monitor test

wandb/errors/__init__.py, wandb/errors/errors.py, wandb/errors/warnings.py, wandb/old/core.py
Description
-----------
Testing
-------
=> chore: remove duplicate code under old

.github/ISSUE_TEMPLATE/sdk-bug.yml
Description
-----------
we renamed the label from a:cli to a:sdk, so need to change it in the template to make sure it is labeled correctly
Testing
-------
=> chore: update label from a:cli to a:sdk in issue template 

core/pkg/server/stream.go
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix: prevent double initialization of logger in core

core/cmd/wandb-core/main.go, wandb/sdk/service/service.py
Description
-----------
> [!NOTE]
> Please note that this change is HOT
> [!TIP]
> Please note that this change is HOT
> [!WARNING]
> Please note that this change is HOT
> [!CAUTION]
> Please note that this change is HOT
> [!IMPORTANT]
> Please note that this change is HOT
Testing
-------
=> chore: imporve help for wandb-core service

core/cmd/wandb-core/main.go, experimental/client-csharp/src/Wandb/Internal/Manager.cs, wandb/cli/cli.py, wandb/sdk/service/server.py, wandb/sdk/service/service.py
Description
-----------
Testing
-------
=> chore: remove deprecated `sock-server` flag

wandb/__init__.pyi, wandb/__init__.template.pyi
Description
-----------
- Fixes WB-21018
- Fixes #8442
This PR fixes the type hints in our `.pyi` stub file, we were using instance assignment instead of type annotation
Testing
-------
=> chore: fix stub type annotations

tests/system_tests/test_functional/conftest.py
Description
-----------
Testing
-------
=> chore: allow to pass arguments to the execute script fixture

core/core.go, core/scripts/pre-commit-hooks/run-go-unit-tests.sh, core/scripts/pre-commit-hooks/run-go-vet.sh
Description
-----------
Testing
-------
=> chore: remove unused top file in wandb-core

core/internal/filetransfer/file_transfer_manager.go, core/pkg/server/stream_init.go
Description
-----------
Some style change following the recommendation in the google style guide see here:
https://google.github.io/styleguide/go/best-practices.html#variadic-options
Testing
-------
=> chore: replace Variadic options with Option structure in the file transfer manager

core/pkg/server/headfoot.go, core/pkg/server/stream.go
Description
-----------
move header/footer helper functions to server pkg instead of having them in util
Testing
-------
=> chore: move headfoot out of util

wandb/util.py
Description
-----------
Testing
-------
=> chore: use metadata attribute for distribution

CHANGELOG.md, core/pkg/monitor/gpu_nvidia.go, nvidia_gpu_stats/src/gpu_nvidia.rs
Description
-----------
Testing
-------
=> fix: nvidia gpu name blooper

wandb/sdk/artifacts/artifact.py
https://weightsandbiases.slack.com/archives/CT4901KC5/p1727472669056929
Description
-----------
- Fixes #NNNN
Testing
-------
=> docs(sdk): fix docstring for Artifact.add_dir()

core/pkg/monitor/noop_darwin.go, core/pkg/monitor/noop_freebsd.go, core/pkg/monitor/noop_windows.go
Description
-----------
Testing
-------
=> fix: fix dummy NewGPUNvidia func signature on win & freebsd

core/pkg/monitor/monitor.go, core/pkg/monitor/tpu.go, core/pkg/monitor/tpu_test.go
Description
-----------
Testing
-------
=> fix: remove unused ListSupportedMetrics func in tpu.go

tests/system_tests/test_core/test_mode_disabled_full.py, tests/unit_tests/test_wandb_run.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py
Description
-----------
Fixes #8513.
Testing
-------
=> chore: set _backend attribute for Run class

experimental/client-csharp/src/Wandb/Internal/Manager.cs
Description
-----------
Testing
-------
manually
=> chore: avoid capturing analytics for c# client

CHANGELOG.md
Mentions #8518 in the changelog.
=> chore: update 0.18.3 changelog for #8518

wandb/data_types.py
Description
-----------
Fixes broken docugen due to missing classes
Testing
-------
=> chore: expose `Media` and `BatchableMedia` classes

experimental/client-csharp/src/Wandb/Internal/TcpClient.cs
Description
-----------
- Fixes #NNNN
Title Explains.
Testing
-------
Tested locally as part of an integration.
=> WandbTcpClient - Limit disposal time to prevent deadlock

wandb/__init__.pyi, wandb/__init__.template.pyi, wandb/sdk/wandb_run.py
Description
-----------
update type annotation in wandb_run to use future annotations.
Testing
-------
=> chore: update type annotation in `wandb_run`

experimental/client-csharp/examples/Basic/Program.cs, experimental/client-csharp/src/Wandb/.editorconfig, experimental/client-csharp/src/Wandb/Internal/SocketInterface.cs, experimental/client-csharp/src/Wandb/Internal/TcpClient.cs, experimental/client-csharp/src/Wandb/Lib/Uuids.cs, experimental/client-csharp/src/Wandb/Run.cs, experimental/client-csharp/src/Wandb/Settings.cs
Description
-----------
- fixes deadlock int he resource disposal path in the experimental C# client
- fixes and suppresses warnings
Testing
-------
=> fix: deadlock in the resource disposal path in experimental c# client

core/internal/randomid/randomid.go
Description
-----------
Testing
-------
=> chore: fix error message in generate unique id

core/pkg/server/headfoot.go, experimental/client-go/pkg/gowandb/run.go
Description
-----------
remove logic that is related to the go client from the wandb-core 
Testing
-------
=> chore: move client print function into the go client

wandb/util.py
Description
-----------
- Fixes WB-20900
Testing
-------
=> chore: fix working set check again

core/internal/gitops/git.go, core/internal/gitops/git_test.go, core/pkg/server/handler.go
Description
-----------
move git ops logic outside of the server pkg
Testing
-------
=> chore: move git related logic to a separate package

wandb/sdk/artifacts/_validators.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix(artifacts): ensure internal helpers validate_tags and validate_aliases accept single strings

noxfile.py, wandb/analytics/sentry.py, wandb/env.py, wandb/sdk/data_types/_dtypes.py, wandb/util.py
For some reason, these showed up in an unrelated PR after I updated the typing_extensions in `pyproject.toml`.
=> chore(sdk): fix a few mypy lints

gpu_stats/Cargo.lock, gpu_stats/Cargo.toml, gpu_stats/src/gpu_nvidia.rs
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix: gpu_stats dependencies on windows

noxfile.py, tests/system_tests/test_functional/test_tensorboard/test_keras_tb_callback.py
Description
-----------
Add explanation on why to use n=4 instead of n=auto for functional tests.
Testing
-------
=> chore: update docs in noxfile.py

wandb/sdk/lib/printer.py, wandb/sdk/wandb_run.py
* Documents all members of `Printer`
* I documented, but didn't fix, the idiosyncrasies of `progress_update` and `progress_close`. I should be able to remove them soon.
* Removes unused members like `abort`
* Removes the `off` and `default_text` parameters in `display()`
=> chore(sdk): document printer.py

wandb/analytics/sentry.py
Description
-----------
Testing
-------
=> chore: move sentry to future annotations

wandb/env.py
Description
-----------
Testing
-------
=> chore: replace annotations in `wandb/env`

wandb/__init__.py
Description
-----------
Testing
-------
=> chore: add future annotation to __init__

tests/unit_tests/test_library_public.py
Description
-----------
Testing
-------
=> chore: fix broken CI

wandb/cli/beta.py, wandb/cli/cli.py
Description
-----------
This PR is a first in a series of PRs that split out the commands that are sub grouped into separate file to avoid very long main file
Testing
-------
=> refactor: split out beta group out of main cli file

wandb/errors/term.py, wandb/sdk/wandb_run.py
Description
-----------
Testing
-------
=> chore: fix typing for 3.7

pyproject.toml, wandb/docker/__init__.py
Description
-----------
Testing
-------
=> chore: add rules UP022 and UP036

pyproject.toml, tests/unit_tests/test_lib/test_apikey.py, wandb/sdk/data_types/video.py, wandb/sdk/launch/_launch.py
Description
-----------
for more details about the rule see: https://docs.astral.sh/ruff/rules/#flake8-implicit-str-concat-isc
Testing
-------
=> chore: add ISC rule and fix issues

CHANGELOG.md, wandb/__init__.pyi, wandb/__init__.template.pyi, wandb/plot/__init__.py
Description
-----------
- Fixes WB-21519
Testing
-------
=> chore: fix type hint for the `wandb.plot` module

wandb/plot/confusion_matrix.py
Description
-----------
- Fixes WB-21485
Testing
-------
=> chore: fix doc-string of `wandb.plot.confusion_matrix` and minor refactor

wandb/plot/confusion_matrix.py
Description
-----------
- Fixes WB-14182
Testing
-------
=> fix: make `y_true` and `preds` types more general

wandb/plot/bar.py, wandb/plot/confusion_matrix.py
Description
-----------
Testing
-------
=> chore: update `wandb.plot.bar` and fix `wandb.plot.confusion_matrix`

wandb/plot/histogram.py
Description
-----------
Testing
-------
=> chore: update `wandb.plot.histogram` docs + typing

tests/unit_tests/test_plot.py, wandb/plot/line_series.py
Description
-----------
This PR updates the type annotation and doc-strings of `wandb.plot.line_series`
Testing
-------
=> chore: update `wandb.plot.line_series`

wandb/plot/bar.py, wandb/plot/confusion_matrix.py, wandb/plot/line.py
Description
-----------
Testing
-------
=> chore: update `wandb.plot.line`

pyproject.toml, wandb/plot/scatter.py
Description
-----------
Update docstring and typing for wandb.plot.scatter
Testing
-------
=> chore: improve docs + type annotation on scatter plot

tests/unit_tests/test_plot.py, wandb/plot/roc_curve.py
Description
-----------
Update docstings and type annotation for `wandb.plot.roc_curve`
Testing
-------
=> chore: update roc curve

tests/unit_tests/test_plot.py, wandb/plot/bar.py, wandb/plot/histogram.py, wandb/plot/line.py, wandb/plot/line_series.py, wandb/plot/pr_curve.py
Description
-----------
modernize wandb.plot.pr_curve 
Testing
-------
=> chore: update docstring + typing for PR curve

tests/system_tests/test_core/test_wandb.py, wandb/__init__.pyi, wandb/__init__.template.pyi, wandb/integration/tensorboard/log.py, wandb/plot/bar.py, wandb/plot/confusion_matrix.py, wandb/plot/custom_chart.py, wandb/plot/histogram.py, wandb/plot/line.py, wandb/plot/line_series.py, wandb/plot/roc_curve.py, wandb/plot/scatter.py, wandb/plot/viz.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/wandb_run.py
Description
-----------
split out the custom chart logic out of the visualization logic.
Testing
-------
=> chore: split custom_chart from viz

tests/system_tests/test_core/test_wandb.py, wandb/__init__.py, wandb/__init__.pyi, wandb/__init__.template.pyi, wandb/integration/tensorboard/log.py, wandb/plot/__init__.py, wandb/plot/bar.py, wandb/plot/confusion_matrix.py, wandb/plot/custom_chart.py, wandb/plot/histogram.py, wandb/plot/line.py, wandb/plot/line_series.py, wandb/plot/pr_curve.py, wandb/plot/roc_curve.py, wandb/plot/scatter.py, wandb/plot/viz.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/wandb_run.py
Description
-----------
Testing
-------
=> chore: move plot_table to custom_chart module

tests/unit_tests/test_plot.py, wandb/plot/confusion_matrix.py, wandb/plot/custom_chart.py, wandb/plot/viz.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/wandb_run.py
Description
-----------
refactor the CustomChart class to use split table and spec logic, moved all relevant logic into a single place.
also cleaned up the plot tests and removed unneeded fixtures
Testing
-------
=> refactor: refactor CustomChart class and fix tests

core/internal/runbranch/state.go, tests/system_tests/test_core/test_wandb.py, wandb/sdk/wandb_init.py
Description
-----------
- Fixes WB-21759
- Fixes #8771 
Testing
-------
=> fix: run.config response must include a "value" key for all values

wandb/sdk/wandb_run.py
Description
-----------
This PR turned out to be a no-op just minor re-name
Testing
-------
=> chore: minor rename of a function and some clean up

.vscode/settings.json
Description
-----------
Update VSCode settings:
- Re-enable standard pylance type checks
- Disable auto-imports
Testing
-------
=> chore: update pylance settings in vscode

CONTRIBUTING.md
Description
-----------
Testing
-------
=> chore: update contributing doc for rust install

requirements_dev.txt
Description
-----------
Fix for #8820 
Testing
-------
=> chore: use boto3 instead of botocore

.github/workflows/pre-commit.yml
Description
-----------
Testing
-------
=> chore: force pre-commit to run on python 3.8

.github/workflows/release-sdk.yml
Description
-----------
Adds missing dependencies for the release action
Testing
-------
=> chore: update release action to include click

wandb/errors/__init__.py, wandb/errors/errors.py, wandb/sdk/lib/service_connection.py
Description
-----------
Export errors related to service/core management so that our users can catch them without having to import our internal modules.
Testing
-------
=> chore: make public errors related to service/core management

wandb/sdk/wandb_settings.py
Description
-----------
Fixes typing to support python 3.7
Testing
-------
=> fix: make wandb_settings work with python 3.7

tests/unit_tests/test_wandb_settings.py
Description
-----------
Minor follow up to #8884 adding simple test for coverage.
Testing
-------
=> chore: add simple test to validate branching args

wandb/sdk/wandb_settings.py
Description
-----------
Testing
-------
=> chore: fix an issue with validator return type

wandb/util.py
Description
-----------
Fix error message to have proper spaces
Testing
-------
=> chore: fix spaces in the error message

CHANGELOG.unreleased.md
Description
-----------
follow up to fix lint issue from #8870
Testing
-------
=> chore: fix format issue

tests/system_tests/test_core/test_footer.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` fixture from test_footer

tests/system_tests/test_core/test_console.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` fixutre from test_console

tests/system_tests/test_core/test_metric_full.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` fixture from test_metric_full

tests/system_tests/test_core/test_wandb_run.py
**Stack**:
- #8918
- #8917
- #8916 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> chore: remove wandb_init fixture from test_wandb_run

tests/system_tests/test_core/test_data_types_full.py, tests/system_tests/test_core/test_wandb_run.py
**Stack**:
- #8918
- #8917 ⬅
- #8916
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> chore: remove wandb_init fixture from test_data_types_full

tests/system_tests/test_core/test_wandb.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` fixture from test_wandb

wandb/errors/links.py, wandb/sdk/internal/settings_static.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore: fix mypy 1.13-related linting

experimental/rust-sdk/src/settings.rs
Description
-----------
Testing
-------
=> chore: fix rust sdk using renamed settings

experimental/go-sdk/internal/uuid/uuid.go, experimental/go-sdk/pkg/gowandb/mailbox.go, experimental/go-sdk/pkg/gowandb/manager.go
Description
-----------
make uuid an internal package
Testing
-------
=> chore: make uuid internal package

experimental/go-sdk/internal/mailbox/mailbox.go, experimental/go-sdk/pkg/gowandb/connection.go, experimental/go-sdk/pkg/gowandb/run.go
Description
-----------
Testing
-------
=> chore: move mailbox to be internal

.circleci/config.yml, .pre-commit-config.yaml, tests/system_tests/test_notebooks/conftest.py, wandb/integration/keras/keras.py, wandb/integration/sklearn/utils.py, wandb/integration/torch/wandb_torch.py, wandb/jupyter.py, wandb/sdk/artifacts/storage_handlers/gcs_handler.py, wandb/sdk/artifacts/storage_handlers/local_file_handler.py, wandb/sdk/artifacts/storage_handlers/s3_handler.py, wandb/sdk/data_types/histogram.py, wandb/sdk/data_types/table.py, wandb/sdk/data_types/utils.py, wandb/sdk/internal/internal_api.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_watch.py, wandb/wandb_controller.py
Description
-----------
Testing
-------
=> chore: install rust in win circleci jobs

tests/system_tests/test_core/test_system_info.py, tests/system_tests/test_core/test_validation_data_logger.py, tests/system_tests/test_core/test_wandb_integration.py
Description
-----------
see title
Testing
-------
=> chore: remove `wandb_init` fixture from tests

core/internal/fileutil/files.go, core/internal/fileutil/files_test.go, core/internal/settings/settings.go, core/internal/stream/sender.go, core/pkg/service_go_proto/wandb_settings.pb.go, tests/system_tests/test_core/test_file_upload.py, wandb/proto/v3/wandb_settings_pb2.pyi, wandb/proto/v4/wandb_settings_pb2.pyi, wandb/proto/v5/wandb_settings_pb2.pyi, wandb/proto/wandb_settings.proto
Description
-----------
See title
Testing
-------
=> chore: sanitize output file name when using user provided labels

CHANGELOG.unreleased.md
Description
-----------
Testing
-------
=> chore: fix format issue in changelog

wandb/cli/cli.py
Description
---------------
fix this bug https://github.com/wandb/wandb/issues/6907
=> fix(artifacts): fix client download for registry artifacts

wandb/env.py
Description
-----------
Unify using just WANDB_DEBUG instead of WANDB_CORE_DEBUG
Testing
-------
=> chore: use WANDB_DEBUG instead of WANDB_CORE_DEBUG

wandb/sdk/wandb_settings.py
Description
-----------
Adds a docstring to settings.
Testing
-------
=> chore: document anonymous setting

tests/system_tests/test_artifacts/test_wandb_run_artifacts.py, tests/system_tests/test_core/test_mode_disabled_full.py, tests/system_tests/test_core/test_resume.py, tests/system_tests/test_core/test_system_info.py, tests/system_tests/test_launch/test_job_status_tracker.py, wandb/sdk/interface/interface.py, wandb/sdk/interface/interface_sock.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py
Description
-----------
This PR replaces all usages of `_run_obj` with `wandb.Settings` and keeps track of all the changes in the settings object.
Testing
-------
=> chore: remove run_obj from Run class

.pre-commit-config.yaml
Description
-----------
Testing
-------
=> chore: bump version dependencies

tests/system_tests/test_functional/console/test_console.py, tests/system_tests/test_functional/test_tensorboard/test_tb_w_sb3.py, tests/system_tests/test_functional/test_tensorboard/test_tensorboardX.py
Description
-----------
Testing
-------
=> chore: remove wandb_init fixture from functional tests

tests/system_tests/test_functional/test_tensorboard/test_tf_summary.py, tests/system_tests/test_functional/test_tensorboard/test_torch_tb.py
Description
-----------
Testing
-------
=> chore: remove wandb_init from functional tests

tests/system_tests/test_core/test_label_full.py, tests/system_tests/test_core/test_mp_full.py, tests/system_tests/test_core/test_public_api.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` fixture from system_tests/test_core

tests/system_tests/test_artifacts/conftest.py, tests/system_tests/test_artifacts/test_model_workflows.py, tests/system_tests/test_artifacts/test_registry.py, tests/system_tests/test_artifacts/test_wandb_artifacts.py, tests/system_tests/test_artifacts/test_wandb_artifacts_api.py, tests/system_tests/test_artifacts/test_wandb_artifacts_full.py, tests/system_tests/test_artifacts/test_wandb_run_artifacts.py
Description
-----------
Testing
-------
=> chore: remove `wandb_init` from test_artifacts

.github/workflows/pre-commit.yml
Description
-----------
fix warning re: go.sum path
Testing
-------
=> chore: fix warnings on the pre-commit action

core/internal/stream/stream_init.go
Description
-----------
Remove usrename handling that is misleading as username is the username for wandb not the host machine
Testing
-------
=> fix: replace env variables with settings for service headers

pyproject.toml
Description
-----------
To avoid accidentally merging a PR with prints in the code, we are adding this new lint rule (T20).
Currently all the existing prints are being skipped, but in follow up PR we need to unskip these.
Testing
-------
=> chore: add rule to avoid prints in code

pyproject.toml, tests/system_tests/conftest.py, tests/system_tests/test_core/test_cli_full.py, tests/system_tests/test_core/test_console.py, tests/system_tests/test_core/test_metric_internal.py, tests/system_tests/test_core/test_mode_disabled_full.py, tests/system_tests/test_core/test_offline_sync.py, tests/system_tests/test_core/test_public_api.py, tests/system_tests/test_core/test_resume.py, tests/system_tests/test_core/test_validation_data_logger.py, tests/system_tests/test_core/test_wandb_settings.py, tests/system_tests/test_functional/console/test_console.py, tests/system_tests/test_functional/interrupt/pass_if_interrupted.py, tests/system_tests/test_notebooks/conftest.py, tests/system_tests/test_notebooks/test_notebooks.py, tests/system_tests/test_plot.py, tests/system_tests/test_sweep/test_wandb_sweep.py, tests/unit_tests/test_data_types.py, tests/unit_tests/test_file_stream.py, tests/unit_tests/test_lib/test_redir.py, tests/unit_tests/test_library_public.py, tests/unit_tests/test_ssl.py, tests/unit_tests/test_system_metrics/test_open_metrics.py, tests/unit_tests/test_util.py, tests/unit_tests/test_wandb_config.py, tests/unit_tests/test_wandb_login.py, tests/unit_tests/test_wandb_summary.py, wandb/sync/sync.py
Description
-----------
Follow up on #9103 
Testing
-------
=> chore: fix T20 rule on more files

pyproject.toml, tests/system_tests/test_core/test_cli_full.py, tests/unit_tests/test_cli.py, wandb/docker/__init__.py, wandb/integration/fastai/__init__.py, wandb/integration/keras/keras.py, wandb/integration/metaflow/metaflow.py, wandb/integration/prodigy/prodigy.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/verify/verify.py, wandb/sdk/wandb_sweep.py, wandb/wandb_agent.py, wandb/wandb_controller.py
Description
-----------
follow up on #9104
Testing
-------
=> chore: fix T20 rule for more files

core/cmd/wandb-core/main.go, core/internal/stream/stream.go, core/pkg/server/connection.go, core/pkg/server/server.go
Description
-----------
make sure to wire through the debug flag passed as an argument to wandb-core
Testing
-------
=> chore: wire through the debug flag for now

core/internal/settings/settings.go, core/internal/stream/handler.go, core/internal/stream/handler_test.go, core/internal/stream/stream.go, core/internal/tensorboard/tensorboard.go
Description
-----------
Testing
-------
=> chore: use hostname from settings for tensorboard

core/cmd/wandb-core/main.go, core/internal/sentry_ext/client.go, core/internal/stream/stream.go, core/pkg/server/connection.go, core/pkg/server/server.go, tests/system_tests/test_core/test_wandb_setup.py, wandb/sdk/service/service.py
Description
-----------
This is minor change to prepare for an option to specify custom debug levels.
Testing
-------
=> refactor: use log levels instead of binary debug flag

gpu_stats/src/gpu_nvidia.rs
Description
-----------
...As they are private now anyways. Re-enable when UI aggregations are merged / there's a request to have them enabled.
Testing
-------
=> chore: disable PCIe stats for Nvidia GPUs

core/internal/observability/logging.go, core/internal/observability/logging_test.go, core/internal/runwork/runwork_test.go, core/internal/stream/stream.go, core/internal/tensorboard/tfeventconverter_test.go
Description
-----------
Further simplification of the logger code, now explicitly includes the sentry client instead of having general capture functions
Testing
-------
=> refactor: simplify the logger interface

wandb/sdk/lib/apikey.py
=> revert: "fix: wandb login anonymously would write invalid value to system settings file"

tests/system_tests/backend_fixtures.py, tests/system_tests/conftest.py, tests/system_tests/test_importers/test_wandb/conftest.py
Description
-----------
- Minor partial cleanup of `test/system_tests/conftest.py`
- Refactors implementation of local backend fixture factories (e.g. `user_factory` -> `make_user`), attempting to reduce nested closures / callbacks
- Separates backend fixtures into their own file (`tests/system_tests/backend_fixtures.py` -- this is treated as a `pytest_plugin` by `conftest.py`)
Testing
-------
N/A
=> chore(sdk): test config cleanup

tests/system_tests/backend_fixtures.py
Description
-----------
N/A
Adds support for adding `organizations` as local backend fixtures during test setup.
Testing
-------
N/A
=> chore(sdk): add support for organization fixture factories

noxfile.py
Description
-----------
Remove unused nox sessions related to the experimental py-rs sdk.
=> chore: remove unused nox sessions

core/api/graphql/schemas/README.md
Description
-----------
This PR updates the ref to the graphql schema version to use when generating graphql queries.
Testing
-------
=> chore: update ref to core graphql schema for latest server info updates.

CONTRIBUTING.md, core/api/graphql/generate-graphql.sh, core/api/graphql/genqlient.yaml, core/api/graphql/schemas/README.md, core/api/graphql/schemas/commit.hash.txt, noxfile.py
Description
-----------
This PR automates the download of the correct schema and auto generate the graphql code based on it.
Testing
-------
=> chore: enforce using correct hash for new graphql schemas

CHANGELOG.unreleased.md, tests/system_tests/test_core/test_cli_full.py, wandb/cli/cli.py, wandb/sdk/internal/internal_api.py
Description
-----------
- Fixes #9134 
- Fixes WB-22524
see title.
Testing
-------
Added system test to exercise this code path
=> fix: remove unsupported settings when using `wandb offline`

wandb/sdk/wandb_run.py, wandb/sdk/wandb_settings.py
Description
-----------
Testing
-------
=> refactor: actually use the settings object instead of internal_api

tests/system_tests/wandb_backend_spy/spy.py
Description
-----------
Testing
-------
=> chore: add support for exit_code in `wandb_backend_spy`

CHANGELOG.unreleased.md
Description
-----------
Adds the changelog entry for #9211 
Testing
-------
=> chore: add changelog entry for the metaflow fix

tests/system_tests/test_launch/test_launch_kubernetes.py
Description
-----------
Testing
-------
=> chore(launch): skip flakey test test_kubernetes_run_clean_generate_name

.circleci/config.yml, requirements_dev.txt
Description
-----------
Fix CI to make sure that we don't install outdated version of tensorflow (this will be skipped for 3.8) and tensorboard 
Testing
-------
=> chore: fix failing CI by explicitly installing tensorboard

.github/workflows/generate-docodile-documentation.yml
Description
-----------
There was a typo resulting in an error, e.g.: https://github.com/wandb/wandb/actions/runs/12659482575/job/35278676891#step:4:1
Testing
-------
=> chore: fix a bug in the reference docs generating GH Action

.github/workflows/release-sdk.yml
Description
-----------
make sure to vendor the correct dependencies for the go==1.22 releases
Testing
-------
=> chore: fix vendoring for go<1.23

.github/workflows/generate-analytics-pr.yml
Description
-----------
This PR adds the analytic step action, this currently not fully working, but i need to have this action merged to be able to iterate on it.
Testing
-------
=> chore: add analytics step to the CI

tools/perf/README.md
Description
-----------
Fixed typos in the README file
Testing
-------
=> chore: (perf) update README

CHANGELOG.unreleased.md, wandb/sdk/data_types/utils.py
Description
-----------
- Fixes [WB-22687](https://wandb.atlassian.net/browse/WB-22687)
Testing
-------
- Verified that table artifact shows up and is accessible via query engine in personal account
[WB-22687]: https://wandb.atlassian.net/browse/WB-22687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(sdk): update sanitization rules for logged table artifact name

tests/conftest.py, tests/system_tests/backend_fixtures.py, tests/system_tests/conftest.py, tests/unit_tests/test_term.py
Description
-----------
N/A
Fixes or attempts to address minor issues with test setup/execution that were encountered in checks on upstack PRs (for automations API).
=> fix(sdk): misc fixes for test setup and config

wandb/sdk/wandb_run.py
Manual fixes for a new `ruff format` change.
=> refactor: reformat wandb_run.py

wandb/sdk/wandb_init.py
Improve Python style in `_WandbInit.init()` where errors from `deliver_run` are checked and add notes about `x_disable_service`.
=> refactor: deliver_run exception handling on init

tests/system_tests/test_artifacts/test_object_references.py
Description
-----------
- [WB-23050](https://wandb.atlassian.net/browse/WB-23050)
Reconfigures `test_audio_refs` so that it uses a factory function `_make_wandb_audio_ref(...)` (instead of module-level constants) to generate `wandb.Audio` instances used in each invocation of the test.
-----
Note: This is meant as a minimal fix for the linked issue.  If possible + time permits, it would be better to just refactor the `_make_wandb_*()` factories into fixtures, in which test objects that need to be shared across tests (e.g. to compare equality) can be session-scoped, otherwise function-scoped.
-----
Context: `test_audio_refs` is failing in CI, evidently only on `wandb_core`.  However, **this is not a `wandb_core` issue**.  To corroborate this, note that:
- Reversing the order of generated …
=> chore(sdk): fix test setup of `test_audio_refs` in test_object_references

tests/system_tests/test_launch/test_launch_kubernetes.py, tests/unit_tests/test_launch/test_runner/test_kubernetes.py
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore(launch): deflake launch kubernetes tests

tools/perf/scripts/bench_run_log.py, tools/perf/scripts/process_sar_helper.py, tools/perf/scripts/run_load_tests.py, tools/perf/scripts/test_case_helper.py
Fixes some `ruff` and `mypy` findings.
=> refactor: lint fixes for tools/perf/scripts

experimental/rust-sdk/Cargo.lock, experimental/rust-sdk/Cargo.toml, experimental/rust-sdk/examples/basic/Cargo.lock
Description
-----------
Fixes security alerts:
https://github.com/wandb/wandb/security/dependabot/1193
https://github.com/wandb/wandb/security/dependabot/1192
Testing
-------
=> security: update the openssl indirect dependency

.github/CODEOWNERS
Description
-----------
Testing
-------
=> chore: add sdk team as code owners on infra changes

tests/unit_tests/test_lib/test_apikey.py, wandb/sdk/lib/apikey.py
This reverts commit 820e47080abd912bafc89c04f48f6e4cf716ee57.
Description
-----------
- Fixes #NNNN
Testing
-------
=> fix: revert "log an error when we do not have access permission to the netrc file (#9334)"

tools/local_wandb_server.py
Description
-----------
If a `local-testcontainer` server was previously started but is no longer running/healthy, `local_wandb_server.py start` still exits with the message: `Server wandb-local-testcontainer is already running.`
PR fixes the behavior of `local_wandb_server.py start` by checking the health of the previous server, if found, and -- if the server no longer appears to be running/healthy -- attempts to restart it.
Testing
-------
=> chore: fix `local_wandb_server.py start` when previous server is no longer running

wandb/sdk/data_types/saved_model.py
Description
-----------
Fix `mypy` failures in CI jobs that seem to look like (e.g. [here](https://app.circleci.com/pipelines/github/wandb/wandb/44078/workflows/9e7e885a-0906-44d0-aa80-383a7e47b587/jobs/1342917?invite=true#step-107-3936_110)):
```
wandb/sdk/data_types/saved_model.py:420: error: Module "tensorflow.keras" is not valid as a type  [valid-type]
wandb/sdk/data_types/saved_model.py:420: note: Perhaps you meant to use a protocol matching the module structure?
wandb/sdk/data_types/saved_model.py:421: error: tensorflow? has no attribute "keras"  [attr-defined]
wandb/sdk/data_types/saved_model.py:422: error: Module "tensorflow" is not valid as a type  [valid-type]
wandb/sdk/data_types/saved_model.py:422: note: Perhaps you meant to use a protocol matching the module structure? …
```
=> chore: fix failing mypy checks in saved_model.py

.gitattributes
https://github.com/github-linguist/linguist/blob/main/docs/overrides.md#generated-code
=> chore: mark core/vendor/ and generated Go protobuf files in gitattributes

CHANGELOG.unreleased.md
Updates the changelog for #9427 just in case anyone used the setting and forgot to remove it.
=> chore: update changelog for PR 9427

wandb/apis/public/api.py
Description
-----------
- Fixes WB-22821
This PR adds more documentation on the root level attributes a user can filter runs by. Currently it is not clear what attributes a user can filter on, and what the names for the fields are.
Testing
-------
=> docs: add more details on fields that are supported by Api.runs query

wandb/sdk/interface/interface_shared.py
After #9420, these are no longer used.
=> refactor: delete unused keepalive fields in interface_shared.py

wandb/__init__.pyi, wandb/sdk/wandb_run.py
Description
-----------
docs(sdk): update link to tables-walkthrough
Testing
-------
N/A
=> docs(sdk): update link to tables-walkthrough

tools/perf/README.md, tools/perf/scripts/bench_run_log.py, tools/perf/scripts/test_case_helper.py
Description
-----------
- add setting x_server_side_derived_summary to perf setting
Testing
-------
Locally
=> chore: add setting x_server_side_derived_summary to perf framework

core/pkg/service_go_proto/wandb_internal.pb.go, gpu_stats/src/wandb_internal.rs, wandb/proto/v3/wandb_internal_pb2.pyi, wandb/proto/v4/wandb_internal_pb2.pyi, wandb/proto/v5/wandb_internal_pb2.pyi, wandb/proto/wandb_internal.proto
Description
-----------
This PR adds doc strings on the Server features to describe the purpose of each feature.
Testing
-------
=> chore: add doc string for ServerFeature enum

core/go.mod
Description
-----------
- Fixes #NNNN
Testing
-------
=> chore: remove accidentally added toolchain statement in go.mod

core/go.mod, wandb/apis/public/api.py
Description
-----------
This is needed for https://wandb.atlassian.net/browse/WB-23517 (see https://github.com/wandb/wandb/pull/9605) -- relaxing pydantic version requirement to allow both v1 and v2. Generated code replaced in this PR required v2.
=> chore: remove dependency of server feature checks on pydantic

wandb/_pydantic/base.py
Description
-----------
Fixes mypy errors introduced by today's release of `pydantic==2.11.0`, e.g. from [link](https://app.circleci.com/pipelines/github/wandb/wandb/45447/workflows/1f885b6e-b44a-45e9-a4dc-a291eeb04a70/jobs/1363141)
```
wandb/_pydantic/base.py:30: error: Signature of "model_dump" incompatible with supertype "BaseModel"  [override]
wandb/_pydantic/base.py:30: note:      Superclass:
wandb/_pydantic/base.py:30: note:          def model_dump(self, *, mode: Literal['json', 'python'] | str = ..., include: IncEx | None = ..., exclude: IncEx | None = ..., context: Any | None = ..., by_alias: bool | None = ..., exclude_unset: bool = ..., exclude_defaults: bool = ..., exclude_none: bool = ..., round_trip: bool = ..., warnings: Literal['none', 'warn', 'error'] | bool = ..., …
```
=> fix(sdk): fix new mypy errors from updated pydantic 2.11 method signatures

tests/unit_tests/test_launch/test_runner/test_kubernetes.py
Description
-----------
see title
Testing
-------
=> chore: skip flaky launch test until fixed

pyproject.toml, tests/unit_tests/test_automations/_strategies.py, tests/unit_tests/test_automations/test_filters.py, tests/unit_tests/test_library_public.py, tools/graphql_codegen/generate-graphql.sh, wandb/_pydantic/__init__.py, wandb/_pydantic/base.py, wandb/_pydantic/v1_compat.py, wandb/automations/_filters/__init__.py, wandb/automations/_filters/expressions.py, wandb/automations/_filters/operators.py
Description
-----------
- Fixes [WB-24128](https://wandb.atlassian.net/browse/WB-24128)
Adds (for now internal) classes for parsing/serializing/handling MongoDB-like query filters.
At the time of implementation, this is specifically intended for supporting filtering expressions in Automation events (see upstack PR: https://github.com/wandb/wandb/pull/8935)
Testing
-------
[WB-22035]: https://wandb.atlassian.net/browse/WB-22035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WB-24128]: https://wandb.atlassian.net/browse/WB-24128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(sdk): filter type definitions for automation event filters

.github/CODEOWNERS
Description
-----------
Updates automations API paths in CODEOWNERS (used in upstack PRs)
Testing
-------
N/A
=> chore: edit codeowners paths for automations

tests/system_tests/test_core/test_public_api.py
Description
-----------
Adds a test against the public API to ensure that the internal `projectId` for a run is returned from the server is an integer.
Testing
-------
=> chore: add tests verifying internal projectid

wandb/cli/cli.py, wandb/jupyter.py, wandb/sdk/lib/apikey.py, wandb/sdk/wandb_login.py
Description
-----------
- Fixes WB-24242
This PR adds a `models` referrer value on wandb links printed by the SDK.
Testing
-------
- `wandb login`
- `python sample.py` with existing account
- `python sample.py` with creating an account
=> chore: add model referrer to printed wandb links

wandb/apis/public/__init__.py, wandb/apis/public/automations.py, wandb/apis/public/integrations.py, wandb/apis/public/projects.py
Description
-----------
- Fixes [WB-22612](https://wandb.atlassian.net/browse/WB-22612)
- Docs: [DOCS-1164](https://wandb.atlassian.net/browse/DOCS-1164)
Adapts existing `Paginator` classes to accommodate Automations (Triggers) and Integrations (i.e. SlackIntegrations and WebhookIntegrations).
Testing
-------
[WB-22612]: https://wandb.atlassian.net/browse/WB-22612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1164]: https://wandb.atlassian.net/browse/DOCS-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(sdk): adapt paginators for automations and integrations

wandb/jupyter.py
Removes the `-w` / `--workspace` option to the `wandb` cell/line IPython magic because it is a no-op.
I attempted fixing it as well, but it does not appear to work: using `%%wandb -w` in a cell that initializes a run produces an iframe that fails to load.
The original code:
```python
if self.opts.get("workspace", False):
if self.path is None and wandb.run:
self.path = wandb.run.path
if isinstance(self.path, str):
object = self.api.from_path(self.path)
else:
object = wandb.run
if object is None:
if wandb.Api().api_key is None:
return "You must be logged in to render wandb in jupyter, run `wandb.login()`"
else:
object = self.api.project(...)
return object.to_html(self.height, hidden=False)
```
If `workspace` is False:
* If `self.path` is set (`%%wandb entity/project/id`), it is used
* Else, …
=> refactor: remove the workspace option to wandb ipython magic

wandb/_pydantic/__init__.py, wandb/_pydantic/base.py, wandb/_pydantic/utils.py, wandb/_pydantic/v1_compat.py, wandb/automations/_filters/operators.py, wandb/automations/_filters/run_metrics.py, wandb/automations/automations.py
Description
-----------
Includes updates to internal pydantic helpers (in `wandb/_pydantic/`) that were made in #8896 while making changes for the Automations API.
Changes in this PR were pulled out of #8896 for easier review and slightly cleaner commit history, per [this comment](https://github.com/wandb/wandb/pull/8896#discussion_r2060807676) and offline discussion.
=> chore: internal changes to pydantic helpers for automations API

CHANGELOG.unreleased.md, tests/system_tests/test_automations/conftest.py, tests/system_tests/test_automations/test_automations_api.py, tests/unit_tests/test_automations/_strategies.py, tests/unit_tests/test_automations/conftest.py, tests/unit_tests/test_automations/test_automations.py, tests/unit_tests/test_automations/test_events.py, tests/unit_tests/test_automations/test_run_events.py, wandb/automations/__init__.py, wandb/automations/_filters/run_metrics.py, wandb/automations/_utils.py, wandb/automations/events.py
Description
-----------
- Fixes [WB-24539](https://wandb.atlassian.net/browse/WB-24539)
Implements support for `RUN_METRIC_CHANGE` events.
Testing
-------
Added unit and system tests
[WB-24539]: https://wandb.atlassian.net/browse/WB-24539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: run metric change events for automations

.github/workflows/release-sdk.yml, core/go.mod.1.22
Description
-----------
Create custom go.mod file to support go 1.22 for macos 10 compatibility 
Testing
-------
=> chore: custom go.mod@1.22 for building core for MacOS 10

.circleci/config.yml
Description
-----------
follow up on this PR #9788, nox fixed the issue with uv
Testing
-------
=> chore: unpin uv

wandb/apis/public/__init__.py
Description
-----------
add registry into public namespace for docs generation
=> chore(artifacts): add registry into public namespace for docs

CONTRIBUTING.md
Description
-----------
Fixes typos and broken links in CONTRIBUTING.md. I tested, the links and they now work as expected.
=> docs: fix typos & broken links in CONTRIBUTING.md

CHANGELOG.unreleased.md, tests/unit_tests/test_data_types.py, wandb/sdk/data_types/image.py
Description
-----------
- Fixes #NNNN
This reverts commit d231626f2d44e05c5d51050921ed931e38f32276.
"fix: inconsistent image normalization for wandb.Image"
Testing
-------
=> revert: "fix: inconsistent image normalization for wandb.Image (#9786)"

core/internal/runmetadata/runmetadata.go, core/internal/runmetadata/runmetadata_test.go
Makes `internal/runmetadata` debounce and flush changes.
=> refactor: runmetadata update methods and debounced syncing

pyproject.toml, wandb/sdk/service/streams.py, wandb/wandb_agent.py
=> refactor: enable and fix TRY203 (useless-try-except)

pyproject.toml, tests/system_tests/test_registries/test_registry.py, tests/unit_tests/test_analytics/test_sentry.py, wandb/apis/public/registries/utils.py, wandb/docker/__init__.py, wandb/docker/auth.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/builder/kaniko_builder.py, wandb/sdk/wandb_login.py, wandb/wandb_agent.py
https://docs.astral.sh/ruff/rules/raise-within-try/
Violating this rule is a sure sign of spaghetti code. I fixed some occurrences but added `# noqa: TRY301` comments in a few places that are too annoying to refactor safely.
=> refactor: enable and fix TRY301 (raising an exception inside try-except)

core/pkg/monitor/dcgm_exporter.go, core/pkg/monitor/openmetrics.go, core/pkg/monitor/openmetrics_test.go, core/pkg/monitor/tpu.go
Description
-----------
...must have missed them in a previous clean-up -- it used to be needed to implement the Asset interface.
Testing
-------
=> chore: remove unused IsAvailable methods from sysmon assets

gpu_stats/Cargo.lock, gpu_stats/Cargo.toml, gpu_stats/src/gpu_nvidia.rs
Description
-----------
What's in a name?
Testing
-------
https://wandb.ai/dimaduev/uncategorized/runs/a8qkm6mv/files/wandb-metadata.json
=> chore: capture Nvidia GPU UUIDs in metadata

wandb/automations/_filters/expressions.py, wandb/automations/_filters/operators.py, wandb/automations/_filters/run_metrics.py, wandb/sdk/data_types/image.py, wandb/sdk/launch/_project_spec.py
Description
-----------
See PR title
Testing
-------
=> chore: ignore mypy errors for new mypy==1.16.0

.codecov.yml
Description
-----------
Before:
After:
=> chore: make codecov ignore tools and tests

CHANGELOG.md
Description
-----------
see title
Testing
-------
N/A
=> chore: fix minor typo in the 0.20.0 changelog

tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Description
-----------
see PR title
Testing
-------
=> chore: skip artifact test that breaks CI

.circleci/config.yml
Description
-----------
see PR title
Testing
-------
=> chore: add test to avoid breaks on import

experimental/client-csharp/.gitignore, experimental/client-csharp/src/Wandb/Internal/IServiceConnectionProtocol.cs, experimental/client-csharp/src/Wandb/Internal/Manager.cs, experimental/client-csharp/src/Wandb/Internal/SocketInterface.cs, experimental/client-csharp/src/Wandb/Internal/TcpClient.cs, experimental/client-csharp/src/Wandb/Wandb.cs
Adds Unix socket support to the experimental C# client and includes a little bit of refactoring.
=> refactor: support Unix sockets in the C# client

wandb/sdk/lib/console_capture.py
Fixes a race condition where the client may send `OutputRaw` records after an `Exit` record, despite `wandb_run.py` unregistering `console_capture.py` callbacks before calling `deliver_exit()`. [Seen in CI](https://app.circleci.com/pipelines/github/wandb/wandb/48595/workflows/31cb5be9-6532-49ba-b4ae-fb30a20346b6/jobs/1414514/parallel-runs/5).
=> fix: race between OutputRaw and Exit records

tests/system_tests/backend_fixtures.py
Description
-----------
- Adds support for team (entity) fixtures in system tests
- Implements `make_team` method in backend fixtures to create teams with associated organizations
- Adds necessary dataclasses for team commands and state management during test setup/teardown
=> chore: add backend fixtures for teams

tests/system_tests/test_core/test_metric_full.py, wandb/sdk/wandb_settings.py
Description
-----------
see title
Testing
-------
=> chore: change default define metric glob expansion

wandb/__init__.pyi, wandb/sdk/interface/interface.py, wandb/sdk/wandb_init.py
Description
-----------
- Fixes WB-24333
- Fixes #9691
Testing
-------
=> fix: relax tag type to allow any sequence

CHANGELOG.unreleased.md
Description
-----------
see title
Testing
-------
=> chore: fix changelog typo

core/pkg/monitor/portfile.go, gpu_stats/Cargo.lock, gpu_stats/Cargo.toml, gpu_stats/src/main.rs, gpu_stats/src/monitors.rs
Description
-----------
In this PR:
- Fix a bug on Windows introduced in #10108 (UDS is not supported by tokio on Win)
- Clean up the gpu_stats main.rs module - using async-trait-based design 
Testing
-------
- Arm Mac
- Win machine with GPU
- Linux machine with GPU
=> chore: clean up gpu_stats code and fix an issue on windows

.github/workflows/release-sdk.yml
Description
-----------
see title
Testing
-------
=> chore: update slack release message

CONTRIBUTING.md
Description
-----------
Autoformat CONTRIBUTING.md so that any changes can be isolated from future PRs.
No content change.
Testing
-------
n/å
=> docs(sdk): autoformat CONTRIBUTING.md

CONTRIBUTING.md
Description
-----------
Add documentation to `CONTRIBUTING.md` that you need to run `local_wandb_server.py` when running `system_tests`.
Testing
-------
n/a
=> docs(sdk): document how to run `system_tests`

core/internal/monitor/gpu.go
=> chore: fix comment in gpu.go

tests/unit_tests/test_media/test_media_logging.py
Description
-----------
fixes failing windows ci tests for invalid media paths
Testing
-------
- `nox -s "unit_tests"` on windows
=> fix: failing ci for windows

CONTRIBUTING.md
Description
-----------
see PR title
Testing
-------
=> chore: add amd to the list of gpus supported

core/internal/stream/handler.go, core/internal/stream/handler_test.go, core/internal/stream/sender.go, core/internal/stream/sender_test.go, core/internal/stream/stream.go, core/internal/stream/streaminject.go, core/internal/stream/wire_gen.go, core/pkg/server/connection.go
This makes NewStream significantly simpler.
=> refactor: move NewStream's Handler/Sender to wire

core/internal/runconsolelogs/runconsolelogs_test.go, core/internal/runfiles/runfiles.go, core/internal/runfiles/runfiles_test.go, core/internal/runfiles/uploader.go, core/internal/runfilestest/runfilestest.go, core/internal/stream/sender.go, core/internal/stream/sender_test.go, core/internal/stream/stream_init.go, core/internal/stream/streaminject.go, core/internal/stream/wire_gen.go
=> refactor: create runfiles.UploaderFactory

wandb/apis/public/api.py, wandb/apis/public/files.py, wandb/apis/public/reports.py, wandb/apis/public/runs.py, wandb/apis/public/sweeps.py
Description
-----------
- Fixes #NNNN
This PR updates to documentation for API object which are lazy iterators. Meaning that not all data will be available when the object is initialized, and data will be retrieved in pages.
Testing
-------
=> chore: document which API objects are lazy iterators

wandb/sdk/wandb_run.py
Description
-----------
We were only displaying where data are saved locally for an offline run upon its completion.
=> chore: display local run path for offline runs

core/internal/stream/recordparser.go, core/internal/stream/stream.go, core/internal/stream/wire_gen.go
=> refactor: create RecordParserFactory

core/internal/stream/recordparser.go, core/internal/stream/stream.go, core/internal/stream/wire_gen.go, core/internal/tensorboard/tensorboard.go, core/internal/tensorboard/tensorboard_test.go
=> refactor: create tensorboard.Factory

.bumpversion.cfg
Description
-----------
see PR title
Testing
-------
=> chore: fix typo in the bumpversion config file

tools/graphql_codegen/artifacts/artifact_collections.graphql, tools/graphql_codegen/artifacts/artifact_files.graphql, tools/graphql_codegen/artifacts/artifact_types.graphql, tools/graphql_codegen/artifacts/artifacts.graphql, tools/graphql_codegen/automations/automations_queries.graphql, tools/graphql_codegen/projects/projects.graphql
Description
-----------
Non-functional changes -- only cosmetic autoformatting (mainly whitespace changes) to GraphQL queries used in codegen.
=> chore: autoformatting graphql operations

tests/unit_tests/test_artifacts/test_saved_model.py, wandb/sdk/artifacts/_validators.py, wandb/sdk/artifacts/artifact.py
=> refactor(artifacts): use pydantic to handle `Artifact._assign_attrs`

wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_manifest.py, wandb/sdk/artifacts/artifact_manifest_entry.py, wandb/sdk/artifacts/artifact_manifests/artifact_manifest_v1.py
=> chore(artifacts): minor timeboxed cleanup 2025-08-14

wandb/sdk/artifacts/artifact_file_cache.py
Description
-----------
PR refactors the artifact file cache implementation to use `@lru_cache` to memoize the current `ArtifactFileCache` instance, avoiding potential risks/issues of relying on a global `_artifact_file_cache` variable.  That global variable has also been removed.
Note that this should be thread-safe, as it memoizes via `@lru_cache` from the stdlib, which is expressly supposed to be thread-safe ([docs](https://docs.python.org/3/library/functools.html#functools.lru_cache))
Testing
-------
No intended changes to runtime functionality or any public part of the API.  Relying on existing tests continuing to pass.
=> chore(artifacts): avoid global variable for memoizing ArtifactFileCache

wandb/sdk/artifacts/_factories.py, wandb/sdk/artifacts/artifact.py
Description
-----------
PR extracts a dedicated default factory function, `make_storage_policy()`, into a new file `_factories.py`.
Testing
-------
=> chore(artifacts): define factory for StoragePolicy

CHANGELOG.unreleased.md, wandb/sdk/wandb_setup.py
=> fix: incorrect message about environment variables on init

CHANGELOG.unreleased.md
Documents the change made in #10418.
=> chore: document click version constraint update in changelog

core/internal/runsync/errors.go, core/internal/runsync/runreader.go, core/internal/runsync/runreader_test.go, core/internal/runsync/runsync.go, core/internal/runworktest/runworktest.go, core/internal/stream/store.go
Implements the core logic of `wandb beta sync`.
=> feat: create RunReader for wandb beta sync

core/internal/filestream/filestreamrequest.go
Cleans up the logic estimating whether the accumulated FileStream request is at maximum size.
`isAtMaxSize` didn't take the summary size into consideration before (`addStringsToRequest`​ is not used for the summary). The only difference this makes is that if the user does something like `run.summary["key"] = "huge value ..."` while turning off system metrics, not logging any data and not printing anything to the console, then we'll now make the request immediately rather than waiting to accumulate more data.
It was odd to use a stateful computation to compute this value.
=> refactor: filestream request size calculation

.github/workflows/release-sdk.yml
Description
-----------
Builds wheels for ARM Windows.
Testing
-------
https://github.com/KTibow/wandb/actions
=> feat(ci): build wheels for ARM Windows

wandb/apis/public/files.py, wandb/apis/public/registries/registry.py, wandb/sdk/wandb_settings.py
Description
-----------
- Fixes #NNNN
Simple docstring formatting fixes.
Testing
-------
=> docs(sdk): docstring formatting

wandb/sdk/data_types/image.py
Description
-----------
- Fixes #NNNN
https://wandb.atlassian.net/browse/DOCS-1016
Testing
-------
=> docs(sdk): add context to Image class on normalization 

core/internal/filestream/filestreamrequest.go, core/internal/filestream/filestreamrequest_test.go
Fixes the logic that calculates `isAtMaxSize`. I broke it in PR #10470, causing FileStream to fail to ignore rate limits once `x_file_stream_max_bytes` is reached (not a terrible bug).
> It was odd to use a stateful computation to compute this value.
Turns out it wasn't odd! I just confused myself by naming it `isAtMaxSize`​. I renamed it to `isTruncatedDueToSize`​ in this PR.
=> fix: filestream request truncation detection

wandb/sdk/wandb_settings.py
Description
-----------
- Fixes: https://wandb.atlassian.net/browse/DOCS-1766
Fixes docstring formatting.
Testing
-------
=> docs(sdk): fixed formatting for console arg in Settings Class

core/cmd/wandb-core/main.go, core/internal/leet/config.go, core/internal/leet/config_test.go, core/internal/leet/handlers.go, core/internal/leet/model.go, core/internal/leet/testhelpers.go
Description
-----------
This PR introduces the ConfigManager struct that manages the LEET application configuration.
=> chore: leet configuration

core/internal/runconsolelogs/runconsolelogs.go
=> chore: fix a typo in runconsolelogs.go
