- tests/pytest_tests/unit_tests/test_launch/test_create_job.py
- wandb/sdk/launch/create_job.py
Description
-----------
- Fixes #NNNN
Testing
-------
> fix(launch): wandb job create should not look for requirements.txt if Dockerfile.wandb is next to entrypoint

- tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
- tests/pytest_tests/unit_tests/test_artifacts/test_storage.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_file_cache.py
- wandb/sdk/artifacts/artifact_manifest_entry.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/artifacts/storage_policy.py
Description
-----------
This resolves the issue here: https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1705601806215009
Fixes: https://wandb.atlassian.net/browse/WB-17009?filter=10470
- Fixes WB-17009
Optimizes artifact downloads via two dimensions: (1) make the cache copy optional (it takes 6-10 seconds) and (2) scale the number of boto threads we use to the size of the big artifact
Testing
-------
Proved a reduction in latency of llama-13b download from 6.3-7.1 minutes to 5.88 minutes (though the variance of download speeds is large)
> perf(artifacts): Reduce artifact download latency via optional cache copy + threads

- wandb/__init__.py
- wandb/cli/cli.py
- wandb/data_types.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/data_types/_private.py
- wandb/sdk/data_types/image.py
- wandb/sdk/internal/file_pusher.py
- wandb/sync/__init__.py
- wandb/sync/sync.py
Description
-----------
- Fixes WB-16987
- Fixes #5258
Clean up temp dirs that are created in different places in the code, mainly atexit.
Note that most of the relevant python code will soon be gone with the transition to Rust in the client.
Testing
-------
> fix(sdk): clean up temp folders

- wandb/apis/public/api.py
Description
-----------
[WB-17072](https://wandb.atlassian.net/browse/WB-17072)
Artifacts docs: https://github.com/wandb/docodile/pull/566 that need to use this method.
Adds docstrings to `api.artifact_collection()` to update Artifacts docs.
Testing
-------
[WB-17072]: https://wandb.atlassian.net/browse/WB-17072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(artifacts): add docstrings for artifact collection method on public api

- tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/artifact.py
Description
-----------
- Fixes WB-13672
Read: https://wandb.atlassian.net/browse/WB-13672
* We allow users to optionally only download files that match the prefix of an input path prefix.
* If nothing is specified, the behavior is as before, we download all paths in the artifact. This prefix match only applies to OUR W&B path structure, NOT references or download file path structures.
* See the below for examples:
Testing
-------
Download prefix case:
Result:
Basecase (no arg given and we download everything):
**Final comments**: this method is easier to code but a little off from the 'optimal' way of doing things. Ideally within the graphQL query itself we specific a prefix and in the backend we do the filtering. however for now we will just filter after querying …
> feat(artifacts): Add partial file downloads, via directory prefix

- tox.ini
- wandb/apis/reports/v2/interface.py
Description
-----------
Pydantic 2.6 introduces some changes to dataclasses that caused our old internal attr setting to break.  This PR fixes that.
Testing
-------
unit tests
> fix(sdk): Update Report API to work with pydantic2.6

- wandb/sdk/launch/git_reference.py
Description
-----------
When the launch agent clones a git repository referenced in a job, it needs to do a full fetch. Prior to this PR we were doing a shallow fetch `depth=1` which only fetches the last commit.
Testing
-------
> fix(launch): fetch all commits to enable checking out by sha

- wandb/agents/pyagent.py
Description
-----------
- Fixes [WB-16926](https://wandb.atlassian.net/browse/WB-16926)
`pyagent` currently only shows a top level error message and not a full traceback when a called sweep function raises an exception. For example, if I had a `my_train.py` that looked like this:
my_train.py:
```python
def exc_fn():
raise Exception('bad')
def sweep_fn():
exc_fn()
```
and a sweep config that looked like this:
config.yaml:
```
method: grid
metric:
goal: minimize
name: val_loss
parameters:
a:
values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
program: train.py
```
Then if I ran this code before this PR I would see log entires that look like this: 
```
wandb.agent('dannygoldstein/uncategorized/brqlf3cs', my_train.sweep_fn)
wandb: Agent Starting Run: fgbwdyfk with config:
wandb:  a: …
```
> fix(sweeps): dont swallow exceptions in pyagent

- core/pkg/artifacts/saver.go
Description
-----------
- Fixes [WB-17209](https://wandb.atlassian.net/browse/WB-17209)
- Fixes #NNNN
Testing
-------
Todo: Add test
[WB-17209]: https://wandb.atlassian.net/browse/WB-17209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): artifact file upload progress in nexus

- core/pkg/monitor/gpu_amd.go
- tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_amd.py
- wandb/sdk/internal/system/assets/gpu_amd.py
Description
-----------
- Fixes #6757 (hopefully, needs verification)
Testing
-------
> fix(sdk): exercise caution in system monitor when rocm-smi is installed on a system with no amd gpus

- .gitignore
Description
-----------
Add the conventional ".venv" directory to .gitignore to make it easy to develop in a virtual environment.
> chore(sdk): Add .venv to gitignore

- wandb/cli/cli.py
Description
-----------
When running `wandb beta` commands, if `wandb-core` is not found, print a warning but don't exit. This was breaking the doc generation GitHub workflow.
Testing
-------
```
pip install -e .
wandb beta sync --help
```
> chore(sdk): Don't exit in 'wandb beta' if wandb-core not found

- wandb/cli/cli.py
Description
-----------
Follow-up to try to fix docugen. Write the error to stderr so that (hopefully) docugen doesn't pick it up as part of the `--help` string.
Also updated to use `click.secho` to combine `click.echo` and `click.style`.
> chore(sdk): Write 'wandb beta' error to stderr

- tests/pytest_tests/unit_tests_old/test_launch/test_launch.py
- tests/pytest_tests/unit_tests_old/test_launch/test_launch_aws.py
- wandb/sdk/launch/_project_spec.py
- wandb/sdk/launch/builder/build.py
- wandb/sdk/launch/builder/docker_builder.py
- wandb/sdk/launch/builder/kaniko_builder.py
Description
-----------
- Fixes #NNNN
Launch used to use a file in the build context called `launch_metadata.json` to pass in overrides. This has been deprecated for some time but there is still code being used to construct this file in the docker and kaniko builders. But it's never read. This PR removes all of that old stuff.
Testing
-------
> chore(launch): scrub launch_metadata.json from codebase

- .gitignore
- tools/wini/subprocess.py
- tools/wini/wini.py
Description
-----------
The `rm -rf` is a little scary, but I don't have another way that's still simple. Alternatively, I considered adding a selection prompt to the install command if there are multiple wheels, but I think it might be more annoying than useful.
Testing
-------
```sh
./wini package wandb-core
./wini package wandb-core --install
```
> chore(sdk): Delete ./core/dist/ directory when rebuilding in wini

- .circleci/config.yml
- tox.ini
Description
-----------
Use a single job called "unit-tests-new" to run both SDK and non-SDK unit tests on Linux (non-"legacy" tests).
I didn't add an option to run unit tests on Mac, assuming that there is not much value in running unit tests on different systems and machines, but I can add it if we think it's still useful.
Testing
-------
Running on CircleCI.
> chore(sdk): Use a single unit test job in CircleCI

- core/pkg/server/handler.go
Description
-----------
- Fixes WB-17256
- Avoid populating Git info, when there is not values. This more of a preventative measure as the real fix is to fix it on the App side to avoid displaying empty strings.
Testing
-------
> fix(core): don't send git data if it's not populated

- tools/wini/wini.py
Description
-----------
Instead of using "rm", use Python APIs for cross-platform compatibility. I'm not sure if "rm" would consistently work on Windows.
Also, this avoids using "-rf" which always makes me nervous.
Testing
-------
Running `./wini package wandb-core --install` several times, manually creating files in `.wini/core/` and making sure they got deleted.
> chore(sdk): Don't use "rm" in wini

- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
- wandb/apis/public/artifacts.py
Description
-----------
- Fixes WB-16910
- Fixes #16910
Allow users in the SDK, given an artifact object, change the artifact's entire collection type
If the typename is invalid, throw an error.
We termlog the before and after.
Testing
-------
Running the command
The result in WandB UI
> feat(artifacts): Add ability to change artifact collection types

- wandb/sdk/wandb_run.py
Description
-----------
https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1707770105303319
```
Ghost is trying to execute run.use_artifact(digest)  or run.use_artifact(entity/project/digest) but they cannot get it to work. According to our docs, we can pass the digest as the artifact_or_name but this does not seem to work for me. I keep getting a wandb.errors.CommError: artifacts must be specified as 'collection:alias' (Error 400: Bad Request). Do we have an example for how to pass the digest to run.use_artifact() ?
```
Testing
-------
> docs(artifacts): remove from doc string that we can use artifact with digest

- tests/pytest_tests/unit_tests/test_lib/test_apikey.py
- tests/pytest_tests/unit_tests/test_sender_config.py
- wandb/sdk/internal/sender.py
- wandb/sdk/internal/sender_config.py
- wandb/sdk/lib/config_util.py
Description
-----------
Refactors a portion of `sender.py` (huge file!) to make WB-16244 a little easier to reason about.
Testing
-------
* Codecov shows that existing tests cover the new codepaths, including 100% of the changed lines in sender.py
* Unit tests for sender_config.py
> refactor(sdk): Factor out config manipulation logic in sender.py

- core/internal/clients/retry_policy.go
Description
-----------
When trying to resume a deleted run the server returns a 409, which currently we would retry and hence would hang the client. This PR exclude this error code from retrying.
Testing
-------
Manually
> fix(core): avoid retrying on conflict status code

- .github/CODEOWNERS
Description
-----------
Add SDK team as codeowner of all the CI and GitHub repo config files
> chore(sdk): add SDK as codeowners of the CI configs

- .circleci/config.yml
Description
-----------
Don't run very expensive macOS legacy-unit-test jobs.
These add up to around 4.3M CircleCI credits per month, which is around $2500/month.
> ci(sdk): Remove legacy unit test macOS jobs

- core/pkg/server/config.go
- core/pkg/server/config_test.go
- core/pkg/server/sender.go
Description
-----------
Factors out a RunConfig type to consolidate config manipulation logic and simplify `sender.go`.
I tried to mostly preserve semantics. The `updateConfigPrivate()` method had some odd usage: it accepted a `telemetry` parameter but also used the `Sender::telemetry` field. It seems in all cases the given telemetry was merged into `Sender::telemetry` anyway, so I removed that parameter. The only case semantics are different is where the method was called with a `nil`, where it wouldn't have added "cli_version" and "python_version" previously but does now.
This isn't a complete refactor---I didn't want to touch too many files in a single PR.
Testing
-------
Unit tests.
> refactor(sdk): Factor out RunConfig in Go code

- core/pkg/server/config.go
- core/pkg/server/config_test.go
- core/pkg/server/resume.go
- core/pkg/server/resume_test.go
- core/pkg/server/sender.go
Description
-----------
- Fixes WB-16244 in wandb-core
Correctly merges the "visualize" and "viz" config keys when resuming a run.
Testing
-------
- Existing tests
- Manual testing as in #7005
> fix(sdk): Fix visualization config merging for resumed runs in wandb-core

- core/pkg/server/handler.go
Description
-----------
Replace the standard library's encoding/json with sementio's. See here for more details: https://github.com/segmentio/encoding?tab=readme-ov-file#encodingjson-
> fix(core): replace usage of standard library's json with `segmentio`'s

- core/pkg/server/config.go
- core/pkg/server/config_test.go
- core/pkg/server/sender.go
Description
-----------
* Use MixedCase for enums
* Format errors in the conventional way: lowercase first letter with a prefix mentioning the source
> chore(sdk): Use better Go style in config.go

- tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py
- tests/pytest_tests/system_tests/test_artifacts/test_misc2.py
- tests/pytest_tests/system_tests/test_artifacts/test_model_workflows.py
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
- tests/pytest_tests/system_tests/test_core/test_cli_full.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_saver.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/internal/job_builder.py
- wandb/sdk/internal/sender.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_run.py
…s reporting (#6497)"
This reverts commit cb57e43018daff0909147f09f76f675dc59968b2.
Description
-----------
We discovered a significant performance regression with polling for file pusher stats in order to report progress. This lead to artifact uploads to take 3-4 times longer for very large artifacts.
Testing
-------
Tested uploading 1 million files with around 300GB of data and confirmed performance is back to around 0.16.1 levels.
> fix(artifacts): Revert "make upload request async to support progress reporting (#6497)"

- core/internal/api/api.go
- core/internal/api/ratelimit.go
- core/internal/api/send.go
- core/internal/api/transport.go
Description
-----------
Fixes WB-17344.
The crux of it is using a condvar in the classic way.
Note that if we're sending requests super fast, then after the first rate-limit header there may still be requests in flight which could fail. To minimize failed requests, the server should tell us to rate-limit ourselves sufficiently early.
Another thing to note is that we ignore rate-limit headers from requests that finish while a rate-limit is in effect. This shouldn't matter as long as the server's rate-limit responses are consistent.
Testing
-------
TODO
> feat(sdk): Respect rate-limiting headers

- .circleci/config.yml
- tests/pytest_tests/system_tests/test_functional/test_mode_shared.py
- tests/pytest_tests/system_tests/test_sweep/test_wandb_sweep.py
- tests/pytest_tests/system_tests/test_system_metrics/test_open_metrics.py
Description
-----------
This PR just unifies all the system tests under same job to make sure we ran all the tests with nexus.
This found another issue with sweeps that wasn't covered earlier.
In follow up PRs we are going to slowly enabling all the tests that marked as `wandb_core_failure`
> ci(sdk): clean up system tests to use a single job spec

- core/internal/api/api.go
- core/internal/api/transport.go
Description
-----------
Fixes WB-17769.
I capitalized `rateLimitedTransport` because it's used outside of `transport.go`, even though it shouldn't be used outside of `api/`. It just feels wrong to use lowercase names defined in other files, even if they're in the same package.
Testing
-------
Unit tests.
> feat(sdk): Rate-limit GraphQL and filestream separately

- core/internal/api/api.go
- core/internal/clients/clients.go
- core/internal/filetransfer/file_transfer_default_test.go
- core/pkg/server/sender.go
Description
-----------
Clean up a little by removing most functions from `clients.go` and setting retryablehttp client fields directly at callsites.
> chore(sdk): Remove functions from clients.go

- core/setup.py
`Path.exists()` can return `False` even if a file exists! Happens for broken symlinks.
> chore(core): Correctly delete existing file in setup.py

- pyproject.toml
This started failing recently. There are 64 instances and no auto-fix.
> chore(sdk): Ignore ruff UP032

- requirements_test.txt
- tox.ini
Description
-----------
Example failing test: https://app.circleci.com/pipelines/github/wandb/wandb/31608/workflows/76f5f3d3-be59-4bdf-8fa4-3a8c697b2cd7/jobs/1049934/tests
```
File "/root/project/.tox/py312/lib/python3.12/site-packages/pytest_rerunfailures.py", line 351, in pytest_handlecrashitem
sched.mark_test_pending(crashitem)
File "/root/project/.tox/py312/lib/python3.12/site-packages/xdist/scheduler/loadscope.py", line 245, in mark_test_pending
raise NotImplementedError()
NotImplementedError
```
This appears to be a bad interaction between pytest-rerunfailures and pytest-xdist. As a result, the actual test failure is hard to find.
> chore(sdk): Disable pytest reruns, as they don't work with xdist

- core/internal/runconfig/runconfig.go
- core/internal/runconfig/runconfig_test.go
- core/pkg/server/resume.go
- core/pkg/server/resume_test.go
- core/pkg/server/sender.go
Description
-----------
It was due to get factored out.
> refactor(core): Move server/config.go into its own package

- tests/pytest_tests/unit_tests/test_lib/test_filesystem.py
- wandb/sdk/lib/filesystem.py
Description
-----------
This test is flaky because it is wrong. Using `wb` in the `open()` mode in `delayed_copy_with_pause()` causes it to truncate the contents written so far, resulting in the null bytes you can see in [this run](https://app.circleci.com/pipelines/github/wandb/wandb/31659/workflows/f709e516-f2f4-4ae0-ad51-836af1b880b4/jobs/1052364/tests).
Could "fix" it by changing `wb` to `ab`, but the fact that this test was usually passing despite being wrong is proof that it's useless. Tests that rely on thread ordering and `time.sleep` make CI slow and flaky without adding value.
There is no way to test this aspect of the `safe_copy` function, but that's okay: it's short and straightforward. The key to being confident in this kind of code is not to write fake tests, but to make it …
> chore(sdk): Kill bad filesystem test

- tests/pytest_tests/unit_tests/test_wandb_settings.py
- wandb/sdk/wandb_login.py
- wandb/sdk/wandb_settings.py
Description
-----------
Make the code easier to read. We definitely shouldn't be using `locals()` as much as we are!
Testing
-------
Wait for CI.
The functions are private, so we should be able to freely change signatures. There are no additional code references I could find. It could break things if we do weird dynamic stuff somewhere instead of calling functions directly---but then it's the calling code that's at fault and should be fixed.
> refactor(sdk): Use parameters directly rather than via `locals()`

- tests/pytest_tests/unit_tests/test_artifacts/test_artifact_manifest_entry.py
Description
-----------
Failure: https://app.circleci.com/pipelines/github/wandb/wandb/31659/workflows/f709e516-f2f4-4ae0-ad51-836af1b880b4/jobs/1052367/tests
It's broken on Windows because it uses `/` rather than `\` as the separator.
> chore(sdk): Fix Artifacts test that's broken on Windows

- tests/pytest_tests/unit_tests/test_public_api.py
Description
-----------
Explicitly replace `stdin` by `None` as a way to simulate there not being a TTY available. `pytest` is supposed to replace `stdin`, but there's no guarantee that it replaces it with something that doesn't _look_ like a TTY. In fact, when I try to run this test locally, it prompts me for input!
See the second failure here: https://app.circleci.com/pipelines/github/wandb/wandb/31659/workflows/f709e516-f2f4-4ae0-ad51-836af1b880b4/jobs/1052367/tests. The `login()` routine tries to prompt using `input()` which raises an EOF error. I think the code might not be testing for a TTY correctly, but it's hard to follow.
> chore(sdk): Fix bad test that reads from stdin

- core/internal/settings/settings.go
- core/pkg/server/connection.go
- core/pkg/server/stream.go
Description
-----------
Use methods instead of fields on Settings because we have to keep the underlying proto.
My original plan was for `settings.Parse()` to create a Settings struct and discard the proto, but since we pass the proto back to the user process, we'll want to keep its original value. This is because it may include fields not used by Nexus, so if `Settings` only contains accessors for fields that are used by Nexus, we won't be able to reconstruct the proto.
I prefix the methods with "Get" to make bugs like this obvious:
```go
// Without Get... see the problem?
s.logger.Info("created new stream", "id", s.settings.RunID)
// With Get, it's easier to spot!
s.logger.Info("created new stream", "id", s.settings.GetRunID)
```
> refactor(sdk): Settings fields => methods

- CHANGELOG.md
- tests/pytest_tests/system_tests/test_core/test_footer.py
- tests/pytest_tests/system_tests/test_launch/test_launch_run.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/internal/handler.py
- wandb/sdk/internal/sender.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_run.py
Description
-----------
This PR removes the job links from the information displayed in the terminal, as well as explicitly point the run's link to the workspace, even though it is the same link now, in the future it is potentially could change.
Testing
-------
> fix(sdk): remove job link and link run to workspace

- CHANGELOG.md
Description
-----------
This PR just remove the changelog entry that we decide is too internal details implementation.
Testing
-------
> chore(sdk): remove from changelog internal change

- core/internal/filetransfer/file_transfer_manager.go
- core/internal/filetransfertest/filetransfertest.go
- core/pkg/artifacts/downloader.go
- core/pkg/artifacts/saver.go
- core/pkg/server/sender.go
Description
-----------
I needed this while trying to write better file upload tests. This makes `FileTransferManager` an interface and creates a fake implementation in the `filetransfertest` package.
> chore(sdk): Create FakeFileTransferManager for tests

- tests/pytest_tests/unit_tests/test_wandb_login.py
Description
-----------
Fixes flakes such as https://app.circleci.com/pipelines/github/wandb/wandb/32064/workflows/a785eae5-e0d3-4e05-be62-4aab29087eb3/jobs/1071652.
> chore(sdk): Don't assert on time passed in test_wandb_login.py

- core/pkg/server/sender.go
- core/pkg/server/sender_test.go
- core/pkg/server/stream.go
- core/pkg/server/stream_init.go
Description
-----------
I was trying to clean up file stats upload code but ran into issues while trying to rewire FilesInfoHandler and FileTransferManager because Sender creates them directly. Then while trying to inject them into Sender, I ended up having to move a lot of other code.
I'm going to rewrite Sender and possibly Handler to inject objects rather than create them directly. This will improve testability and unlock some nice refactors.
In this PR, I inject the Backend object.
> chore(core): Inject backend into sender

- core/setup.py
At first I didn't understand why it wasn't working. Now I don't understand how it ever worked.
> fix(core): symlink to resolved path rather than relative path

- core/internal/filetransfer/file_transfer_default.go
- core/internal/filetransfer/file_transfer_retry_policy.go
- core/pkg/server/stream_init.go
Fixes WB-17558: `run.save(directory)` will retry until it runs out of retries.
This happened because of retryablehttp retries Go errors from the HTTP transport (i.e. not HTTP response error statuses):
https://github.com/hashicorp/go-retryablehttp/blob/main/client.go#L506-L507
Our request body is a ReadSeeker, so retryablehttp doesn't try to read the entire file into memory when we create a Request. Instead, it passes the ReadSeeker to the underlying transport in Do(). When Go's http library calls Read(), it gets an error saying that the file is a directory; then retryablehttp treats it as a retryable error!
> fix(core): Don't retry when trying to upload a directory

- tests/pytest_tests/system_tests/conftest.py
I also tried to add type hints, but unfortunately mypy still doesn't pick it up. It could be because there are other mypy issues in conftest.py.
I removed the `try ... finally` because `del relay_server` doesn't do anything except unbind the variable locally, as far as I understand.
> chore(sdk): Document relay_server fixture a tiny bit more

- .bumpversion.core.cfg
- core/pyproject.toml
- core/setup.py
pyproject.toml is the more modern way of specifying project information. I was adding the `build-system.requires` field because `cibuildwheel` doesn't include `wheel` by default in the newest version (1.17.0), and I figured I might as well make the full move.
`./wini package wandb-core` still works and produces the correct output locally.
> chore(core): Move wandb-core metadata to pyproject.toml

- core/internal/runfiles/debounced_transfer.go
- core/internal/runfiles/runfiles_test.go
- core/internal/runfiles/uploader.go
Resolves WB-18103.
This affects only run.save() and some internal files which use that codepath, not artifacts behavior. The main purpose is to not reupload files at the end (in UploadRemaining()) if they were previously uploaded with the "now" policy and unchanged since.
> feat(core): Don't reupload files that have already been uploaded

- core/internal/runfiles/uploader.go
This race condition should be super rare and maybe impossible to trigger in production. I discovered it because it got triggered in CI: https://app.circleci.com/pipelines/github/wandb/wandb/32643/workflows/8f3de1df-c8e8-4f39-8fb3-942a3ad099ff/jobs/1099232
Unfortunately, the `watcher` package we depend on has not been updated in 6 years and has a few design flaws, one being that to know whether Start() succeeded, we have to create a separate goroutine that blocks until Wait() returns. If Start() returns an error instead, then Wait() blocks forever and the goroutine is wasted. The API doesn't provide a channel that we could listen to in a `select` statement.
> fix(core): Fix a race condition caused by watcher in runfiles

- core/internal/api/api.go
- core/internal/api/transport.go
Improves WB-18172.
It turns out that 20QPS is very easy to hit in a Python script that calls `run.save()` on a large number of files.
> fix(core): Raise the default rate limit

- CHANGELOG.md
- tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py
- wandb/sdk/launch/agent/agent.py
- wandb/sdk/launch/agent/config.py
Description
-----------
- Fixes issue raised in [this Slack thread](https://weightsandbiases.slack.com/archives/C01KQ5KTDC3/p1712011361017579)
Adds the `stopped_run_timeout` parameter to the agent config.
When a run is stopped, it first tries to upload any necessary artifacts before exiting. By default, if that process takes more than 60 seconds, the agent cancels the run, force-removing any related processes (e.g. Kubernetes jobs). Sometimes users will have larger artifacts and want some extra time to allow them to upload, so now they can set the `stopped_run_timeout` parameter to increase the grace period.
Testing
-------
Created an agent with the new parameter
> feat(launch): Allow overriding stopped run timeout

- CHANGELOG.md
- wandb/sdk/interface/interface.py
Description
-----------
- Fixes #NNNN
Makes it so when a job artifact fails to downloaded or the json fails to be parsed, an error is emitted outside of the internal logs, and prevents protobuff from being passed to the backend process, forcing a new job to be created associated with the run
Testing
-------
> fix(launch): Make partial job download fail verbosely

- CHANGELOG.md
- tests/pytest_tests/system_tests/test_launch/test_launch.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/wandb_init.py
Description
-----------
- Fixes #NNNN
Removes a clause which cleared the run id setting in any call to `wandb_init` in the launch context. This was used to allow multiple different runs to be created from a single launched run. This had the undesired effect of causing jobs that made an initial call to wandb.login not have a run associated with the associated queued item. Now all runs created from one launch run will share an id.
Testing
-------
> fix(launch): wandb.login causes runs to not be associated in launch queue table

- core/internal/runfiles/uploader.go
The read of u.category in scheduleUploadTask() was not protected by a mutex, causing a panic in CI: https://app.circleci.com/pipelines/github/wandb/wandb/32680/workflows/db4e43c2-e481-49df-9f5e-1dde424987b1/jobs/1101049
> fix(core): Avoid concurrent map read and write

- .github/workflows/release-core.yml
- core/setup.py
- core/wandb_core/__init__.py
- tools/wini/print.py
- tools/wini/subprocess.py
- tools/wini/wini.py
Description
---
Fixes WB-18030, unblocking us from making wandb-core a required dependency of wandb. This is a stopgap; eventually we will create source distributions and build Go from source.
Testing
---
Run `./wini package wandb-core --noop`. This creates a wheel named `wandb_core-0.17.0b10-py3-none-any.whl`. Unzipping the wheel shows that it does not contain any binary files.
Install the wheel with `pip install --force-reinstall $(./wini info wandb-core-wheel)`. Then `pip show wandb-core` shows that `wandb-core` is installed, but running `wandb.init()` doesn't print a message saying that wandb-core is being used.
Finally, you can see a successful workflow run and view the `wandb-core-distributions` artifact, which includes a universal wheel: …
> chore(core): Build universal no-op wandb-core wheel

- tests/pytest_tests/system_tests/test_launch/test_job.py
- wandb/sdk/launch/create_job.py
Description
-----------
- Fixes [WB-18110](https://wandb.atlassian.net/browse/WB-18110)
Code artifacts were being made much larger than needed because they contain the generated `wandb` directory. This removes it from the artifact before logging it, along with the `.git` directory that users probably don't want to include either.
Testing
-------
A system test was modified to ensure a `wandb` subdirectory isn't added. Also, manual testing:
- Create a directory with a simple python job file and a `wandb` subdirectory
- Run `wandb job create`
- Confirm that the [generated code artifact](https://wandb.ai/tim-hays/debugging/artifacts/code/code-testjob2/v0/files) doesn't contain a `wandb` directory.
[WB-18110]: https://wandb.atlassian.net/browse/WB-18110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> chore(launch): Exclude wandb and .git folders from code artifact when creating a job from the CLI

- core/internal/filetransfer/file_transfer_manager.go
- core/internal/filetransfertest/filetransfertest.go
- core/pkg/filestream/filestream.go
- core/pkg/server/sender_test.go
- core/pkg/server/stream.go
- core/pkg/server/stream_init.go
I'll add a replacement in `runfiles` in a separate PR.
> refactor(core): Remove unused FileStreamCallback in FileTransferManager

- wandb/sdk/wandb_run.py
Description
---
Following up on https://github.com/wandb/wandb/pull/7146#discussion_r1554654915.
> chore(sdk): Explain abs path folder structure in run.save() docs

- core/pkg/server/handler.go
- core/pkg/server/util.go
- core/pkg/utils/files.go
Description
-----------
- Fixes #NNNN
Refactor, make `CopyFile` an exported function of utils.
I'm using this in another PR, and thought it would be better to reuse this one rather than writing another helper.
Testing
-------
> refactor(sdk): move copyFile helper function to pkg/utils/files.go

- core/pkg/filestream/filestream.go
- core/pkg/filestream/filestream_test.go
- core/pkg/filestream/loop_transmit.go
- core/pkg/filestream/loop_transmit_test.go
- core/pkg/filestreamtest/filestreamtest.go
- core/pkg/server/stream_init.go
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-18360
Send heartbeats to the server to ensure the latter never erroneously marks the run as crashed if we don't send any data for a long period of time.
Testing
-------
> feat(core): send heartbeat to server

- tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
- wandb/sdk/artifacts/artifact_file_cache.py
- wandb/sdk/internal/datastore.py
Description
-----------
This is mostly to simplify tests and remove some counter-intuitive behavior that happens when the cache is mocked out. Test changes are included.
Technically this helps with the issue brought up by [WB-18090](https://wandb.atlassian.net/browse/WB-18090) but this shouldn't be considered a supported feature--changing the cache directory mid-run isn't something that we want to encourage.
Testing
-------
Implicitly, by the existing tests.
[WB-18090]: https://wandb.atlassian.net/browse/WB-18090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(artifacts): allow updates to WANDB_CACHE_DIR during execution

- tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/artifact.py
Description
-----------
- Fixes [WB-18383](https://wandb.atlassian.net/browse/WB-18383)
Support `pathlib.Path` and other `os.PathLike` objects as the download root, e.g. `Artifact.download(root=Path("test/path"))`
Testing
-------
Added small unit test.
[WB-18383]: https://wandb.atlassian.net/browse/WB-18383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(artifacts): allow any os.PathLike as the download root

- core/pkg/artifacts/builder.go
- core/pkg/utils/files.go
- core/pkg/utils/hash.go
- core/pkg/utils/hash_test.go
Description
-----------
This could be split up, but it's pretty small. This PR:
* Adds a convenience function `VerifyFileHash` that returns true/false rather than both an error and a digest to check
* Adds documentation strings for the other functions in `hash.go`
* Removes `EncodeBytesAsHex`, since it just forwards to `hex.EncodeToString`
It also removes the `err` returned by `ComputeB64MD5`, since it turns out that function can't actually fail.
Testing
-------
Added some unit tests, both for previously existing hashing code and for the new helpers.
> chore(artifacts): add helper functions for verifying data/files

- core/pkg/artifacts/manifest.go
Description
-----------
- Fixes [WB-18010](https://wandb.atlassian.net/browse/WB-18010)
As per the `TODO` comment, move to using a retryable http client. Presumably comment was written before we started using `retryablehttp`?
Testing
-------
Just CI
[WB-18010]: https://wandb.atlassian.net/browse/WB-18010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(artifacts): use a retrying client to download manifests

- requirements_dev.txt
Description
-----------
- Fixes #NNNN
`pip` doesn't care, but `uv pip` is more strict, and without this change attempting to install with `uv pip install -r requirements_dev.txt` results in:
```
error: Couldn't parse requirement in `requirements_dev.txt` at position 1265
Caused by: Missing space before ';', the end of the URL is ambiguous
.[sweeps]; sys_platform != 'darwin' or (sys_platform == 'darwin' and platform.machine != 'arm64')
```
Testing
-------
`uv pip install -r requirements_dev.txt` now works.
> chore(sdk): add space before ';' in requirements_dev.txt

- .circleci/config.yml
Description
---
Adds commands to save and restore the `tox` cache. This cache includes the virtualenvs created by `tox`, so it significantly speeds up the Python dependency installation step. It seems this shaves off around 4 minutes from the workflow (from ~18m to ~14m).
Different executions of _the same job_ reuse the cache if the requirements files are unchanged. Different jobs don't share caches because .venvs are not portable. The cache is invalidated if `tox.ini` changes, since envs can specify dependencies.
As an alternative, I tried updating CI to use `uv`, but it did not reduce install times by a lot (from 180s to 160s in unit-tests-linux-sdk-3-8, for example) and caused various job failures (e.g. https://app.circleci.com/pipelines/github/wandb/wandb/33297/workflows/221ead99-b9d7- …
> chore(sdk): Cache .tox in CircleCI

- tox.ini
Description
---
Replaces the `install_command` setting by environment variables that pip knows. This makes it easier to use our `tox` with `uv`.
https://pip.pypa.io/en/stable/topics/configuration/#environment-variables
> chore(sdk): Replace install_command in tox envs

- .circleci/config.yml
- core/hatch.py
- tox.ini
Description
---
Instead of selecting test directories through positional arguments to `tox`, start creating separate `tox` environments for different directories. This will allow us to better manage test dependencies by grouping tests with similar requirements in different directories.
This starts by adding the `unit-tests-...` environment. The `unit-tests-{macos,linux}-{sdk,other}-<py>` jobs are now `unit-tests-{macos,linux}-<py>`. As a nice side effect, the CircleCI config is a little shorter!
All tests generally succeed now, so we no longer need to separate them into different jobs. If any tests are flaky or slow, we should fix them or move them to other folders.
> chore(sdk): Don't discriminate between unit_tests subdirectories

- .circleci/config.yml
- CHANGELOG.md
- wandb/sdk/wandb_run.py
Description
---
Fixes WB-18412. Tested by temporarily enabling Windows unit tests to run for this PR: https://app.circleci.com/pipelines/github/wandb/wandb/33397/workflows/60292dc6-9104-4439-852a-cfe3fdd96c86/jobs/1135123/steps
The resolve() implementation of the WindowsPath subclass of Path doesn't like asterisks.
> fix(sdk): Don't resolve() globs on Windows

- pyproject.toml
- tests/standalone_tests/executor_tests/requirements.txt
- wandb/env.py
Description
-----------
- Fixes #7409 
`appdirs` is no longer maintained; this moves to `platformdirs`, an actively maintained fork.
Testing
-------
> chore(sdk): migrate from appdirs (deprecated) to platformdirs

- .github/workflows/release-sdk.yml
Description
-----------
Increase sleep time in the release action for TestPyPI to make sure the package is uploaded, we saw that 30 sec wasn't enough. 
Testing
-------
> ci(sdk): increase sleep time before installing from TestPyPI

- core/internal/paththree/pathtree.go
- core/internal/pathtree/pathtree.go
- core/internal/runconfig/runconfig.go
- core/internal/runconfig/runconfig_test.go
- core/pkg/server/sender.go
Description
-----------
This PR creates a common PathTree object that will be used with many objects in the stream, in this PR we just use it for RunConfig
Testing
-------
> refactor(core): create common PathTree struct and use  in RunConfig

- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
- wandb/sdk/artifacts/artifact.py
Description
-----------
- Fixes reported regression [WB-18421](https://wandb.atlassian.net/browse/WB-18421)
Improves the error message returned when `Api().artifact("foo/bar/baz:X")` is called but doesn't exist.
Testing
-------
New test for existence error message.
[WB-18421]: https://wandb.atlassian.net/browse/WB-18421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): report why an artifact can't be found

- tests/pytest_tests/unit_tests/test_lib/test_mailbox.py
Description
---
Updates the test file to not use unittest which is a built-in framework that's superceded by pytest for us. This is necessary to use pytest's test parametrization capabilities (which I'm trying to use to run all tests with and without wandb-core).
See also https://docs.pytest.org/en/7.1.x/how-to/unittest.html
> refactor(sdk): Migrate test_mailbox.py to pytest from unittest

- CHANGELOG.md
- core/pkg/artifacts/downloader.go
- core/pkg/artifacts/file_cache.go
- core/pkg/artifacts/file_cache_test.go
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Description
-----------
- Fixes [WB-18294](https://wandb.atlassian.net/browse/WB-18294)
Add a file cache manager and integrated it into the wandb-core artifact downloader.
`FileCache` is a lightweight struct (it only contains a reference to the cache directory) used to centralize access.
New exported Methods (all on `FileCache`):
* `AddFile(path)`: Copies file at `path` into the cache and returns the B64MD5 digest that's used as the cache key.
* `AddFileAndCheckDigest(path, digest)`: Convenience function, same, but checks that the digest matches what's expected. Used for background adds, since it logs errors but doesn't return them.
* `RestoreTo(entry, path)`: uses the entry digest/etag to attempt to restore a cached file to given path. Succeeds without copying anything if the file is …
> feat(artifacts): use the cache when downloading through wandb-core

- core/pkg/filestream/filestream.go
- core/pkg/filestream/filestream_test.go
- core/pkg/filestreamtest/filestreamtest.go
- core/pkg/server/sender.go
Description
---
Replaces the SetPath() and SetOffsets() methods by parameters to Start(). Also moves the responsibility for constructing the URL path from Sender to FileStream.
> refactor(core): Move FileStream.SetPath/SetOffsets into Start()

- CHANGELOG.md
- core/pkg/artifacts/downloader.go
- core/pkg/artifacts/file_cache.go
- core/pkg/artifacts/manifest.go
- core/pkg/artifacts/saver.go
- tests/pytest_tests/system_tests/test_artifacts/test_artifact_cli.py
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Description
-----------
- Fixes [WB-18295](https://wandb.atlassian.net/browse/WB-18295)
Cache files when uploading with `wandb-core`, unless `SkipCache` is set to true for that entry
Testing
-------
Removed the `wandb_core_failure` mark from tests that previously failed because they relied on the upload caching behavior of the Python core.
[WB-18295]: https://wandb.atlassian.net/browse/WB-18295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(artifacts): cache files when uploading with wandb-core

- core/internal/runfiles/runfiles.go
- core/internal/runfiles/runfiles_test.go
- core/internal/runfiles/upload_batcher.go
- core/internal/runfiles/uploader.go
- core/internal/waiting/waiting.go
- core/internal/waitingtest/waitingtest.go
- core/pkg/server/stream_init.go
Description
---
I was updating tests for `filestream` and found several untested bits of code relying on `time.After()`. This PR extracts the pattern I used in `runfiles` so that I can better test `filestream` later.
> refactor(core): Introduce 'waiting' package for testable code with Sleep()

- core/pkg/filestream/collector.go
- core/pkg/filestream/loop_transmit.go
Description
---
Every time I looked at this file I kept forgetting the differences between "isTransmitReady" and "isDirty", how "isDone" is set, and the fact that "finalTransmitData" is just used to store two booleans. Added docs so that I don't have to reread the whole thing every time :)
Also updated its interface to just a "CollectAndDump" method instead of calling read(), readMore() and dump() from loop_transmit.go. This lets loop_transmit.go focus on its job and clarifies the contract for collector.go.
> refactor(core): Add comments in `collector.go`

- tests/pytest_tests/unit_tests/test_launch/test_inputs/test_files_helpers.py
- wandb/sdk/launch/inputs/files.py
Description
-----------
This PR adds an internal library to the launch SDK for reading and writing user config files that are being managed as part of job inputs. The PR also includes a test suite.
Testing
-------
> chore(launch): add helpers for config file job inputs

- core/pkg/server/sender.go
Description
-----------
Every time we send an update message to the sender, we set the debounce logic, hence there is no need to do it when we are flushing the summary, as if we already debounce it, we won't need to do anything.
Testing
-------
> fix(core): avoid setting the debouncer if there were no changes made

- wandb/sdk/interface/interface.py
Description
-----------
The `source` attribute of the `JobInputRequest` was not being set after being constructed in `publish_job_input`. This is a fix but since this is not directly exposed to users in any way I'm not updating the changelog.
Testing
-------
> fix(launch): add source message to job input in publish method

- core/internal/runfiles/saved_file.go
Description
---
The query part of the URL can change, e.g. if it contains an expiration time or an auth token.
There was no bug here as far as I can tell, but there was certainly the opportunity for a bug. I rearranged the code to make the assumption unnecessary.
> refactor(core): Don't assume file upload URL doesn't change

- core/internal/api/api.go
- core/internal/api/send.go
- core/internal/filetransfer/file_transfer_default.go
Description
---
Moves the err==nil && resp==nil check into `api` to avoid duplicating it. We had this check in `filetransfer` but we also need it to apply in `filestream`.
As I recall, this is some bug in the retryablehttp client, but I don't remember if we have a tracking bug or a way to reproduce it.
> refactor(core): Move (nil, nil) retryablehttp output handling

- tests/pytest_tests/unit_tests/test_launch/test_inputs/test_internal.py
- wandb/sdk/launch/inputs/internal.py
Description
-----------
This PR adds the internal library for handling user specified launch job inputs. The library serves as a layer between the user SDK functions (not yet added) and the wandb internal process. The library has two `handle` functions, `handle_config_file_input` and `handle_run_config_input`
These methods process user requests to add config file and run config inputs to their job, respectively. This mostly consists of passing these arguments to the internal process to configure the job builder with the correct inputs.
`handle_config_file_inputs` is also responsible for patching the config file.
Testing
-------
> chore(launch): add internal library for handling inputs and applying overrides

- wandb/apis/public/api.py
Description
-----------
- Follows up on [WB-15063](https://wandb.atlassian.net/browse/WB-15063)
This PR follows up on #7483 and makes the docstrings for `artifact_exists` and `artifact_collection_exists` clearer
Testing
-------
Just a documentation change, no testing needed
[WB-15063]: https://wandb.atlassian.net/browse/WB-15063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(public-api): make docstrings for public api exists functions clearer

- tests/pytest_tests/unit_tests/test_launch/test_inputs/test_internal.py
- wandb/sdk/launch/inputs/internal.py
- wandb/sdk/wandb_run.py
Description
-----------
This PR modifies the internal handlers for launch job input customization. Instead of requiring an active run (`wandb.run`) to pass input customizations to the job builder, the functions can now stage user arguments on a singleton. When `wandb.init` is called, any staged arguments will be passed to the job builder in the `run._on_ready` hook.
> chore(launch): make job input handlers callable before `wandb.init`

- wandb/apis/public/api.py
Description
-----------
- Follows up on [WB-15063](https://wandb.atlassian.net/browse/WB-15063)
This PR follows up on #7483 and #7519 to make the doc strings for the `name` argument in `artifact_exists` and `artifact_collection_exists` more accurate.
Testing
-------
[WB-15063]: https://wandb.atlassian.net/browse/WB-15063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(public-api): make `name` argument clearer in exists functions

- core/pkg/observability/logging.go
Description
---
Without this, fatal log lines in debug-internal.log don't include an "error" field unless the caller writes something like
```go
logger.CaptureFatal(msg, err, "error", err)
```
> fix(core): Log error in CaptureFatal

- core/hatch.py
Description
-----------
- Fixes #NNNN
We pass the `--weak-unresolved-symbols` flag to the gold linker on Linux when building core. It is necessary to
because the NVML libraries that are needed for Nvidia GPU monitoring may not be available at build time. (The Go buildings for nvml assume that those libs are available at build time, see https://github.com/NVIDIA/go-nvml)
Testing
-------
> docs(sdk): update comment on unresolved symbols when building with cgo

- core/pkg/launch/config.go
- core/pkg/launch/config_test.go
Description
-----------
In the code for filtering configs down by prefix, we were using the same
slice address as a key for multiple paths. I modified the code that flattens
the user config into this map so that it creates distinct memory for each
path slice.
Testing
-------
> fix(launch): slice memory bug in core process job input filtering

- core/pkg/filestream/logsupdate.go
- core/pkg/server/sender.go
Description
---
Moves some console logs related code from `sender.go` into `filestream` as a pre-cursor to adding carriage-return handling.
> refactor(core): Move some output preprocessing into filestream

- core/pkg/filestream/filestream.go
- core/pkg/filestream/filestream_test.go
- core/pkg/filestream/transmitchunk.go
Description
---
Accidentally missed this in https://github.com/wandb/wandb/pull/7553, so `filestream` was always writing to offset 0 in Nexus.
It's a little surprising that no tests caught this! It would seem it's because of request batching, but a test only needs to log just over 20 milliseconds apart to send more than a single batch.
Testing
---
I originally wrote a test, but it was flaky because there's no way to wait until `collector.go` reads exactly one update from the input stream. I have a different PR in which I delete `collector.go` completely, and other PRs where I improve the tests.
> fix(core): Increment file offsets in filestream

- pyproject.toml
- tests/pytest_tests/conftest.py
- tests/pytest_tests/system_tests/test_core/test_wandb_run.py
- tests/pytest_tests/system_tests/test_launch/test_launch_manage.py
Description
---
Creates a "wandb_core_only" pytest marker intended for tests for features in wandb-core that are not available in the Python service implementation.
> chore(sdk): Add "wandb_core_only" pytest marker

- tests/pytest_tests/unit_tests/test_launch/test_builder/test_docker.py
- tests/pytest_tests/unit_tests/test_launch/test_create_job.py
Description
-----------
This PR disables two launch unit tests on Windows because to make them pass we would need to make the assertions more complex and windows is not even a supported environment for launch.
Testing
-------
> ci(launch): disable 2 launch unit tests on windows

- core/pkg/observability/util.go
Description
-----------
Currently the nexus core creates a cache dir at:
```
~/.cache/.wandb
```
And stores a bunch of files there related to nexus startup logs.
This is somewhat hard to find, i don't think we do a great job of advertising that this file exists.
But the more trivial problem, is that it probably could be more better named.   We already create a cache dir at:
```
~/.cache/wandb
```
which stores:
```
~/.cache/wandb/artifacts/
```
The .wandb is possibly an over-reaction to the troubles we have felt with the "wandb" dir in the users working directory.   In the cache dir, it is more common to be less hidden -- and we should be consistent.
I propose:
```
~/.cache/wandb/logs/
```
Testing
-------
> chore(core): use more standard cache dir for logs

- tests/pytest_tests/system_tests/conftest.py
Description
-----------
Bump wait time for local-testcontainer spin up when running system tests. It can sometimes take a while to download and extract docker layers.
Testing
-------
> test(sdk): bump wait time for local-testcontainer spin up

- .github/workflows/generate-docodile-documentation.yml
Description
-----------
See thread: https://weightsandbiases.slack.com/archives/C01DX8LRZEJ/p1715021790435539
Updates docugen tag used in GH workflow.
Testing
-------
> docs(sdk): Updated workflow docugen version release tag

- core/pkg/launch/config_files.go
- core/pkg/launch/job_builder_test.go
- tests/pytest_tests/system_tests/test_launch/test_launch_manage.py
- wandb/sdk/launch/inputs/internal.py
Description
-----------
- Fixes WB-18773
This PR changes the value of an important constant: the path within run files where we save config files managed by launch. The features this is used for has not been officially released so this is a chore.
Testing
-------
> chore(launch): save config files to `_wandb_configs/` instead of `configs/`

- core/pkg/launch/job_builder.go
- tests/pytest_tests/system_tests/test_launch/test_launch_manage.py
Description
-----------
- Fixes WB-18772
This PR modifies the core job builder to save `wandb.config` inputs iff `launch.manage_wandb_config` was called. A system test has been updated to check this.
Testing
-------
> chore(launch): only save run config inputs to metdata if manage_wandb_config is called

- core/api/graphql/mutation_update_artifact.graphql
- core/internal/gql/gql_gen.go
Description
-----------
This PR adds the `UpdateArtifact` mutation for use in core. This is to enable enable the job builder in core to update partial job metadata.
Testing
-------
> chore(artifacts): add updateArtifact mutation to wandb-core code gen

- tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
- tests/pytest_tests/unit_tests/test_launch/test_create_job.py
- tests/pytest_tests/unit_tests/test_launch/test_project/test_project.py
- wandb/sdk/launch/_project_spec.py
- wandb/sdk/launch/builder/build.py
- wandb/sdk/launch/create_job.py
Description
-----------
- Fixes [WB-18376](https://wandb.atlassian.net/browse/WB-18376)
Display a warning when the user tries to create or launch a job where `wandb` isn't in the `requirements.txt`, since it's generally required for a run to succeed.
Testing
-------
Made a code job with no wandb in the `requirements.txt`
[WB-18376]: https://wandb.atlassian.net/browse/WB-18376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(launch): Warn when wandb is missing from requirements

- CHANGELOG.md
- wandb/beta/workflows.py
Description
-----------
- Fixes [SV-71](https://wandb.atlassian.net/browse/SV-71)
HiddenLayer has discovered three vulnerabilities while researching the Weights and Biases (WandB)
project, which this document describes in detail. As defined by MITRE’s CWE specification, these
vulnerabilities are Deserialization of Untrusted Data and Improper Control of Generation of Code ('Code
Injection'). These vulnerabilities allow for a threat actor to craft a malicious model which, when loaded,
can execute arbitrary code on the system. 
Testing
-------
[SV-71]: https://wandb.atlassian.net/browse/SV-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> security(sdk): Adding unsafe flag to use_model

- CHANGELOG.md
- wandb/sdk/launch/utils.py
Description
-----------
- Fixes #NNNN
Testing
-------
> fix(launch): Support Azure repo URI format in Launch

- core/internal/filestream/filestreamimpl.go
- core/internal/filetransfer/file_transfer_manager.go
- core/internal/filetransfer/tasks.go
Description
-----------
- Fixes WB-18895
Pass data by value when sending on filestream to prevent potential races.
Testing
-------
> fix(sdk): pass data by value when sending on filestream

- CHANGELOG.md
- core/internal/filetransfer/file_transfer_manager.go
- core/pkg/artifacts/saver.go
- core/pkg/server/sender.go
Description
-----------
- Fixes [WB-17571](https://wandb.atlassian.net/browse/WB-17571)
Rewrite of `ArtifactSaver.uploadFiles` to use buffered channels and switch between available pending tasks
This is an alternative to https://github.com/wandb/wandb/pull/7274, and should be considered to supersede it. It's dramatically simpler, has similar (though slightly lower) performance, and handles retries better.
**Key differences**:
1. We don't impose an arbitrary minimum time (previously 1 hour) before retrying failed uploads
2. We bound the number of outstanding goroutines to limit maximum memory consumption
3. Overall this version is 20-25% faster for artifacts with many small files
Minor differences:
Differences:
1. I hope that this version is simplified and a little easier to follow, though …
> perf(artifacts): pipeline the artifact file uploader

- core/internal/runfiles/upload_batcher.go
- core/internal/waitingtest/fakedelay.go
Description
---
Fixes `FakeDelay::Wait()` which was doing the following:
1. Checking `isZero` while holding a lock
2. Briefly releasing the lock
3. Locking it again, then waiting for `isZero` to change
On rare occasions, `isZero` could change during (2), causing (3) to block forever.
> fix(core): Fix race condition in fakedelay.go

- CHANGELOG.md
- core/pkg/server/handler.go
- core/pkg/server/handler_test.go
- core/pkg/server/sender.go
- core/pkg/server/sender_test.go
- core/pkg/server/stream.go
- core/pkg/server/writer.go
- tests/pytest_tests/system_tests/test_core/test_resume.py
Description
-----------
- Fixes WB-18313
- Fixes #4727
Output log files will from now on be called YYYYMMDD_HHmmss.ms_output.log and placed in the logs folder in the run dir. This solves the issue where we would overwrite logs when resuming runs.
Testing
-------
> fix(sdk): correctly upload console log files when resuming

- tests/pytest_tests/unit_tests/test_launch/test_create_job.py
- wandb/sdk/launch/create_job.py
Description
-----------
This PR changes a line from 
```python
_, python_version = get_current_python_version()
```
to
```python
python_version, _ = get_current_python_version()
```
The first argument returned by `get_current_python_version` is what we actually want to assign `python_version` to. The second return value is just the major version. This was leading to repo jobs being created by `wandb launch -u` having `3` as their python version and crashing when we tried to launch them.
Testing
-------
> fix(launch): repo jobs use correct default python version

- wandb/integration/gym/__init__.py
Description
-----------
- Fixes https://github.com/wandb/wandb/issues/7047
- Related: https://github.com/Farama-Foundation/Gymnasium/issues/944
This PR updates the `monitor_gym` integration to support the upcoming Gymnasium `v1.0.0` release. The key changes include:
- Added version checks for Gymnasium to handle breaking changes introduced in `v1.0.0`.
- Updated the handling of RecordVideo for Gymnasium `v1.0.0` and later versions.
- Adjusted the logic to maintain backward compatibility with older versions of both Gym and Gymnasium.
- Ensured that the path variable is set correctly based on the Gym/Gymnasium version.
Testing
-------
I ran the ["Stable Baselines 3 - Track Experiments with Weights and Biases"](https://github.com/wandb/examples/blob/master/colabs/stabl …
> Gymnasium v1.0.0 support

- core/pkg/launch/job_builder.go
- core/pkg/launch/job_builder_test.go
- core/pkg/server/sender.go
- tests/pytest_tests/system_tests/test_launch/test_job.py
- tests/pytest_tests/unit_tests/test_job_builder.py
- wandb/sdk/internal/internal_api.py
- wandb/sdk/internal/job_builder.py
- wandb/sdk/internal/sender.py
- wandb/sdk/launch/create_job.py
Description
-----------
- Fixes WB-18438
This PR modifies the core and legacy job builder to never create a new job version when a partial job is used.
Partial jobs are created by the `wandb job create` or `wandb launch -u` commands. They include source information but no input or output type info. When a run created from a partial job finishes, the job builder constructs a new, non-partial job version with the input and output info saved into the `wandb-job.json` file.
Jobs now support having i/o types stored in artifact version metadata, which can be mutated without producing a new job version. Partial jobs now write `_partial` key to the metadata that can be used to identify partial jobs. If a partial job is detected the job builder will overwrite the artifact metadata with the i/o …
> fix(launch): overwrite partial job metadata instead of building a new job version

- .github/workflows/check-pr-title.yml
- CHANGELOG.md
- CONTRIBUTING.md
- core/pkg/server/handler.go
- tests/pytest_tests/system_tests/test_core/test_metric_full.py
- tests/pytest_tests/system_tests/test_functional/test_mode_shared.py
Description
-----------
We were not flushing the history record and instead kept accumulating stuff, which produces some weird result when saved to leveldb and sent to the backend.
Testing
-------
> fix(core): flush history record correctly in shared mode

- wandb/sdk/wandb_run.py
Description
-----------
This PR fixes the docstring for `run.log_artifact` by removing the statement that the name argument "May be prefixed with entity/project". When this function takes in an artifact path, we actually do not support names prefixed with entity/project.
Testing
-------
Just a docstring change
> docs(artifacts): fix name argument docstring in `run.log_artifact`

- core/internal/filetransfer/file_transfer_retry_policy.go
Description
-----------
- Fixes WB-18702, I hope
use retryablehttp's default retry policy for file transfer
Testing
-------
> chore(sdk): use retryablehttp's default retry policy for file transfer

- core/pkg/server/sender.go
- core/pkg/server/stream.go
Description
---
Calls `TBHandler::Finish()` in the "defer" state machine in the sender. I added this method in a recent PR but forgot to invoke it.
> fix(core): Call Finish() on TBHandler

- .codecov.yml
Description
---
Adds `**/*.pb.go` to the codecov `ignore` setting. This came up because the protos for the TB integration are under `core/internal/tensorboard/tbproto/` rather than `wandb/proto/` where they wouldn't belong.
> chore(sdk): Ignore all .pb.go files in codecov

- core/internal/filestream/filestream.go
- core/internal/filestream/filestreamimpl.go
- core/internal/filestream/update.go
- core/internal/filestream/updatehistory.go
- core/pkg/server/handler.go
- core/pkg/server/stream_init.go
Description
---
Creates the `_client_id` pseudo-metric in the Handler method that also sets `_step`, so that that method is the only place where new HistoryItems are created and so that the logic is more cohesive.
> refactor(core): Move `_client_id` logic to handler from filestream

- tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py
- wandb/sdk/launch/environment/aws_environment.py
- wandb/sdk/launch/runner/sagemaker_runner.py
- wandb/sdk/launch/utils.py
Description
-----------
- Fixes #NNNN
Right now the aws environment always assumes users are on the aws partition. This breaks the Sagemaker runner for those on different aws partitions. This fixes that
Testing
-------
> chore(launch): Support getting the partition from aws environments

- core/internal/filestream/updatehistory.go
- core/internal/filestream/updatesummary.go
- core/pkg/observability/printer.go
- core/pkg/observability/printer_test.go
- core/pkg/server/handler.go
Description
---
Changes the `Printer` to allow rate-limiting (`AtMostEvery(duration)`) messages containing dynamic data.
Testing
---
Unit tests.
> refactor(core): Rate limit printer messages based on format string

- core/internal/runhistory/runhistorysampler.go
- core/pkg/server/handler.go
Description
---
The sampler implementation in `handler.go` was not reading the `NestedKey` field of `HistoryItem`. This pulls out history sampling logic into a dedicated `runhistorysampler.go` file and implements it properly.
There is a bug in Python where it doesn't _read_ the `nested_key` field. I left a comment about it in `runhistorysampler.go`. Amazingly, this is countered by a bug in the Python TensorBoard integration, which seems to produce items that use `key` instead of `nested_key`, causing them to have sparklines anyway.
Testing
---
The following doesn't print a sparkline with the Python implementation but does with `wandb.require("core")`:
```python
with wandb.init() as run:
for x in range(100):
run.log({"my": {"value": x}})
```
The TensorBoard integration with and without …
> fix(core): Correctly sample history metrics with nested keys

- pyproject.toml
Description
---
Updates Ruff linting rules.
> chore(sdk): Don't require docstrings in test functions

- core/internal/filestream/filestreamimpl.go
Description
---
```go
// Before:
thing := ...
go func() {
use(thing)
}()
// After:
go func() {
thing := ...
use(thing)
}()
```
> refactor(core): Move variable into scope where it's used

- core/internal/filestream/collectorstate.go
Description
---
Don't append to `wandb-summary.json`; always overwrite the last line instead.
> fix(core): Always overwrite the same line in wandb-summary.json

- tools/bench/bench.py
Description
-----------
Usage:
```
./bench.py --core false
```
Will make sure we are running without wandb-core even in opt-out mode (current dev environment)
Testing
-------
Manually tested as it is a performance tool and doesn't (yet) have any sanity tests.
> chore(sdk): modify benchmark tool for opt-out core

- tests/pytest_tests/system_tests/test_notebooks/test_notebooks.py
- wandb/sdk/wandb_run.py
Description
---
Adds a notice that's printed at the end of every run that informs users that wandb>=0.18.0 will use wandb-core by default.
The notice is not printed if we're in "quiet" mode or if the run used core.
Testing
---
```
$ WANDB__REQUIRE_CORE=false python
>>> run = wandb.init()
>>> run.finish()
$ WANDB__REQUIRE_CORE=true python
>>> run = wandb.init()
>>> run.finish()
```
> chore(sdk): Add notice about wandb-core becoming opt-out

- core/pkg/server/sender.go
- core/pkg/server/store.go
- core/pkg/server/store_test.go
- core/pkg/server/writer.go
Description
---
Removes logging from `store.go` since all errors are logged by the callers.
> refactor(core): Don't double-log errors in `store.go`

- core/internal/filestream/filestream.go
- core/internal/filetransfer/file_transfer_manager.go
- core/pkg/artifacts/linker.go
- core/pkg/observability/logging.go
- core/pkg/server/handler.go
- core/pkg/server/responder.go
- core/pkg/server/sender.go
- core/pkg/server/stream_init.go
- core/pkg/server/writer.go
Description
---
Refactors `CaptureFatal` and `CaptureFatalAndPanic` to include the error log message as well as the error.
```go
// BEFORE.
//
// This would log only 'err' in Sentry without the log message
// which contains important context.
logger.CaptureFatal(
"sender: failed during XYZ",
err,
)
// AFTER.
//
// All useful information is uploaded.
logger.CaptureFatal(
fmt.Errorf("sender: failed during XYZ: %v", err))
```
I finished this refactor completely for `CaptureFatal` / `CaptureFatalAndPanic`. I'll do `CaptureError` in a separate PR as it involves more changes.
> refactor(core): Upload more context with CaptureFatal

- wandb/proto/v5/wandb_internal_pb2.pyi
Description
-----------
Update docstring in generated protobuf v5 stubs. There must have been a sync issue with multiple prs merging around the same time.
Testing
-------
> chore(sdk): update docstring in generated protobuf v5 stubs

- CHANGELOG.md
- tests/pytest_tests/unit_tests/test_launch/test_internal_api.py
- wandb/cli/cli.py
- wandb/sdk/internal/internal_api.py
Description
-----------
- Fixes [WB-19251](https://wandb.atlassian.net/browse/WB-19251)
We already have the ability to add already-completed runs to a sweep from the UI. This PR adds the ability to do the same using the command line, using `wandb sweep -R <run id> -R <run id> ...`
Testing
-------
A unit test was added.
Tested manually using the following: `wandb sweep -R cq35n9a1 -R oobmkxxw sweep_config.yaml -e tim-hays -p debugging`, and confirming in the UI that the sweep had the two runs added to it (the contents of the runs and the sweep config are not important).
[WB-19251]: https://wandb.atlassian.net/browse/WB-19251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(launch): Add prior runs when creating a sweep from the CLI

- wandb/sdk/internal/system/assets/gpu.py
bypass pynvml
Description
-----------
- Fixes #7770 
- Fixes #7168
There is an issue with pynvml upstream where it is unable to get driver version of the latest nvidia driver and is breaking a lot of tools, one of which is wandb.
Unfortunately pynvml is closed so we have to make changes in our tools to handle it.
The issue seems to be in pynvml.nvmlDeviceGetName which throws an error.
This is a minimal fix where I handle the error thrown by the GPU probe
Testing
-------
I ran this on my local code and verified it as working.
> fix(sdk): guard against unexpected pynvml errors when probing GPU info

- tests/pytest_tests/unit_tests_old/test_launch/test_public_api.py
- wandb/apis/public/projects.py
Description
-----------
- Fixes WB-18415
Allows users to access all attrs of a sweep when doing `api.project.sweep`
Testing
-------
Using this code:
```
import wandb
project = api.project(name="test_relation_sweep", entity="luis_team_test")
sweep = [sweep for sweep in project.sweeps() if sweep.id == "xrr345rs"][0]
try:
print(sweep.runs)
print(sweep.state)
except Exception as e:
print("Project error")
print(e)
```
Before:
```
[]
Project error
'<Sweep test-debug/pytorch-sweeps-demo/vdnc4y73 (Unknown State)>' object has no attribute 'state'
```
After:
```
<Runs luis_team_test/test_relation_sweep>
RUNNING
```
> fix(public-api): make all sweep attrs accessible via api.project.sweeps

- tests/pytest_tests/system_tests/test_sweep/test_sweep_public_api.py
- wandb/sdk/wandb_sweep.py
Description
---
Defines the 'terminalemulator' package with support for basic escape sequences:
* '\r' -- carriage return
* '\x1b[A' -- cursor up
* '\x1b[B' -- cursor down
These are used by `tqdm` when displaying nested progress bars. I'm not sure if `tqdm` uses any other escape sequences.
Testing
---
Unit tests, plus manual testing in the final PR in this series which wires everything up.
> feat(core): Simple terminal emulator

- .circleci/config.yml
Description
-----------
Instead of `pip install -U pip`, use `python -m pip install -U pip`.
> chore(sdk): Fix Windows CI pip upgrade issue

- CHANGELOG.md
- core/internal/auth/netrc.go
- core/internal/auth/netrc_test.go
- core/internal/settings/settings.go
- tests/pytest_tests/unit_tests_old/conftest.py
- wandb/sdk/internal/internal_api.py
- wandb/sdk/lib/apikey.py
Description
-----------
- Fixes WB-19324
The netrc file on Windows should be named `_netrc` (for historical reasons, I believe). However, sometimes it's called .netrc like everywhere else. This PR implements the following logic:
- if NETRC env var is set, use that as the path
- If either ~/.netrc or ~/_netrc exists, use it on either platform
- If not, use ~/.netrc on non-win systems and ~/_netrc on win.
Testing
-------
Verified that the fix works on a Win VM.
> fix(sdk): robustly handle netrc file on windows

- core/pkg/server/connection.go
- core/pkg/server/tokenizer.go
Description
---
Fixes: WB-19434
Rewrites `tokenizer.go` to return an error if the header magic byte is wrong. Also refactors it to follow `bufio` conventions---instead of a stateful object, we define a pure function called `ScanWBRecords` like `ScanLines`/`ScanRunes`/`ScanWords` with a similar documentation style.
Testing
---
Run any WB script with some logging and printing.
> fix(core): Panic on invalid magic byte

- core/internal/filestream/retry_policy.go
Description
---
Fixes: WB-19478
Updates the code so that it retries HTTP 408 Request Timeout which retryablehttp's default policy does not retry.
> fix(core): Retry more errors in filestream

- CHANGELOG.md
- wandb/sdk/wandb_manager.py
- wandb/sdk/wandb_setup.py
Description
---
Instead of calling `os._exit()`, calls `sys.exit()`---ensuring that it does not happen inside an `atexit` hook.
I kept the current behavior of exiting the process on teardown() if the internal process exits with a non-zero code, but it feels like a terrible semantic that we should reconsider.
I looked for uses of `_teardown` by doing a regex search using `\._teardown\(`; `wandb_setup` is the only place that invoked this.
Testing
---
In my PR that enables Go race detection, using `sys.exit()` makes tests fail when there's a data race rather than quitting pytest and sending pytest-xdist into a "worker crashed" loop.
> fix(sdk): Don't os._exit() if internal process had non-zero exit code

- core/pkg/server/sender.go
Description
-----------
- Fixes WB-19375
We use the same record type for the initial run upsert and the follow-up run updates, such as setting the name, tags, and notes. The client only expects a response for the initial upsert, the consequent updates are fire-and-forget and thus don't have a mailbox slot. But we were always expecting one and wrongfully capturing an error.
TODO: We should probably separate the initial upsert from the updates.
Testing
-------
> fix(core): do not expect control.mailbox_slot for run record updates

- CHANGELOG.md
- core/internal/filestreamtest/filestreamtest.go
- core/internal/runconsolelogs/debouncedwriter.go
- core/internal/runconsolelogs/debouncedwriter_test.go
- core/internal/runconsolelogs/filestreamwriter.go
- core/internal/runconsolelogs/outputfilewriter.go
- core/internal/runconsolelogs/runconsolelogs.go
- core/internal/runconsolelogs/runconsolelogs_test.go
- core/internal/runconsolelogs/runlogschangemodel.go
- core/internal/terminalemulator/lines.go
Description
---
Fixes a race condition caused by the buffering goroutine using the mutable `RunLogsLine`.
Testing
---
Caught by enabling race detection in https://github.com/wandb/wandb/pull/7862.
I also added a new test which (occasionally) fails without `line.Clone()` in `debouncedwriter.go` if you run with `go test -race`.
> fix(core): Fix race condition in `runconsolelogs`

- hatch_build.py
- pyproject.toml
- requirements_dev.txt
Description
---
We should be marking overridden methods with `@override` (introduced in PEP 698). This silences the Ruff's D102 lint (requiring public methods to have docstrings) because the method in the base class provides the docstring, and it also makes the intention more explicit.
The import is from `typing_extensions` rather than `typing` because `typing.override` was added in Python 3.12.
> chore(core): Add `@override` to method to silence lint

- core/pkg/server/stream_init.go
Description
-----------
- Fixes WB-19433
Fixes an issue where a user uses service account, but provides only user_email, in that case we used to provide a wrong username that takes precedence over user_email and would assign the run to the wrong user. 
Now this logic matches the logic we have in our python code, but it seems that the real issue is that `username` has a specific usage in case of a service account, and auto populated breaks the assumption that it is always correct.
Testing
-------
manually tested to see that the attached user matches the one specified in this script:
```
import os
import random
import wandb
wandb.require("core")
os.environ["WANDB_USER_EMAIL"] = "user2@xyz.com" …
```
> fix(core): use correct headers for service account

- core/internal/filetransfer/file_transfer_manager.go
- core/internal/runfiles/uploader.go
Description
---
In `file_transfer_manager.go` and `runfiles/uploader.go`, replaces some dynamic text in error strings by `CaptureError` tags.
> refactor(core): Move some error message properties to tags

- core/internal/filestream/filestream.go
Description
---
Makes `StreamUpdate` return immediately after filestream has experienced a fatal error.
This just reduces the amount of resource usage in that case, but shouldn't have any observable effect otherwise.
> refactor(core): Ignore filestream inputs after fatal error

- core/pkg/monitor/monitor.go
Description
---
Gets rid of `record.GetItem().Item = append(record.GetItem().Item, ...)`.
> refactor(core): Refactor monitor.go::makeStatsRecord

- core/internal/pathtree/pathtree.go
Description
---
Removes the "config:" prefix which is wrong and adds more info to the message.
> refactor(core): Better error message in pathtree.go

- CHANGELOG.md
- wandb/sdk/wandb_run.py
Description
---
Stops calling `os._exit()` when an exception is encountered in `Run._atexit_cleanup()` and refactors the surrounding code. We should not use `os._exit()`.
Semantic changes:
* I removed `_backend.cleanup()` in the exception handler in `_atexit_cleanup`---this just sends a shutdown request to the service.
* With core, this request is a no-op.
* Without core, this was killing the handler without killing the process, causing `streams.py::StreamMux::_finish_all()` to block forever in the `mailbox.wait_all()` step on exit, blocking the user process forever waiting for the service to die. This was unnecessary because `_finish_all()` calls `join()` on each stream at the end which sends the same shutdown signal that `_backend.cleanup()` was sending.
* We re-raise exceptions rather …
> refactor(sdk): Remove os._exit() from Run.finish(), and clean up

- wandb/sdk/artifacts/artifact.py
Description
-----------
This minor PR adds a line to the add_reference() function about the behaviour when checksum=False for a directory. More specifically, if the checksum argument is set to False, add_reference() will not create a new version of the artifact.
More discussion on [Slack](https://weightsandbiases.slack.com/archives/C04656QPFHN/p1718370664829409).
Fixes [WB-18037](https://wandb.atlassian.net/browse/WB-18037)
Fixes [DOCS-898](https://wandb.atlassian.net/browse/DOCS-898)
Testing
-------
Tested locally.
[WB-18037]: https://wandb.atlassian.net/browse/WB-18037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-898]: https://wandb.atlassian.net/browse/DOCS-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
> docs(sdk): update add_reference() docstring

- CHANGELOG.md
Description
-----------
Due to merge evolution, #7721 added an update to the 0.17.4 section instead of the "unreleased" section. This just moves it back.
Testing
-------
Doc only, no tests
> chore(sdk): fixup changelog from #7721

- wandb/util.py
Description
---
Fixes a KeyError thrown in `merge_dicts` if the destination dictionary has a value type that doesn't match the source. This seems like it was overlooked rather than done intentionally. I ran into this in a test.
NOTE: If the destination dictionary has a NumPy array, this will now overwrite rather than extend it. I don't think we were relying on this, but I wouldn't put it past our code... There aren't many `merge_dicts` usages, and none of them look suspicious to me.
> refactor(sdk): Improve `util.py::merge_dicts()`

- core/internal/pathtree/pathtree.go
- core/internal/pathtree/pathtree_test.go
- core/internal/runconfig/runconfig.go
- core/internal/runconfig/runconfig_test.go
- core/internal/runhistory/runhistory.go
- core/internal/runhistory/runhistory_test.go
- core/internal/runresume/resume_test.go
- core/internal/runresume/runresume.go
- core/internal/runsummary/runsummary.go
- core/internal/runsummary/runsummary_test.go
- core/pkg/launch/job_builder.go
- core/pkg/launch/wandb_config.go
- core/pkg/server/handler.go
- core/pkg/server/sender.go
Description
---
Removes `pathtree.Tree()` which is dangerous to use and cleans up all former usages of it.
A few places are modified to use `CloneTree()`, some others `GetLeaf()`, and I also added `ToExtendedJSON()` for serialization use-cases.
> refactor(core): Replace `pathtree.Tree()` by alternatives

- wandb/sdk/wandb_manager.py
Description
---
Uses `raise ... from` in `wandb_manager.py` to produce a nicer exception. I noticed this when I hit an exception in CI which was displayed by showing "ConnectionRefusedError" first, followed by "During handling of the above exception, another exception occurred:" for the resulting "ManagerConnectionRefusedError". This was mildly confusing.
> refactor(sdk): Correctly chain exception in wandb_manager.py

- wandb/filesync/upload_job.py
- wandb/sdk/internal/internal_api.py
Description
-----------
With Wandb server installed behind another application which requires a header to be authenticated, file upload doesn't work because file upload doesn't use the header passed to the setting "extra HTTP headers".
This PR fixes it by passing the setting "extra HTTP headers" as default value for header for the file upload.
> fix(sdk): Pass extra headers from settings as default headers for file upload

- wandb/proto/wandb_internal_pb2.py
Description
---
Raise an `ImportError` instead of silently leaving `wandb_internal_pb2.py` empty if the `protobuf` version is wrong, causing `import wandb` to fail with uninformative errors like "module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'" in random spots like 'wandb/sdk/lib/mailbox.py:103'.
Testing
---
If you delete the non-failing cases locally and try importing `wandb`, you see this:
```
File "<stdin>", line 1, in <module>
File "/Users/timoffex/Documents/workspace/wandb/wandb/__init__.py", line 27, in <module>
from wandb import sdk as wandb_sdk
File "/Users/timoffex/Documents/workspace/wandb/wandb/sdk/__init__.py", line 25, in <module>
from .artifacts.artifact import Artifact
File …
```
> fix(sdk): Raise ImportError on protobuf version mismatch

- wandb/wandb_agent.py
Description
-----------
- Fixes #NNNN
Pops the WANDB_SERVICE env var from the subprocess environment for sweep runs, causing them to spin up their own service
Testing
-------
> chore(sweeps): Dont reuse service in launched sweep runs

- tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py
- tests/pytest_tests/unit_tests/test_launch/test_builder/test_context_manager.py
- wandb/sdk/launch/builder/build.py
- wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Description
-----------
- Fixes [WB-19511](https://wandb.atlassian.net/browse/WB-19511)
Use uv to install packages instead of plain pip, since it's faster.
Testing
-------
Unit tests were updated. Manually tested by launching an artifact job and confirming `uv` was used to install packages.
Timing improvement over vanilla pip install can be seen [here](https://weightsandbiases.slack.com/archives/C044BQJCB46/p1721339421654649?thread_ts=1721336121.262159&cid=C044BQJCB46) (summary: installation time of 1:17 reduced to 0:17)
[WB-19511]: https://wandb.atlassian.net/browse/WB-19511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(launch): Use uv instead of pip to install requirements

- core/pkg/server/writer.go
Description
-----------
- Fixes WB-19850
(Marked as fixes corruption, but it might not be the only fix. will reopen after merge)
This PR fixes a potential issue where the writer goroutine could modify the protobuf record after forwarding it to the sending goroutine.   Since we send references around, this is unsafe and needs to be avoided.
The comment in the function describes what the intended behavior was: first write the record before sending it.
To make this behavior more explicit, the `writeRecord` function was broken into two, one which modifies the protobuf, and the other that adds it to the store channel.
Testing
-------
> fix(core): fix unsafe modification of protobuf in writer

- tests/pytest_tests/unit_tests/test_lib/test_hashutil.py
Description
-----------
- Fixes [WB-20049](https://wandb.atlassian.net/browse/WB-20049)
This tests is occasionally flaky; the issue seems to be timeouts, and the test "normally" takes 100's of milliseconds. There's no reason we should be running so many examples in CI, so this just caps it at 10 + two examples that have failed in CI (but seem to be fine themselves).
Testing
-------
Test run time reduced by 90%; no observed flakes yet.
[WB-20049]: https://wandb.atlassian.net/browse/WB-20049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(artifacts): use fewer examples for hypothesis file hashing tests

- tests/pytest_tests/__init__.py
- tests/pytest_tests/unit_tests/test_lib/test_hashutil.py
Description
-----------
- Fixes [WB-20049](https://wandb.atlassian.net/browse/WB-20049)
Since https://github.com/wandb/wandb/pull/8015 left at least one example that ran too long, this changes the default for hypothesis for all unit tests--even the non-file related tests were taking upwards of 100ms before.
Testing
-------
[WB-20049]: https://wandb.atlassian.net/browse/WB-20049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(artifacts): default to only testing 10 examples with hypothesis

- core/pkg/server/handler.go
Description
---
Logs the `_wandb.runtime` using a nested metric rather than a dot-separated key to fix regression introduced in #8004.
Testing
---
Create a run and finish it immediately. See the uploaded `wandb-summary.json` file (note that on the workspace overview page, the summary is always flattened in the UI, so there is no difference there).
> fix(core): '_wandb.runtime' => [_wandb, runtime]

- core/internal/runsummary/runsummary.go
- core/internal/runsummary/runsummary_test.go
- core/pkg/server/sender.go
Description
---
Uses the nested-maps representation of the summary in `sendJobsFlush` because it seems like the structure might matter. Removes the last remaining spot where we flatten summary keys.
> fix(core): Don't flatten summary in sendJobFlush()

- core/cmd/wandb-core/main.go
- core/pkg/observability/util.go
- core/pkg/server/connection.go
- core/pkg/server/handler.go
- core/pkg/server/handler_test.go
- core/pkg/server/stream.go
Description
-----------
We store the commit hash (passed in at build time) in the leveldb log header. This got broken at some point, this PR fixes it.
Testing
-------
> fix(core): correctly propagate the commit hash to version string

- wandb/sdk/wandb_run.py
Description
---
Prevents RunStatusChecker from looping forever after a timeout reading a mailbox handle.
> fix(sdk): Fix RunStatusChecker loops

- core/pkg/server/sender.go
- wandb/sdk/wandb_settings.py
Description
-----------
- Fixes WB-19659
Based on a user feedback added explicit error messages for `wandb-core` not supporting fork_from/resume_from
As well as slightly modified the warning for `resume_from`
Testing
-------
> chore(sdk): add better errors/warnings for resume_from/fork_from

- core/internal/runmetric/runmetric.go
Description
-----------
Update the logic that insert a step if sync_step is set, instead of iterating over all the steps we iterate over the current history keys and insert only for these that need to be synced
Testing
-------
> fix(core): only try to insert steps for active history lines

- CHANGELOG.md
- core/pkg/artifacts/manifest.go
- core/pkg/artifacts/manifest_test.go
- tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Description
-----------
@kptkin left some comments post-merge on #8017 which unveiled some significant issues. This is effectively a fix for that PR.
Most importantly, the types used during JSON decoding weren't correct and the errors were being silently ignored. The additional unit tests for the Go side decoding should cover every possible field and their defaults.
Testing
-------
Added unit tests for functions from `manifest.go`, including extensive tests for reading the manifest from file.
> fix(artifacts): fix issues from #8017, including JSON decoding bugs

- core/pkg/artifacts/file_cache.go
- core/pkg/artifacts/file_cache_test.go
- core/pkg/utils/hash.go
- core/pkg/utils/hash_test.go
Description
-----------
- Fixes [WB-20142](https://wandb.atlassian.net/browse/WB-20142)
Extend `artifacts.FileCache` so that it can restore manifest entries that are references using the etag cache.
Note that this code isn't currently (yet) ever invoked because reference artifacts are still handled in the Python core even when `wandb-core` is enabled, but this will change in a future PR. Since this doesn't cause a user-visible change I'm not updating the changelong.
A future PR <> will add writing through to the cache.
Testing
-------
Added new unit tests for new behavior.
There's no test yet that verifies / forces the Go core to use the same cache paths as the Python core, but it's easy to verify that it works.
[WB-20142]: https://wandb.atlassian.net/browse/WB-20142?atlOrigin=eyJpIjoiNWRk …
> feat(artifacts): restore reference entries from etag cache in wandb-core

- core/pkg/artifacts/saver.go
- core/pkg/server/sender.go
- core/pkg/server/store.go
- core/pkg/server/store_test.go
- core/pkg/server/stream.go
- core/pkg/server/writer.go
Description
---
Removes instances where the `ctx` or `loopBackChan` is passed but never used to make them easier to reason about.
> refactor(core): Remove unused ctx and fwdChan

- .github/workflows/release-sdk.yml
- hatch.toml
- hatch_build.py
Description
-----------
Fix $PATH in the SDK release GH action / `cibuildwheel` to pick up the Rust toolchain.
Testing
-------
> ci(sdk): fix rust toolchain setup in cibuildwheel

- .github/workflows/release-sdk.yml
Description
-----------
The release-sdk GH action publishes a draft of Release Notes.
Publishing the generated release notes draft in turn triggers a gh action that generates a new Docs PR.
This PR ensures that target_commitish is pointed at the release branch with the correct released version. (It was pointing by default at main, which obviously has the .dev1 version, so all the generated links in the docs would be wrong)
See https://github.com/softprops/action-gh-release/blob/0ab9029cac4874ac25cd2d941052851bef4d66f4/README.md?plain=1#L191
Testing
-------
> ci(sdk): set target_commitish in publish-release-notes job in release-sdk GH action

- .bumpversion.go.cfg
- .circleci/config.yml
- CONTRIBUTING.md
- core/go.mod
- experimental/client-go/go.mod
Description
-----------
Bump go runtime version to 1.22.6.
Testing
-------
> chore(sdk): bump go runtime version to 1.22.6

- wandb/integration/openai/fine_tuning.py
Description
---
Reapplies #7974 which got erroneously reverted in #8086.
The revert was caused by the PR being updated through the GitHub UI by one contributor while concurrently being updated locally by its author.
---
The details are kind of interesting:
I use spacedentist/spr to manage remote branches for my PRs. `spr` creates commits on the GitHub branch by diffing it against my local state. A merge commit was added to the remote branch by pressing the Update button on GitHub which included the changes from #7974, but my local branch was still based off of an older commit on `main`, so the diff included the inverse of the additional commits from `main`.
This is where things break: Due to the merge commit, the merge base between `main` and the PR branch became the head of `main`, but …
> chore(sdk): Un-revert #7974

- CHANGELOG.md
- core/internal/runmetric/runconfigmetrics.go
- core/internal/runmetric/runconfigmetrics_test.go
- core/pkg/server/sender.go
Description
---
WB-20108
Fixes cases like `run.define_metric("x", step_metric="x")` when using core.
Testing
---
Unit test.
> fix(core): Allow metric to be own step in define_metric

- CHANGELOG.md
- core/internal/filetransfer/file_transfer_default.go
Description
---
WB-18265, WB-20153
Ensures that zero-byte file uploads still include the Content-Length header.
The bug is caused by an interaction between a confusing contract in net/http and a somewhat poor implementation of `NewRequest` in retryablehttp:
* `http.Request.ContentLength == 0` is treated as "unknown". I don't know what that means exactly, but it results in a Content-Length not being sent at least sometimes (if not all the time). I don't know if we're sometimes succeeding without a Content-Length.
* To set an explicit zero ContentLength, net/http expects the body to be the `http.NoBody` constant.
* `retryablehttp.NewRequest` has a type-switch on the body
* If given a `Reader`, retryablehttp reads the entire body into a buffer after which it checks its length. If the length …
> fix(core): Use http.NoBody when uploading empty file

- core/internal/auth/netrc.go
Description
-----------
Triggered a data race with this simple script:
```python
import multiprocessing
import wandb
def run_experiment(params):
with wandb.init(config=params):
pass
if __name__ == "__main__":
wandb.setup(settings={"project": "my_project"})
experiment_params = [
{"learning_rate": 0.01, "epochs": 10},
{"learning_rate": 0.001, "epochs": 20},
]
processes = []
for params in experiment_params:
p = multiprocessing.Process(target=run_experiment, args=(params,))
p.start()
processes.append(p)
for p in processes:
p.join()
wandb.teardown()
```
```
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
warning: GOCOVERDIR not set, no coverage data emitted
wandb: Currently logged in as: dima. Use `wandb login --relogin` to force …
```
> fix(core): fix data race in netrc.go

- .bumpversion.wandb.cfg
Description
-----------
Include the `__init__.pyi` and `__init__.template.pyi` files in the bumpversion config since both have `__version__`.
Testing
-------
> chore(sdk): bump version in stubs

- .bumpversion.wandb.cfg
Description
---
Bumps an internal timeout to 30s to potentially help with an issue where the 5s timeout may be hit during `wandb.init()` on certain systems.
> chore(sdk): Bump _communicate default timeout to 30s

- core/internal/pathtree/pathtree.go
- core/internal/pathtree/pathtree_test.go
Description
---
Fixes WB-20379.
Fixes a panic caused due to an incorrect interface conversion. This can happen if a user logs a metric at a nested path followed by a metric at a subpath of that path.
> fix(core): Fix interface conversion error

- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/internal/handler.py
- wandb/sdk/service/streams.py
Description
---
Replaces `communicate_status()`, which uses the deprecated "communicate" verb and MessageRouter path, by `deliver_status()` which uses the newer Mailbox.
This changes a method in `streams.py` to wait indefinitely rather than with a 5s timeout. Users that previously hit the `AssertionError` in that method will now see either:
* A success, if the 5s timeout was just not enough (what we expect)
* A hanging process, if a response was never going to happen. This would be a bug.
We do not currently have a mechanism to propagate deadlines, but it would be more appropriate than using an indefinite timeout. The goal of this PR is to replace a deprecated codepath.
Testing
---
A simple `wandb.init()` script with `WANDB__REQUIRE_CORE=false` to trigger the `streams.py` change.
I …
> chore(sdk): communicate_status => deliver_status

- requirements_dev.txt
- tools/generate_stubs.py
Description
-----------
generate_stubs.py used in pre-push hook requires a new-ish feature of `ast`
Testing
-------
> chore(sdk): ensure generating module stubs works on py<3.9

- nvidia_gpu_stats/src/gpu_nvidia.rs
Description
-----------
- Fixes WB-20394
- Fixes #8137
The Cldfire/nvml-wrapper crate we use in nvidia_gpu_stats by default looks for `libnvidia-ml.so`, which is normally just a symlink to `libnvidia-ml.so.1` and not always available.
To solve, we follow go-nvml: [go-nvml/pkg/nvml/lib.go at 0e815c71ca6e8184387d8b502b2ef2d2722165b9 · NVIDIA/go-nvml](https://github.com/NVIDIA/go-nvml/blob/0e815c71ca6e8184387d8b502b2ef2d2722165b9/pkg/nvml/lib.go#L30) and attempt to directly load `libnvidia-ml.so.1`.
Testing
-------
> fix(core): ensure nvidia_gpu_stats captures gpu metrics when libnvidia-ml.so is unavailable

- CHANGELOG.md
- core/internal/debounce/debounce.go
- core/pkg/server/sender.go
Description
---
Fixes WB-20395.
`Sender.Do()` invokes `Debounce()` after every record, potentially trying to send summary or config updates after the shutdown logic in the corresponding "defer" step. This PR adds a `Stop` method to `Debouncer` and calls it in the summary and config "defer" logic.
> fix(core): Don't send summary/config after finishing

- nvidia_gpu_stats/src/main.rs
Description
-----------
- Fixes WB-20399
Make `nvidia_gpu_stats` respect the WANDB_ERROR_REPORTING env var.
Testing
-------
> chore(core): add ability to disable sentry reporting in nvidia_gpu_stats

- nvidia_gpu_stats/src/main.rs
- nvidia_gpu_stats/src/metrics.rs
Description
-----------
Fixes WB-20405
Gracefully capture broken pipe panic in nvidia_gpu_stats.
Testing
-------
> fix(core): capture broken pipe panic in nvidia_gpu_stats

- CHANGELOG.md
- core/cmd/wandb-core/main.go
- core/pkg/server/server.go
Description
---
Fixes WB-19983.
When a user hits Ctrl+C twice, the service process receives a teardown signal (first Ctrl+C) and the user's process is killed (second Ctrl+C, while in an atexit handler). When this happens, the service process should shut itself down immediately rather than waiting for uploads to complete.
> fix(core): Exit if parent dies even after teardown

- core/internal/filestream/filestreamimpl.go
- core/internal/filestream/retry_policy.go
Description
---
Don't retry HTTP 422 Unprocessable Content errors in filestream.
> fix(core): Don't retry HTTP 422

- wandb/sdk/wandb_run.py
Description
-----------
Fixes #8157.
In disabled mode, do not attempt updating the run telemetry.
Testing
-------
> fix(sdk): do not attempt to update run telemetry in disabled mode

- .circleci/config.yml
- tests/pytest_tests/system_tests/test_importers/test_wandb/test_wandb.py
Description
-----------
Run system tests against an older version of wandb server (more specifically, `local-testcontainer`).
By default, all tests are run agains the `local-testcontainer` corresponding to the current master of `wandb/core`.
We've been maintaining a dedicated artifact registry of older `local-testcontainer`'s corresponding to server releases as for production, they only keep those around for 30 days, so that in many cases it is impossible to get a `local-testcontainer` for older releases. 
The oldest Version we have is 0.48.0 (we started collecting them in Jan 2024), so this is what we're testing against.
Testing
-------
> chore(sdk): test against an older version of server

- wandb/sdk/wandb_run.py
Description
-----------
It was set to 1 second, which generates a bit too much internal traffic to my taste :)
Testing
-------
> chore(sdk): increase internal message polling interval

- wandb/sdk/artifacts/artifact.py
- wandb/sdk/wandb_run.py
Description
-----------
Hopefully fixes WB-20421.
`wandb/sdk/artifacts/artifact.py::_download_using_core` comes with an overhead of `wandb-core` / stream management in a non-standard way resulting in a significant slowdown compared to the non-core path. 
Note that the latter does not use `wandb-service` and instead does everything in the user process.
Disabled the codepath using core for now until a refactor is done.
Testing
-------
> chore(core): temporarily disable artifact downloads with core

- core/internal/tensorboard/tensor.go
- core/internal/tensorboard/tfeventconverter_test.go
- core/internal/tensorboard/tfeventconverterscalars.go
Description
---
Replaces `ToHistogramJSON()` by `Scalar()` as it is impossible to log a non-scalar value using `tf.summary.scalar()`.
Testing
---
```python
import tensorflow as tf
import wandb
with wandb.init(sync_tensorboard=True) as run:
writer = tf.summary.create_file_writer("tblogdir")
with writer.as_default():
tf.summary.scalar(
"mynum",
123,
step=3,
)
```
> refactor(core): Remove Tensor.ToHistogramJSON()

- core/internal/tensorboard/tfeventconverter_test.go
- core/internal/tensorboard/tfeventconverterimages.go
Description
---
All PNG files start with 8 magic bytes. Adds a check in the TensorBoard integration to verify that images are in the expected format to be robust to future changes.
This also adds a missing `return` statement.
Testing
---
Same as in https://github.com/wandb/wandb/pull/8189.
> chore(core): Check TB image PNG validity

- wandb/sdk/wandb_manager.py
- wandb/sdk/wandb_setup.py
Description
---
Instead of doing this in the WandbManager which is responsible for the service process, do it in WandbSetup. This ensures that we run `unregister_all_post_import_hooks` if the user does `wandb.teardown()`; an implicit atexit teardown does not do this, but I don't think it matters since the process is exiting at that point.
> refactor(sdk): Move unregister_all_post_import_hooks

- .bumpversion.wandb.cfg
- CHANGELOG.md
- core/internal/version/version.go
- wandb/__init__.py
- wandb/__init__.pyi
- wandb/__init__.template.pyi
Description
-----------
[chore(sdk): bump version to 0.17.9.dev1](https://github.com/wandb/wandb/commit/03f7f43b385a3b17f9239c5f49a8344fdc3a468b)
Testing
-------
> chore(sdk): bump version to 0.17.9.dev1

- core/pkg/monitor/monitor.go
- core/pkg/monitor/slurm.go
- core/pkg/monitor/slurm_test.go
Description
-----------
Use a special asset to capture SLURM-related env vars.
Testing
-------
> chore(core): add SLURM asset to capture SLURM-related env vars

- core/pkg/server/handler.go
Description
---
The Header record is a no-op in the Sender, so there's no point in marking it "AlwaysSend" (which is a hacky mechanism to get records to the Sender in offline mode).
> refactor(core): Don't AlwaysSend Header record

- core/pkg/server/handler.go
Description
---
When using core, make sure we respond to a few requests even in offline mode.
For ServerInfo, this was previously a side effect of setting AlwaysSend, which was confusing.
For StopStatus and CheckVersion, we were not responding before. It's not clear whether this was a problem.
> refactor(core): Respond to ServerInfo/StopStatus/CheckVersion in offline mode

- core/pkg/server/handler.go
Description
---
Simplify Handler code for record types where the handle function just runs `fwdRecord`.
The target state is to use `fwdRecord` by default. Later PRs will handle more subtle cases.
> refactor(core): Consolidate Handler fwdRecord logic

- core/pkg/server/handler.go
Description
---
Moves the `fwdRecord` for History, Metric and Summary to `Handler.Do()`. Adds Exit, Header, Tbrecord, Request and Run records to the explicit no-forward list:
* Tbrecords terminate in the Handler
* Exit and Header modify their records before forwarding
* Request handlers call `fwdRecord` themselves; I'll update them in a separate PR
I'll make `fwdRecord` the `default` case in the next PR since that's a riskier change (it's hard to verify that a record type wasn't forgotten): https://github.com/wandb/wandb/pull/8236
> refactor(core): Refactor fwdRecord for remaining Handler records

- core/pkg/server/handler.go
Description
---
Makes `fwdRecord` the default case in Handler and documents all exceptions.
I double checked against `wandb_internal.proto` that every single record type is covered by the switch.
> refactor(core): Make fwdRecord default in Handler

- .github/workflows/generate-docodile-documentation.yml
- .github/workflows/release-sdk.yml
Description
-----------
- Publish release notes upon a successful release to automatically trigger docs generation action
- Post on Slack in #docs channel when the docs PR is ready.
Testing
-------
> chore(sdk): trigger docs generation upon release

- .github/workflows/generate-docodile-documentation.yml
- .github/workflows/release-sdk.yml
Description
-----------
Update the release action to automatically open a `<major>.<minor>.<patch+1>.dev1` version bump PR upon a successful non-rc release (that is, a one that publishes release notes).
Testing
-------
> chore(sdk): automatically open a dev1 version bump PR upon a release

- core/pkg/server/sender.go
Description
---
Ensures that panics in goroutines started in Sender.sendRequestDefer are logged to Sentry.
> refactor(sdk): recover panics in defer goroutines

- core/pkg/monitor/gpu_nvidia.go
Description
-----------
Return filtered metrics instead of the raw sample in `GPUNvidia.Sample`.
Testing
-------
> fix: skip underscorred nvidia gpu metrics

- core/internal/runconsolelogs/debouncedwriter.go
- core/internal/runconsolelogs/debouncedwriter_test.go
- core/internal/runconsolelogs/runconsolelogs.go
Description
---
Removes BeforeEndCtx() in runconsolelogs as it is not actually utilized.
It was meant to short-circuit the writer to prevent further writes to the output.log file in case runconsolelogs.Sender.Finish() isn't invoked (but runwork.RunWork.Close() is), but there's no point in that as the file is only used if Finish() happens.
> refactor(sdk): remove cancellation ctx in runconsolelogs

- core/internal/paths/longestcommonprefix.go
- core/internal/paths/longestcommonprefix_test.go
- core/internal/tensorboard/tensorboard.go
Description
---
Fixes WB-20666.
Instead of naively taking a string prefix of the log directories, define a `paths.LongestCommonPrefix` utility that compares path components.
> fix(sdk): correctly infer TB root directory

- tests/unit_tests/test_launch/test_inputs/test_internal.py
- wandb/sdk/launch/inputs/internal.py
Description
-----------
- [Slack thread](https://weightsandbiases.slack.com/archives/C01UUUHP153/p1725564705466629)
The way we were converting Pydantic models to JSONSchema was causing some keys to be dropped for pydantic>=2.9.0. 
Testing
-------
Tested against both Pydantic 2.7 and 2.9
> fix(launch): fix job input schemas for newer Pydantic versions

- wandb/sdk/wandb_init.py
Description
---
We were only setting the tensorboard_sync telemetry field on the first run that used `sync_tensorboard=True`, but we should be setting it on every such run.
> refactor(sdk): set tb sync telemetry for every run that uses it

- nvidia_gpu_stats/Cargo.lock
- nvidia_gpu_stats/Cargo.toml
- nvidia_gpu_stats/src/main.rs
Description
-----------
Adds error message cache to reduce sentry traffic in nvidia_gpu_stats.
Testing
-------
> chore: add error message cache to reduce sentry traffic in nvidia_gpu_stats

- CHANGELOG.md
- wandb/jupyter.py
Description
-----------
Fixes #8104.
Detect the notebook name in VS Code's built-in jupyter server.
Testing
-------
> fix: detect notebook name in VS Code

- pyproject.toml
Description
---
Adds "landfill" to the pytest `norecursedirs` option.
This *should* be redundant, since none of those directories are under `tests/`, but VS Code somehow ignores the `testpaths` setting when doing pytest discovery. This was causing it to execute `test_*.py` files under `landfill` which included `yea` tests, which were creating W&B runs.
> chore(sdk): don't let pytest execute yea test files

- apple_stats/hatch.py
- core/pkg/monitor/gpu_amd.go
- core/pkg/monitor/gpu_amd_test.go
- core/pkg/monitor/gpu_apple.go
- core/pkg/monitor/gpu_apple_test.go
- core/pkg/monitor/gpu_nvidia.go
- core/pkg/monitor/noop.go
- core/pkg/monitor/noop_linux.go
- core/pkg/monitor/querymap.go
- hatch_build.py
Description
-----------
- Fixes WB-20633.
In this PR:
- Only build the `apple_gpu_stats` binary for arm64 macs as it's not intended for x86 macs.
- Clean up the Apple GPU monitoring code, add docs and tests.
- On Linux and Windows, include only dummy stubs for `GPUApple` in the `wandb-core` binary.
Testing
-------
Added a unit test for `GPUApple`, manually tested on an old  x86 MacBook.
> chore: improve apple gpu stats monitor

- core/pkg/monitor/noop_darwin.go
- core/pkg/monitor/noop_linux.go
- core/pkg/monitor/noop_windows.go
Description
-----------
Make noop files platform-specific at the cost of minor code duplication. I think it's better to be explicit.
Testing
-------
> chore: split noop definitions per platform in system monitor

- apple_stats/hatch.py
Description
-----------
Removed the platform arch check in apple_stats/hatch.py as it's hatch_build's responsibility to decide whether to call build_applestats in the first place.
Prevents a situation like this: https://github.com/wandb/wandb/actions/runs/10800478179/job/29958598454#step:5:473 
Testing
-------
> fix: remove platform arch check in apple_stats/hatch.py

- core/internal/runconsolelogs/outputfilewriter.go
- core/internal/runconsolelogs/runconsolelogs.go
Description
---
Stops writing to `output.log` after the first error.
The most common error that happens is when users delete their wandb directory before stopping a run. There are also more rare failures related to mounted file systems and disk issues where we can't guarantee the file isn't corrupted, so we should stop writing to it. Any content that was successfully written is uploaded at the end of the run.
> refactor(sdk): stop writing output.log after error

- core/internal/runbranch/state.go
- core/pkg/server/sender.go
Description
-----------
- Fixes WB-20863
Minimal change to avoid race condition when sending a run update, we used to update the run state every time we send run update, however part of the update includes the filstream offset, which after the first run update can be used in other call-sites, hence we limit the update to the first run update. Also from a conceptual point of view, it doesn't make sense to update the initial run state after every upsert
Testing
-------
> fix: avoid race condition by updating the run state once

- CHANGELOG.md
- core/internal/tensorboard/tfeventconverter.go
- core/internal/tensorboard/tfeventconverter_test.go
- core/internal/tensorboard/tfeventconverterscalars.go
Description
---
Fixes WB-20897.
Always use `simplejsonext` to produce values in the expected format.
> fix(sdk): properly encode infinite scalars from tensorboard

- CHANGELOG.md
- wandb/apis/public/runs.py
Description
-----------
- Fixes #8398 
Updates the signature and docstring of `wandb.apis.public.runs.Run` to more closely reflect those of `wandb.sdk.wandb_run.Run`.
Note for clarity: the latter type is the type that's returned by `wandb.init()` (e.g. when executing `with wandb.init(...) as run: ...`) and currently supports tags, while the former did not, prior to this PR.
Testing
-------
> fix(sdk): update signature and docstring of `Run.log_artifact()` (in `wandb.apis.public.runs`) to also include artifact tags

- pyproject.toml
- wandb/sdk/data_types/video.py
Description
-----------
This makes our error message clearer and ensures we have imageio even if moviepy somehow stops depending on it.
Testing
-------
> fix(sdk): fix error message when media dependency is missing

- CHANGELOG.md
- core/internal/runmetric/runmetric.go
- core/internal/runmetric/runmetric_test.go
Description
-----------
- [Fixes WB-20950](https://wandb.atlassian.net/browse/WB-20950)
Uses a starts with strategy instead of direct glob matching for defined metrics
Testing
-------
> fix(sdk): fix glob matching in define metric to work with logged keys containing `/`

- CHANGELOG.md
- tests/system_tests/test_launch/test_launch_public_api.py
- wandb/apis/internal.py
- wandb/apis/public/api.py
- wandb/apis/public/jobs.py
- wandb/sdk/internal/internal_api.py
Description
-----------
- Fixes WB-19125
This PR adds `upsert_run_queue` to the public and internal apis. These hit the `UpsertRunQueue` mutation to create a run queue for launch. This can be used as follows:
```
import wandb
api.upsert_run_queue(
name="docker-queue",
resource_type="local-container",
resource_config={"cpus": "{{cpus}}"},
template_variables={
"cpus": {
"schema": {
"type": "integer",
"minimum": 1,
"maximum": 4,
},
},
},
external_links={
"google": "https://google.com",
},
)
```
This provides a very similar but powerful alternative to the `create_run_queue` method.
This PR also adds `externalLinks` to the query for the `RunQueue` class in our public api, and adds an `external_links` `@property` on the class. This is useful for testing and also something we …
> feat(launch): add upsert_run_queue to public api

- wandb/sdk/lib/service_connection.py
- wandb/sdk/lib/sock_client.py
- wandb/sdk/wandb_init.py
Description
---
Instead of raising "Exception: No response", raise "wandb.errors.errors.UsageError: Unable to attach to run rmlkh5ze".
The regression was introduced in e66e4765047fa06af6576f6feba265339dd69ee8 (not yet released).
> fix(sdk): show better error when attaching fails

- core/pkg/monitor/gpu_nvidia.go
- core/pkg/monitor/noop_darwin.go
Description
-----------
The `nvidia_gpu_stats` process used to collect Nvidia GPU metrics must be waited on in `gpu_nvidia.go` to prevent the zombification of the former.
Testing
-------
> fix: prevent zombification of nvidia_gpu_stats

- core/internal/api/logging.go
- tests/system_tests/test_core/test_file_stream.py
Description
---
`retryablehttp.CheckRetry`'s documentation states that it only returns an error to override the error returned by the client. A nil error means that the original error is used.
Without this fix, disconnecting WiFi and running `wandb.init()` logs mysterious "api: retrying HTTP request, no error or response" messages. With this fix, the log message is "api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host".
> fix(sdk): correctly log retries

- CHANGELOG.md
- tests/system_tests/test_artifacts/test_wandb_artifacts_api.py
- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
Description
-----------
- Fixes [WB-21061](https://wandb.atlassian.net/browse/WB-21061)
A simpler, more performant solution is #8440, but as of now the backend doesn't support that filter properly.
Instead, this implements a very basic client-side filter when getting artifacts that match a set of tags. It should be compatible with upgrading to a server-side solution once one becomes available.
Testing
-------
Adds a basic test for getting artifacts matching one or multiple tags
[WB-21061]: https://wandb.atlassian.net/browse/WB-21061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(artifacts): add client-side tag filtering

- CHANGELOG.md
- core/internal/runmetric/runmetric.go
- tests/system_tests/test_core/test_metric_full.py
Description
-----------
- Fixes WB-20622
This PR allows users to provide metrics with dots `.` in the name when calling `run.define_metric` by escaping the dot.. (e.g. `a\.b`)
Testing
-------
- unit tests
[WB-20622]: https://wandb.atlassian.net/browse/WB-20622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: fixes users not being able to define metrics with a dot (.) in the metric name

- .circleci/config.yml
- experimental/client-csharp/src/Wandb/Wandb.csproj
Description
-----------
Ensure we use the correct go binary path when building the experimental C# client on Windows.
Testing
-------
> fix: use correct go binary path when building c# client on windows

- tests/system_tests/test_artifacts/test_wandb_artifacts_api.py
- wandb/apis/public/artifacts.py
Description
-----------
Allow the `tags` argument to `Api.Artifacts()` to be a string instead of a list, interpreting it to be a list with just that element. 
Testing
-------
Updated test to check this usage pattern.
> feat(artifacts): allow `tags` to be a single string

- experimental/client-csharp/examples/Basic/Program.cs
- experimental/client-csharp/src/Wandb/Internal/SocketInterface.cs
- experimental/client-csharp/src/Wandb/Run.cs
Description
-----------
Make it clearer how to hide a metric from the UI with a statement like:
```csharp
await run.DefineMetric("epoch", hidden: true);
```
Testing
-------
> chore: improve behavior of Run::DefineMetric in experimental c# client

- core/pkg/monitor/gpu_amd.go
- core/pkg/monitor/gpu_amd_test.go
Description
-----------
Fixes WB-21186.
`rocm-smi` version `~7.3` for `rocm~6.3` changed the names of some of the reported metrics -- this PR addresses that on our side.
Testing
-------
tested on aac.amd.com: https://wandb.ai/dimaduev/wandb/runs/dsdvbu2q/workspace?nw=nwuserdimaduev
> fix: add support for parsing amd gpu stats with rocm 6.x

- core/pkg/server/sender.go
Description
---
Reduces the threshold before logging that an operation is taking too long from 30m to 10m, to match the threshold we use in `runwork`.
> chore(sdk): reduce long-operation threshold to 10m

- hatch_build.py
- nvidia_gpu_stats/hatch.py
Description
---
Add `raise AssertionError()` in two spots after functions that never return so that `mypy` can properly narrow union types. Use `pathlib.Path` instead of `pathlib.PurePath` in a function that uses `pathlib.Path` methods.
> chore(sdk): fix lints in hatch files

- CHANGELOG.md
- README.md
- pyproject.toml
Description
-----------
- Fixes WB-20894
This PR fixes one dependency installation failure when running `pip install wandb[media]`.  Additionally, it updates the README file with instructions of installing dependencies needed for working with media files.
Testing
-------
- `pip install wandb[media]`
- before: `ERROR: Could not find a version that satisfies the requirement rdkit-pypi`
- after: `﻿Successfully installed wandb-0.18.3.dev1`
> fix: installing media dependencies fails to find rdkit install

- .circleci/config.yml
- .vscode/settings.json
- CHANGELOG.md
- core/pkg/monitor/gpu_nvidia.go
- core/pkg/monitor/monitor.go
- core/pkg/monitor/noop_windows.go
- hatch_build.py
- nvidia_gpu_stats/hatch.py
- nvidia_gpu_stats/src/gpu_nvidia.rs
- nvidia_gpu_stats/src/main.rs
Description
-----------
- Fixes WB-20401
- Fixes #8417
Testing
-------
Used this job in CircleCI to test:
```yaml
jobs:
...
gpu-win:
executor:
name: win/server-2019-cuda
shell: bash.exe
steps:
- checkout
- run:
name: Install Python
command: >
nuget.exe install python \
-Version 3.12 \
-ExcludeVersion \
-OutputDirectory "/c/nox-tests-python" &&
setx PATH '/c/nox-tests-python/python/tools;%PATH%'
- run:
name: "Install system deps: ffmpeg"
command: choco install -y ffmpeg
- run:
name: "Install system deps: mingw"
command: choco install -y mingw --version 12.2 --allow-downgrade
- install_go
- install_rust
```
> fix: capture nvidia gpu stats on windows

- core/internal/filetransfer/file_transfers.go
Description
-----------
This PR stops logging gcs client instantiation issues to sentry and instead just logs it to the debug log, as this is expected to fail whenever someone doesn't have gcloud authentication set up and is only relevant if they actually need to use the client, in which case we fail later.
Testing
-------
> refactor(artifacts): remove sentry logs for GCS File Transfer set up

- CHANGELOG.md
- wandb/__init__.pyi
- wandb/__init__.template.pyi
- Fixes: #8520
The type changes in #8447 introduced a type error for `wandb.Api` from `Type[PublicApi]` to `PublicApi`.
> chore(sdk): fix type annotation for wandb.Api to Type[PublicApi]

- wandb/sdk/launch/inputs/internal.py
Description
-----------
- Fixes WB-21393
- Fixes #8562
This PR addresses an issue where the `_replace_refs_and_allofs` function fails when the same `$ref` is used multiple times in a schema. Previously, the function removed/popped definitions from `defs` upon encountering them, causing a `KeyError` when the same reference was needed again later in the schema.
Changes Made:
- Modified the `_replace_refs_and_allofs` function to copy `$ref` definitions from `defs` instead of popping them, ensuring that the same reference can be reused multiple times without causing errors.
Testing
-------
> fix(launch): allow for repeated $ref usage in _replace_refs_and_allofs function

- requirements_dev.txt
Description
-----------
when trying to resolve dependencies for sb3, uv uses gym, which doesn't seem to work.
sb3 has a strict requirement to use gymnasiun < 0.30 (https://github.com/DLR-RM/stable-baselines3/blob/56c153f048f1035f239b77d1569b240ace83c130/setup.py#L103), but since we install gymnasium 1.0 (the latest that was released, we get resolution issues)
This is a stop-gap we probably want better management of these conflicting dependencies
Testing
-------
> chore: skip installing latest gymnasium as it breaks sb3

- nvidia_gpu_stats/hatch.py
Description
---
Extract the path to the built `nvidia_gpu_stats` binary from `cargo build` output instead of hard-coding it, as suggested by @flferretti in https://github.com/conda-forge/wandb-feedstock/pull/129.
> chore(sdk): more robust nvidia_gpu_stats build

- core/internal/filetransfer/file_transfer_s3.go
- core/internal/filetransfer/file_transfer_s3_test.go
Description
-----------
- Fixes [WB-21099](https://wandb.atlassian.net/browse/WB-21099)
This PR adds unit tests for the s3 file transfer download implementation. This specifically tests the following cases:
1. erroring with invalid reference (not s3 ref)
2. erroring with an invalid s3 reference (valid format but no object)
3. downloading an unversioned obj
4. downloading the given version when it exists
5. finding and downloading the correct version when versionId not given (and latest obj doesn't have a matching etag)
6. erroring when no version has a matching checksum
7. downloading all the items under the reference when uploaded with `checksum=False` (and so digest = reference)
not applicable, just adds tests
Testing
-------
[WB-21099]: …
> feat(artifacts): add unit tests for s3 file transfer download

- noxfile.py
- tests/system_tests/test_functional/test_tensorboard/test_keras_tb_callback.py
Description
-----------
- For functional tests, the default n=auto spins up too many workers on CircleCI as it's based on the number of detected CPUs in the system, and doesn't take into account the number of available CPUs in the container, which results in OOM errors.
- Fixed a keras/tb test
Testing
-------
> chore: reduce parallelism in functional tests

- tests/unit_tests/test_lib/test_printer.py
- wandb/sdk/lib/printer.py
- wandb/sdk/lib/progress.py
- wandb/sdk/wandb_run.py
* Use `__future__` annotations
* Rename `_Printer` => `Printer`
* Rename `PrinterTerm` => `_PrinterTerm`
* Rename `PrinterJupyter` => `_PrinterJupyter`
* Replace usage of `_html` attribute outside of module by public `supports_html` property
> chore(sdk): clean up wandb/lib/printer.py

- requirements_test.txt
- tests/conftest.py
- tests/unit_tests/test_term.py
Makes an `emulated_terminal` fixture available for all tests to allow testing code that uses ANSI escape sequences.
> chore(sdk): allow terminal emulation in tests

- requirements_test.txt
- tests/unit_tests/test_datastore.py
Description
---
NOTE: This was originally https://github.com/wandb/wandb/pull/8653 which got mistakenly merged into a branch that wasn't main.
---
Adds version constraints to `requirements_test.txt`. While package dependency versions should be loose, requirements files should be strict. I chose to use `~=` (compatible version) rather than `==` (exact version) so that we don't have to update these as often, but using exact versions would also work (in which case we should set up dependabot for this file).
Using explicit versions can also help debug issues in CI or development environments.
NOTE: `pyte~=0.8` would match `0.9`, which is wrong, since in major version 0, minor increases may cause incompatible changes. Using `pyte~=0.8.0` works like `pyte >= 0.8.0, pyte < 0.9`.
> chore(sdk): specify versions requirements_test.txt

- wandb/errors/term.py
Description
---
Wrap the `yield` in a `try-finally` block to ensure that cleanup happens even if the code running inside a `dynamic_text` context manager raises an exception.
> refactor(sdk): use try-finally in dynamic_text

- CHANGELOG.md
- wandb/sdk/artifacts/storage_handlers/azure_handler.py
Description
-----------
This PR fixes downloading azure reference artifacts when `skip_cache=True` by setting `_cache` on the Azure handler. This field is assumed to exist when loading reference artifacts [here](https://github.com/wandb/wandb/blob/b588b252066bb25cfa00e3558375690014a1430f/wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py#L183), and because it didn't for the azure handler, we previously did not download the artifacts when we chose to skip caching.
Testing
-------
tested by downloading locally with `skip_cache=True`
> fix(artifacts): fix azure downloads when `skip_cache=True`

- CHANGELOG.md
- core/pkg/artifacts/saver.go
Description
-----------
- Fixes [WB-21562](https://wandb.atlassian.net/browse/WB-21562)
This PR fixes a bug where we threw an error when trying to upload large files with no content type. Previously, we just appended an empty string for these cases to the request header, which is what we now do. 
See this line for non-core implementation: https://github.com/wandb/wandb/blob/b588b252066bb25cfa00e3558375690014a1430f/wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py#L238
Testing
-------
tested locally with the script in the ticket
[WB-21562]: https://wandb.atlassian.net/browse/WB-21562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): fix multipart upload when content type not defined

- CHANGELOG.md
- tests/conftest.py
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_manifest.py
Description
-----------
- Fixes [WB-21304](https://wandb.atlassian.net/browse/WB-21304)
Adds a boolean `overwrite` param to 
- `Artifact.add()`
- `Artifact.add_file()`
...in order to allow overwriting previously-added artifact files with the same path(s).
Testing
-------
See added tests in: [tests/system_tests/test_artifacts/test_wandb_artifacts.py](https://github.com/wandb/wandb/pull/8553/files#diff-7a050cfc8b89eecc7a18cf87031e103df052f0da99cfa8a37a5fc40940736efa)
[WB-21304]: https://wandb.atlassian.net/browse/WB-21304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): allow artifact.add, artifact.add_file to overwrite

- tests/unit_tests/test_file/test_file_public_api.py
- wandb/apis/public/utils.py
Description
-----------
Some aws urls don't have regions in them, so make sure s3 parsers also account for that
Testing
-------
Used BYOB to run 
```
api = wandb.Api(overrides={"entity": "my-entity"})
artifact = api.artifact("my-entity/test/test_simple_file:v0")
for f in artifact.files():
print("file: ", f.path_url)
```
> chore(artifacts): lax regex to also allow urls without regions

- core/internal/runwork/runwork.go
- core/internal/stream/sender.go
Description
-----------
There is no added value to keep capturing these events, as we know it happens and had enough data how often it happens.
Testing
-------
> chore: stop capturing events of sending exit after closed

- wandb/__init__.pyi
- wandb/data_types.py
- wandb/sdk/wandb_run.py
Fix broken docs links that show up here: 
- https://docs.wandb.ai/ref/python/log/
- https://docs.wandb.ai/ref/python/run/
- https://docs.wandb.ai/ref/python/data-types/
Description
-----------
- Fixes WB-DOCS-990
Some of the docs links are not working; this fixes them.
Testing
-------
URLs resolve in browser with HTTP 200 response
> fix: fix broken docs links

- CHANGELOG.md
- wandb/wandb_controller.py
Description
-----------
`sweep.configure_parameter()` silently ignored the `distribution` parameter. This PR saves it in the parameter dict.
Testing
-------
> fix(sweeps): do not ignore distribution when configuring params from SDK

- tests/system_tests/conftest.py
- tests/system_tests/wandb_backend_spy/proxy.py
Description
---
Instead of hardcoding port 8000, pick a free port. This is only necessary when running multiple pytest invocations concurrently, such as when using pytest-xdist.
> chore: pick a free port for the test proxy server

- tools/local_wandb_server.py
Description
---
Pass `--pull always` to the `docker run` command. This only affects local test runs and does not affect CI.
> chore: always use latest image in local_wandb_server

- tests/system_tests/test_functional/multiprocessing/test_mp.py
Tests under `tests/system_tests/test_functional/` currently use `runpy` to run test scripts, which means if the test script forks, it forks the pytest process. This is problematic.
> chore: don't fork pytest worker

- .circleci/config.yml
- tests/system_tests/conftest.py
- tools/local_wandb_server.py
* If the test container wasn't started manually, pytest errors out with a hint
* Since pytest no longer starts/stops the server, removed ID tracking, simplifying the experience
* Removed `--interactive` option, making `start` interactive by default
* Replaced `stopall` by `stop` command
* Improved `docker port` usage
> chore: improve local_wandb_server.py

- tests/system_tests/test_functional/test_tensorboard/test_tb_w_sb3.py
- tests/system_tests/test_functional/test_tensorboard/test_tensorboardX.py
- tests/system_tests/test_functional/test_tensorboard/test_tf_summary.py
- tests/system_tests/test_functional/test_tensorboard/test_torch_tb.py
Description
-----------
This PR enables most tensorboard tests that were disabled for wandb-core.
One more test needs a deeper investigation as to why it times out during circleci runs:
https://github.com/wandb/wandb/blob/main/tests/system_tests/test_functional/test_tensorboard/test_torch_tb.py#L13-L38
Testing
-------
- nox -s "functional_tests" --python 3.12 -- tests/system_tests/test_functional/test_tensorboard
- `39 passed, 2 skipped, 11 warnings in 240.81s (0:04:00)`
> chore: reenable tensorboard tests for wandb-core

- requirements_dev.txt
Description
-----------
New version of botocore was released today and it seems that the api changed causing all code that uses boto to fail.
See release here: https://pypi.org/project/botocore/1.35.56/
Testing
-------
> chore: skip broken botocore for now

- .github/workflows/release-sdk.yml
- CHANGELOG.md
- CHANGELOG.unreleased.md
- tools/changelog.py
Require PRs to put unreleased changes into `CHANGELOG.unreleased.md` instead of `CHANGELOG.md` to avoid having the changes appear in the wrong section if a release happens before the PR is merged.
> chore: introduce CHANGELOG.unreleased.md

- tests/system_tests/test_notebooks/.gitignore
- tests/system_tests/test_notebooks/conftest.py
Works around https://github.com/jupyter/jupyter_client/issues/487 in tests, which run in parallel due to pytest-xdist, by holding a file lock while starting up the kernel.
> chore: work around jupyter parallelism bug in notebook tests

- wandb/util.py
Includes the `wandb-core` file path to help debugging, as this is often the first thing we ask users to check. Example:
> wandb.errors.errors.WandbCoreNotAvailableError: Looks like wandb-core is not compiled for your system (macOS-14.1-arm64-arm-64bit). Please contact support at support@wandb.com to request `wandb-core` support for your system. File does not exist: /Users/timoffex/Documents/workspace/wandb/wandb/bin/wandb-core
This might even be enough for users to debug themselves, in cases where the issue is their `PATH`.
> chore: improve wandb-core missing error

- tools/changelog.py
The tuple syntax for `with` statements was only added in 3.10.
> chore: fix tools/changelog.py to work with py38

- pyproject.toml
Description
-----------
pydentic requires this package for python <= 3.9 to support modern typing.
Testing
-------
> fix: add missing depency of backport types for py<=3.9

- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_settings.py
Description
-----------
Minor clean up, moving the validation logic for resume, resume_from,, fork_from into settings.
Testing
-------
> chore: move validation of resume mutex into settings

- noxfile.py
- requirements_test.txt
- tests/conftest.py
- tests/unit_tests/test_artifacts/test_storage.py
- tests/unit_tests/test_lib/test_hashutil.py
Description
-----------
Track memory usage of our tests with pytest-memray. 
Results are reported at the end of a testing session, which looks like this:
```
================================ MEMRAY REPORT =================================
Allocation results for tests/unit_tests/test_data_types.py::test_matplotlib_plotly_with_multiple_axes[no_wandb_core] at the high watermark
📦 Total memory allocated: 140.0MiB
📏 Total allocations: 3128
📊 Histogram of allocation sizes: | █   |
🥇 Biggest allocating functions:
...
```
Testing
-------
> chore: track memory consumption in tests with pytest-memray

- noxfile.py
- requirements_test.txt
- tests/conftest.py
Description
-----------
Because it's not available on Windows, and they say likely will never be.
Testing
-------
> fix: skip memray profiling of tests on windows

- pyproject.toml
Description
-----------
Need to switch to later pydantic version to support `|` in older python versions
Testing
-------
I'm on python v3.9.13 and I had pydantic `2.5.3` which was erroring when i ran wandb
Switching to pydantic `2.6.0` fixed the typing errors
> chore(sdk): specify pydantic version 2.6 to support union in earlier python

- wandb/sdk/wandb_settings.py
Description
-----------
- Missed the default value in a recent refactor.
- Added "/System/Volumes/Data" to the MacOS default
Testing
-------
> fix: set default disk paths in settings to track with the system monitor

- core/go.mod
- core/internal/filetransfer/file_transfer_azure.go
- core/internal/filetransfer/file_transfer_azure_test.go
- core/internal/filetransfer/file_transfers.go
Description
-----------
- Fixes [WB-21487](https://wandb.atlassian.net/browse/WB-21487)
This PR adds unit tests and mocks for the azure file transfer download implementation. This specifically tests the following cases:
1. erroring with invalid reference (not s3 ref)
2. erroring with an invalid s3 reference (valid format but no object)
3. downloading an unversioned obj
4. downloading the given version when it exists
6. downloading all the items under the reference when uploaded with checksum=False (and so digest = reference)
in particular due to limitations with mocking + overriding clients in tests, this does not include tests for:
1. erroring out when there is no version of the blob with a matching checksum
2. finding and downloading the correct version when versionId not given (and …
> feat(artifacts): add unit tests for azure ref arts downloads 

- core/internal/filetransfer/file_transfer_azure_test.go
Description
-----------
This PR removes a test that tries to setup an Azure container client, which fails in CI because there are no credentials to use
Testing
-------
tested locally and made sure none of the other tests are trying to set up that client
> revert(artifacts): remove faulty azure download unit test

- wandb/__init__.py
- wandb/sdk/wandb_settings.py
Description
-----------
When users pass env variables with `WANDB__` prefix make sure to convert it to `WANDB_X_` prefix, to make sure we respect these settings.
Testing
-------
> chore: respect private env variables with the name change

- tests/system_tests/test_api/test_public_api_run_summary.py
- tests/system_tests/test_core/test_cli_full.py
- tests/system_tests/test_core/test_mode_disabled_full.py
Description
-----------
Testing
-------
> chore: remove `wandb_init` from a set of system tests

- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-22157
- Fixes #8969
This PR fixes an issue where the `Runs.histories()` method did not respect the order of runs specified in the `Runs` object. Previously, when using `Pandas` or `Polars` export format, the combined dataframe of `histories` was being sorted by `run_id`, which altered the original order of runs. This could lead to mismatches between run metadata and history data when iterating over runs.
This PR removes unnecessary sorting of the combined `DataFrame` by `run_id` in the `histories` method for both `Pandas` and `Polars` formats.
Testing
-------
- Tested the `histories` method with multiple runs to verify that the order of runs in the combined `DataFrame` matches the order specified in the `Runs` object.
- Verified that both `Pandas` and …
> fix(sdk): preserve run order in Runs.histories() method

- .github/workflows/release-sdk.yml
Description
-----------
This is for the situation:
- Version uploaded to testpypi is bad
- Action is aborted, fix is pushed
- Release action is restarted, upload to testpypi passes due to `skip-existing: true`, but smoke tests still fail bc of the already uploaded version.
Testing
-------
> chore: continue release action if smoke tests fail

- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-21873
This PR updates the `Run.update()` method to include the `jobType` parameter when persisting run state changes. Previously, programmatic updates to `run.job_type` were not reflected in the UI and not persisted in new API sessions. 
By adding `jobType` to the `upsertBucket` mutation, the backend now correctly stores and displays these updates.
Testing
-------
Verified by updating a run's `job_type` through the API and confirming that the change now appears in the UI after calling `run.update()`.
test code:
```
import wandb
run = api.run('entity/project/id')
print('logged job type', run.job_type)
run.job_type = 'new-type'
run.update()
print('same session type', run.job_type)
run = api.run('entity/project/id') …
```
> fix(sdk): persist job_type updates by adding jobType to upsertBucket mutation

- CHANGELOG.unreleased.md
- wandb/sdk/wandb_settings.py
Hey, 
I noticed that in the latest version of wandb, setting `WANDB__SERVICE_WAIT` leads to wandb crashing with a `TypeError`:
```
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
```
The issue is that in wandb_settings.py, `validate_service_wait` does not return `value`. This PR fixes that.
Best,
Tim
> fix: fixes missing return value of validate_service_wait in wandb_settings.py

- core/internal/api/logging.go
- core/internal/wboperation/wboperation.go
- core/internal/wboperation/wboperation_test.go
Description
---
If an HTTP operation fails with a Go error, such as due to a protocol issue, mention that in the current operation's status. An example might look like this:
> retrying: tls: failed to parse certificate from server: x509: negative serial number
NOTE: In this case, the corresponding `ClearError` is in `api/send.go` after `retryableHTTP.Do()` returns.
> feat: track retried Go errors in wboperation

- wandb/sdk/internal/settings_static.py
Description
-----------
- Fixes WB-22264
There apparently was a regression in the ancient code path for disable service (that is, using neither core, nor old python service). 
Note that this code path is slated for removal in the near future (in 0.20 most likely), and we print a warning message about that.
Testing
-------
```shell
WANDB_DISABLE_SERVICE=true python -c "import wandb; run = wandb.init(); run.finish()"
```
> chore: fix ancient disable service code path

- core/internal/filestream/updatestats.go
- gpu_stats/Cargo.lock
- gpu_stats/Cargo.toml
- gpu_stats/src/gpu_apple.rs
- gpu_stats/src/gpu_nvidia.rs
- gpu_stats/src/main.rs
- gpu_stats/src/metrics.rs
- wandb/sdk/internal/sender.py
Description
-----------
- Fixes #9047
This PR fixes an issue in 0.19.0 where I missed properly skipping private system metrics in a refactor: was only skipping in the sender, but not in the writer, which exposed another issue where offline runs would not sync because of a bug in json serialization of string "metrics" in gpu_stats.
Additionally, offline sync will now skip stats items that fail to serialize.
Testing
-------
> fix: correctly handle private system metrics

- CHANGELOG.unreleased.md
- tests/system_tests/test_functional/interrupt/pass_if_interrupted.py
- tests/system_tests/test_functional/interrupt/test_interrupt.py
- wandb/sdk/lib/interrupt.py
- wandb/sdk/wandb_run.py
Description
---
Fixes WB-18098, making the stop button more reliable.
Testing
---
Run the following:
```python
import time
import wandb
wandb.init()
time.sleep(9999)
```
Then press the stop button in the run's Overview tab, next to its State property. Prior to this fix, the stop button would not interrupt the sleep on any platform.
Tested manually on macOS and Windows. Tested on Linux via system-tests.
> fix: correctly interrupt main thread

- pyproject.toml
- tests/system_tests/test_functional/conftest.py
- tests/system_tests/test_functional/interrupt/test_interrupt.py
Description
---
`test_interrupt.py` didn't cover `wandb/sdk/lib/interrupt.py` because it covered `.nox/<site-packages>/wandb/sdk/lib/interrupt.py`. This is because the command `python pass_if_interrupted.py` ran from the test directory, not the repository root, and so `import wandb` loaded the `wandb` installed in the virtual environment, and the paths in the resulting `coverage.xml` file pointed to the venv files rather than the repository files.
Solution: tell `coverage.py` that `.nox/.../site-packages/wandb/` is the same as `wandb/`.
[After the fix: codecov reports coverage for `interrupt.py`.](https://app.codecov.io/gh/wandb/wandb/commit/13c367de5ee283fa2af892a7ba8029e57c53bdb2/blob/wandb/sdk/lib/interrupt.py)
> chore: fix codecov for test_interrupt.py

- CHANGELOG.unreleased.md
- wandb/apis/public/runs.py
Description
-----------
https://github.com/wandb/wandb/pull/8837 included a `print()` statement, presumably for debugging, but the result is that a bool is printed to the console many times (possibly dozens or hundreds of times depending on the run group queried) when inspecting a `wandb.Api().runs()` instance. This print statement should be removed or at least be toggleable. This PR removes the print statement. 
Testing
-------
Manual testing: Prior to this change, inspecting the runs in given by an `wandb.Api().runs()` call would print `True\n` many times to the console, whereas afterwards it does not.
> runs API: Remove noisy print statement

- core/internal/runfiles/uploader.go
Description
-----------
Correctly report the type of the file that being send to `wandb-core` for the following example:
```python
import wandb
with wandb.init() as run:
for i in range(10):
image = np.zeros((10, 10, 3), dtype=np.uint8)
run.log({"image": wandb.Image(image)})
```
Before:
After:
media files were reported as other, which are usually user saved files, after the change these files are correctly reported as media files.
Testing
-------
> fix: make sure media is counted correctly

- wandb/sdk/lib/apikey.py
Description
-----------
when logging in from the cli with `wandb login --anonymously` the value being written to the global settings file is invalid.
This can lead to a loop where running any wandb script would fail.
The config file with the invalid value
running a python script to log an integer gives
global settings file
running a file works fine
Testing
-------
> fix: wandb login anonymously would write invalid value to system settings file

- tests/unit_tests/test_wandb_init.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
Grepping the repository for `_on_init` shows no other references. In an old commit, this used to print version statistics; I'm not sure when that got removed, but now it does nothing.
> refactor: delete no-op wandb.Run._on_init

- wandb/sdk/backend/backend.py
- wandb/sdk/wandb_init.py
Description
-----------
Fixes #9151.
Replace pydantic's deprecated `BaseModel.copy()` with `BaseModel.model_copy()` in the Settings object.
Testing
-------
> fix: replace pydantic's deprecated BaseModel.copy with model_copy in Settings object

- tests/system_tests/test_core/test_wandb_metadata.py
Description
-----------
Fix indentation issue in `tests/system_tests/test_core/test_wandb_metadata.py::test_metadata_access`.
Testing
-------
> chore: fix flaky run.metadata test with legacy service

- tools/perf/Dockerfile
Description
-----------
In the perf dockerfile, pre-install the profiling tools
perf, py-spy for python
go pprof for go
Testing
-------
Tested locally
> chore: preinstall perf and go pprof in dockerfile

- .github/CODEOWNERS
Description
-----------
Assigns @wandb/mlw-team as owner for automations files.  These files will be added in subsequent PRs.
This PR can be merged anytime.
Testing
-------
N/A
> chore(sdk): add automations codeowners

- wandb/sdk/wandb_run.py
The function should use the run's setting for `x_disable_service`, not the singleton value, especially after https://github.com/wandb/wandb/pull/9172.
> fix: possible logic error in _console_start with x_disable_service

- gpu_stats/tools/generate-proto.sh
- noxfile.py
Description
-----------
..as the cargo build command belongs with the gpu_stats project and shouldn't be in the noxfile.
Testing
-------
> chore: move rust protobuf binding generation script closer to source

- gpu_stats/hatch.py
Description
-----------
...Now that there are two binaries (gpu_stats + build_proto).
Testing
-------
> fix: explicitly build gpu_stats binary

- CHANGELOG.unreleased.md
- pyproject.toml
- requirements_dev.txt
Description
-----------
- Fixes [WB-21788](https://wandb.atlassian.net/browse/WB-21788)
(fixed via @amusipatla-wandb too)
Requires `botocore>=1.5.76` in order to prevent errors due to the following issues:
- https://github.com/boto/botocore/issues/1079 (fixed by https://github.com/boto/botocore/pull/1107 in `botocore>=1.4.87`)
- Note: Issue refers to Python 3.6, but this issue was reproducible in Python 3.8 and Python 3.9 as well.
- https://github.com/boto/boto3/issues/1144 (fixed by https://github.com/boto/botocore/pull/1230 in `botocore>=1.5.76`)
Testing
-------
Locally, by running (and passing) system tests while artificially pinning `botocore==1.5.76`.  Pinning `botocore==1.5.75` or earlier will result in test failures due to one of the aforementioned, now-fixed issues.
[WB-21788]: …
> fix(sdk): prevent issues due to bugs in earlier botocore versions

- CHANGELOG.unreleased.md
- wandb/sdk/wandb_setup.py
`_WandbSetup._get_logger()` could never return `None` (unless a user patched `wandb_setup.logger` directly). This PR replaces the module-level `logger` variable and `_set_logger` function by an instance variable and fixes the types.
These are private symbols, but I documented this in the changelog just in case. I recall some users patching our internal logging functionalities in the past.
> refactor: _WandbSetup._get_logger() cannot return None

- CHANGELOG.unreleased.md
- wandb/sdk/internal/internal_api.py
- wandb/sdk/internal/system/system_info.py
- wandb/sdk/lib/apikey.py
- wandb/sdk/wandb_run.py
- wandb/sdk/wandb_settings.py
Description
-----------
This PR fixes multiple checks against an invalid settings value for anonymous mode.
Following up this PR a check if the current user for the run has `accountType == ANONYMOUS` will allow better enforcement of data collected for anonymous runs.
Testing
-------
> fix: checks against invalid anonymous settings value.

- tests/system_tests/test_core/test_resume_auto.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_settings.py
Moves "resume logic" to where it's used and documents it.
I use offline mode in the tests to speed them up, but unfortunately `wandb.init()` still takes a while even in this case (especially with `legacy-service`).
> refactor: move Settings.handle_resume_logic into wandb_init.py

- core/internal/stream/handler.go
Description
-----------
Removes logging of `_client_id` when the user is using shared mode. This appears as an empty chart in the UI which is confusing. We may want to differentiate between different shared mode clients in the future, but we will probably put this in the header or as a config rather than as a history metric. 
Testing
-------
Built locally and tested in QA.
> fix(sdk): remove client_id key from shared mode

- requirements_dev.txt
Cleans up the `tensorflow` dependencies and fixes an issue in the resolved Python 3.8 dependencies where `tensorboard` breaks because of a `protobuf` that's too new.
See https://github.com/wandb/wandb/pull/8679 for the reasoning behind using stricter version constraints in this file.
There are multiple valid choices for the versions. I picked `tensorflow==2.9.2` and `tensorflow-macos==2.9.2` because they have the same `protobuf` constraint, leading to the simplest requirements specification.
> chore: add protobuf version constraint to requirements_dev.txt

- tests/system_tests/test_launch/test_launch_kubernetes.py
Description
-----------
- Fixes #NNNN
Skips a flakey test to keep CI green until we can debug it
Testing
-------
> chore(launch): skip flakey launch kubernetes test `test_kubernetes_run_with_annotations`

- wandb/sdk/wandb_init.py
Fix a typo introduced in https://github.com/wandb/wandb/pull/9232: `init_settings => run_settings`
> chore: fix telemetry typo in wandb.init()

- tools/perf/scripts/bench_run_log.py
Description
-----------
During perf testing, sometimes we want a subset of metrics to have more dense points. i.e. logged more
frequently than others.  This PR supports that 
e.g. 
python3.12 -m scripts.bench_run_log -s 1000 -n 9000 -f 0.01 -c 1000
This will run 1000 steps using 9000 base metrics and 1000 dense metrics. At each step 1% of the base metric and the entire dense metrics will be logged, in this case, a total of 90 + 1000 = 1090 metrics logged per step.
At the end of the test, each of the dense metric would have been logged 1000 times.  Each of the base metric would have been logged 10 times.
Testing
-------
Tested on the perf nodes on GCP
> chore: performance benchmark add support for optional dense metrics

- wandb/sdk/wandb_init.py
Collect telemetry on whether the run is offline immediately after inferring its settings.
NOTE: The original code, at first glance, looks like it could emit a telemetry record: `telemetry.context()` with a Run runs its `_telemetry_callback` which calls `_telemetry_flush`. It only doesn't emit a record because of the `_telemetry_obj_active` field which happens to be `False` at that time: it is set to `True` in `Run._on_ready` called from `Run._on_start` called at the end of `_WandbInit.init()`. The new code is straightforwardly correct without this analysis.
> refactor: record 'offline' telemetry near other telemetry

- wandb/sdk/interface/interface.py
- wandb/sdk/wandb_init.py
Delete unused fields.
`_iface_port` and `_set_iface_port()` were completely unused. `_iface_pid` was also unused; `_set_iface_pid()`, however, was called from a `_hack_set_run()` method. Removing these fields brings us closer to deleting `_hack_set_run()`.
> refactor: delete unused Run._iface_port and _iface_pid fields

- tools/inspect_tool.py
Description
-----------
Adds [Inline script metadata](https://packaging.python.org/en/latest/specifications/inline-script-metadata/#inline-script-metadata) for `tools/inspect_tool.py` to make it standalone / executable with `uv`:
```shell
uv run tools/inspect_tool.py
```
> chore: make tools/inpect_tool.py stanalone/executable with uv

- CHANGELOG.unreleased.md
- core/pkg/monitor/tpu.go
- core/pkg/monitor/tpu_test.go
Description
-----------
Follow up on #9266.
Fixes the issue where non-consecutive TPU device IDs were not handled properly -- we assumed device ids always run from 0 to `n_chips * n_devices_per_chip`, which may not be true, for example, for newer TPU devices/slices in GKE jobs, that can get ids such as:
```
Connected to libtpu at grpc://localhost:8431...
TPU Utilization                                
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Device ┃ Memory usage          ┃ Duty cycle ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 122    │ 24.37 GiB / 95.74 GiB │      0.00% │
│ 123    │ 24.37 GiB / 95.74 GiB │      0.00% │
│ 126    │ 24.37 GiB / 95.74 GiB │      0.00% │
│ 127    │ 24.37 GiB / 95.74 GiB │      0.00% │
└────────┴───────────────────────┴────────────┘
``` …
> fix: handle non-consecutive TPU device IDs in system monitor

- .github/workflows/release-sdk.yml
Description
-----------
`actions/upload-artifact: v3` [has been deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/), which has started to fail the release action.
I followed the migration guide from https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md.
Testing
-------
> chore: update release-sdk action to use upload/download-artifact@v4

- wandb/sdk/backend/backend.py
Fix type annotation in `Backend`: `_settings` is never `None` because a non-`None` value is always passed to the constructor.
It was probably optional before because `_WandbSetup.settings` was also incorrectly marked optional and is passed as the `settings` in a couple spots.
> refactor: fix type hint, Backend._settings cannot be None

- .github/workflows/release-sdk.yml
Description
-----------
The `build-macos-10-wheels` and `build-platform-wheels` on `macos-14` steps in the release action somehow produce the same wheel for arm `wandb-0.19.4rc1-py3-none-macosx_11_0_arm64.whl`, but the former downgrades the go version and go dependencies before making the wheel. The new `download-artifact@v4` action corrupt the wheel (which is just a zip archive) with the `merge-multiple: true` flag. To fix, I:
- Skip the arm target on `build-macos-10-wheels`.
- Explicitly move wheels around as opposed to relying on the action to merge artifacts.
> chore: update release-sdk action to use upload/download-artifact v4

- tests/unit_tests/test_step_upload.py
Description
-----------
There's a time-based wait in `tests/unit_tests/test_step_upload.py` that has started consistently failing in some Mac jobs.
These tests are slated for removal, so no big deal.
Testing
-------
> chore: band-aid a test in test_step_upload.py

- tests/system_tests/test_core/test_wandb_login.py
- tests/unit_tests/conftest.py
- tests/unit_tests/test_wandb_login.py
- tests/unit_tests/test_wandb_settings.py
- wandb/apis/internal.py
- wandb/cli/cli.py
- wandb/sdk/internal/internal_api.py
- wandb/sdk/lib/server.py
- wandb/sdk/wandb_login.py
- wandb/sdk/wandb_setup.py
Description
-----------
This change moves the login API key verification from `wandb_login.py::login()` to `wandb_login.py#_WandbLogin::_login` since this function is used by the previous function as well as directly by `wandb.init()`. Providing a common place path to validating API keys.
Testing
-------
> refactor: move API key verification to common _login method

- wandb/__init__.pyi
- wandb/sdk/data_types/image.py
- wandb/sdk/wandb_run.py
We haven't been running yeadoc-test for quite some time.
> docs: remove unused yeadoc-test tags from docstrings

- .github/workflows/generate-docodile-documentation.yml
Description
-----------
Relates to this update made in wandb/docugen: https://github.com/wandb/docugen/pull/49
Latest docugen release: https://github.com/wandb/docugen/releases/tag/v0.4.5
Testing
-------
> docs(sdk): updates generate-docodile workflow file to use latest docugen release

- tests/system_tests/backend_fixtures.py
- tests/system_tests/conftest.py
- tests/system_tests/test_importers/test_wandb/conftest.py
Originally this PR tried to make 'user' session-scoped, but many artifacts, launch and sweep tests fail: https://app.circleci.com/pipelines/github/wandb/wandb/43365/workflows/741a125e-f337-4b70-8193-5b598a24ca88/jobs/1333011/tests. We may be able to use function-scoped users for these but have a session-scoped user for other tests, but a better direction is to make the user fixture fast enough for this to not matter.
> refactor: always use 'function' scope for the user fixture

- tests/unit_tests/test_iterutils.py
- wandb/_iterutils.py
Description
-----------
Adds a helper function `one()` to extract the only item from an iterable (raising an error if the iterable has too few/many items). 
Intended primarily for internal use, though as implemented, it's technically a public function.  That said, users who may discover the function and wish to use it are strongly encouraged to use `more-itertools.one()` instead, as the implementation here was only lightly adapted from `more-itertools`.
Note: The primary reason for reimplementing, as opposed to importing directly from `more-itertools`, was to prevent adding a required install dependency at this time.
Testing
-------
> chore(sdk): add internal helper to extract the only item from an iterable

- core/internal/runmetric/definedmetric.go
- tests/system_tests/test_core/test_metric_full.py
Description
-----------
- Fixes WB-22812
This PR fixes the behavior where we used to reset the configuration of a new setting was provided.
Testing
-------
> fix: handle correctly multiple summary types in define_metric

- CHANGELOG.unreleased.md
- wandb/cli/cli.py
Description
-----------
- Fixes WB-22851
This PR adds an alias (`--base-url`) for the `--host` option when running `wandb login`. This aligns with the expected user provided environment variable for setting the base url as well (`WANDB_BASE_URL`)
Testing
-------
- `wandb login --base-url https://api.wandb.io`
- `wandb login --host https://api.wandb.io`
> chore: add additional --base-url option for wandb login to match the env variable WANDB_BASE_URL

- BREAKING.md
Creates a `BREAKING.md` file to help plan batches of breaking changes.
- WB-21750
> chore: add BREAKING.md for breaking changes

- wandb/sdk/lib/apikey.py
- wandb/sdk/wandb_login.py
Description
-----------
This PR removes the side effect of immediately writing the API key when the user is prompted, and instead does it in an explicit function call.
Additionally the `noop` settings check has been moved to the common `_login` function.
Testing
-------
> refactor: remove writing api key during user prompt function.

- tests/system_tests/test_notebooks/conftest.py
- tests/system_tests/test_notebooks/test_notebooks.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_login.py
Description
-----------
- Fixes WB-8622
- Fixes WB-17065
- Fixes WB-15849
This PR removes a third layer of abstraction by removing the `_WandbLogin.login` function, and restructures the `_login` function. This fixes multiple issues, such as writing invalid API keys to the netrc file, or not displaying the login message when in a notebook environment.
Testing
-------
> refactor: remove third login abstraction layer

- tools/perf/scripts/bench_run_log.py
Description
-----------
Added forking capacities to support perf testing forks. 
Added an option to prefix the scalar metric names.
Added an optional project name as input
Testing
-------
Tested on perf nodes on prod (SaaS)
> chore: support run-forking in performance tests 

- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
Instead of initializing `_wandb/code_path` and `_wandb/branch_point` in `Run._init`, do it in `_WandbInit.make_run_config`.
Their values depend solely on settings, which are finalized by the time `make_run_config` is called. The `result.base_no_artifacts` dict at the end of `_WandbInit.make_run_config` is the `config` dict at the start of `Run._init`---no changes to the config happen in between. Nothing in-between those calls depends on the config values either.
The only semantic change is that now, a disabled run will have the `_wandb` key in its config because `make_disabled_run` uses the result of `make_run_config`.
The `Run` constructor takes three "config" parameters and merges them into its `Config` object. These values cannot be combined and passed as one dict because the keys from …
> refactor: move some config initialization out of wandb_run.py

- wandb/sdk/lib/mailbox.py
The `Mailbox.wait()` method, which just calls `MailboxHandle.wait()`, is not used anywhere and can be removed.
> refactor: delete unused Mailbox.wait method

- CHANGELOG.unreleased.md
- core/pkg/monitor/cpu.go
- wandb/sdk/internal/system/assets/cpu.py
Description
-----------
TBU: In the next release, we'll introduce the ability to configure the set of system metrics to collect. Per-core CPU utilization will however be disabled by default, to reduce the number of metrics collect by default as it can get large on beefy systems and is not always useful vs, say, the aggregated/averaged process tree CPU utilization.
> chore: temporarily disable collecting per-core CPU utilization stats

- requirements_dev.txt
Description
-----------
Its absence there started breaking the importer (unit) tests, see e.g. https://app.circleci.com/pipelines/github/wandb/wandb/43686/workflows/7111a909-3850-4de1-ac13-6289e457a6de/jobs/1337484?invite=true#step-106-158059_67. I'd guess that some other dependency dropped a dep on it, and it was working for us as it was implicit.
> chore: add tenacity to requirements_dev.txt

- CHANGELOG.unreleased.md
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py
Description
-----------
- [WB-22870](https://wandb.atlassian.net/browse/WB-22870)
Fixes slow (client-side) instantiation of `Artifact` objects due to a separate blocking HTTP request to fetch the artifact manifest.
This request can occur during internal calls to `Artifact._from_attrs()`, so this affects most code paths that parse an `Artifact` from GQL response data.
This PR "defers" the HTTP request -- by wrapping the request URL in an internal dataclass (since using Futures or similar probably risks unforeseen side effects) --until the getter on `artifact.manifest` is invoked.
Testing
-------
No intended change in functionality, so relying on existing tests to catch regressions.
[WB-22870]: https://wandb.atlassian.net/browse/WB-22870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> fix(artifacts): fix slow instantiation of Artifact from GQL responses

- CHANGELOG.unreleased.md
- gpu_stats/src/gpu_nvidia.rs
Description
-----------
In Nvidia GPUs there are two ECC counters: volatile and aggregate. Volatile counter is being reset whenever driver is reloaded or GPU is reset. Aggregate counter is intended to be kept during all the GPU lifetime. When ECC error occurs because of memory corruption, one of the common actions is applying the memory row remapping (i.e. using redundant memory areas instead of damaged) that fixed ECC cause but does not reset the aggregate counter. This can be confusing since healthy (after row remapping) GPU will appear as broken according to ECC metric on the system dashboard. I propose to use volatile counter here that is less misleading in such cases.
Testing
-------
> chore: use volatile ECC counter instead of aggregate for system dashboard

- wandb/sdk/lib/run_moment.py
- wandb/sdk/wandb_settings.py
Description
-----------
Moves (and cleans up) the Settings class attributes descriptions to docstrings. This is understood by pydantic (with a config flag) and recognized by pywrite, vscode etc:
Testing
-------
> docs: add Settings object attribute docstrings

- CHANGELOG.unreleased.md
- tests/unit_tests/test_normalize.py
- wandb/apis/normalize.py
- wandb/util.py
Fixes the string representation of HTTP errors encountered by the public API.
The `parse_backend_error_messages` function now properly handles the `{"error": "message"}` and `{"error": {"message": "value"}}` formats.
When the response body is not in a known format, `normalize.py` now includes the response body text instead of the `Response` object, whose string representation was `<Response: status>`.
> fix: public API error messages

- wandb/sdk/internal/sender.py
- wandb/sdk/lib/mailbox.py
- wandb/sdk/lib/retry.py
Replace `mailbox.ContextCancelledError` by `retry.RetryCancelledError`.
This error is only raised in `retry.py` and only caught in `sender.py`. It subclasses `mailbox.MailboxError`, but this is only caught in `wandb_run.py` while running `MailboxHandle.wait()` which cannot throw `ContextCancelledError`.
There was no reason for this to be in `mailbox.py`.
> refactor: replace mailbox.ContextCancelledError

- tests/unit_tests/test_launch/test_runner/test_kubernetes.py
Description
-----------
- [Slack thread](https://weightsandbiases.slack.com/archives/C0108SLEP6K/p1738180653893699)
Some Launch-related tests are failing because the `LaunchAgent` is being instantiated before the test. This adds a fixture to clear the `LaunchAgent` before running the affected tests.
Testing
-------
The test is flaky so it's hard to say for sure, but it passes locally and in CI.
> chore(launch): clean launch agent mock between launch kubernetes tests

- tests/unit_tests/test_normalize.py
Removes `raise_exception` from `test_normalize.py`, which is no longer used.
Prefixing test helper method with underscores makes it easier to see if a method is unused as IDEs often highlight that, so I did that too in this file.
> refactor: remove unused method in test_normalize.py

- core/pkg/monitor/openmetrics.go
- core/pkg/monitor/openmetrics_test.go
The hashes are computed from labels extracted for individual metrics and are used to provide a stable indexing / mapping when collecting metrics from an OpenMetrics/Prometheus endpoint.
This PR ensures labels are sorted before computing hashes.
Example of an OpenMetrics metric:
```
DCGM_FI_DEV_GPU_TEMP{DCGM_FI_DEV_SERIAL="175212400829", DCGM_FI_DEV_VBIOS_VERSION="96.00.A5.00.01", Hostname="l1337", UUID="GPU-66f74c59-1fd7-7943-526e-cdb89a69516b", cluster="ml-dev", container="exporter", device="nvidia6", endpoint="metrics", gpu="6", instance="10.0.0.102:9400", job="metrics/dcgm-exporter", modelName="NVIDIA H100 80GB HBM3", node="l1337", region="US-WEST-02", uuid="GPU-66f74c59-1fd7-7943-526e-cdb89a69516b"} => 24 @[1738025769]
```
> chore: sort computed metric label hashes for openmetrics collector in system monitor

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/storage_handlers/local_file_handler.py
Description
-----------
- Fixes [WB-22558](https://wandb.atlassian.net/browse/WB-22558)
Fixes the calculation of file hashes when adding a local reference file with `checksum=False` (i.e. when calling `artifact.add_reference("file:///...", checksum=False)`).
Although this is discouraged in documentation, the behavior of `checksum=False` on local files and other types of reference artifacts should be consistent (S3, etc).  Specifically, adding local references with `checksum=False` will only result in logging a new artifact version if the reference **URI** changes (and ignoring the file contents).
This expectation also means that with `checksum=False`, calculated file hashes/digests will only depend on the (absolute) reference path.  For local files, `checksum=False` hashes were calculated …
> fix(artifacts): add_reference with checksum=False should only log new version if URI changes

- core/internal/stream/stream_init.go
Fixes the SDK side of WB-23039.
The `X-WANDB-USE-ASYNC-FILESTREAM` header in the `GraphQL` client is used to indicate to the backend that the run is in shared mode to prevent a race condition when two UpsertRun requests are made simultaneously for the same run ID in shared mode. For regular runs, this would result in a 409 conflict error, but for shared runs, the backend returns a retryable error.
> chore: set X-WANDB-USE-ASYNC-FILESTREAM header in GQL client in shared mode

- core/pkg/server/connection.go
In the extremely rare case of failing to parse incoming data on a connection, log the first 1KB of the token.
This will show up as a base64-encoded string in the log file:
1. We use a JSONHandler, which [documents](https://pkg.go.dev/log/slog#JSONHandler.Handle) it formats values using `json.Encoder`
2. `json.Encoder` [documents](https://pkg.go.dev/encoding/json#Marshal) it outputs `[]byte` as a base64-encoded string
> refactor: log token on unmarshal error

- tests/unit_tests/test_lib/test_apikey.py
- wandb/sdk/lib/apikey.py
Description
-----------
- Fixes WB-22789
This PR fixes a lot of the weird behavior with writing the API key. This of note:
- Adds warning for no read/write permissions to the given netrc file.
- Does not log `Appending key for ...` if we do not have access or an error occurs
- Do not overwrite the netrc file if we do not have read permissions
Testing
-------
> fix: log an error when we do not have access permission to the netrc file

- tests/system_tests/test_core/test_wandb_init.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_settings.py
When running in shared mode, it is expected that there are multiple writers to the same run ID. The `x_label` setting is used to distinguish system metrics and console logs originating from different processes. This PR ensures `x_label` is generated if not provided by the user in shared mode.
> chore: auto-generate x_label in shared mode if not provided

- wandb/sdk/lib/apikey.py
Description
-----------
- Fixes WB-9180
In various notebook environments there are different ways to interrupt to send an interrupt command. Right now we print out a message with "or press ctrl+c to quit" which does nothing in jupyter or colab notebooks. This PR removes that part of the string when running in a notebook/jupyter env.
Testing
-------
> chore: update login message for notebook environments to not show "press ctrl+c to quit"

- CHANGELOG.unreleased.md
- pyproject.toml
- requirements_dev.txt
Description
-----------
This PR adds a constraint for installing moviepy to be >=1.0.0 since older version do not work with the W&B SDK.
Testing
-------
> chore: add constraints on moviepy >=1.0.0

- tests/system_tests/test_artifacts/test_object_references.py
Description
-----------
- [WB-23099](https://wandb.atlassian.net/browse/WB-23099)
Follows up on #9371 with a more extensive refactor and cleanup of `system_tests/test_artifacts/test_object_references.py`, which:
- contains the slowest individual tests within this repo,
- is vulnerable to flaky behavior, partly since the objects being tested may be sharing state across tests in ways that are not intentional.
Locally, this PR appears to reduce execution time of `test_object_references.py` test by ~25-50%, depending on the number of workers requested.
Sample durations from local execution:
- For **16 workers** (`pytest -n=auto --durations=10 ...test_object_references.py`):
- `main`: ~60-90s ![image](https://github.com/user-attachments/assets/597740ba-7166-4155-a983-f8d348643e88)
- this PR: …
> refactor: speedup and more cleanup of test_object_references.py

- wandb/__init__.pyi
- wandb/__init__.template.pyi
- wandb/sdk/wandb_require.py
This was missed before, causing IDEs to not recognize `wandb.require()` .
> refactor: add `wandb.require()` to `wandb/__init__.pyi`

- tests/system_tests/test_core/test_wandb_init.py
- wandb/sdk/wandb_init.py
Fix for https://github.com/wandb/wandb/pull/9399: all Run settings modifications should happen in `wandb/sdk/wandb_init.py::_WandbInit.make_run_settings`.
> chore: move automatic x_label setting setup to make_run_settings

- wandb/util.py
The nested `get_message` function's `err` parameter was unused. Miraculously, it still worked because `error` is always bound to what `err` would be.
> fix: parse_backend_error_messages naming blooper

- .circleci/config.yml
- noxfile.py
- requirements_test.txt
- Addresses the default nox behavior change in version 2025.2.9 where apparently os.environ is not propagated into session.env.
- Dependency fix for py3.8 fix.
> chore: env var inheritance in nox 2025.2.9 sessions

- core/internal/api/backenderrors.go
- core/internal/api/backenderrors_test.go
- core/internal/api/logging.go
- core/internal/wboperation/wboperation.go
- core/internal/wboperation/wboperation_test.go
When the HTTP response from the backend contains error messages in a known format, include them in operation stats, making `run.finish()` more informative and also `wandb.init()` (with PR #9431).
The logic is the same as in `wandb/util.py::parse_backend_error_messages()`, and the test cases are the same as those in `test_normalize.py`.
> refactor: include backend error messages in operation stats

- CHANGELOG.unreleased.md
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_setup.py
Make `wandb.setup()` always start up a service, which multiprocessing use-cases rely on.
PR #9172, first included in 0.19.2, added `_WandbSetup.ensure_service()` to start up the service lazily in `wandb.init()` so that it's not started when creating a disabled run.
> fix: ensure service on wandb setup

- noxfile.py
The latest nox release updated `session.env` so that it is no longer based on `os.environ`.
> fix: use os.environ instead of session.env in noxfile

- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
- wandb/sdk/wandb_setup.py
Removes the `_WandbSetup._global_run_stack` field as all the ways we use it can be done with `wandb.run`.
Its only use was in `wandb.init()`, which called `finish()` on its latest item if `reinit` is true, but this is equivalent to calling `finish()` on `wandb.run`.
> refactor: delete the _global_run_stack

- tests/system_tests/test_functional/asyncio_compat_run/pass_if_cancelled.py
- tests/system_tests/test_functional/asyncio_compat_run/test_asyncio_compat_run.py
- tests/unit_tests/test_asyncio_compat.py
- wandb/sdk/lib/asyncio_compat.py
Adds `asyncio_compat.py` file with some important utilities for using `asyncio` safely.
In `asyncio`, cancelling a task does not cancel subtasks that it started. Python 3.11 adds a `TaskGroup` class to fix this, but we need custom code for Python 3.8 - 3.10.
Using `asyncio.run` inside an `asyncio` event loop is not allowed. In case any of our users call `wandb` functions in an `asyncio` context, the `asyncio_compat.run` function starts an `asyncio` loop in a new thread.
> refactor: asyncio compatibility tools

- tests/unit_tests/test_new_mailbox.py
- wandb/sdk/mailbox/__init__.py
- wandb/sdk/mailbox/handles.py
- wandb/sdk/mailbox/mailbox.py
A reimplementation of `mailbox.py` with tests and documentation, that works with `asyncio`.
This PR does not delete the old mailbox, and no code uses the new mailbox yet.
The `MailboxProbe` / `MailboxProgress` mechanism in the old implementation relied heavily on callbacks and was undocumented / untyped making it difficult to use. The new mailbox provides an async interface for the same purpose, see PR #9382.
The `wait()` method on `MailboxHandle` is there for compatibility with old code, so that it's possible to migrate incrementally.
The old mailbox's "keepalive" mechanism is replaced by a `Mailbox.close()` method which the Router is meant to call when it stops reading new messages (in a `finally` block).
The test file is a little repetitive because it tests both the sync (`wait_or`) …
> refactor: new mailbox implementation

- tests/system_tests/test_functional/openai/test_finetuning.py
Mark test wandb_core_only because it is order-dependent and cannot run twice.
When we run it twice, the second time it outputs a warning like
> wandb: WARNING Fine-tune ftjob-H3DHssnC1C82qfc3ePQWeP3V has already been logged successfully at http://127.0.0.1:32845/user-gw3-98exia799lz2/OpenAI-Fine-Tune/runs/ftjob-H3DHssnC1C82qfc3ePQWeP3V. Use `overwrite=****` if you want to overwrite previous run
Interestingly, this doesn't fail consistently: if the two instances run simultaneously, they can both pass.
The tested functionality does not appear to depend on the service process.
> chore: make test_finetuning wandb_core_only

- wandb/sdk/interface/router.py
- wandb/sdk/interface/router_sock.py
- wandb/sdk/lib/sock_client.py
Log the cause of a MessageRouterClosedError to distinguish between empty reads and OS errors.
Note that ConnectionResetError subclasses OSError, so it didn't need its own `except` clause.
> refactor: better debugging in router.py

- tests/unit_tests/test_wait_with_progress.py
- wandb/sdk/mailbox/__init__.py
- wandb/sdk/mailbox/wait_with_progress.py
Implements `wait_with_progress`, which replaces the old  `MailboxProbe` / `MailboxProgress` mechanism.
Basic usage:
```python
async def display_progress() -> NoReturn:
while True:
update_screen()
await asyncio.sleep(0.1)
wait_with_progress(
handle,
timeout=30,
progress_after=1,
display_progress=display_progress,
)
```
Using `asyncio` allows `display_progress` to poll (e.g. RequestPollExit) and update the screen simultaneously---at independent rates!---by starting two tasks (not shown above).
> refactor: mailbox wait_with_progress

- wandb/sdk/artifacts/artifact.py
- wandb/sdk/mailbox/handles.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
- wandb/sdk/wandb_sync.py
Deletes the `MailboxHandle.wait()` method and replaces all uses with `MailboxHandle.wait_or()`. The difference was that passing `timeout=-1` to `wait()` would cause it to block forever (even though `timeout=-0.9` or `timeout=-1.1` would cause it to timeout immediately).
Changes:
```py
wait(timeout=-1)      # Old
wait_or(timeout=None) # New
result = wait(...)
assert result
result = wait_or(...)
result = wait(...)
if result:
...
else:
...
try:
result = wait_or(...)
except TimeoutError:
...
else:
...
```
> refactor: delete deprecated handle wait

- wandb/sdk/artifacts/artifact.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/internal/sender.py
- wandb/sdk/wandb_run.py
Rewrite `communicate_artifact`, which used the old `MessageFuture` abstraction, as `deliver_artifact` using `Mailbox`.
NOTE: The records used to set `req_resp` and `uuid`, and now they use `mailbox_slot`. I updated `sender.py` because it asserted `req_resp` was set; otherwise, I don't see these used in `sender.py` or `sender.go`, and `handler.py`/`handler.go` simply forward the request.
This was used by `run.log_artifact()`. To test it manually, create a large file called `large_file.txt` and run:
```python
import wandb 
artifact = wandb.Artifact(name="large_artifact", type="junk") 
artifact.add_file(local_path="large_file.txt") 
run = wandb.init() 
run.log_artifact(artifact) 
print(f"state: {artifact.state}")  
print("waiting...")
artifact.wait(timeout=...)
print("done waiting!") 
```
> refactor: communicate_artifact => deliver_artifact

- core/internal/stream/handler.go
- core/pkg/service_go_proto/wandb_internal.pb.go
- gpu_stats/src/wandb_internal.rs
- wandb/proto/v3/wandb_internal_pb2.pyi
- wandb/proto/v4/wandb_internal_pb2.pyi
- wandb/proto/v5/wandb_internal_pb2.pyi
- wandb/proto/wandb_internal.proto
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/internal/handler.py
- wandb/sdk/internal/sender.py
Removes `communicate_login` and `publish_login` methods from `InterfaceShared` as they are not used anywhere, and the former relies on the old `communicate` mechanism.
Since these are not used and were never saved to any transaction logs (due to being local), I also removed all the corresponding handling code in `wandb-core` and `legacy-service`.
> refactor: remove unused communicate_login and publish_login

- CHANGELOG.unreleased.md
- core/internal/stream/sender.go
- tests/unit_tests/test_lib/test_progress.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/lib/progress.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
Fixes WB-23194.
Display a message during `wandb.init()` that describes the work being done and any errors.
Before, `wandb.init()` would simply print `wandb: Waiting for wandb.init()...` with an old-style spinner.
Now `wandb.init()` prints:
```
wandb: ⢿ creating run (4.2s)
```
with a new style spinner. If there is an error, the message is updated to something like:
```
wandb: ⢿ creating run (4.2s)
wandb:   ↳ ⢿ retrying HTTP 409 Conflict
```
In the future, this can be extended to display the HTTP response body as well in case it contains a useful error message from the backend.
> refactor: show operation stats on init

- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/interface/interface_sock.py
Replaces `_communicate_shutdown()` by `_deliver_shutdown()` and deletes `InterfaceShared._communicate()` and `_communicate_async()` as they are no longer used.
`handler.go` and `handler.py` both respond to `RequestShutdown` immediately without checking `req_resp` or `uuid`.
> refactor: delete InterfaceShared._communicate

- wandb/sdk/interface/interface_queue.py
- wandb/sdk/interface/interface_relay.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/interface/interface_sock.py
- wandb/sdk/service/streams.py
The `_process` and `_process_check` fields are only used by `InterfaceQueue`, so this PR removes them from `InterfaceShared`.
`Backend` is the only place that instantiates `InterfaceQueue` passing the `process` parameter.
`InterfaceRelay` inherits from `InterfaceQueue` and is only instantiated in `streams.py` with `_process_check` set to False, so it doesn't need the `process` parameter at all.
> refactor: remove "process_check" from InterfaceShared

- tests/unit_tests/test_mailbox.py
- wandb/sdk/mailbox/__init__.py
- wandb/sdk/mailbox/mailbox.py
- wandb/sdk/service/streams.py
Raise an error instead of allowing the creation of a handle to which a response will never be delivered.
This PR also updates `StreamRecord` in `legacy-service` to own its own `Mailbox` instead of sharing one from `StreamMux`. A `StreamRecord` corresponds to a Run and starts up a `MessageRouter` that delivers responses to the mailbox. When the run ends, the `MessageRouter` closes the mailbox, so it cannot be reused by future runs.
There was no need for StreamRecords to share a Mailbox because a Record delivered to a stream can only get a Result from that same stream. Using different Mailbox instances can never result in a situation where `require_response` is called on one `Mailbox` and the result is delivered to another.
> refactor: raise MailboxClosedError when creating handle in closed mailbox

- wandb/sdk/wandb_run.py
The type of `run_obj.tags` is an internal protobuf type for repeated scalar fields, but `self._settings.run_tags` expects `tuple[str, ...]`.
Testing:
```python
with wandb.init() as run1:
pass
run2 = wandb.init(id=run1.id, resume="must")
run2.tags  # This will print the tags set in the UI.
```
> refactor: fix mypy finding in wandb_run.py::Run._set_run_obj when setting tags

- core/internal/sentry_ext/client_test.go
Fixes WB-23353.
An unfortunate blooper where reporting to sentry was not properly disabled in Sentry client tests in Go.
> chore: disable sentry in sentry go client tests

- wandb/sdk/data_types/helper_types/bounding_boxes_2d.py
- wandb/sdk/data_types/helper_types/image_mask.py
- wandb/sdk/data_types/video.py
Description
-----------
This PR updates examples which explicitly do `wandb.log(...)` to be `run = wandb.init() ... run.log(...)`, which is the standard we want to push users towards.
Testing
-------
> docs: change wandb.log to run.log in media documentation.

- wandb/sdk/wandb_run.py
Handle `MailboxClosedError` in addition to `HandleAbandonedError`.
This error is normally unexpected and should be bubbled up, but the `RunStatusChecker` is intended to stop silently if the service process dies. It already catches `HandleAbandonedError`, but it does not catch the related `MailboxClosedError`.
> fix: handle MailboxClosedError in loop_check_status

- .github/workflows/release-sdk.yml
- core/hatch.py
Description
-----------
When CGO is disabled, the Go compiler's internal linker does not respect the MACOSX_DEPLOYMENT_TARGET value to lower the minimum OS version, which we rely on for building wheels for MacOS 10.x in CI. Instead, it embeds a minimum target based on the SDK in the CI runner, which as of 2025-02-20 is 11.0.
To work around this, we enable CGO and force the Go compiler to use the system linker, which respects MACOSX_DEPLOYMENT_TARGET.
Testing
-------
Sample dry release run proving that it works: https://github.com/wandb/wandb/actions/runs/13447475773/job/37575849970.
> chore: enable cgo for macos10/amd64 builds

- core/internal/runwork/sentinel.go
- core/internal/stream/sender.go
Fixes the format specifier used in `WorkSentinel.DebugInfo()`. Using `%s` is incorrect when the argument (of interface type `any`) does not have the concrete type `string`. Specifically, it was producing the string
```
WorkSentinel(%!s(stream.senderSentinel=1))
```
Where `%!s` is `fmt.Sprintf`'s way of indicating that it caught and suppressed a panic. Now, with the added `String()` method on the `senderSentinel` type, the above becomes
```
WorkSentinel(senderSentinel(1))
```
> fix: format specifier in WorkSentinel DebugInfo()

- tests/unit_tests/test_mailbox.py
- tests/unit_tests/test_wait_with_progress.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/interface/router.py
- wandb/sdk/interface/router_queue.py
- wandb/sdk/interface/router_relay.py
- wandb/sdk/interface/router_sock.py
- wandb/sdk/mailbox/__init__.py
- wandb/sdk/mailbox/mailbox.py
- wandb/sdk/mailbox/mailbox_handle.py
- wandb/sdk/mailbox/response_handle.py
- wandb/sdk/mailbox/wait_with_progress.py
Generalize `Mailbox` to work on the `ServerRequest` / `ServerResponse` level instead of `Record` / `Result`.
`MailboxHandleT` is a generic class that replaces `MailboxHandle` to allow for both `MailboxHandleT[pb.Result]` and `MailboxHandleT[spb.ServerResponse]`. `MailboxHandle` is an alias to `MailboxHandleT[pb.Result]` to keep this PR small, but the next PR completes the renaming.
`Mailbox.deliver()` now requires `spb.ServerResponse` instead of `pb.Result`. The only callsite is in `MessageRouter`, which I updated. Unfortunately, `legacy-service` uses `MessageRouter` internally, so it has to continue to handle the `pb.Result` codepath. To do this, it creates an `spb.ServerResponse()` and sets its `result_communicate` to the given `pb.Result`.
> refactor: change Mailbox to operate on ServerRequest / ServerResponse

- wandb/sdk/artifacts/artifact.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/mailbox/__init__.py
- wandb/sdk/mailbox/mailbox.py
- wandb/sdk/mailbox/mailbox_handle.py
- wandb/sdk/mailbox/response_handle.py
- wandb/sdk/mailbox/wait_with_progress.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_run.py
Finish the refactor started in https://github.com/wandb/wandb/pull/9488 by renaming `MailboxHandleT` to `MailboxHandle` and updating types throughout the codebase.
> refactor: rename MailboxHandleT to MailboxHandle

- tests/system_tests/test_core/test_console.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/backend/backend.py
- wandb/sdk/interface/interface.py
- wandb/sdk/interface/interface_queue.py
- wandb/sdk/interface/interface_relay.py
- wandb/sdk/interface/interface_shared.py
- wandb/sdk/interface/interface_sock.py
- wandb/sdk/lib/service_connection.py
- wandb/sdk/lib/sock_client.py
- wandb/sdk/service/server_sock.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_sync.py
Separate `MessageRouter` from `InterfaceShared`. A `MessageRouter` is a handle on a thread that delivers results from the service into a `Mailbox`.
This PR also updates `inform_attach` to use `Mailbox` and removes the deprecated `SockClient.send_and_recv` mechanism. This is necessary because `send_and_recv` assumes nothing else is reading on the socket, but this PR causes a reader thread to be created earlier in `wandb_init.py::_attach()`.
There can only be one `MessageSockRouter` per socket, and there is only one socket connection to the service per client process. If `InterfaceShared` owns `MessageSockRouter`, then there can only be one `InterfaceShared` instance at a time, and therefore only a single run at a time.
This PR makes code that instantiates `InterfaceShared` be responsible …
> refactor: remove `_router` from `InterfaceShared`

- .gitignore
- pyproject.toml
- tests/conftest.py
Makes code coverage count lines executed by subprocesses started by tests, such as in tests/system_tests/test_functional/multiprocessing/test_mp.py.
The key fix is in the `filesystem_isolate` fixture. It was also necessary to remove the `tool.coverage.run.source` setting in `pyproject.toml` because it fails to collect coverage this way. This setting actually does not apply in our normal usage of `pytest` in `noxfile.py`, where `--cov=""` overrides it.
> fix: code coverage collection in subprocesses

- tests/system_tests/test_functional/console_capture/patch_stdout_and_stderr.py
- tests/system_tests/test_functional/console_capture/patching_exception.py
- tests/system_tests/test_functional/console_capture/test_console_capture.py
- tests/system_tests/test_functional/console_capture/uncapturing.py
- wandb/sdk/lib/console_capture.py
Creates `console_capture.py` for patching `stderr` and `stdout`'s `write` methods.
The original way of doing this is in `redirect.py`, and I replace it in the next PR. `redirect.py` only allows a single hook at a time which forces us to only have a single run at a time. It also isn't thread-safe and doesn't document important edge cases (or much else).
> refactor: console capture redo

- tests/system_tests/test_core/test_console.py
- tests/system_tests/wandb_backend_spy/spy.py
- wandb/sdk/lib/console_capture.py
* Makes most tests run without `capfd`, which interacts poorly with `console_capture.py`
* Simplifies and speeds up some tests
> refactor: update test_console.py

- wandb/sdk/lib/redirect.py
- wandb/sdk/wandb_run.py
Updates `StreamWrapper` and `StreamRawWrapper` (used for `wrap` and `wrap_raw` console modes, respectively) to use `console_capture.py`.
* The `RedirectBase.save()` method is removed as it is no longer necessary
* The base `install` and `uninstall` implementations are moved down into `Redirect` because they're irrelevant to `StreamWrapper` and `StreamRawWrapper`
> refactor: use new console_capture.py implementation

- wandb/sdk/lib/redirect.py
Removes an INFO-level log statement added in a previous PR that was used for debugging.
> chore: remove accidental log statement

- CHANGELOG.unreleased.md
- tests/system_tests/test_core/test_wandb.py
- tests/unit_tests/test_data_types.py
- tests/unit_tests/test_sender.py
- wandb/filesync/dir_watcher.py
- wandb/sdk/internal/sender.py
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-22927
- Fixes WB-11116
This PR fixes a bug which some characters (`[`, `?`, `*`) would be escaped and cause the file upload to fail. 
Testing
-------
- Wandb core test
```
import wandb
run = wandb.init(
project="sample-image-upload-long",
)
img = np.random.randint(0, 255, (100, 100, 3))
image_path_buggy = "Validation/Plots/ex30[]]"
run.log({
f"media/images/{image_path_buggy}": wandb.Image(img),
})
run.finish()
```
- Wandb legacy test
```
import wandb
wandb.require("legacy-service")
run = wandb.init(
project="sample-image-upload-long",
)
img = np.random.randint(0, 255, (100, 100, 3))
image_path_buggy = …
```
> fix: strings with glob charaters were not being uploaded with wandb-core

- core/internal/stream/stream_mux.go
- core/pkg/server/connection.go
Removes the `nc.stream` field and replaces it by calls to `streamMux.GetStream()`.
The risk is if we ever send messages without a stream ID to wandb-core, they will not be processed. `InterfaceSock` assigns a stream ID on all outgoing records; `ServiceConnection` in `service_connection.py` assigns a stream ID on Init, Finish, Attach and Start requests.
I have not checked other clients, but note that they would not work with legacy-service since it always requires the stream ID to be set.
> refactor: allow multiple streams per connection in core

- wandb/sdk/wandb_init.py
Adds a missing `# type: ignore[method-assign]` and updates the other `# type: ignore` annotations ones to be more selective.
> chore: ignore mypy lint in wandb_init.py::make_disabled_run when assigning to method

- tools/perf/scripts/bench_run_log.py
Description
-----------
Remove derived_summary from default setting as it is supported on certain version of the backend. Will use env variable to configure it instead.
Testing
-------
Locally
> chore: remove the derived_summary from default setting

- CHANGELOG.unreleased.md
* Puts the current bullet point into a Fixed section
* Updates the wording
* Escapes the backslash
> chore: fix CHANGELOG.unreleased.md formatting

- CHANGELOG.unreleased.md
- tests/assets/notebooks/init_finishes_previous.ipynb
- tests/system_tests/test_notebooks/test_notebooks.py
- wandb/__init__.pyi
- wandb/__init__.template.pyi
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_settings.py
Adds a `"default"` option to `reinit` that behaves like `"finish_previous"` in notebooks and `"return_previous"` elsewhere.
Originally broken in 0.19.0 in https://github.com/wandb/wandb/pull/8649. The type of `reinit` used to be incorrectly annotated as `bool` but initialized to `None`. After that PR rewrote Settings using pydantic, `reinit` started to be initialized to `False` instead of `None`. Then https://github.com/wandb/wandb/pull/9445 removed the `settings._jupyter` check in `wandb_init.py` because 
```
settings.reinit or (settings._jupyter and settings.reinit is not False)
```
was equivalent to `settings.reinit` since `reinit` could not be `None`.
> fix: default reinit to "finish_previous" in notebooks

- CHANGELOG.unreleased.md
- requirements_dev.txt
- tests/conftest.py
- tests/system_tests/test_functional/wb_logging/last_resort.py
- tests/system_tests/test_functional/wb_logging/test_wb_logging_last_resort.py
- tests/system_tests/test_launch/test_launch_cli.py
- tests/unit_tests/test_lib/test_filesystem.py
- tests/unit_tests/test_mailbox.py
- tests/unit_tests/test_wb_logging.py
- wandb/__init__.py
- wandb/jupyter.py
- wandb/sdk/lib/wb_logging.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
- wandb/sdk/wandb_setup.py
Defines the `wb_logging` module to filter out log messages for other runs from a run's log file.
Since most of our log statements don't include a run ID, to support multiple simultaneous active runs we need to direct only relevant log messages to each run's `debug.log` file. Without this PR, all log messages go to all runs' log files. With this PR, log messages that are known to be irrelevant to a run (due to `wb_logging.log_to_run(...)` being used for another run ID) are filtered out.
Messages logged outside the context of `wb_logging.log_to_run` are written to all runs' log files with a `[no run ID]` prefix. This can happen if we forget to use `wb_logging.log_to_run()` somewhere, or if a message really is not run-specific.
This only affects logging handlers added through …
> refactor: support per run logging

- CHANGELOG.unreleased.md
- requirements_dev.txt
- wandb/integration/metaflow/metaflow.py
Description
-----------
This PR fixes some tests that are failing due to a fastcore release ([v1.8.0](https://github.com/AnswerDotAI/fastcore/releases/tag/1.8.0)) which removes the `@typedispatch` annotation. [Migration guide](https://answerdotai.github.io/fasttransform/fastcore_migration_guide.html) suggests using plum-dispatch's `@dispatch` decorator as a replacement.
Testing
-------
> fix: test failures due to fastcore upgrade to 1.8.0

- wandb/sdk/wandb_settings.py
Don't repeat `f"{self.run_mode}-{self.timespec}-{self.run_id}"` in `wandb_settings.py`.
> refactor: do not repeat sync_dir computation

- CHANGELOG.unreleased.md
- tests/system_tests/test_core/test_public_api.py
- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-23206
This PR fixes a bug where the delete file API would fail due to 
`CommError: could not unmarshal "..." (string) into int32: incompatible type (Error 500: Internal Server Error)`
Due to the SDK passing an base64 encoded string of the project ID but the server expecting the integer version of the project id.
Testing
-------
- Test script 
```
import wandb
run = wandb.init(project="testDelete")
run_id = run.id
image = wandb.Image(np.random.rand(100, 100, 3))
run.log({"image": image})
run.finish()
run = api.run(f"testDelete/{run_id}")
print(run.entity)
for file in run.files():
print(file)
file.delete()
```
> fix: delete file API fails when passing internal project id

- core/internal/runconfig/runconfig.go
- tests/system_tests/test_core/test_resume.py
- wandb/sdk/internal/sender_config.py
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-15237
When resuming a run, the image mask is not carried over to the new run config. This causes the original image to lose any image masks which it had.
This change adds `masks/class_labels` config key as one of the keys which should be copied over during run resume.
Testing
-------
> fix: resuming a run would overwrite image masks

- core/internal/stream/stream.go
- core/pkg/monitor/gpu.go
- core/pkg/monitor/gpuresourcemanager.go
- core/pkg/monitor/monitor.go
- core/pkg/monitor/monitor_test.go
- core/pkg/server/connection.go
- core/pkg/server/server.go
Factors out a `monitor.GPUResourceManager` struct that manages the `gpu_stats` process and whose lifetime is tied to the server rather than a run.
When using `reinit="allow"` (added in #9562) only a single `gpu_stats` process is started up when multiple runs are active. The process is killed when no runs are active.
> refactor: share gpu_stats process between multiple runs

- pyproject.toml
Description
-----------
Drops the `python_version < '3.12'` constraint on `typing-extensions`, which doesn't seem to be necessary: `pydantic` has required `typing-extensions` since `v1.10` (or earlier) regardless of Python version.
Testing
-------
N/A
> chore(sdk): drop unused python version constraint for typing-extensions dependency

- tests/assets/notebooks/init_finishes_previous.ipynb
Adds a `time.sleep(1)` between initializing runs with `reinit="finish_previous"` to avoid issues caused by both runs getting assigned the same directory.
> refactor: work around bug in notebook test

- core/internal/sampler/reservoirsampler.go
The description of 'w' was slightly off. It's the maximum of the smallest k numbers sampled, not the maximum of all numbers sampled (since then it would approach 1 over time).
> chore: update comment in reservoir sampler

- tests/system_tests/test_notebooks/conftest.py
- tests/system_tests/test_notebooks/test_notebooks.py
Improves docs, removes code that doesn't do anything, reorganizes things to make more sense.
Strips ANSI escape sequences from cell execution errors when the output is not a TTY so that stack traces are readable in CI.
> refactor: clean up notebook test fixture

- CHANGELOG.unreleased.md
- wandb/apis/paginator.py
- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
- wandb/apis/public/files.py
- wandb/apis/public/projects.py
- wandb/apis/public/reports.py
- wandb/apis/public/runs.py
Description
-----------
- Fixes [WB-24075](https://wandb.atlassian.net/browse/WB-24075)
Refactors and adds type hints to `Paginator` base classes.
- Ensures `Paginator` formally implements the [`Iterator` protocol](https://docs.python.org/3.13/library/collections.abc.html#collections.abc.Iterator)
- Defines a separate `SizedPaginator` subclass for paginators that formally implement the [`Sized` protocol](https://docs.python.org/3.13/library/collections.abc.html#collections.abc.Sized) (i.e. by defining `__len__()`).
This allows common patterns like `list(paginator)` to work as expected on all wandb paginators, including those that haven't or can't implement `__len__()` -- e.g. for Integrations and Automations added in #9194 (upstack).
Testing
-------
[WB-24075]: …
> fix(sdk): ensure paginator base types conform to iterator/collection protocols

- tests/system_tests/test_artifacts/test_wandb_run_artifacts.py
- wandb/sdk/wandb_config.py
Removes `wandb.run` and `wandb.config` mentions from the `Config` documentation.
> chore: improve Config docs

- tests/system_tests/test_functional/console/test_console.py
Description
-----------
The backend now supports structured console log format, and the SDK will now send structured logs in this case by default, which broke a couple tests.
Testing
-------
> fix: console log test expecting legacy vs structured format

- .github/workflows/release-sdk.yml
Description
-----------
GH is deprecating the 20.04 images on 4/15/25 and is currently doing brown-outs.
> chore: update ubuntu to 22.04 in release sdk action

- wandb/sdk/wandb_run.py
Raise an error in `Run.use_model()` when running in offline mode. The check in `Artifact.download()` relies on `wandb.run` and this cannot easily be fixed, so it is better to make it the responsibility of callers.
> refactor: fail Run.use_model early when offline

- tests/system_tests/test_functional/asyncio_compat_run/pass_if_cancelled.py
- tests/system_tests/test_functional/asyncio_compat_run/test_asyncio_compat_run.py
- wandb/sdk/lib/asyncio_compat.py
Prints timestamps in the test for future debugging, and protects access to `_got_cancelled` with a lock to ensure it is synchronized.
The test [fails on rare occasion](https://app.circleci.com/pipelines/github/wandb/wandb/45473/workflows/f02fd269-1721-4922-931f-b199d06e2d1c/jobs/1363571/tests) with the message `FAIL: Interrupted but not cancelled`. Since the `__exit__` of the `ThreadPoolExecutor` used by `asyncio_compat.run` blocks until the future completes, there are only two ways this can happen:
1. The KeyboardInterrupt is really not received by the main thread and the asyncio task is not cancelled
2. The asyncio task is cancelled, but the main thread does not observe the new value of `_got_cancelled`
If the problem is (2), the lock will fix it. If the problem is (1), the timestamps …
> chore: attempt to fix test_asyncio_compat_run flake

- tests/unit_tests/test_lib/test_printer_asyncio.py
- wandb/sdk/data_types/video.py
- wandb/sdk/lib/printer_asyncio.py
- wandb/util.py
Description
-----------
- Fixes WB-5971
When creating a wandb.Video object with a numpy array of video frames it appears like the SDK is hanging. This is due to the fact that under the hood we are actually encoding the video and saving to a file. This PR adds a loading spinner while encoding the video to communicate that the SDK is encoding the video data.
- [] I updated CHANGELOG.unreleased.md, or it's not applicable
Testing
-------
- Sample script
```python
import wandb
fps = 10
video_length = 30  # seconds
video_length_frames = fps * video_length
frames = np.random.randint(0, 256, (video_length_frames, 3, 100, 100), dtype=np.uint8)
with wandb.init(mode="offline") as run: …
```
> chore: add loading animation while encoding video

- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
Improves run decorator types so that Pylance can correctly infer decorated method arguments and return values.
I'm not sure if it is a recent Pylance change, but annotating a decorator as returning a `Callable` (with no parameters) causes Pylance to treat a method's return type as `Any`. For example, VSCode fails to find the reference to `Artifact.download()` in `Run.use_model()` because of this!
This PR also removes the unnecessary `_run_decorator` wrapper class, renames decorators, adds documentation, and cleans up implementations. I also removed the `only_warn` parameter from `_raise_if_finished` (formerly `_noop_on_finish`), which was only used by `_console_raw_callback`. This is OK because `StreamRawWrapper` catches exceptions.
> refactor: improve run decorator types

- tests/system_tests/test_notebooks/test_notebooks.py
- wandb/jupyter.py
- wandb/sdk/wandb_init.py
Improves types in `jupyter.py` and the usage of `Notebook` in `wandb_init.py`. Since `wandb_init.py` is the only place where `Notebook` is used, it's safe to add a `run` parameter to `save_history` to avoid using the global run.
The silly `if TYPE_CHECKING: import wandb.jupyter` in `wandb_init.py` is needed because of our terrible lazy-loading system. Importing it directly causes `test_notebooks.py` to fail because monkeypatching stops working (even though `test_notebooks.py` never uses the functionality in `wandb_init.py`). The entire problem can be solved by removing the `jupyter = _lazyloader.LazyLoader(...)` line from `wandb/__init__.py`, but that would be a breaking change.
> refactor: improve types and docs in jupyter.py

- CHANGELOG.unreleased.md
- tests/unit_tests/test_util.py
- tests/unit_tests/test_wandb_settings.py
- wandb/sdk/wandb_settings.py
- wandb/util.py
Description
-----------
- Fixes: #9676 
When running a W&B script on Windows from a different drive than the drive the script is located on will cause a ValueError when attempting to determine the relative [path of the program](https://github.com/wandb/wandb/blob/main/wandb/sdk/wandb_settings.py#L1669)
This change checks the drives for both the root directory and the program file location to determine if they both exist on the same drive.
Testing
-------
> fix: windows throws ValueError when running from a different drive.

- CHANGELOG.unreleased.md
> chore: remove Go upgrade mention from changelog

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_wandb_artifacts_api.py
- wandb/sdk/artifacts/artifact.py
Removes the `util._is_offline()` check in `Artifact.download()` which relies on a global `wandb.run`.
This check was originally added in PR #8009 because of a crash in wandb-core, but the crash no longer happens.
The repro in the PR that added the check can be used:
```python
import os
import wandb
os.environ["WANDB_MODE"] = "offline"
os.environ["WANDB_DEBUG"] = "true"
def download_artifact(artifact_name: str):
artifact = wandb.Api().artifact(artifact_name)
return artifact.download(root="/tmp/wandb_artifacts")
if __name__ == "__main__":
run_path = "wandb/timoffex-test/r0sczcuf"
project = "timoffex-test"
artifact_name = "wandb/timoffex-test/trained-model:v2"
with wandb.init(project=project) as run:
run.restore(name="output.log", replace=True, run_path=run_path)
artifact_path = …
```
> refactor: do not raise in Artifact.download() if an offline run exists

- CHANGELOG.unreleased.md
- tests/system_tests/test_notebooks/conftest.py
- tests/system_tests/test_notebooks/test_notebooks.py
- wandb/jupyter.py
- wandb/sdk/wandb_run.py
Drops the `wandb.jupyter.quiet()` method and the `-q`/`--quiet` option to the `wandb` magic. The only use of this method was in `wandb_run.py` right below a TODO about using settings instead.
This is technically a breaking change, but the option does not appear to have ever been documented anywhere, and "broken" notebooks are trivial to fix.
> refactor: use settings.quiet instead of wandb.jupyter.quiet()

- tests/unit_tests/test_api_utils.py
- wandb/apis/public/utils.py
Adds a new `gql_compat()` helper function (in `wandb.apis.public.utils`) that allows GraphQL queries to be rewritten for compatibility with older server versions. The function optionally scrubs any of the following items from a GQL query or mutation:
- variables (by name)
- fragment definitions and spreads (by name)
- selected response fields (by name)
Added `test_gql_compat()` unit test
> chore(sdk): add helper to rewrite graphql requests for compatibility

- wandb/sdk/data_types/image.py
- wandb/sdk/data_types/utils.py
Instead of using `util._is_offline()`, which relies on a global `wandb.run`, check the available `run` object directly.
> refactor: do not use util._is_offline() in data_types/image.py

- wandb/sdk/wandb_run.py
- wandb/util.py
PR #9653 improved the type annotations on run method decorators, but used `...` as the parameter type for all `Callable` values which made Pylance and MyPy unable to infer the argument types for Run methods. This PR fixes that by completing the type annotations.
> refactor: further improve run decorator types

- CHANGELOG.unreleased.md
- wandb/sdk/wandb_init.py
Description
-----------
- Fixes #NNNN
This PR passes the user provided host/base_url to `wandb.login` to ensure the correct host is logged in.
Testing
-------
- Before this change
```
python
﻿﻿>>> import wandb
>>> wandb.init(settings=wandb.Settings(base_url="https://staging-aws.wandb.io"))
﻿wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:
```
- After this change
```
python
>>> wandb.init(settings=wandb.Settings(base_url="https://staging-aws.wandb.io"))
wandb: Using …
```
> fix: user provided base_url was not provided to wandb.login

- tests/unit_tests/test_automations/_strategies.py
- tests/unit_tests/test_automations/conftest.py
- tests/unit_tests/test_automations/test_actions.py
- tests/unit_tests/test_automations/test_automations.py
- tests/unit_tests/test_automations/test_events.py
- tests/unit_tests/test_automations/test_scopes.py
- wandb/_pydantic/__init__.py
- wandb/_pydantic/base.py
- wandb/_pydantic/utils.py
- wandb/_pydantic/v1_compat.py
- wandb/automations/__init__.py
- wandb/automations/_filters/__init__.py
- wandb/automations/_filters/expressions.py
- wandb/automations/_filters/operators.py
- wandb/automations/_filters/run_metrics.py
- wandb/automations/_utils.py
- wandb/automations/_validators.py
- wandb/automations/actions.py
- wandb/automations/automations.py
- wandb/automations/events.py
- wandb/automations/integrations.py
- wandb/automations/scopes.py
Description
-----------
- Fixes [WB-22035](https://wandb.atlassian.net/browse/WB-22035)
- Docs: [DOCS-1164](https://wandb.atlassian.net/browse/DOCS-1164)
Defines the initial `wandb.automations` subpackage<strike>, including generated code enabled by changes in #8901</strike> (EDIT: see #9693 now for generated code).
In particular, this includes both public (importable) types and private (internal) helpers for parsing, processing, and serializing:
- automations
- scopes
- events
- actions
- related integrations (ie slack/webhook)
- <strike>filters (conforming to the MongoDB query format/spec already used elsewhere in this API -- e.g. `{"$and": [{"display_name": "my-run"}, ...], ...}` etc)</strike> (handled in #9311)
Adds initial unit tests, albeit heavily mocked, for the above.
- Adds:
- …
> feat(sdk): public `wandb.automations` submodules

- tests/system_tests/test_core/test_resume.py
- wandb/sdk/interface/interface.py
- wandb/sdk/wandb_run.py
Description
-----------
This PR correctly adds the initial run time for resumed runs, before this change we wouldn't return the correct runtime for resumed run and would always reset the runtime.
Testing
-------
added system test to verify that the correct runtime is added to the run initialization
> fix: propagate correct starting runtime when resuming

- wandb/apis/public/api.py
- wandb/apis/public/integrations.py
Description
-----------
- Fixes [WB-22611](https://wandb.atlassian.net/browse/WB-22611)
- Docs: [DOCS-1164](https://wandb.atlassian.net/browse/DOCS-1164)
Adds methods to fetch existing Slack and GenericWebhook integrations from instances of `wandb.Api`.  Among other things, this will be needed to programmatically define new Automations
Testing
-------
[WB-22611]: https://wandb.atlassian.net/browse/WB-22611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1164]: https://wandb.atlassian.net/browse/DOCS-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sdk): add methods to fetch integrations from wandb.Api

- wandb/old/summary.py
Removes `wandb.run` usage in `wandb/old/summary.py`.
This checked the `_jupyter_agent` property, which I think no longer exists. This code would likely have crashed with an AttributeError before. It is possible this is dead code.
> refactor: no global run in old summary

- wandb/sdk/verify/verify.py
Replaces `wandb.save()` by `run.save()` in two spots.
> refactor: don't use global run in wandb verify

- wandb/sdk/lib/redirect.py
- wandb/sdk/wandb_run.py
Instead of checking whether `wandb.run` is online, pass that information through the initializer.
> refactor: don't use global run in redirect.py

- wandb/sdk/lib/printer_asyncio.py
* Updated docstring as `func` is not "async", just slow
* Removed unnecessary usage of `functools` to pass parameters to `_loop_run_with_spinner` that it can already access
> refactor: small code improvements in printer_asyncio.py

- pyproject.toml
- tests/assets/notebooks/magic.ipynb
- tests/system_tests/test_notebooks/test_notebooks.py
- wandb/jupyter.py
- wandb/sdk/wandb_run.py
Refactors the wandb IPython magic (`%%wandb` / `%wandb`) to avoid using the global run when displaying a run as part of `wandb.init()`.
The old `maybe_display()` function was only called when printing the Run header when initializing a run, but it used `wandb.run` to decide what to display. Now it accepts a run explicitly.
`wandb.run` is still used when running the `%wandb` magic on its own, like
```python
%wandb -h 600
```
On the other hand, this uses the explicit run and will continue to work when `wandb.run` is removed:
```python
%%wandb -h 600
with wandb.init() as run:
...
```
> refactor: avoid global run in wandb ipython magic

- tests/unit_tests/test_lib/test_printer.py
- tests/unit_tests/test_lib/test_printer_asyncio.py
- wandb/sdk/data_types/video.py
- wandb/sdk/lib/printer.py
- wandb/sdk/lib/printer_asyncio.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
Instead of checking whether `wandb.run` has `silent` set to True in its settings, use the global settings. This matches the behavior for terminal output which relies on `termsetup()` whose `_silent` parameter can only come from an explicit `silent` setting passed to `wandb.setup()`.
> refactor: don't use global run in printer.py

- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
- wandb/integration/keras/keras.py
- wandb/integration/langchain/wandb_tracer.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_manifest_entry.py
- wandb/sdk/lib/deprecate.py
- wandb/sdk/lib/disabled.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
* Improves wording in the docstring
* Updates all calls to `deprecate` to pass an explicit run if it's available
* The only places it's available and not passed were in `wandb_run.py`
* After `reinit="create_new"` is merged, we can update the fallback to rely on the most recent active run rather than `wandb.run`
* Removes check for unknown field names, as it adds unnecessary complexity and `setattr` would throw anyway
* I considered catching this and printing a warning, but type checking should catch this case anyway
* Removes `__all__` because `from deprecate import *` is not used anywhere in the codebase
* Removes `Deprecated` export and updates all imports to get it directly from `wandb.proto.wandb_deprecated`
> refactor: clean up deprecate.py

- requirements_test.txt
- tests/unit_tests/test_data_types_box3d.py
Description
-----------
Stopgap fix to prevent `sys.modules`-related `RuntimeError`, which appears to have been inadvertently introduced on/after `hypothesis==6.131.1`.
In detail, this manifests in CI as `RuntimeError`s like:
```python
.0 = <dict_valueiterator object at ...>
return tuple(
module
>       for module in sys.modules.values()
if (
getattr(module, "__file__", None) is not None
and _is_local_module_file(module.__file__)
)
)
E   RuntimeError: dictionary changed size during iteration
.../site-packages/hypothesis/internal/constants_ast.py:147: RuntimeError
```
Testing
-------
> fix: pin hypothesis version (stopgap fix for failing hypothesis unit tests)

- wandb/sdk/service/service.py
Fixes WB-24478.
Instead of printing a message when the user is on `wandb-core`, which has been the norm for a long time now, print a warning on init when the user is on `legacy-service`.
The new warning is in addition to the warning printed at the end of each `legacy-service` run. Having it at the start can help users (realistically, only developers) notice if they're accidentally using `legacy-service`.
To test:
* `python -c 'import wandb; wandb.init()'`
* `WANDB_X_REQUIRE_LEGACY_SERVICE=true python -c 'import wandb; wandb.init()'`
> refactor: remove wandb-core message from wandb.init()

- wandb/sdk/service/server_sock.py
- wandb/sdk/service/streams.py
- wandb/sdk/wandb_run.py
Don't send telemetry, such as deprecation telemetry, after a run is finished. The service process does not expect records for a run after it is complete.
The following snippet was failing in `legacy-service`:
```python
import wandb
run.finish()
run.mode  # This causes legacy-service to crash.
```
I also updated `legacy-service` to avoid crashes like this in the future.
> fix: don't send telemetry after a run is finished

- BREAKING.md
- CHANGELOG.unreleased.md
- tests/unit_tests/test_data_types.py
- wandb/sdk/data_types/html.py
Description
-----------
- Fixes WB-24403
- Fixes #9648
This change updates the documentation for the `html.py` media object to more clearly specify that an HTML data type can be initialized with a path to a file, and will use the files contents first if such a file exists.
Additionally there was a bug which the SDK would attempt to open and read a directory if a valid path was provided on creation on an HTML datatype (see testing below).
Testing
-------
- Unit tests added
- Test script
```python
import wandb
with wandb.init(project="htmltest") as run:
run.log({"html": wandb.Html(".")})
```
```
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more …
```
> fix: html media object raises IsADirectoryError

- CHANGELOG.unreleased.md
- tests/system_tests/test_core/test_wandb_run.py
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-21466
The frontend for W&B checks for the key `code_path` in the run config to determine if the `code` sidebar tab should be displayed. The SDK only sets the `code_path` key in the config if the user sets `wandb.init(save_code=True)`. But will not set this if a user explicitly logs their code via the `run.log_code` function.
This PR updates the config to include the code path when a user calls `run.log_code`.
This change aligns with the way the frontend determins which code to display in the `code` tab as well, which will look for the last artifact with the type `code`.
Testing
-------
- system tests added
- test script
```python
import os
import wandb …
```
> fix: log_code function would not properly set the config code path

- requirements_test.txt
Description
-----------
- Fixes [WB-24525](https://wandb.atlassian.net/browse/WB-24525)
`hypothesis` released v6.131.3 yesterday, which fixes the (race condition) issue described in #9737 and which was previously causing unit tests to fail in CI.
This PR updates the version constraint accordingly.
Testing
-------
[WB-24525]: https://wandb.atlassian.net/browse/WB-24525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update hypothesis version constraint after fix release

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
- tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/apis/public/artifacts.py
- wandb/sdk/artifacts/_validators.py
- wandb/sdk/artifacts/artifact.py
Description
-----------
- [WB-21718](https://wandb.atlassian.net/browse/WB-21718)
Validates `Artifact` names on instantiation, raising a `ValueError` if the name is expected to be invalid (i.e. the artifact cannot be logged).
Testing
-------
[WB-21718]: https://wandb.atlassian.net/browse/WB-21718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): raise for invalid artifact names

- .circleci/config.yml
Description
-----------
- Fixes #NNNN
Copy from https://github.com/wandb/weave/pull/4349 uv 0.70 changed the version command and it is breaking nox's backend detection logic https://github.com/wntrblm/nox/issues/953
Testing
-------
Let Circle CI run and see if it passes ...
> chore: pin uv to fix CI

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_wandb_artifacts_api.py
- tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_file_cache.py
- wandb/sdk/artifacts/artifact_manifest_entry.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/artifacts/storage_policy.py
Description
-----------
- Fixes WB-24073
The existing download logic in Python (and in the temporarily disabled Go core) uses a **single HTTP request** to download objects from the object store (e.g., GCS, S3), regardless of file size.
However, for large files, it is more efficient to use **multiple HTTP range requests in parallel**, as recommended in [AWS S3 performance guideline](https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance-guidelines.html#optimizing-performance-guidelines-get-range) and [GCS sliced object download](https://cloud.google.com/storage/docs/sliced-object-downloads)
Other tools and SDKs—such as [`s3transfer`](https://github.com/boto/s3transfer) and `gcloud storage cp` already implemented this optimization by default for large object downloads. …
> feat(artifacts): add multipart download to download large file in parallel

- tests/unit_tests/test_artifacts/test_wandb_artifacts.py
Description
-----------
- Fixes WB-24215
The test was assuming network requests get cancelled when there is disk error. However, if the threads run fast enough, the network request can still trigger and fail the test because the actual requests is same as max requests.
Example failure on windows CI https://app.circleci.com/pipelines/github/wandb/wandb/47053/workflows/90295498-3bce-47a3-bef0-0b8c236da747/jobs/1389132
Testing
-------
Run on CI, it should pass.
> chore(artifacts): fix flaky test for disk error

- CHANGELOG.unreleased.md
- tests/system_tests/test_automations/test_automations_api.py
- wandb/apis/public/api.py
Description
-----------
- Fixes [WB-21902](https://wandb.atlassian.net/browse/WB-21902)
- Docs: [DOCS-1164](https://wandb.atlassian.net/browse/DOCS-1164)
Adds `wandb.Api` support for updating **existing** automations.
Testing
-------
[WB-21902]: https://wandb.atlassian.net/browse/WB-21902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-1164]: https://wandb.atlassian.net/browse/DOCS-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sdk): add methods to edit automations

- core/internal/runbranch/fork.go
- core/internal/runbranch/fork_test.go
- core/internal/runbranch/resume.go
- core/internal/runbranch/resume_test.go
- core/internal/runbranch/rewind.go
- core/internal/runbranch/rewind_test.go
- core/internal/runbranch/state.go
- core/internal/runbranch/state_test.go
- core/internal/stream/sender.go
Cleans up `internal/runbranch` in wandb-core to prepare for an UpsertBucket-related refactor:
* Simplified `RunParams` and organized it for better readability
* Changed fork/rewind/resume.go to modify the `RunParams` in-place instead of returning updates that are then merged
* Instead of accepting `RunParams` and `RunPath`, fork/rewind/resume.go read the entity/project/run ID from `RunParams`. The `RunPath` parameter was always derived from `RunParams` in `Sender`.
* Removed the `Config` field of `RunParams` and made rewind/resume.go accept and mutate a `RunConfig` directly
In the `Sender`, `startState` now starts out as `nil` and becomes set when processing the first `RunRecord` (if an error occurs, it is set back to `nil`).
`Sender` no longer clones the `RunRecord` at the start of …
> refactor: rewrite RunParams and clean up fork/rewind/resume.go

- core/internal/stream/sender.go
- core/pkg/launch/job_builder.go
- core/pkg/launch/job_builder_test.go
- core/pkg/launch/wandb_config.go
Removes the SetRunConfig method on JobBuilder, replacing it by an explicit parameter to Build instead.
> refactor: run config usage in job_builder.go

- core/internal/settings/settings.go
- core/internal/stream/stream.go
Description
-----------
- Fixes #9807
In implicit finish mode we use wandb-core to print the footer, in that case we weren't respecting the silent setting.
This PR adds a check for silent mode to make sure to respect the silent setting.
Testing
-------
> fix: avoid outputting footer in silent mode

- core/internal/gqlmock/assert.go
- core/internal/gqlmock/gqlmock.go
- core/internal/gqlmock/gqlmock_test.go
- core/internal/gqlmock/matchers.go
- core/internal/gqlmock/prettyprint.go
- core/internal/stream/sender_test.go
- core/pkg/artifacts/saver_test.go
Makes internal/gqlmock error messages nicer, replaces `AssertRequest` by `AssertVariables` to remove a bit of indentation, and adds the `JSONEq` matcher that corresponds to the `assert.JSONEq()` statement.
The `JSONEq` matcher is used in a later PR, but added here to reduce noise in that PR.
> refactor: improve gqlmock error messages

- CHANGELOG.unreleased.md
- tests/system_tests/test_core/test_public_api.py
- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-23845
- Fixes https://github.com/wandb/wandb/issues/9588
Recently the ability to include the `projectId` while calling `File.delete()`, to improve performance. However, `projectId` was not being queried when the user would query multiple runs at once with `api.runs(...)`
Testing
-------
- System tests added
- Test script
```python
import wandb
runs = api.runs("jacobromero/sometestproject")
for run in runs:
for file in run.files:
if file.name == "output.log":
file.delete()
print("file deleted.")
```
```
file deleted.
```
```
File "/Users/jacob.romero/workspace/test/api.py", line 15, in <module>
file.delete() …
```
> fix: object has no attribute when deleting file for a run

- core/internal/runmetadata/runmetadata.go
- core/internal/runmetadata/runupdateerror.go
- core/internal/runmetadata/runupdatework.go
Creates `internal/runmetadata` and fills it out with unimplemented methods to serve as an easy-to-review base for later PRs that implement it in parts.
`RunMetadata` will contain the majority of the implementation.
`RunUpdateWork` is the glue that makes `Handler` and `Sender` interact with `RunMetadata`. The `RunMetadata` object will live on a `Stream`, and `Stream` will turn `RunRecord` into `RunUpdateWork`. Its `Accept()` method returns `true`, corresponding to `Handler` unconditionally forwarding the record; `Process()` is the `Sender` portion. `BypassOfflineMode()` returns true corresponding to `Handler` setting `AlwaysSend` on the `RunRecord`.
> refactor: create internal/runmetadata

- tests/conftest.py
- tests/unit_tests/test_internal_api.py
- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
- wandb/apis/public/registries/registry.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/internal/internal_api.py
Description
-----------
- Fixes [WB-24861](https://wandb.atlassian.net/browse/WB-24861)
Follow-up change to address previous comment from #8896: https://github.com/wandb/wandb/pull/8896#discussion_r2069636870
Renames redundant `InternalApi._check_server_feature_with_fallback()` method.  Refactors affected code accordingly.
Testing
-------
N/A - relies on existing unit/system tests that check server feature flag-related behavior.
[WB-24861]: https://wandb.atlassian.net/browse/WB-24861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: rename/refactor use of `InternalApi._check_server_feature_with_fallback()`

- noxfile.py
Description
-----------
Adds `tests/unit_tests/test_artifacts` to the list of test paths for Pydantic v1 compatibility testing.
Pydantic, while useful, can introduce unexpected/unforeseen side effects -- moreso since we currently aim to support both pydantic v1 and v2 in most parts of the SDK.
This change adds a partial -- but still useful -- extra safeguard against inadvertently breaking Pydantic v1 compatibility in artifacts-related code paths.
Testing
-------
Verified that the unit tests for artifacts are now included -- and passing -- in the `unit_tests_pydantic_v1` nox sessions.
> chore: add artifacts to pydantic v1 unit tests

- core/internal/runmetadata/runmetadata.go
- core/internal/runmetadata/runmetadata_test.go
Implements the `UpsertBucket` request in `internal/runmetadata`, except for portions related to the run config which are added in a separate PR.
The key method is `lockedDoUpsert` which is called when initializing a run or flushing changes to its parameters (notes, tags, etc.) or config.
To allow testing, this removes a few `panic()` statements and replaces them with TODO comments.
> refactor: runmetadata UpsertBucket

- core/internal/runmetadata/runmetadata.go
- core/internal/runmetadata/runmetadata_test.go
Implements run config handling in `internal/runmetadata`.
> refactor: runmetadata config

- tests/system_tests/test_launch/test_launch_sweep_cli.py
Description
-----------
- Fixes #NNNN
In Python3.12 when there are no required arguments, but also `no_args_is_help` for a  Click CLI command, the command returns with an exit code of 2 instead of 0 (as in python3.8). This was causing the test to fail in 3.12.
Testing
-------
> chore(launch): handle non-zero exit code when no args passed for wandb launch-sweep test

- noxfile.py
- pyproject.toml
Description
-----------
code-check ci is failing because `pkg_resources` has been removed from the installation of `setuptools`. Starting in [setuptools v80.7.0](https://setuptools.pypa.io/en/stable/history.html#v80-7-0). 
`pkg_resources` is deprecated and should be moved to the various other files recommended [here](https://setuptools.pypa.io/en/latest/pkg_resources.html). For now we can pin the version and will work on migrating `pkg_resources` ([jira](https://wandb.atlassian.net/browse/WB-25032))
Testing
-------
> chore: fix mypy failures due to missing pkg_resources

- CHANGELOG.unreleased.md
- tests/unit_tests/test_data_types.py
- wandb/sdk/data_types/image.py
Description
-----------
- Fixes WB-15801
- Fixes #6287, #7377
When normalizing image values, during the creation of a `wandb.Image` from data (numpy array, or pytorch tensor) there are inconsistencies in the output image. 
For some small values normalized and converted image will be entirely black, or for small negative values the image will be entirely white. Additionally, between passing in a numpy array or a pytorch tensor would also yield different image results.
This PR uses the same normalization between the image data passed into the `wandb.Image` initialization function. As well as adds a flag to allow a user to normalize image data, since this can affect the output results of the image which might be …
> fix: inconsistent image normalization for wandb.Image

- CHANGELOG.unreleased.md
- wandb/sdk/lib/service_connection.py
- wandb/sdk/wandb_setup.py
Fixes a bug that prevented calling `wandb.teardown()` in a child of a process that called `wandb.setup()`.
Calling `wandb.setup()` is OK in a child process and doesn't start wandb-core, so `wandb.teardown()` should also be OK and not tear down wandb-core.
> fix: allow wandb.teardown() in child processes

- core/internal/paths/longestcommonprefix.go
- core/internal/paths/longestcommonprefix_test.go
- core/internal/paths/paths.go
- core/internal/paths/paths_notwindows_test.go
Adds two new functions to `paths` and adds some missing unit tests.
The functions are used in later PRs: `LongestCommonPrefixStr` is the core logic of `LongestCommonPrefix` but not necessarily requiring a real system path, which is used when comparing cloud URLs in `internal/tensorboard`.
`paths.Join` is natural to have here, but I didn't add it before because it wasn't needed.
> refactor: paths.LongestCommonPrefixStr and paths.Join, tests

- wandb/sdk/wandb_run.py
Without this, MyPy cannot infer the type of `run.summary` (but Pylance can because of the assignment in `_init()`). There are probably other similar cases; this just came up in https://app.graphite.dev/github/pr/wandb/wandb/9834/chore(sdk)-handle-resumed-runs-when-logging-tables-incrementally#comment-PRRC_kwDOBSC9Os59Ex_G.
> refactor: annotate `wandb.Run.summary` field

- pyproject.toml
- tests/system_tests/backend_fixtures.py
- tests/system_tests/test_notebooks/conftest.py
- tests/system_tests/wandb_backend_spy/gql_match.py
- wandb/sdk/internal/run.py
- wandb/sdk/internal/system/assets/aggregators.py
- wandb/sdk/lib/fsm.py
- wandb/sdk/lib/printer.py
- wandb/sdk/mailbox/mailbox_handle.py
- wandb/sdk/mailbox/response_handle.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
- wandb/util.py
Instead of checking the Python version and importing either from `typing` or `typing_extensions`, always prefer to import from `typing_extensions`. Only import from `typing` if Ruff complains about [deprecated imports](https://docs.astral.sh/ruff/rules/deprecated-import/) (some symbols, like Dict, List and Union).
I only updated files that have a conditional import. There are many other files where we import from `typing` where we could import from `typing_extensions`, but updating them manually just for the sake of consistency doesn't seem worth it.
> refactor: unconditionally import from typing_extensions

- tests/unit_tests/test_cli.py
Description
-----------
This PR fixes consistent test failures related to `wand docker` cli tests. This was caused by an update with our dependency `click` in version `v8.2.1`, which changed the behavior with how the `CliRunner` is handling input when there is a prompt but no more input provided. (see click [issue here](https://github.com/pallets/click/pull/2934), and the [fix here](https://github.com/pallets/click/pull/2934))
Testing
-------
- running unit tests for `tests/unit_tests/test_cli.py`
> chore: fix failing unit tests due to click dependency update

- requirements_dev.txt
Constrains `moviepy` to versions compatible with `1.0` so that `tensorboardX` and `torch`'s versions of `SummaryWriter.add_video()` work. These seem to be vendored, so they use similar code that relies on importing `moviepy.editor`.
> chore: add moviepy CI constraint to fix functional test

- pyproject.toml
Slightly reorganizes and updates comments in the `ruff` parts of `pyproject.toml`.
> chore: clean up ruff sections in pyproject.toml

- core/internal/runupserter/runupdateerror.go
- core/internal/runupserter/runupdatework.go
- core/internal/runupserter/runupserter.go
- core/internal/runupserter/runupserter_test.go
Renames `runmetadata` to `runupserter`, `RunMetadata` to `RunUpserter` and the variable name `metadata` to `upserter`. Did search-and-replace by hand to avoid false positives.
> refactor: rename runmetadata to runupserter

- landfill/standalone_tests/all_media_types.py
- noxfile.py
- pyproject.toml
- tests/unit_tests/test_launch/test_project/test_project.py
- wandb/apis/public/api.py
- wandb/integration/gym/__init__.py
- wandb/integration/keras/callbacks/model_checkpoint.py
- wandb/integration/keras/keras.py
- wandb/integration/kfp/kfp_patch.py
- wandb/integration/openai/fine_tuning.py
- wandb/sdk/data_types/base_types/wb_value.py
- wandb/sdk/data_types/image.py
- wandb/sdk/data_types/video.py
- wandb/sdk/internal/profiler.py
- wandb/sdk/internal/sender.py
- wandb/sdk/launch/_project_spec.py
- wandb/sdk/verify/verify.py
- wandb/util.py
Description
-----------
- Fixes WB-25032
This PR removes the dependency on `pkg_resources`.
`pkg_resources` is deprecated and should be moved to the various other files recommended [here](https://setuptools.pypa.io/en/latest/pkg_resources.html). 
Specifically most of our code relied on using version parsing, which has moved to the `packaging` package.
The bulk of this change is removing the `wandb.util::parse_version` wrapper used in many places, and replacing with `packaging.version::parse`
Testing
-------
> chore: remove pkg_resources dependency, add packaging dependency

- CHANGELOG.unreleased.md
- pyproject.toml
- tools/inspect_tool.py
- wandb/agents/pyagent.py
- wandb/apis/importers/internals/util.py
- wandb/apis/importers/wandb.py
- wandb/apis/normalize.py
- wandb/apis/public/api.py
- wandb/cli/cli.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/data_types/base_types/media.py
- wandb/sdk/data_types/table.py
- wandb/sdk/internal/file_stream.py
- wandb/sdk/internal/internal_api.py
- wandb/sdk/internal/tb_watcher.py
- wandb/sdk/launch/builder/kaniko_builder.py
- wandb/sdk/launch/sweeps/scheduler.py
- wandb/sdk/launch/utils.py
- wandb/sdk/service/streams.py
- wandb/sync/sync.py
https://docs.astral.sh/ruff/rules/verbose-raise/. Instead of
```python
except Exception as e:
raise e
```
do
```python
except Exception:
raise
```
The fix was applied automatically, but it is marked unsafe because it sometimes doesn't work well with shadowed error variables. I manually checked all changes---we don't do this type of shadowing anywhere.
> refactor: enable and fix TRY201 (verbose-raise)

- pyproject.toml
- tools/perf/scripts/process_sar_helper.py
- wandb/apis/importers/validation.py
- wandb/apis/importers/wandb.py
- wandb/cli/cli.py
- wandb/docker/__init__.py
- wandb/sdk/internal/file_stream.py
- wandb/sdk/internal/handler.py
- wandb/sdk/internal/internal_api.py
- wandb/sdk/internal/sender.py
- wandb/sdk/internal/system/assets/gpu.py
- wandb/sdk/internal/system/assets/interfaces.py
- wandb/sdk/internal/system/assets/trainium.py
- wandb/sdk/internal/system/system_info.py
- wandb/sdk/internal/system/system_monitor.py
- wandb/sdk/launch/agent/job_status_tracker.py
- wandb/sdk/lib/gitlib.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_run.py
https://docs.astral.sh/ruff/rules/error-instead-of-exception/
All fixes are manual because in most cases I had to remove redundant string-interpolation of the error. In a few spots, `logger.exception()` would have been called multiple times in a row, so I condensed those into a single `logger.exception()` call. Also, in `internal_api.py`, I simplified some `logger.exception()` calls to not parse the underlying error; I am assuming all the needed info will appear in log files when the exception is formatted.
I think some of the stranger `logger.error()` invocations came from a time when we didn't consistently set up the `wandb` logger, causing their messages to sometimes get printed to the user's console. That's probably why `cli.py` had statements like `logger.error("=== %s ===", e)`.
> refactor: enable and fix TRY400 (logger.exception() instead of logger.error())

- hatch_build.py
- wandb/apis/attrs.py
- wandb/apis/public/api.py
https://docs.astral.sh/ruff/rules/try-consider-else/
This one takes some manual work to really fix, and I don't enable this lint in this PR because its suggestion can be a little misleading. For instance, it will produce a diagnostic on this:
```python
try:
result = computation()
return result
except SomeError:
return other
```
The lint message will make it seem that the solution is this:
```python
try:
result = computation()
except SomeError:
return other
else:
return result
```
But an even better solution is
```python
try:
return computation()
except SomeError:
return other
```
In many cases in our codebase, the right fix is to narrow the scope of the `try-except` rather than to use `try-except-else`. It also sometimes makes sense to not use an `else` block at all, especially when the …
> refactor: fix a few instances of TRY300

- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-24994
Allows setting the state of a run in Run.create(). The server returns an error if it's not a valid state
Code to test:
````
import wandb
from wandb.apis.public import Run
import itertools, uuid, requests, json
entity  = "luis-bergua-weights-biases"
project = "test_create_run_api"
states = ["running", "pending", "finished", "failed", "crashed", "killed", "preempted", "preempting", "invalid_state"]
for s in states:
run_name = f"state-test-{s}-{uuid.uuid4().hex[:8]}"
try:
run = Run.create(api=api, project=project, entity=entity, state=s, run_id=run_name)
print(f"{run_name:30} -> create() returned state = {run.state}")
run.load(force=True)
print(f"{'':30}    after …
```
> feat(sdk): allow setting run state in Run.create()

- core/internal/stream/handler.go
- core/internal/stream/sender.go
- core/internal/stream/sender_test.go
- core/internal/stream/stream.go
- core/internal/stream/streamrun.go
- tests/system_tests/test_core/test_wandb_init.py
Replaces all old UpsertBucket code with `internal/runupserter`.
`RunUpserter` lives on a `Stream` and is operated on by `RunUpdateWork` in the sender goroutine. `Handler` and `Sender` no longer receive `RunRecord` and the corresponding code has been removed---when we implement syncing in wandb-core, we will create `RunUpdateWork` from `RunRecord` values the same way it happens in the `Stream` in this PR.
Unlike the old code in `Sender`, `RunUpserter` can batch updates to run parameters (such as its notes and tags) with updates to the run config in a single upload. Also, the updates happen asynchronously and do not block the `Sender` from doing other work.
> refactor: use runupserter, delete old Sender code

- tests/unit_tests/test_cli.py
- wandb/cli/cli.py
- wandb/docker/__init__.py
- wandb/sdk/launch/builder/build.py
- wandb/sdk/launch/runner/abstract.py
The `find_executable()` in `dockerpycreds` used to wrap `distutils.spawn.find_executable()` to additionally handle `PATH_EXT` on Windows, which is why we used it according to comments in the code. The replacement suggested by [PEP 0632](https://peps.python.org/pep-0632/#migration-advice) is `shutil.which()` which appears to have logic using `PATH_EXT` (at least in Python 3.10).
> refactor: use `shutil.which()` instead of find_executable() from dockerpycreds

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- tests/system_tests/test_automations/test_automations_api.py
- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes #NNNN
- Adds the `@normalize_exceptions` decorator to some automations and artifacts api methods so that server errors are printed when errors are raised
- Doesn't query for the linked version upon encountering an error from the server
Testing
-------
> chore(artifacts): show error messages from server in artifacts and automations api

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_data_types.py
- wandb/sdk/artifacts/_internal_artifact.py
- wandb/sdk/data_types/utils.py
- wandb/sdk/internal/incremental_table_util.py
Description
-----------
- Fixes [WB-25173](https://wandb.atlassian.net/browse/WB-25173), [WB-25176](https://wandb.atlassian.net/browse/WB-25176)
Ensures all instances of `InternalArtifact` have their names sanitized on instantiation.
Sanitized names are suffixed with an alphanumeric hash of the original name in order to maintain uniqueness / avoid collisions.
Testing
-------
[WB-25173]: https://wandb.atlassian.net/browse/WB-25173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WB-25176]: https://wandb.atlassian.net/browse/WB-25176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(artifacts): sanitize names of all internal artifacts

- core/internal/filestream/updatesummary.go
- core/internal/stream/sender.go
Instead of converting a `RunSummary` to a list of records, then rebuilding it from the records and converting it to JSON, just convert it to JSON.
> refactor: remove unnecessary summary encoding/decoding in filestream

- .github/workflows/release-sdk.yml
Description
-----------
See https://github.com/actions/runner-images/issues/12045
> chore: update windows runner to 2022 in release action

- core/internal/stream/stream.go
I recently saw a complete `debug-core.log` paired with a `debug-internal.log` file that is cut off in the middle of a JSON line near the end.
I don't know for sure why this can happen. I've read that Go's files are unbuffered, so there's probably some OS buffer that's not getting flushed. Calling `File.Sync()` invokes [fsync](https://linux.die.net/man/2/fsync) which sounds like it should solve this issue.
> fix: wait to finish writing to debug-internal.log

- core/pkg/launch/job_builder.go
- core/pkg/launch/job_builder_test.go
- wandb/apis/public/jobs.py
- wandb/cli/cli.py
- wandb/sdk/internal/job_builder.py
- wandb/sdk/launch/_launch.py
- wandb/sdk/launch/_project_spec.py
- wandb/sdk/launch/agent/agent.py
- wandb/sdk/launch/create_job.py
https://linear.app/wandb/issue/ENG-15/separate-handling-of-evals-and-vllm-api-jobs
Description
-----------
- Fixes #NNNN
Testing
-------
> feat: add flag to include inference server on job create via wandb launch

- CHANGELOG.unreleased.md
Description
-----------
I had to put the service and core options of wandb.require back in in #9965 for backwards compat, but didn't update the changelog.
> chore: fix error in unreleased changelog

- CHANGELOG.unreleased.md
- tests/unit_tests/test_data_types.py
- wandb/sdk/data_types/image.py
For comparison, the original code is [here](https://github.com/wandb/wandb/blob/fa9063d08d753434676e1cbe3206932faf839f23/wandb/sdk/data_types/image.py#L525-L533).
```python
dmin = np.min(data)
if dmin < 0:
data = (data - np.min(data)) / np.ptp(data)
if np.max(data) <= 1.0:
data = (data * 255).astype(np.int32)
return data.clip(0, 255).astype(np.uint8)
```
Note that this rescales [-1, 1] images to the _entire_ [0, 255] range mapping the image's minimum to 0 and its maximum to 255. For [0, 1] images, this simply multiplies them by 255.
After a refactor, PR #9883 changed the code to something almost similar, but with a bug:
```python
if np.min(data) < 0:
data = data - np.min(data)
if np.ptp(data) != 0:
data = data / np.ptp(data)
if np.max(data) <= 1.0:
data = (255 * data).astype(np.int32) …
```
> fix: restore original image normalization behavior

- wandb/sdk/launch/runner/kubernetes_runner.py
Adds `WANDB_CONFIG` to auxiliary resources. To test, I created an additional resource in my [queue config](https://wandb.ai/wandb/launch/UnVuUXVldWU6NTk0NzI5MQ==/config) that runs the following code and verified that the config is accessible
```
echo "=== All Environment Variables ==="
env | sort
echo ""
echo "=== WANDB_CONFIG specifically ==="
echo "WANDB_CONFIG: $WANDB_CONFIG"
echo ""
echo "=== WANDB Variables ==="
env | grep WANDB | sort
echo "=== Test Complete ==="
```
Recording verifying the above:
https://github.com/user-attachments/assets/e9547f57-8ae3-46f2-9b18-e416e1095cba
--- 
Additionally, here's the resource spec that I added:
```
kind: Job
spec:
template:
spec:
containers:
- args:
- -c
- |
echo "=== All Environment Variables ==="
env | sort
echo ""
echo "=== WANDB_CONFIG …
```
> chore(launch): expose wandb config to auxiliary resources

- wandb/sdk/wandb_setup.py
Removes the method which would have at best printed mysterious messages to the user's console.
The `sys.frozen` attribute is set by PyInstaller. I don't know why it "could be trouble".
The main thread check was a complete noop: the `threading` module has contained `main_thread` since Python 3.4, and we only support down to Python 3.8.
> refactor: remove `_WandbSetup._check()`

- tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Description
-----------
- Fixes #NNNN
We changed the result returned by the `Project -> Artifact` endpoint for a missing artifact, where instead of returning `collection not found`, we now return `null`. This changed the error raised by `api.artifact()`, since it now receives a null value for a non-existent artifact. 
This PR updates the test to just expect a `CommError` instead of matching on exact strings from the server.
Testing
-------
> chore(artifacts): fix artifacts test to match on updated error message

- tests/unit_tests/test_lib/test_service_token.py
- wandb/sdk/lib/service/service_token.py
- wandb/sdk/lib/sock_client.py
Adds support for Unix domain sockets in Python. Since the server does not emit such sockets yet, this code never runs (except in unit tests!)
> refactor: support Unix domain sockets on the client-side

- wandb/sdk/launch/runner/kubernetes_runner.py
As with https://github.com/wandb/wandb/pull/10028, when we create k8s Deployments, we should ensure that their name is unique
> chore(launch): make deployments names unique

- wandb/sdk/wandb_init.py
Removes a `raise AssertionError` that was added to satisfy type checkers. It is no longer needed, as `reraise()`'s return type was updated to `Never`.
Note that `assert False` is [the more idiomatic way](https://typing.python.org/en/latest/guides/unreachable.html) (if we needed it).
> refactor: remove unreachable statement

- core/internal/filestream/filestream.go
- core/internal/filetransfer/file_transfer_manager.go
- core/internal/runconsolelogs/debouncedwriter.go
- core/internal/runconsolelogs/debouncedwriter_test.go
- core/internal/runconsolelogs/runconsolelogs.go
Fixes potential race conditions in `Sender.finishRunSync()` by ensuring any objects not guarded by `Sender.mu` are concurrency-aware. The main problem is with `Finish()` methods, which often involve a `WaitGroup.Wait()` call. Calling `Wait()` and `Add()` simultaneously can cause a panic.
These race conditions can only occur if certain kinds of records are processed after `Exit`. I think there is a race condition in the Python client that can allow it to sometimes send `OutputRaw` records after `Exit`.
> fix: potential race conditions in Sender on exit

- pyproject.toml
UP007 is for changing `Union[X, Y]` to `X | Y`, and UP045 is for `Optional[X]` to `X | None`. If we aren't doing one, we aren't doing the other.
> chore: ignore ruff UP045 in files ignoring UP007

- CHANGELOG.unreleased.md
- tests/system_tests/test_functional/console_capture/removes_callback_on_error.py
- tests/system_tests/test_functional/console_capture/test_console_capture.py
- wandb/sdk/lib/console_capture.py
Makes `console_capture.py` clear all callbacks if a callback raises an error.
Since callbacks are invoked when stdout or stderr is being written to, and since errors are likely to be printed to the console, this can trigger an infinite loop. This is especially problematic for `KeyboardInterrupt` as it makes it difficult to stop the program using Ctrl+C if a callback is permanently stuck (imagine a callback that does `time.sleep(600)`).
Also updates `console_capture.py` to log and suppress regular Exceptions thrown by callbacks, since these will almost always be W&B bugs that shouldn't propagate to the user's `print()` statements.
> fix: clear console capture callbacks on error

- wandb/sdk/wandb_require.py
Description
-----------
Missed this warning in #9965
> chore: remove a misleading require warning

- CHANGELOG.unreleased.md
- wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-25536
respect different settings of verbosity when printing warning messages provided from the service process. 
in this case the relevant settings are: 
- quiet
- silent
- show_warnings
Testing
-------
> fix: respect verbosity settings when printing service warnings

- tests/system_tests/test_registries/test_link_registry.py
- wandb/apis/public/api.py
- wandb/sdk/artifacts/artifact.py
Description
-----------
Fixes `artifact.link()` so that the linked artifact is fetched successfully, even if the user's current default entity is in a different org.
Testing
-------
Updated `test_artifact_link_to_registry_collection` to run with the user's default entity set to different teams.
Note that the updated test does indeed fail without the changes in this PR, so it should be guarding against regressions on this bug going forward.
> fix(artifacts): ensure `artifact.link` can fetch the linked artifact regardless of user's default entity

- tests/unit_tests/test_launch/test_agent/test_agent.py
- wandb/sdk/launch/agent/agent.py
Description
-----------
- https://linear.app/wandb/issue/ENG-79/obfuscate-api-token-in-launch-agent-logs
* When logging the job, `<redacted>` will show for the api key
Merges into the `cw-wandb-evals-project` dev branch
Testing
-------
* unit test
> chore(launch): redact api key in runSpec

- CHANGELOG.unreleased.md
- tests/unit_tests/test_wandb_settings.py
- wandb/sdk/wandb_settings.py
Description
-----------
Fixes WB-25638.
I must have missed it when re-implementing Settings with `pydantic` in 0.19.0.
Testing
-------
Added a unit test.
> fix: correctly parse x_extra_http_headers setting from env variable

- BREAKING.md
- CHANGELOG.unreleased.md
- wandb/apis/paginator.py
- wandb/apis/public/artifacts.py
- wandb/apis/public/files.py
- wandb/apis/public/reports.py
- wandb/apis/public/runs.py
Description
-----------
- Fixes WB-16060
When querying `api.Runs.length` before loading any data the value would return `None`. After data was loaded the actual value would be returned.
This would cause inconsistency when calling `len(Runs)` because the `__length__` function would force an api call to the backend, and would always return the number of runs in the queried project.
This behavior would also happen for `Files` associated with a specific run as well.
Testing
-------
```python
import wandb
runs = api.runs("wandb/api-run-query", per_page=1) # note: api-run-query has 100 runs
print(runs.length)
print(len(runs))
print(runs.length)
run = runs[0]
files = run.files() …
```
> fix: inconsistent length values in `api.Runs` and `api.Files`

- core/pkg/monitor/gpuresourcemanager.go
- core/pkg/monitor/portfile.go
- core/pkg/monitor/portfile_test.go
- gpu_stats/Cargo.lock
- gpu_stats/Cargo.toml
- gpu_stats/src/main.rs
Description
-----------
Fixes WB-25245.
This PR adds support for using Unix Domain Sockets for the `wandb-core` <> `gpu_stats` gRPC communication.
Testing
-------
Added Go unit tests, tests manually in different environments.
> chore: unix domain socket support for wandb-core/gpu_stats gRPC communication

- core/hatch.py
- hatch_build.py
Description
-----------
Fixes #10131
Fixes: WB-26048
Add env var `WANDB_ENABLE_CGO` to force `CGO_ENABLED=1` when building `wandb-core`.
> chore: add env variable to enable CGO

- core/internal/stream/recordparser.go
- core/internal/stream/stream.go
Factors out `RecordParser` to convert serialized `Record` values into `Work` domain objects; the logic was originally in `Stream` (which gets records from the client), but it will be reused for `wandb sync` (which gets records from the transaction log).
> refactor: factor out RecordParser for Record => Work parsing

- core/internal/filetransfer/file_transfer_stats.go
- wandb/sdk/lib/progress.py
- wandb/sdk/wandb_run.py
Removes unused "deduped bytes" code, as we don't track this in wandb-core.
> refactor: remove unused "deduped bytes" printing code

- tests/system_tests/test_functional/keras/test_keras.py
Makes `test_keras.py` use the subprocess module instead of `runpy` to fix a flaky test.
Example of a flake: https://app.circleci.com/pipelines/github/wandb/wandb/49366/workflows/55c71ca7-bb87-4b4b-b022-1aa2dfca8626/jobs/1427172/tests
The flake was likely happening because of a race condition: `execute_script` would return after all `run.summary[...] = ...` statements in `WandbCallback` were executed but not necessarily processed by `wandb-core`. By executing the script using `subprocess`, it triggers `wandb.teardown()` at the end and blocks until `wandb-core` finishes all of its work.
> fix: flaky test in test_keras.py

- requirements_dev.txt
https://github.com/Netflix/metaflow/issues/2489 causes tests/system_tests/test_functional/metaflow/test_metaflow.py to fail.
> chore: skip metaflow 2.16.0 in CI

- tests/system_tests/backend_fixtures.py
Increase timeout for backend fixtures (like creating a test user) from 5s to 30s to avoid the occasional timeout errors such as https://app.circleci.com/pipelines/github/wandb/wandb/49425/workflows/7b5850d0-19f8-457b-b4cd-ce50f5c30240/jobs/1428146/tests
> chore: increase backend fixture timeout

- wandb/integration/metaflow/__init__.py
- wandb/integration/metaflow/metaflow.py
* Moves the module docstring to `__init__.py` so that it appears on hover over `import wandb.integration.metaflow`
* Simplifies the docstrings and makes their source more readable
* Updates type annotations on the `wandb_log` decorator
> chore: update metaflow integration docs

- tests/conftest.py
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- tests/unit_tests/test_launch/test_agent/test_run_queue_item_saver.py
- tests/unit_tests/test_library_public.py
- wandb/__init__.py
- wandb/integration/lightning/fabric/logger.py
- wandb/integration/openai/fine_tuning.py
- wandb/jupyter.py
- wandb/sdk/data_types/base_types/media.py
- wandb/sdk/data_types/helper_types/bounding_boxes_2d.py
- wandb/sdk/data_types/helper_types/image_mask.py
- wandb/sdk/data_types/image.py
- wandb/sdk/data_types/saved_model.py
- wandb/sdk/data_types/table.py
- wandb/sdk/integration_utils/auto_logging.py
- wandb/sdk/launch/agent/run_queue_item_file_saver.py
- wandb/sdk/launch/create_job.py
- wandb/sdk/launch/inputs/internal.py
- wandb/sdk/launch/sweeps/scheduler.py
- wandb/sdk/lib/deprecate.py
- wandb/sdk/lib/disabled.py
- wandb/sdk/lib/module.py
- wandb/sdk/wandb_watch.py
- wandb/wandb_run.py
We have it defined in `__init__.pyi` but not in `__init__.py`.
I updated a lot of code to use `wandb.Run` instead of `wandb.wandb_sdk.wandb_run.Run`, but there are still some spots left (like the many `LocalRun` definitions in `data_types`).
The line
```python
from wandb import sdk as wandb_sdk
```
triggers the line
```python
from .wandb_run import finish
```
which executes `wandb/sdk/wandb_run.py`. So the new line,
```python
from wandb.sdk.wandb_run import Run
```
does not perform an import, and its addition cannot introduce any new import cycles or change the import behavior in any way.
> refactor: expose `wandb.Run`

- wandb/apis/public/history.py
Description
-----------
- Fixes #8381
- Fixes WB-21179
This PR removes a redunant decorator from the `_load_next` functions in the `apis.public.History` classes. Which was already being retried from the retrying client provided to the History scan objects.
When doing a full or sampled history scan, the public API is passing a `RetryingClient` which itself retries on exceptions. Additonally, the `_load_next` functions are also wrapped with the decorator `@retry.retriable` which retries when an exception is raised. 
The load next internally is calling `.execute` on the retrying client provided during initialization which will retry until 20 seconds have elapsed, at which point the exception will be raised. Because the …
> fix: api.history scans retries were being multiplied with the clients retries

- CHANGELOG.unreleased.md
- core/internal/paths/longestcommonprefix.go
- core/internal/paths/longestcommonprefix_test.go
Fixes WB-25912.
Fixes a panic that could be triggered when using `sync_tensorboard` depending on the logging directories.
In the test file, reordering data in a test case is enough to cover this.
> fix: panic in LongestCommonPrefix

- .github/workflows/release-sdk.yml
- hatch_build.py
- noxfile.py
Since legacy-service is no longer supported, the universal wheel (which simply doesn't have the `wandb-core` binary) cannot work.
> chore: do not build universal wheel

- wandb/integration/metaflow/data_pandas.py
- wandb/integration/metaflow/errors.py
- wandb/integration/metaflow/metaflow.py
Moves Pandas-related code in the Metaflow integration into its own file and improves docstrings and type annotations.
The idea is to do this for all the other types as well, so that the `metaflow.py` file itself is only responsible for the general `wandb_log` machinery.
> refactor: move Metaflow integration Pandas support to its own file

- CONTRIBUTING.md
This PR fixes a small typo in the contributing guide: "environements" → "environments".
> docs: fix typo in 'environments'

- tests/system_tests/test_core/test_public_api.py
- tests/unit_tests/test_public_api.py
- wandb/apis/public/projects.py
Description
-----------
- Fixes WB-15364
This pr fixes a mismatch of attributes provided when querying a single project (`Api().project(...)`) or multiple projects (`Api().projects(...)`).
Testing
-------
> fix: mismatch attributes for single vs multiple project queries

- core/internal/stream/stream.go
- core/internal/stream/streaminject.go
- core/internal/stream/wire_gen.go
- core/pkg/server/connection.go
When using `wire`, `Params` structs aren't helpful since everything is wired up by type and all parameter types are different.
> refactor: replace StreamParams by direct params

- core/internal/stream/handler.go
- core/internal/stream/handler_test.go
- core/internal/stream/sender.go
- core/internal/stream/sender_test.go
- core/internal/stream/stream.go
- core/internal/stream/streaminject.go
- core/internal/stream/wire_gen.go
- core/internal/stream/writer.go
Creates `HandlerFactory`, `WriterFactory` and `SenderFactory` structs to be used instead of directly injecting `Handler`, `Writer` and `Sender`.
These allow separating injectable values from explicit parameters. `WriterFactory.New` is an example: the `fwdChan` is an explicit parameter, whereas `Logger` and `Settings` are provided implicitly through injection.
`wire` simplifies construction but in doing so hides object lifecycles and ownership. Objects with lifecycles (like `RunWork`, `TBHandler`, `FileStream`, etc.) are best constructed explicitly; shared objects without lifecycles (`observability.CoreLogger`, `Settings`, etc.) can continue to be injected.
> refactor: create Factory structs for Handler, Writer, Sender

- core/internal/monitor/monitor.go
- core/internal/monitor/monitor_test.go
- core/internal/runfiles/runfiles.go
- core/internal/runfiles/uploader.go
- core/internal/runfilestest/runfilestest.go
- core/internal/stream/handler.go
- core/internal/stream/handler_test.go
- core/internal/stream/recordparser.go
- core/internal/stream/sender.go
- core/internal/stream/sender_test.go
- core/internal/stream/stream.go
- core/internal/stream/streaminject.go
- core/internal/stream/wire_gen.go
- core/internal/tensorboard/tensorboard.go
- core/internal/tensorboard/tensorboard_test.go
Now that all objects that depend on it are also constructed explicitly, `RunWork` can be removed from the injection set. This is done because `RunWork` needs ownership to be explicit because of its `Close()` method, which is like closing a channel.
> refactor: construct RunWork explicitly instead of injecting

- .github/CODEOWNERS
Description
-----------
Updates CODEOWNERS by:
- replacing `@mlw-team` with one of `@art-reg-team` or `@sweeps-launch-team` as appropriate
- adding additional paths related to artifacts/registries/automations to `@art-reg-team` ownership.
- Note that `@sdk-team` retains co-ownership of these files as well, in keeping with existing patterns & processes.
Testing
-------
> chore(sdk): replace/update codeowners from (deprecated) mlw-team

- wandb/cli/cli.py
- wandb/sdk/launch/create_job.py
Description
-----------
Expose a way for us to update the input schema for the evals jobs
Testing
-------
Verified that the metadata exists: https://app.wandb.test/wandb/launch-tutorial/artifacts/job/test-simple-schema-npun/v0/metadata
Verified that the job drawer shows the input overrides:
Run succeeds with the input:
https://app.wandb.test/wandb/launch-tutorial/runs/jfqkd4lk/logs
> chore(launch): enable setting input schema on job create

- noxfile.py
Best demonstrated with an example:
```bash
nox -s 'functional_tests-3.10' -- tests/system_tests/test_functional/asyncio_compat_run/test_asyncio_compat_run.py
coverage report --include=wandb/sdk/lib/asyncio_compat.py
```
The `--cov` option expects a value (it's not just a switch) in all documentation, so we appear to have been misusing it. **Why** does that break coverage in this way? I couldn't tell you. But I think it has to do with paths because I get the same 28% in a fresh venv doing this:
```bash
uv venv .venv-cov-bad
source .venv-cov-bad/bin/activate
uv pip install -r requirements_dev.txt
pytest --cov-report= --cov --no-cov-on-fail tests/system_tests/test_functional/asyncio_compat_run/test_asyncio_compat_run.py
```
but it becomes 69% if I make sure to use an editable install before …
> chore: fix coverage collection for tests that run subprocesses

- tests/system_tests/test_registries/test_registry.py
- wandb/apis/public/registries/_utils.py
- wandb/apis/public/registries/registries_search.py
- wandb/sdk/artifacts/_graphql_fragments.py
- Fixes #NNNN
Cleanup: removed now-unused `_gql_artifact_fragment()` and `_gql_registry_fragment()`.
> chore(artifacts): remove now-unused internal gql helpers, other misc cleanup

- tests/unit_tests/test_asyncio_compat.py
- wandb/sdk/lib/asyncio_compat.py
Prevents `asyncio_compat.cancel_on_exit()` from raising its task's exception if the code inside the context manager raised an exception, because the traceback for the latter is generally more important.
This matters when `wandb-core` panics during something like `progress.loop_printing_operation_stats()` in `wandb.init()`. The printed traceback looked like this before:
```
@contextlib.contextmanager
def cancel_on_exit(coro: Coroutine[Any, Any, Any]) -> Iterator[None]:
"""Schedule a task, cancelling it when exiting the context manager.
If the given coroutine raises an exception, that exception is raised
when exiting the context manager.
"""
task = asyncio.create_task(coro)
try:
>           yield
.../wandb/sdk/lib/asyncio_compat.py:209: 
------- …
```
> refactor: improve mailbox handle traceback on wandb-core crash

- wandb/integration/metaflow/data_pytorch.py
- wandb/integration/metaflow/metaflow.py
Factors out PyTorch code in `metaflow.py` into its own file and improves docstrings and type annotations.
> refactor: move Metaflow integration PyTorch support to its own file

- wandb/integration/metaflow/data_sklearn.py
- wandb/integration/metaflow/metaflow.py
Factors out `sklearn` code out of `metaflow.py` and into its own file.
> refactor: move Metaflow integration sklearn support to its own file

- wandb/integration/metaflow/data_pandas.py
`TypeIs[X]` means "the type is X if and only if this returns True" whereas `TypeGuard[X]` only implies "the type is X if this returns True". `TypeIs` is more correct, and even though it doesn't really matter here at the moment, it's a better habit.
> refactor: use TypeIs instead of TypeGuard in metaflow/data_pandas.py

- tests/conftest.py
- tests/system_tests/test_core/test_public_api.py
- A `yield` at the very end of a fixture is not necessary
- The `api` fixture was using `yield` instead of `return`, causing it to patch `_login` for all tests instead of just the duration of the `Api()` initializer
> chore: improve code in some pytest fixtures

- wandb/sdk/data_types/video.py
- wandb/sdk/lib/printer.py
- wandb/sdk/wandb_init.py
- wandb/sdk/wandb_login.py
- wandb/sdk/wandb_setup.py
Changes `wandb_setup.singleton()` to not load settings from the environment and replaces `singleton_if_setup()` by a `settings_if_loaded` property.
Before this PR, `singleton_if_setup()` was used to avoid initializing settings if they weren't already initialized, mainly because tests rely on modifying environment variables in fixtures and we don't want to accidentally initialize settings before the fixtures run.
I'm adding an asyncio thread to the singleton, and `singleton()` must be used to get it because there's no alternative if `singleton_if_setup()` returns `None`. This PR prevents `singleton()` from initializing settings.
> refactor: make wandb_setup.singleton() not load settings

- CHANGELOG.unreleased.md
- tests/unit_tests/test_util.py
- wandb/util.py
Description
-----------
- Fixes WB-21766
This PR fixes a bug when attempting to serialize the run config to JSON. This happens when attempting to make complex data types (e.g. dataclasses, real classes) json friendly.
Data classes are converted to dictionaries for serialization, but when a dataclass contains a real class those values were not being converted recursively to json friendly values.
Testing
-------
- unit test added
- repro from WB-21766 passes
> fix: object is not serializable for dataclasses containing real classes

- tests/unit_tests/test_launch/test_inputs/test_internal.py
- wandb/cli/cli.py
- wandb/sdk/launch/inputs/internal.py
- wandb/sdk/launch/inputs/schema.py
Description
-----------
Extends our schema validation to allow for arrays (from python lists or sets) of integer, number or string enums. This is the first pass to enable list types in input schemas and we are purposely only allowing enums so that the FE remains structured. The user will be able to select more than one option from the existing dropdown that is present on enum types.
The following cases are more complex and not yet supported:
- Enums of "complex types" or dicts 
- Generic lists and lists of other types
Testing
-------
- Added unit tests
- Created a job with updated schema: https://wandb.ai/wandb/launch-tutorial/artifacts/job/test-simple-schema-npun/v5/metadata
> chore(launch): allow list/sets in input schemas

- pyproject.toml
Require Click>=8.0.1 to ensure numeric 256-color indices (e.g., 178) are accepted by click.style. This avoids TypeError: Unknown color '178' seen in init spinner. Fixes https://github.com/wandb/wandb/issues/10396.
> chore(deps): require Click>=8.0.1 to avoid numeric color error

- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_file_cache.py
- wandb/sdk/artifacts/artifact_manifest_entry.py
- wandb/sdk/artifacts/storage_handlers/gcs_handler.py
- wandb/sdk/lib/paths.py
- wandb/sdk/wandb_run.py
Copies (and supersedes) #10364, which somehow got merged to a temporary graphite branch without ever merging to `main`.
Description
-----------
- Fixes https://wandb.atlassian.net/browse/WB-27072
Note: Similar to https://github.com/wandb/wandb/pull/10356, which simplified type definitions for, internal `str` hash types (e.g. `ETag`, `HexMD5`, etc) mainly used in artifacts code.
Replaces `NewType` definitions for path/URI string types (`FilePathStr`, `URIStr`) with simple `TypeAlias = str`, since they:
- provided no runtime validation
- incurred minor extra overhead from the runtime call
~Also defines a `URIOrFilePathStr = Union[URIStr, FilePathStr]` type alias, since these 2 often appear together in type hints across the artifacts codebase.  **Note that at runtime**, this evaluates to …
> chore(artifacts): define path strings as TypeAliases, not NewTypes

- wandb/sdk/wandb_settings.py
Follow-up to #10397 
- Removed unnecessary `elif` statement in tag validation (simplified to just `else`)
- Improved error handling to accumulate all validation errors before raising
- Users now see all invalid tags at once instead of failing on the first one
> fix(sdk): improve tag validation

- .github/CODEOWNERS
- tests/system_tests/test_artifacts/test_wandb_artifacts.py
- tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
- wandb/_iterutils.py
- wandb/_strutils.py
- wandb/apis/public/api.py
- wandb/apis/public/artifacts.py
- wandb/apis/public/automations.py
- wandb/apis/public/registries/_freezable_list.py
- wandb/apis/public/registries/_utils.py
- wandb/automations/_filters/expressions.py
- wandb/automations/_filters/operators.py
- wandb/automations/actions.py
- wandb/automations/events.py
- wandb/sdk/artifacts/_validators.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/exceptions.py
- wandb/sdk/artifacts/storage_handlers/s3_handler.py
Description
-----------
- Fixes https://wandb.atlassian.net/browse/WB-27171
Extract generic, repeated helper logic from artifacts/registries/automations code into private modules for reuse anywhere in the SDK.  Updates relevant call sites in artifacts/registries/automations code.
- Added: wandb/_strutils.py
- Updated: wandb/_iterutils.py
Also updates CODEOWNERS so that multiple teams can approve changes to these modules.
Testing
-------
No functional changes intended, relying on existing tests/CI.
> chore: reorganize/pull out helper logic from artifacts/registries/automations

- core/pkg/server/connection.go
- tests/system_tests/test_core/test_offline_sync.py
- tests/system_tests/test_core/test_offline_sync_beta.py
- wandb/cli/beta.py
- wandb/cli/beta_sync.py
- wandb/sdk/lib/service/service_connection.py
Tears out the old `wandb beta sync`​ implementation and replaces it with a new one.
The service process responds with errors and empty responses to sync requests. I add status messages in a separate PR because testing them is a bit more involved.
> refactor: stub implementation for wandb beta sync

- tests/unit_tests/test_asyncio_compat.py
- wandb/sdk/lib/asyncio_compat.py
- wandb/sdk/mailbox/wait_with_progress.py
Adds an optional timeout to `open_task_group()`​ (useful in a test in PR #10441), and a `race()`​ function.
Improves cancellation handling: it’s important to await tasks after calling `cancel()`​ to allow them to run their `finally`​ blocks. Otherwise, the `finally`​ blocks run sometime later, which could be unexpected, for example:
```
event = asyncio.Event()
cleaned_up = False
async def failing_task():
await event.wait()
raise ValueError
async def task_with_cleanup():
try:
event.set()  # allow failing_task() to fail
...          # do work
finally:
cleaned_up = True
async with asyncio_compat.open_task_group() as group:
group.start_soon(failing_task())
group.start_soon(task_with_cleanup())
```
> refactor: improve asyncio_compat.open_task_group()

- .github/workflows/release-sdk.yml
The `legacy-service` was removed in 0.21.0.
> chore: remove legacy-service parts from release action

- core/internal/stream/sender.go
Encountered such a record when syncing an old run. Not entirely sure why it doesn't have `Control` set, but either way we shouldn't assume that it is always set.
> refactor: don't crash in sender if exitRecord.Control is nil

- tests/system_tests/test_core/test_offline_sync_beta.py
- wandb/cli/beta.py
- wandb/cli/beta_sync.py
Since it's possible to sync an entire `wandb` directory using `wandb beta sync ./wandb`, it makes sense to also be able to sync specific runs using `wandb beta sync ./wandb/run-1 ./wandb/run-2`.
This PR also makes it resolve symlinks, since the `wandb/` directory often includes a `latest-run/` symlink, and we wouldn't want to start two `sync` operations simultaneously.
> feat: allow passing multiple paths to `wandb beta sync`

- tools/graphql_codegen/plugin.py
- wandb/_pydantic/__init__.py
- wandb/_pydantic/field_types.py
- wandb/automations/_validators.py
- wandb/automations/actions.py
- wandb/automations/events.py
Description
-----------
- Fixes #NNNN
Moves the `SerializedToJson` field annotation (and the validator function `ensure_json()`) from `wandb._pydantic` into `wandb.automations._validators`, since it's only used there and need pydantic v2 to work properly anyway.
Testing
-------
> chore(artifacts): move SerializedToJson annotation to automations

- core/internal/monitor/monitor.go
- core/internal/monitor/monitor_test.go
Description
-----------
Ignore benign sampling errors such as https://weights-biases.sentry.io/issues/6858581950/events/aeec454dd55d40bf989e0d35c3181b00/?project=4505513612214272, https://weights-biases.sentry.io/issues/6858581950/events/e68a977372e8466a99a5666531dc589a/?project=4505513612214272, or https://weights-biases.sentry.io/issues/6858581950/events/cf4144a77ad0441b92571ab719da6d60/?project=4505513612214272.
> chore: do not send benign system monitor resource sampling errors to Sentry

- wandb/_pydantic/__init__.py
- wandb/_pydantic/base.py
Description
-----------
PR:
- Refactors internal pydantic class definitions by introducing a new `JsonableModel` base class
- Extracts configuration for general JSON serialization/deserialization behavior from `GQLBase` into `JsonableModel`, since it doesn't just apply to generated GQL types
- Makes `GQLBase` inherit from `JsonableModel` to maintain existing behavior
- (internal) Renames `ModelDumpKwargs` to `DumpKwargs` for brevity/clarity
- Improves inline explanatory comments
No intended functional changes.
> chore(sdk): extract base JsonableModel pydantic type

- core/internal/api/api_test.go
- core/internal/api/credentials_test.go
- core/internal/debounce/debounce_test.go
- core/internal/featurechecker/features_test.go
- core/internal/filetransfer/file_transfer_azure_test.go
- core/internal/filetransfer/file_transfer_default_test.go
- core/internal/filetransfer/file_transfer_gcs_test.go
- core/internal/filetransfer/file_transfer_s3_test.go
- core/internal/gitops/git_test.go
- core/internal/monitor/cwmetadata_test.go
- core/internal/monitor/dcgm_exporter_test.go
- core/internal/monitor/monitor_test.go
- core/internal/monitor/openmetrics_test.go
- core/internal/observabilitytest/logging.go
- core/internal/runconsolelogs/runconsolelogs_test.go
- core/internal/runsync/runreader_test.go
- core/internal/runupserter/runupserter_test.go
- core/internal/runwork/runwork_test.go
- core/internal/stream/handler_test.go
- core/internal/stream/sender_test.go
- core/internal/tensorboard/rootdirguesser_test.go
- core/internal/tensorboard/tensorboard_test.go
- core/internal/tensorboard/tfeventconverter_test.go
- core/internal/tensorboard/tfeventreader_test.go
- core/pkg/artifacts/multipart_test.go
- core/pkg/artifacts/saver_test.go
- core/pkg/launch/job_builder_test.go
Unlike `NewNoOpLogger()`, this creates a logger whose logged messages show up in test output on failure.
Updated most uses of `NewNoOpLogger()` in tests so that `NewTestLogger()` is the preferred convention.
> refactor: create observabilitytest.NewTestLogger

- tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/storage_handlers/gcs_handler.py
- wandb/sdk/artifacts/storage_handlers/http_handler.py
- wandb/sdk/artifacts/storage_handlers/local_file_handler.py
- wandb/sdk/artifacts/storage_handlers/s3_handler.py
- wandb/sdk/artifacts/storage_policies/_factories.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
PR refactors / cleans up / modernizes some existing code for artifacts storage policies / storage handlers.  Timeboxed.
- Defines internal, private factory functions for creating HTTP sessions and default storage handlers
- Reduces unnecessarily verbose patterns in various places, e.g. `manifest_entry.size if manifest_entry.size is not None else 0` --> `manifest_entry.size or 0`
- Registers a hook on creating a `Session` to automatically `raise_for_status()`.  Reduces verbosity and ensures consistent expectations across requests _without_ requiring repeated, manual invocation of `response.raise_for_status()`.
- Refactors existing authentication logic for clarity (i.e. prefer bearer token, cookies, or basic auth in that order)
- Simplifies URL construction in `_file_url` method
> refactor(artifacts): cleanup storage policy session-init logic

- core/internal/runwork/runwork_test.go
Fixes a data race introduced by changing to a test logger. This particular test's goroutines can emit warnings, and since the test doesn't wait for the goroutines to complete, a goroutine can try to emit a warning after the test finishes which is invalid.
I decided against using an `errgroup.Group` or a `sync.WaitGroup` as they add too much noise without a lot of value. It's fine for the goroutines to complete after the test if they don't log.
> chore: fix data race in runwork_test.go

- core/internal/runupserter/runupserter.go
Changes the status text shown during `wandb.init()` from "creating run" to "setting up run {ID}" so that it makes sense when resuming or syncing (using `wandb beta sync`​). This also helps disambiguate status updates for different runs when syncing multiple .wandb files at once.
> refactor: rename operation "creating run" to "setting up run {id}"

- core/scripts/pre-commit-hooks/run-go-unit-tests.sh
Changes the go-unit-tests hook to not use `-v`, which produces uselessly verbose output in which it is difficult to spot a failure.
Some extra cleanup:
- Removes the `dirname` stuff beacuse pre-commit hooks always run from the repo root
- Removes the `|| fail`​ because that's what `set -e`​ is for
- Removes the `-tags=unit`​ flag; we set build tags on our tests as far as I can tell
I'm not sure about the `-short` option. It's documented as:
```
Tell long-running tests to shorten their run time.
It is off by default but set during all.bash so that installing
the Go tree can run a sanity check but not spend time running
exhaustive tests.
```
and I do not understand what this means.
> chore: don't use -v in the go unit tests pre-commit hook

- core/internal/stream/handler.go
Log before closing channels, so that `handler_test.go` doesn't end the test until the log statement executes.
`handler_test.go` consumes the `outChan` to detect when `Handler` is done with all its work.
> chore: fix another race in handler_test.go

- tools/launch_release/build/Dockerfile
- wandb/sdk/launch/agent/agent.py
- wandb/sdk/launch/agent/launch_api_provider.py
Description
-----------
- Fixes https://wandb.atlassian.net/browse/WB-27889
We ran into auth issues once we opened up our internal testing to orgs outside of wandb. This PR uses `LaunchApiProvider` to perform run status checks on behalf of the user with their auth instead of the agent's auth.
I also did a bit of refactoring and dropped the `self._api` member of the LaunchAgent class to centralize things around the LaunchAgentApiProvider. This will make it clear whether an action should be performed on behalf of the user or for the agent.
Testing
-------
* QA SaaS
* Ramped up an external test account and launched public jobs.
* Confirmed no auth issues in the following scenarios:
* Eval run ran all the way through successfully
* Manually cancelled the run view stop …
> fix(launch): use job api to check run statuses

- CHANGELOG.unreleased.md
- tests/system_tests/test_artifacts/test_artifact_public_api.py
- wandb/apis/public/api.py
- wandb/errors/errors.py
- wandb/sdk/data_types/bokeh.py
- wandb/util.py
Description
-----------
- https://wandb.atlassian.net/browse/WB-27854
`Api.artifact_exists()` and `Api.artifact_collection_exists()` should raise on timeout errors, rather than (potentially erroneously) returning `False`.
Testing
-------
> fix(artifacts): `Api.artifact_exists` and `Api.artifact_collection_exists` should raise on timeout errors

- core/internal/transactionlogtest/readers.go
- core/internal/transactionlogtest/transactionlogtest.go
Adds `internal/transactionlogtest` with some utilities for testing transaction logs realistically. Used in the flow control PR (#10073).
> chore: transactionlogtest

- tests/unit_tests/test_handler.py
- tests/unit_tests/test_job_builder.py
- tests/unit_tests/test_sender.py
- tests/unit_tests/test_wandb_settings.py
- wandb/apis/importers/internals/internal.py
- wandb/sdk/internal/sender.py
- wandb/sdk/internal/settings_static.py
- wandb/sync/sync.py
Instead of converting to a proto and then back to a dict, just pass a dict directly to `SettingsStatic`.
I will be removing `x_files_dir` from the proto but keeping it on the Python `Settings` object for legacy code.
Found all uses by searching for "SettingsStatic(". This class is not part of the public interface (it's not exported in `wandb/__init__.py`).
The `importers/internal.py::make_settings()`​function appears to not be tested, but I removed all fields that you aren't allowed to set explicitly on `Settings`​ (Pydantic raises an error). There were also some tests in `test_job_builder.py`​ that set `_jupyter`​ which isn't settable. The `SettingsStatic._proto_to_dict()`​ method used to silently ignore these fields.
> refactor: initialize SettingsStatic with a dict instead of a proto

- wandb/apis/__init__.py
- wandb/apis/attrs.py
- wandb/apis/internal.py
- wandb/apis/normalize.py
- wandb/apis/public/__init__.py
- wandb/apis/public/api.py
- wandb/apis/public/const.py
- wandb/apis/public/history.py
- wandb/apis/public/jobs.py
- wandb/apis/public/projects.py
- wandb/apis/public/query_generator.py
- wandb/apis/public/registries/__init__.py
- wandb/apis/public/registries/_freezable_list.py
- wandb/apis/public/registries/registry.py
- wandb/apis/public/reports.py
- wandb/apis/public/sweeps.py
- wandb/apis/public/teams.py
- wandb/apis/public/users.py
- wandb/apis/public/utils.py
Description
-----------
Applies autofixes to modernize type annotations in the `wandb.apis.public.*` modules, following PEP 563/585/604, e.g.:
- Adding `from __future__ import annotations` to enable forward references
- Replacing `Optional[T]` with `T | None` syntax
- Replacing `Union[T, U]` with `T | U` syntax
- Replacing `typing` containers with generic collections, e.g. `List[T] -> list[T]`, etc
- Removing redundant imports from typing module
Testing
-------
No intended functional changes, relying on existing tests
> fix(sdk): modernize type hints in `wandb.apis.public.*` modules (PEP 563/585/604)

- tests/unit_tests/test_lib/test_progress.py
- wandb/sdk/lib/progress.py
When `wandb` is used in a script whose output is redirected to a file or a so-called "dumb" terminal, the progress updates it prints during `wandb.init()`, `run.finish()` and some other functions are simplified to avoid dynamic text with ANSI cursor motions and to instead print a single line each time the combined status message changes.
The code was incorrectly printing a blank line when the status was blank (meaning wandb-core didn't report any ongoing operations). This was noticed because it caused a test to flake in `test_offline_sync_beta.py`.
> fix: don't print empty status lines when output device is not a terminal

- wandb/sdk/lib/progress.py
Deletes code that hasn't been in use since we migrated away from legacy-service. The `_show_operation_stats` boolean was always set to `True`.
> chore: delete unused progress.py code

- wandb/sdk/launch/runner/kubernetes_runner.py
Sanitize config before adding env variables, since otherwise we will modify the variable names and values (which are inconveniently defined in the format `{ 'name': <>, 'value': <>}` and we sanitize anything under the `name` key.
> chore(launch): sanitize config before adding env variables

- tests/unit_tests/test_job_builder.py
- tests/unit_tests/test_launch/test_create_job.py
- tests/unit_tests/test_launch/test_job.py
- wandb/sdk/internal/job_builder.py
- wandb/sdk/internal/sender.py
- wandb/sdk/launch/create_job.py
Makes `files_dir` an explicit parameter to `JobBuilder` instead of reading it from `settings` to get rid of the hack of setting `x_files_dir`.
Setting the `files_dir` setting was always an antipattern, and when it was made immutable, `x_files_dir` was added to aid the refactor.
> refactor: don't use `x_files_dir` for JobBuilder

- core/pkg/leveldb/livereader.go
- core/pkg/leveldb/livereader_test.go
Description
-----------
This PR implements a `LiveReader` struct to read records from a W&B LevelDB-style log that may be actively written.
Intentionally kept separate from the battle-tested implementation of leveldb log reader/writer used in `wandb-core`.
> chore: live leveldb log reader

- core/internal/leet/livestore.go
- core/internal/leet/livestore_test.go
Description
-----------
This PR implements a `LiveStore` abstraction (on top of the LiveReader live leveldb reader) that represents a persistent run data store that may be actively written to by another process.
> chore: live store abstraction on top of live leveldb log reader

- CONTRIBUTING.md
- noxfile.py
- tools/graphql_codegen/README.md
Description
-----------
- https://wandb.atlassian.net/browse/WB-27987
PR:
- Adds a new `nox` session, `nox -s gql-codegen`, to run codegen for Python GraphQL types.  This improves ease of use -- and discoverability -- for the command.
- Updates relevant repo docs to reflect this
Testing
-------
N/A.  Changes do not touch any runtime code or tests.
Have confirmed that:
- After running `nox -s gql-codegen` locally, all `_generated/**/*.py` remain unchanged.
- After removing all generated files, _then_ rerunning `nox -s gql-codegen`, all previous `_generated/**/*.py` files are regenerated without changes.
Both of these are expected behavior at this time.
> chore(sdk): add nox session for python GraphQL codegen

- core/internal/stream/flowcontrol.go
- core/internal/stream/writer.go
Makes `Writer.Flush` return an error if it failed to flush, and makes `FlowControl` detect the error and stop instead of likely running into another, more confusing error like "failed to seek: EOF".
See [this trace](https://weights-biases.sentry.io/issues/trace/59ed8bd07e02a6e86440887df980f9c6/?groupId=6912553190&node=error-ec4c618f2038484b818e140fe564e49b&pageEnd=2025-10-01T18%3A09%3A37.618&pageStart=2025-09-30T18%3A09%3A37.618&project=4505513612214272&query=release%3A%5B0.22.1%2C0.22.0%5D&referrer=issue-stream&source=issue_details&timestamp=1759298977) where that happened because the machine ran out of disk space.
> refactor: report Writer.Flush error in FlowControl

- .circleci/config.yml
Description
-----------
Our MacOS tests have been taking a long time:
https://app.circleci.com/insights/github/wandb/wandb/workflows/main/jobs?branch=main
And
So let's upgrade to m4pro.medium, which seems like the best deal. These are more expensive:
But I think the saved exec time will compensate for that.
> chore: upgrade MacOS execution environment in CI

- tests/unit_tests/test_artifacts/test_storage.py
- wandb/sdk/artifacts/storage_handler.py
- wandb/sdk/artifacts/storage_handlers/azure_handler.py
- wandb/sdk/artifacts/storage_handlers/gcs_handler.py
- wandb/sdk/artifacts/storage_handlers/http_handler.py
- wandb/sdk/artifacts/storage_handlers/local_file_handler.py
- wandb/sdk/artifacts/storage_handlers/multi_handler.py
- wandb/sdk/artifacts/storage_handlers/s3_handler.py
- wandb/sdk/artifacts/storage_handlers/tracking_handler.py
- wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py
- wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/artifacts/storage_policy.py
- Fixes https://wandb.atlassian.net/browse/WB-28038
PR:
- Fixes the definition of the `StorageHandler` base class, defining it as a proper [ABC](https://docs.python.org/3/library/abc.html#module-abc) and following expected patterns.
- Introduces `_BaseStorageHandler` as the underlying ABC for both:
- `StorageHandler`, which handles a single storage protocol)
- `MultiHandler`, which manages multiple storage handlers and previously 
- Fixes / narrows type annotations in StorageHandler method signatures
- Fixes raised error types: `NotImplementedError -> ValueError/TypeError` where appropriate.
- Context: See [docs on NotImplementedError](https://docs.python.org/3/library/exceptions.html#NotImplementedError) for more details on when it's intended/not intended to be used
- Makes …
> fix(artifacts): fix typing and inheritance issues in StorageHandler, StoragePolicy classes

- tests/unit_tests/test_artifacts/test_wandb_artifacts.py
- wandb/sdk/artifacts/artifact.py
- wandb/sdk/artifacts/artifact_manifest_entry.py
- wandb/sdk/artifacts/storage_policies/_multipart.py
- wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
- wandb/sdk/artifacts/storage_policy.py
PR:
- Refactors multipart download functionality into a dedicated, internal module (`wandb/sdk/artifacts/storage_policies/_multipart.py`)
- Extracts multipart download logic from `WandbStoragePolicy` into `_multipart.py`
- Improves thread safety by properly initializing thread-local settings using `ThreadPoolExecutor`'s built-in `initializer`/`initargs` arguments
- Simplifies internal function signatures by removing unnecessary parameters
- Enhances code readability, clarity, idiomatic language usage
This PR reorganizes the artifact multipart download code to make it more maintainable and thread-safe. It moves the implementation details into a dedicated module while preserving the existing functionality and test coverage.
> refactor(artifacts): multipart upload/download - reduce coupling, minor perf fixes

- CHANGELOG.unreleased.md
- core/internal/runfiles/runfiles_test.go
- core/internal/runfiles/saved_file.go
- wandb/__init__.pyi
- wandb/sdk/wandb_run.py
Description
-----------
Older versions (pre 0.18.0) of the SDK had deduplication logic for saving files absent in `wandb-core`: tracking file sizes and modification dates for successfully uploaded files to prevent re-upload. This PR adds this logic to `wandb-core`.
<details>
<summary>The script used for testing:</summary>
```python
import pathlib
from time import sleep
import torch
import wandb
num_bytes = 1 * 1024 * 1024
num_floats = num_bytes // 4
num_steps = 50
save_interval = 5
num_files = 0
with wandb.init(project="file-sync-test") as run:
for i in range(num_steps):
if (i + 1) % save_interval == 0:
num_files += 1
print(pathlib.Path(__file__).parent / f"data_{i + 1}.save")
torch.save(
torch.rand(num_floats, dtype=torch.float32),
f"{wandb.run.dir}/data_{i + 1}.save",
)
print(f"{i + …
```
> fix: excessive data uploads when calling `run.save()` repeatedly on unchanged files

- wandb/jupyter.py
- wandb/sdk/lib/apikey.py
Description
-----------
Potentially fixes WB-27895.
This was a cute hack to auto-login to Colab, but it hasn't been working for some time, and I don't think we should have this kind of hacks anyways.
> chore: remove hacky Colab login magic

- wandb/_pydantic/base.py
- wandb/_pydantic/field_types.py
Description
-----------
- Fixes #NNNN
Pydantic added new keyword args to `BaseModel.model_{dump,dump_json}` in v2.12.  This is totally fine, but we internally override the default kwargs for those methods while preserving the original signature + type hints where possible.
The way we currently handle this caused CI checks to fail after `pydantic==2.12` was released.
PR makes the type hints a bit more future-proof, if verbose.  Future-proofing is worth it here, since this is the 2nd (and very plausibly not the last) time this has happened in our CI checks.
Testing
-------
> fix(sdk): future-proof type hints on BaseModel.{model_dump,model_dump_json}

- CHANGELOG.unreleased.md
- tests/unit_tests/test_public_api/test_public_api.py
- wandb/apis/public/api.py
Description
-----------
No JIRA
User explicitly pass api key in `wandb.Api(api_key=...)` was picking up wrong key from thread local when switching between different keys.
The API key resolve logic should prefer the explicit key over the implicit thread local values.
Testing
-------
Manual test
```python
def download_with_manual_thread_local():
cleanup()
key1 = read_key("u1.key.txt")
key2 = read_key("u2.key.txt")
from wandb.sdk.internal.thread_local_settings import _thread_local_api_settings
_thread_local_api_settings.cookie = {"wandb": "invalid-cookie-value"}
_thread_local_api_settings.api_key = key1
a2_name = f"{U2_ENTITY}/{P2}/10mb_test_switch_user_reg-team-2:latest"
api2 = wandb.Api(api_key=key2) # key1 is used instead of key2
artifact2 = api2.artifact(a2_name) …
```
> fix(sdk): use explict api key before thread local
