tests/api_mocks.py, tests/test_cli.py, wandb/api.py, wandb/cli.py
@shawnlewis this fixes #8, adds a `--version` flag, and improves the init command by opening a browser and also querying for the API keys username.  Also fixed a couple tests.
=> Open a browser to get a key, empty bucket pull, better netrc, test fixes

wandb/api.py, wandb/cli.py, wandb/sync.py
@shawnlewis bunch of stuff here:
1. Don't open the log tempfile in binary
2. Echo stdout to stdin so progress can be viewed
3. Nicely display errors when using the sync command
4. Opening a browser was causing funky output
5. Fix `status` and `push` for custom buckets
6. Didn't test any of it :wink:
=> General cleanup for the sync command

Makefile, README.md, setup.py, tests/test_api.py, tests/test_cli.py, tests/test_config.py, tests/test_git_repo.py, tests/utils.py, wandb/__init__.py, wandb/api.py, wandb/cli.py, wandb/git_repo.py, wandb/sync.py
@shawnlewis
Added git support to the CLI.  For now, if called from within a training script will fail gracefully if a tree is dirty and from the CLI bombs out.  If it's not run from within git, all is good.  Both stores the current HEAD in wandb and tags the repo with `wandb/bucket_name` then force pushes it.
=> Feature GIT

.vscode/settings.json, conftest.py, setup.cfg, setup.py, tests/test_api.py, tests/test_cli.py, tests/test_git_repo.py, tests/test_sync.py, wandb/__init__.py, wandb/api.py, wandb/cli.py, wandb/config.py, wandb/sync.py
@shawnlewis finally got CI green!
Major changes are:
1. `wandb describe`
_opens up your EDITOR and persists the description in the .wandb folder, this is to support embedding the wandb module in your code and having it push the description the next time your training script runs_
2. `wandb restore bucket`
_checkouts a new branch named after your bucket at the commit your bucket was created at.  Also pulls down the config variables used and writes them to config.yaml_
3. `wandb.sync(files=["*.h5"])`
_spawns a watchdog thread listening to the patterns listed and stores a copy of stdout to pass along as the log.  This, along with `config = wandb.Config()` should be all that's needed in your training script to have everything persisted_
=> Bunch-O-Changes to support new workflow

wandb/git_repo.py
Fixes wandb/core#432
If in a repo that doesn't have any commits, the `HEAD` ref ends up invalid, which fails the `show_ref` command. This change treats an invalid HEAD ref as if there is no head ref.
With fix, the run shows up as if it isn't in a git repo
```
>>> wandb.init()
wandb: Started W&B process version 0.6.13 with PID 94741
wandb: Syncing https://app.wandb.ai/tom/testempty/runs/119hfub2
wandb: Run `wandb off` to turn off syncing.
wandb: Local directory: wandb/run-20180709_222245-119hfub2
W&B Run https://app.wandb.ai/tom/testempty/runs/119hfub2
```
=> Treat invalid head ref as absent ref

wandb/run_manager.py, wandb/stats.py
Fixes wandb/core#425
This updates the file handlers to deal with files being renamed.
Running a simple script that renames a file during the run now shows the proper file list in the log, and uploads the renamed file:
```
MacBook-Pro:tftest tom$ PYTHONPATH=~/go/src/github.com/wandb/client:${PYTHONPATH} python ./rename.py
wandb: Started W&B process version 0.6.13 with PID 99263
wandb: Syncing https://app.wandb.ai/tom/digit-recognizer/runs/5p4dknl5
wandb: Run `wandb off` to turn off syncing.
wandb: Local directory: wandb/run-20180709_235944-5p4dknl5
wandb: Waiting for wandb process to finish, PID 99263
wandb: Program ended.
wandb: Run summary:
wandb:        _step 1
wandb:     _runtime 1.41014313698
wandb:   _timestamp 1531180785.81
wandb:       number 2
wandb: Run history:
wandb:   number …
```
=> Handle files being renamed

requirements_dev.txt
The pytest command was failing after a fresh clone and setup of the client. Turns out keras and tensorflow were missing from dev requirements
=> add tensorflow and keras to dev reqs

tests/test_history.py, wandb/data_types.py, wandb/history.py, wandb/util.py, wandb/wandb_config.py
We were silently swallowing exceptions because of the return statement in the finally branch 🙃.  If I get a tensor of size 10 or less I log it's scalar values, otherwise I log the statistics. 
This also fixes a bug with wandb restore.
=> Added support for torch and tensorflow, fixed wandb restore, log raises

.circleci/config.yml, requirements_dev.txt
Looks like [pytest-flask](https://github.com/pytest-dev/pytest-flask/releases) 0.12.0 requires `pytest>3.6`, but we're locked to `pytest==3.0.7`, resulting in an invalid set of dependencies. Hence tests failing on master (for some reason they're working on py3.6 though).
This PR locks `pytest-flask` to 0.11.0, remedying the situation for now. A future task would be updating to the latest versions of these libraries.
python3.5:
```
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'flask' could not be loaded: (pytest 3.0.7 (/home/circleci/repo/venv/lib/python3.5/site-packages), Requirement.parse('pytest>=3.6'))!
Exited with code 1
```
python2.7:
```
"Plugin %r could not be loaded: %s!" % (ep.name, e))
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'flask' could …
```
=> Lock pytest-flask to 0.11.0, fixing broken dependencies in master

wandb/apis/internal.py
This doesn't affect any core functionality, but does ensure that the displayed URLs and opened browser pages go to the right endpoint.
Should be: `https://app.wandb.ai` for prod, and `https://app.qa.wandb.ai` for QA.
=> Add support for QA (and other environments) in app url

conftest.py, tests/api_mocks.py, tests/test_cli.py, tests/test_run_manager.py, wandb/__init__.py, wandb/apis/internal.py, wandb/run_manager.py
Use pip instead of graphQL to look up the latest version number.
Version not available:
Version available:
=> Lookup latest version in pip

tests/test_headless.py, wandb/git_repo.py, wandb/io_wrap.py, wandb/run_manager.py
iRobot was having their runs fail in docker.  I was able to reproduce locally, this fixes the wrapping as well as an issue with FakeGitRepo, and sparklines in non-utf8 docker containers.
=> Fixes for py2 and iRobot

standalone_tests/logging_granuarity_test.py, tests/test_history.py, tests/test_wandb.py, wandb/__init__.py, wandb/core.py, wandb/history.py
Do the right thing with intermixed History.step() contexts, and .add()s with "step=" both specified and unspecified. Issue a warning if someone overwrites a History key in the current row. Link to the online docs in the History pydoc.
Are people happy with the way I did the warnings?
Fixes wandb/core#803
=> Allow specifying a step number when adding new History steps. 

standalone_tests/logging_granuarity_test.py, wandb/file_pusher.py, wandb/run_manager.py, wandb/stats.py
… because we do weird things with local paths. Fixes wandb/core#813 by adding media files to the upload progress reporting at the end, and being more explicit about how many files they are and what they are. Also adds a few comments.
=> CLI: Track file upload progress by "save_name" rather than local path

wandb/agent.py, wandb/apis/internal.py, wandb/cli.py, wandb/internal_cli.py
This adds back support for sweeps. This is dependent on some backend changes being deployed, so won't work until then.
Changes:
- graphql APIs have changed a little, so the calls have been updated
- the agent directly exec's each run instead of execing the internal agent wrapper
- the exec'd process is moved to a different process group so interrupting the agent properly waits for runs to finish, or kills them if it received a sigint a second time
=> Re-enable sweep support

tests/test_torch.py, wandb/data_types.py
More complicated pytorch networks will not always pass single tensors as outputs.  This fixes that case.
=> Fixed issue where pytorch crashes when a layer passes a tuple as output

tests/api_mocks.py, tests/test_cli.py, tests/test_internal_api.py, wandb/__init__.py, wandb/apis/file_stream.py, wandb/apis/internal.py, wandb/env.py, wandb/run_manager.py, wandb/wandb_run.py
We no longer require setting entity or project to run a run. The server will use the user's default entity, and auto-create projects.
Currently the tests die saying "KeyboardInterrupt"
=> Allow starting without entity or project, use server result.

tests/test_internal_api.py, tests/test_retry.py, wandb/apis/__init__.py, wandb/apis/internal.py, wandb/file_pusher.py, wandb/internal_cli.py, wandb/retry.py, wandb/run_manager.py, wandb/stats.py, wandb/summary.py, wandb/util.py
This lets us actually finish syncing if there are permanent errors rather than hanging forever. Fixes #269. Also move stats.Stats into file_pusher.FilePusher so there aren't so many classes. Fixes wandb/core#917 by using six.reraise().
=> Give up trying to upload files that fail permanently

wandb/run_manager.py
Looks like I missed a naming change in https://github.com/wandb/client/commit/89031acefa13752d70bedd24e7671a1e331e123a
=> Fix name on throttled file uploader event handler

wandb/apis/internal.py, wandb/retry.py, wandb/streaming_log.py
This makes the agent not retry validation errors in register_agent, which can happen if e.g. the sweep is no longer running.
=> agent: don't retry validation errors in register_agent

requirements_dev.txt, tests/test_summary.py, tests/test_wandb.py, wandb/util.py
Add pytest-faulthandler so we get tracebacks on future segfaults. Disable Jupyter test that keeps randomly failing.
=> Fix pyarrow segfault by switching to fastparquet

wandb/apis/internal.py
If you havent created the project yet you will get a message like:
```WANDB_ENTITY=jeffxx WANDB_PROJECT=xxx wandb sweep gridsweep.yaml 
Creating sweep from: gridsweep.yaml
Error: Project jeffxx/xxx not found during upsertSweep
```
Instead of an infinite retry loop.
=> Lets not retry forever for sweep commands that 404

wandb/core.py, wandb/run_manager.py, wandb/util.py
Also log error strings as errors rather than as messages so we get tracebacks.
=> Sentry: set environment so dev errors don't mess up the actual list of production issues

standalone_tests/simpsons_data_frames.py, standalone_tests/simpsons_data_tables.py, tests/test_callbacks.py, tests/test_public_api.py, tests/test_summary.py, tests/test_wandb.py, wandb/__init__.py, wandb/run_manager.py, wandb/summary.py, wandb/util.py, wandb/wandb_run.py
Start renaming data tables to data frames. Make Simpsons example update the results DataFrame after each epoch as well as at the end of the run.
=> Data frames: get rid of wandb-run.json files

tests/test_internal_api.py, wandb/apis/internal.py, wandb/run_manager.py, wandb/util.py
Previously, when a user would push to a run that has already been deleted, gorilla would return a 500, and a generic error would display with a "retrying in the background" message.
Now, W&B displays an error message and refuses to allow you to proceed. And related PR https://github.com/wandb/core/pull/1413 updates the backend to return a 400 instead of a 500.
Changes:
- Don't retry 400 errors.
- Don't show "retrying in background" on 400 errors.
- Log response body to error log in all HTTP error cases.
=> Improve user and internal messaging case where user tries to push to deleted run

tests/test_torch.py, wandb/__init__.py, wandb/wandb_torch.py
Default logging frequency for both parameters and gradients is 100, this lowers the overhead
=> Add frequency for pytorch gradients/parameters

wandb/fastai/__init__.py
This module hooks fast.ai Learners to Weights & Biases through a callback.
Requested logged data can be configured through the callback constructor.
```
from wandb.fastai import WandbCallback
[...]
learn = Learner(data, ..., callback_fns=WandbCallback)
learn.fit(epochs)
```
Module can:
* log model topology
* log weights
* log gradients
* log losses & metrics
* saves best trained model
* log prediction samples
Logging prediction samples currently works only on images. The approach is to use directly fast.ai show_results functions which are specific to each type of data class (classification vs semantic vs gan…). I'm currently proposing a change to fast.ai which would allow to log more types of data that have a "show_results" function (for example tabular data, text data…): …
=> feat: add callback for fast.ai

tests/test_data_types.py, wandb/data_types.py
PIL has a maximum image dimension of 65500, and I spent far too much time looking for the fluke huge image in my dataset before realizing that wandb gathers image arrays into one big image before sending to the server.
Long term fixes could be:
- tile images horizontally and vertically to get more out of one image
- upload multiple large images to store large collections
- or scale down to fit
For now I just add a warning so folks won't waste time debugging this in the future.
=> add image dimension warning

wandb/cli.py, wandb/wandb_run.py
Example commandline:
`wandb run --run_group g1 --job_type j1 --tags hello,there,this -m runname-33  ./train-dummy.py --epochs 2`
=> Add ability to set jobtype rungroup and tags with wandb run

wandb/wandb_torch.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/wandb/client on Python 3.7.1
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./wandb/wandb_torch.py:399:19: F821 undefined name 'itertools'
rmg_ids = itertools.count()
^
./wandb/vendor/pygments/util.py:351:14: F821 undefined name 'unichr'
unichr = unichr
^
./wandb/vendor/pygments/util.py:352:14: F821 undefined name 'xrange'
xrange = xrange
^
./wandb/vendor/pygments/util.py:353:26: F821 undefined name 'unicode'
string_types = (str, unicode)
^
./wandb/vendor/pygments/util.py:354:17: F821 undefined name 'unicode'
text_type = unicode
^
./wandb/vendor/whaaaaat/utils.py:22:33: F821 undefined name 'unicode'
if not isinstance(data, unicode):
^
./wandb/vendor/whaaaaat/utils.py:23:20: F821 undefined name …
```
=> Undefined name: import itertools for line 400

tests/test_tensorboard.py, wandb/run_manager.py
Summaries were only being pushed to the file stream API on file modification. If watchdog never fires a modification event, maybe because it or the OS is overloaded, `wandb-summary.json` will be uploaded as a plain file, but not sent to the streaming API. Gorilla only watches for it to be streamed, so it won't populate summary metrics if it just gets uploaded as a plain file.
Fixed in a couple of ways:
- Stream the summary in `FileEventHandlerSummary.finish()` so that Gorilla always gets the final state of the summary to put in the metrics table.
- Walk the run directory immediately before ending file syncing so we can be almost certain that we've seen every single file in there. This has been a longstanding issue (with watchdog's unreliable filesystem polling) so I figured now was a good …
=> Fix flakey summary metrics (and flakey file uploading)

tests/test_torch.py, wandb/wandb_torch.py
Possible fix for wandb.watch() causing infinite recursion
This doesnt explain why we have the output of a forward pass containing recursive datastructures but it should prevent a crash at least in this part of the code with marginal overhead.
=> Avoid infinite recursion if output of forward pass has recursive lists

wandb/run_manager.py, wandb/util.py
This is the CLI part of https://github.com/wandb/core/issues/1354 .
The CLI used to upload output.log at the end of the run. We stopped uploading it because the backend was consolidating the streamed copy of that file into its own version of it. Gorilla doesn't do that consolidation process any more, so we should go back to having the CLI upload output.log at the end.
=> Upload output.log at the end of the run

wandb/file_pusher.py, wandb/run_manager.py
Move copies of files we're uploading into a temporary directory (currently they're in the run directory) so that we don't accidentally upload them!
Fixes https://github.com/wandb/core/issues/1875 .
=> Fix uploading tmp files

standalone_tests/upload_simpsons_images.py, wandb/wandb_run.py
Add a script to demonstrate how to upload a set of images, and print out where they'll be available online.
ALSO, important bug fix:
wandb_run.Run.path: use self.project_name() to get the project name instead of self.project, so that we fall back on auto-names.
@raubitsj could you review the project name bug fix?
@staceysv could you review the data upload script? (Make sure it does what you need).
=> Example image upload script

wandb/wandb_torch.py
Graph.criterion was not extracted for Pytorch based models (including fast.ai) when using recurrent neutral networks based models.
I'm not sure how to create a test for it add it is not used at the moment but I'll be happy to look at an existing one and try to replicate.
=> fix(wandb_torch): extract graph.criterion for RNN models

wandb/apis/__init__.py, wandb/apis/internal.py, wandb/data_types.py, wandb/file_pusher.py, wandb/run_manager.py
Print an error and retry if a file shrinks while we're uploading it. Get rid of temporary directory cleanup warnings.
Fixes https://github.com/wandb/core/issues/2056
Fixes https://github.com/wandb/core/issues/1972
=> Make copy=True the default for file uploading

wandb/wandb_config.py
Currently it is a bit ugly to get config items from wandb.Config
Here is what you have to do now:
`parameter_dict_from_sweep = {k: run.config[k] for k in run.config.keys() if not k.startswith('_wandb')}`
Here is what it will be after this PR:
`parameter_dict_from_sweep = dict(run.config.user_items())`
=> Helper function for advanced config users

wandb/io_wrap.py
Fixes https://github.com/wandb/client/issues/401.
Fixes https://github.com/wandb/core/issues/2181.
I tried to reproduce this with Emacs on Mac OS and wasn't able to.
I believe that there is a real bug though, and that this change will at least be an improvement, if not a fix.
=> io_wrap: winsize ioctl values are unsigned shorts.

tests/test_headless.py, tests/test_tensorflow.py, tests/test_wandb_run.py, wandb/__init__.py, wandb/apis/internal.py, wandb/apis/public.py, wandb/run_manager.py, wandb/tensorboard/__init__.py, wandb/tensorflow/__init__.py, wandb/wandb_run.py
You guys were worried about breaking changes in the PR. The only breaking change here should be that Run.run_name doesn't exist any more. I think that's probably not a big deal because external users shouldn't have been using it anyway.
Add deprecation notices for Run.description.
Fix a bunch of tests that were dependent on os.environ, so had race conditions that were making them fail.
If the user passes "id=..." to wandb.init(), also use that value for the run's display name.
Fixes https://github.com/wandb/core/issues/2170.
Combine Run.run_name and Run.display_name into Run._name which is exposed as the Run.name and
Run.display_name properties. This fixes a bug where Run.display_name would've been updated
from the back end but Run.run_name wouldn't have been. Also makes wandb_run.Run …
=> Run name/notes/description cleanup

wandb/apis/internal.py, wandb/util.py
Some features are required for a clean interaction with the onprem vm, which uses a `vm-` API key prefix.
Tested with the local branch for VM development.
=> Add features for W&B on-premises VM

wandb/fastai/__init__.py
This PR allows to log prediction samples when `data_type` is "images".
This should work with all vision problems treated with built-in data loaders from fastai, as well as custom datasets automatically inferred.
Samples can be given through `validation_data` or selected randomly, after which they remain the same until end of training to see the evolution of predictions.
Examples:
* classification problem: https://app.wandb.ai/borisd13/simpsons-fastai/runs/g34gpga7
* segmentation: https://app.wandb.ai/borisd13/semantic-segmentation/runs/zgf5tcu1
Using the callback does not change:
* Option 1: `learn = Learner(data, ..., callback_fns=partial(WandbCallback, data_type="images"))`
* Option 2: `learn.fit(..., callbacks=WandBCallback(learn, data_type="images"))
Once the change is merged, I'll …
=> Display of prediction samples for fastai

wandb/__init__.py, wandb/dataframes.py, wandb/keras/__init__.py, wandb/util.py
This deprecates the `data_type` parameter to the keras callback in favor of `input_type` and `output_type`, which currently support `image`, `label` and `segmentation_mask` (more can be added in the future, e.g. audio). Now instead of just automatically logging image->label or image->image, we will handle all combinations of the above types for input and output.
If `log_evaluation` is set to true, when training finishes we will automatically log a dataframe to the `results` key in summary supporting the following input/output types:
- image->label: categorizer dataframe with per-class probabilities and columns needed for confusion matrix
- image->segmentation_mask: segmentation dataframe with per-class accuracy and iou (or just global accuracy and positive iou for binary segmentation)
=> Add dataframe helpers. Add dataframe logging and improve image logging for keras callback

wandb/apis/file_stream.py, wandb/run_manager.py
Does nothing if another policy has already been set (eg. for resuming).
Fixes https://github.com/wandb/core/issues/1046.
=> File streaming: add ability to set a *default* file policy

wandb/wandb_run.py
Fixes a run description deprecation warning if you call `wandb.init(id='asdf')`.
Also lets us instrument usage of the deprecated description field in the
backend. Previously we'd always set the description field when upserting a run.
Now we set it to null unless the user has explicitly set the old-style
description somehow, either through a `wandb.init()` parameter or an
environment variable.
=> Only update ._name_and_description if .description is set at some point

tests/test_internal_api.py, wandb/history.py
Before this we threw an exception on them. TensorFlow just applies `int()` to
step numbers. That seems kind of wrong, but it'd be good if we at least don't
crash. We now print a warning if we round the step number.
Fixes https://github.com/wandb/client/issues/431.
=> History: allow floating point step numbers

wandb/fastai/__init__.py
Make default "monitor" value consistent with update of fastai library -> changed from "val_loss" to "valid_loss".
fix #442
=> fix(fastai): use TrackerCallback default monitor value

tests/mock_server.py, wandb/apis/file_stream.py, wandb/apis/internal.py
Use the new dedicated `/files` prefix for file streaming. This is necessary as the VM version of W&B serves all services from the same port, so needs path prefixes to differentiate frontend from API requests.
Also handle relative file upload URLs by prepending the base URL path. This is necessary because the server doesn't know what IP or host name it'll be accessed through ahead of time, so it can't return the correct host for uploading.
The old URLs are still functional on the server to support old clients.
Prod, QA, and TRI-AD have all been updated to use the new url.
=> Use files URL prefix for file streaming

wandb/apis/public.py
Adds a `scan_history` field on `Run` that lets you either fetch full history rows or just specific keys. Returns an iterable so all the history doesn't need to be stored in memory all at once (only one page will be in-memory at a time).
Also fixes a bug where you couldn't override `base_url` since the graphql client was constructed prior to applying the overrides.
=> add scan_history field to public api Run to fetch all history

wandb/data_types.py, wandb/fastai/__init__.py
This PR proposes 3 changes:
- a fixed seed is used in fastai callback to ensure the same images are always selected at each epoch. This is nice to visualize the evolution of predictions on a same image during training -> see https://app.wandb.ai/borisd13/DeOldify/runs/pff2osv4
- invert order between ground truth and predictions: this allows for nicer displays -> see https://app.wandb.ai/borisd13/DeOldify/runs/x6g016c4
- increase max number of logged images to 108. This is to make it compatible with the default number of samples in keras & fastai callbacks (36) since we want to log 3 images per sample (input, prediction & ground truth)
Let me know what you think? I could also allow to define the `seed` value but think the default should be to a fixed value such as `12345` as it will also …
=> Feat: use fixed seed, invert order between ground truth and prediction & increase max number of logged images

wandb/wandb_torch.py
This is a possible fix for:
https://github.com/wandb/angle-issues/issues/21
I am having trouble reproducing the failure, but this change should avoid the crash.  
It isn't clear to me whether a more proper fix is to filter out the case where named parameters consist of an empty list.  The side effect of this fix is that an empty named parameter list will be treated as parameter count of 1, instead of 0.
=> Handle case where parameters is empty sequence

wandb/wandb_config.py
Behavior before this change
1) Run created on heartbeat next_args call in gorilla (with hyperparameters)
2) Agent picks up the hyperparameters and writes them into config.yaml
3) Agent runs the training script
4) Training script calls wandb.init() with no args (config is saved to the server with *NO* hyperparameters)
5) training script calls wandb.config.update(), parameters are updated
6) training script ends, parameters are updated
So the race between between 4->5, or 4->6 can make hyperparameters choices very poor.
There still appears to be a race (in gorilla?), but this is the only CLI change for now.
=> pick up config.yaml from run_dir (important for agents)

wandb/wandb_controller.py
util.get_module not used because we want to see the underlying module error
=> fix issue where numpy isnt installed crashes wandb

wandb/data_types.py
Previously the `run_id` column on dataframes was `None` for all rows.
=> Fix run_id logging as None

CHANGELOG.md, standalone_tests/performance.py, wandb/apis/internal.py, wandb/run_manager.py, wandb/util.py
This fixes a few things around error messages:
1. We were displaying generic graphql errors even when we received empty messages
2. We retried 404's indefinitely
3. Don't start the run stopper thread in dryrun mode
BEFORE:
AFTER:
=> Fix error messages when 404ing

tests/test_meta.py, wandb/meta.py
Users with notebook in sub directories were getting errors.  This makes the environment variable take precedence and creates sub directories in "code".
=> Fixes for notebook_metadata

tests/test_run_manager.py, wandb/file_pusher.py
If only 3 or fewer files would be in a batch, upload them individually to minimize server overhead.
=> Add minimum size for a batch

wandb/keras/__init__.py
if you arent on tf2 the patch logic fails because the import fails
I think it was supposed to be get_module not import_module
=> Fix broken keras image logging with tf1

tests/test_data_types.py, wandb/data_types.py
Fixes a customer bug about compression artifacts in images.
Chris suggested making the compression level configurable. I held off doing that for now because the images in question here are the batched ones. I'm not sure there's a good way for all the images in a batch to come to a consensus on which format they should be saved in, and I think we're trying to avoid expanding that feature.
=> Switch to using PNGs rather than JPGs for uploaded images

wandb/cli.py
Add code to make parent directory before download file for `wandb pull` command.
=> Fix to wandb pull command when directory is exists in source

requirements_dev.txt, tests/test_fastai.py, wandb/fastai/__init__.py
**Work in Progress**
* **TODO: add fastai dependency for testing. Is it supposed to be in `requirements_dev.txt`?** @vanpelt 
* TODO: update website documentation per docstring changes
* Optional: test arg `log` -> same as pytorch tests
* Optional: test args `monitor` and `mode` -> not easy
* Optional: test validation data args - `validation_data`, `predictions` and `seed` -> not critical at this stage but it should not be too hard
* Optional: check more types of image logging (bounded boxes, semantic segmentation, image to image…) as they -> I would need to create small datasets and upload them somewhere or create fake ones.
**Already Done**
Tests added to WandCallback:
* callback added to the model: verification of epoch, metrics, model topology, model file
* callback added at the …
=> [WIP] test(fastai): add test of WandbCallback

wandb/util.py
Shawn thinks wandb.init anonymode to default to never for now.  Open source we will send PRs with init(anonymous=allow)
=> default to anonymode being off by default.

requirements_dev.txt, tests/test_internal_api.py, tests/test_settings.py, wandb/settings.py
Using backwards compatible `configparser` so that all the features from 3 are available in 2: https://python-future.org/compatible_idioms.html#configparser
Going to launch a regression run to ensure things aren't broken.
=> Settings should respect default section

wandb/util.py
Anonymode (https://github.com/wandb/client/commit/252dbaab5037daabd4383fcf7bc5c93a15942284) introduced a regression in the handling of onprem API keys, which this PR fixes. (The post-dash suffix is 40 chars, not the entire key).
=> Fix regression in API keys for VM

wandb/util.py
Doesn't do anything for the moment but it's good to make clear that onprem is not a wandb.ai account. We can do more validation (enforce presence of a non-wandb.ai base url, require prefixed api key) in a follow up PR.
Before:
After:
=> Add onprem option to login

tests/test_cli.py, wandb/cli.py, wandb/util.py
Running `wandb login` currently always generates an anonymous login after the first anonymous login. This means that anonymous users will be stuck and unable to log in normally unless they clear their `.netrc`.
=> Fix stuck wandb login after an anonymous login

requirements_windows.txt, wandb/compat/windows.py, wandb/run_manager.py
Right now, we wrap certain windows args (like filepaths) in single quotes, which don't get stripped out by the windows shell.
=> Escape windows args with double quotes instead of single quotes

requirements_dev.txt
with attrs-19.2.0
(wandb-2.7) jhr-mbp:client jeff$ pytest
File "/Users/jeff/.pyenv/versions/wandb-2.7/bin/pytest", line 10, in <module>
sys.exit(main())
File "/Users/jeff/.pyenv/versions/2.7.13/envs/wandb-2.7/lib/python2.7/site-packages/_pytest/config/__init__.py", line 61, in main
config = _prepareconfig(args, plugins)
File "/Users/jeff/.pyenv/versions/2.7.13/envs/wandb-2.7/lib/python2.7/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
config = get_config()
File "/Users/jeff/.pyenv/versions/2.7.13/envs/wandb-2.7/lib/python2.7/site-packages/_pytest/config/__init__.py", line 156, in get_config
pluginmanager.import_plugin(spec)
File "/Users/jeff/.pyenv/versions/2.7.13/envs/wandb-2.7/lib/python2.7/site-packages/_pytest/config/__init__.p …
=> new version of attrs is broken with old pytest

CHANGELOG.md, tests/test_torch.py, wandb/__init__.py, wandb/wandb_torch.py
This will allow multiple calls to wandb.watch in the same process.  Instead we store a bool on the model itself which is a little hacky but should work...  Also added an idx parameter to watch to support multiple watch calls on different models that each should have their own graph logged.  This feature is unlikely to be used by many, but figured we should have it.
=> Refactor watch_called to be set on a per model basis

wandb/keras/__init__.py
The `or` crashes when `class_colors` is not `None`. This replaces it with a ternary
=> keras: fix user-passed class colors

conftest.py, standalone_tests/get_sweep_runs.py, standalone_tests/simple_sweep.py, tests/api_mocks.py, tests/test_public_api.py, wandb/apis/__init__.py, wandb/apis/public.py
Also
- Add unit tests
- Add manual test scripts
- Warn about WANDB_* environment variables when running unit tests
- Stop silently clearing WANDB_* environment variables (in tests)
- Refactor graphql mocking to make it easier (for me) to understand
- Add docstrings
WB-568
=> Add sweeps to runs in public API

wandb/util.py
When someone tries to log a very large object, we issue a warning. Previously, that warning printed the entire object to the user's terminal, making it impossible to see what the warning was or where it occurred. This changes it to only print out the object's type and its size.
=> When warning about large objects, don't print the entire object

wandb/dataframes.py
When using the `image_categorizer_dataframe` function for only one output value the conversion to a two class format is broken since `np.concatenate` takes in a list of arrays for the first argument.
=> Fix numpy concatenation

conftest.py, wandb/util.py
Lyft hit this issue because their VM had one file but not the other.
=> Dont assume we have resourceconfig

conftest.py, tests/test_torch.py, wandb/__init__.py, wandb/apis/public.py, wandb/wandb_torch.py
Could test it more, but definitely better than what we have.  Also realized we were making metrics like "gradients/graph_1conv_1.bias" before which is silly.  Now we name them "gradients/model_1/conv_1.bias", this will make current runs change their metric names but I think the impact will be minimal.
=> Fix wandb.watch, add unwatch, fix sweep bug

wandb/__init__.py, wandb/wandb_config.py
This is safer than the other approach since we do weird stuff writing to config with different processes :)
The old approach:
https://github.com/wandb/client/pull/550
=> detect framework at wandb.init() time

wandb/util.py
The connection to Sentry is initialized regardless of the value of `WANDB_ERROR_REPORTING`. The value is only checked when individual functions `sentry_message` and `sentry_exc` are called.
This PR enables the call to `sentry_sdk.init` depending on the value of `WANDB_ERROR_REPORTING`.
=> Disable Sentry initialization if error reporting is disabled

standalone_tests/file_stream_long_line.py, wandb/__init__.py, wandb/apis/file_stream.py, wandb/history.py, wandb/run_manager.py, wandb/summary.py, wandb/util.py
- Print an error when we drop a file streaming chunk.
- Truncate history and summary lines that are too large for the backend to store properly, and print an error when we do. The full data will be uploaded at the end of the run but data won't be visible in plots.
- Don't retry fatal HTTP errors. When we do this with large requests, it stalls the CLI for a really long time.
- Improve error reporting when the W&B process is stalled. If the user presses ctrl-c, it's better to let the SIGINT through to the W&B process rather than just killing it, because that way we'll get a traceback. If it still doesn't die and they press ctrl-c again, then we kill it.
- Don't indent summary JSON. It wastes a lot of space (> 50%) for large JSON.
=> Improve handling of oversized data

wandb/apis/public.py
This adds optional `min_step` and `max_step` parameters to the public api `run.sampled_history` which lets you just fetch a specific step range.
There's a bunch of extraneous changes because my editor strips trailing whitespace :(
=> Support step range on public API run.sampled_history

conftest.py, tests/test_wandb.py, wandb/__init__.py, wandb/wandb_run.py
This should make running multiple runs in the same process simpler by:
1.  Automatically calling join on the last run if it exists and reinit=True
2. Warning if the stack grows to more than a single run
3. Making wandb_run a context manager that calls wandb.join on exit
4. Adds support for marking runs as failed by passing exit_code to wandb.join
5. Adds a `.log` method to wandb.run to make logging directly from the object easier.
6. Closes open files on join
=> Improve support for multiple runs

wandb/apis/public.py
This changes `run.lastHistoryStep` to be fetched every time you read it. This fixes an issue where you can't continue to scan run history while its running, as it will only ever scan up to where the run was when you got the run object.
=> public: fix scan_history on running runs

wandb/cli.py, wandb/wandb_agent.py
Improvements:
- specify the number of runs for an agent:
wandb agent AGENTID --count 1
- specify project and entity in your sweep config yaml file
- python sweeps works with early stopping (relying on kill though, terminate still not handled)
- remove project from `wandb status`, not sure what it was doing there.
=> sweep improvements:

wandb/file_pusher.py
Fixes 
```
Exception in thread Thread-13075:
File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/opt/conda/lib/python3.7/site-packages/wandb/file_pusher.py", line 85, in run
self.cleanup_file()
File "/opt/conda/lib/python3.7/site-packages/wandb/file_pusher.py", line 76, in cleanup_file
os.remove(self.save_path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqi2z3mzhwandb/config.yaml'
```
=> fix FileNotFoundError

wandb/cli.py, wandb/wandb_agent.py
Message will recommend using a full sweep path: entity/project/sweep_id
This makes it much simpler to run on other machines.
Message looks like:
wandb: Creating sweep from: /Users/jeff/Downloads/sweep (4).yaml
wandb: Created sweep with ID: 0y526anj
wandb: View sweep at: http://app.wandb.test/jeff/uncategorized/sweeps/0y526anj
wandb: Run sweep agent with: wandb agent jeff/uncategorized/0y526anj
=> Improve agent command message

wandb/apis/internal.py, wandb/cli.py, wandb/util.py, wandb/wandb_agent.py
The recommended usage is:
```wandb sweep --update entity/project/sweep_id sweep.yaml```
It will accept `sweep_id` or `project/sweep_id`, but if the user has not configured their entity yet, we do not auto calculate entity on query operations and a query is required before the upsert to get the obj_id
=> allow update of sweep

wandb/apis/public.py
Was trying to run [this example](https://docs.wandb.com/library/api/examples#export-metrics-from-a-large-single-run-without-sampling) and got this error:
```
File "export.py", line 13, in <module>
fid_trains = [row['global_step'] for row in history]
TypeError: iter() returned non-iterator of type 'SampledHistoryScan'
```
=> run.scan_history() should return a valid iterable

wandb/fastai/__init__.py
When trying to log prediction samples, we now test if there are any fastai related issues and log them. The rest of the process continues (logging of metrics and model).
This happens when using arg `input_type` with `wandb.fastai.WandbCallback`.
fix #783
=> feat(fastai): handle fastai related exceptions

wandb/jupyter.py
It's possible for a Jupiter notebook to exist without the 'notebook' key in it's metadata dictionary. clients such as VSCode will create temporary notebooks that exhibit this behavior, resulting in the following error:
```
/usr/local/lib/python3.7/site-packages/wandb/jupyter.py in notebook_metadata()
108             if isinstance(nn, dict) and nn.get("kernel"):
109                 if nn['kernel']['id'] == kernel_id:
--> 110                     return {"root": s['notebook_dir'], "path": nn['notebook']['path'], "name": nn['notebook']['name']}
111     return {}
112 
KeyError: 'notebook'
```
This PR adds a check for the 'notebook' key when returning metadata that prevents the wandb client from failing. 
related to the following Issue: https://github.com/wandb/client/issues/678
=> Check for malformed Jupyter notebook metadata

wandb/gym/__init__.py
python3.5 re.Match class does not implement  `__getitem__`, throwing an error when trying to use gym monitoring. This fix enables compatibility with 3.5.
=> python3.5 compatibility

docs/markdown/wandb_api.md, wandb/__init__.py, wandb/wandb_torch.py
Currently this does not work under jupyter in one cell:
```
Cell 1:
wandb.init()
wandb.watch(...)
run model
```
Or this:
```
Cell 1:
wandb.init()
Cell 2:
wandb.watch(...)
Cell 3:
wandb.log(..)
Cell 4:
run model
```
This does work currently:
```
Cell 1:
wandb.init()
Cell 2:
wandb.watch()
Cell 3:
run model
```
This is because under jupyter we need to reset history every cell that calls wandb.log() (we also do it on wandb.init())
This change is a bit hacky but it will keep a weak reference to the run and if run under jupyter and when gradient and parameter hooks need to log to the history and history has been destroyed, we look up history from the run
=> Recover history from run when running under jupyter

wandb/wandb_agent.py
First part of changes to add more configurability to sweep agents.
The important part of this is that the agent now queries the sweep config.  Currently there is still little validation or error messages (coming in a future PR).
This change introduces to the sweep config:
```
command:
- python3
- ${program}
- ${args}
```
This will give users more control over how things are executed.
This also works if their program is executable:
```
program: ./train.py
command:
- ${program}
```
Notice if you leave out `${args}` you wont pass args to the training script and just use config.
A future change will introduce other ways to control the command line, like:
```
settings:
agent-command-interpretter: python3
```
But it isnt included in this PR as some of the details arent figured out with how best …
=> add command to sweep config to control agent exec

wandb/meta.py, wandb/run_manager.py
The underlying problem still exists, but instead you should get:
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb/debug.log
Changes to come:
=> Improve socket creation timeouts

wandb/wandb_agent.py
There seems to be less issues with the agent so we can remove some of the verbose debugging information.
It can be re-enabled with:
WANDB_AGENT_REPORT_INTERVAL=5 wandb agent SWEEP_PATH
=> make agent less noisy

wandb/__init__.py
Fixes #808
Testcode:
```python
import wandb, os
import tempfile
with tempfile.TemporaryDirectory() as t:
f = wandb.restore('config.yaml', root=t, run_path="borisd13/colorizer/runs/dckzfkk5", replace=True)
expected = os.path.join(t, 'config.yaml')
actual = f.name
assert expected == actual
```
=> Fix root path argument for wandb.restore()

docs/markdown/data_types.md, edgeml_tests/test_fastai.py, edgeml_tests/test_tensorflow_keras.py, standalone_tests/all_media_types.py, tests/test_data_types.py, tests/test_history.py, tests/test_keras.py, tests/test_summary.py, tests/test_torch.py, wandb/data_types.py, wandb/util.py
This PR is ready for review.
We now save tables, plots and model graphs as media files rather than putting them inline in summary and history.
Frontend is deployed, so this is ready for merge.
=> Save table, plot and graph as files

standalone_tests/sparse_tensors.py
Sorry I missed this in your last review @raubitsj. Feel free to merge when you approve.
=> Remove project name from call to wandb init in sparse_tensors test.

wandb/wandb_torch.py
This should help us better deal with older versions of pytorch.
=> Use is_sparse property to determine if a tensor is sparse instead of isinstance call

wandb/wandb_config.py
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
=> Fix DeprecationWarning for collections.Sequence

docs/markdown/keras.md, wandb/keras/__init__.py
Docs say we save summary for best monitored metric so lets do that.
This will change the behavior of previous scripts by adding (by default) two new summary values:
best_epoch
best_val_loss
This can be disabled by specifying:
WandbCallback(log_best_prefix=None)
I am not in love with that parameter name if someone has a better suggestion.
=> Actually do summary log for best metric

wandb/data_types.py, wandb/run_manager.py, wandb/util.py
This fixes an issue where we don't show the model tab on windows, and possibly other types of media).
=> Put forward-slash paths in media file references.

tests/test_wandb.py, wandb/__init__.py, wandb/history.py, wandb/wandb_run.py
Currently this doesn't log the final step:
```
wandb.init()
wandb.log(dict(this=2), step=1)
wandb.log(dict(this=2), step=2)
```
Fix is to close the history at the end of the program (we do this right in join() already, no problem doing it twice if join is already done)
Also we don't handle this correctly:
```
wandb.init()
wandb.log(dict(this=2), step=1, commit=True)
sleep(1000000000000)
```
The user would expect this to commit the step but it doesnt since we change the default behavior for specified steps but we dont provide a way to force a commit.  
The fix is to default commit=None and use default of true when step is not specified, and false if step is specified.
Unit tests are needed.
=> Fix wandb.log() behaviors

wandb/stats.py
Some notebook's GPUs don't provide information about power usage (like the mobile GTX 1050, Win10, 441.45). It leads to missing any available GPU stats.
=> Fixed missing any GPU stats when accessing power usage on the notebook's GPU.

docs/markdown/cli.md, tests/test_internal_api.py, tests/test_run_manager.py, tests/test_settings.py, tests/test_wandb_run.py, wandb/apis/internal.py, wandb/cli.py, wandb/docker/__init__.py, wandb/settings.py, wandb/util.py
This fixes issues with `wandb local` and adds a couple features.  The main addition is no longer writing the local settings file unless `wandb init` is called from the cli.  @raubitsj I changed one line in the controller.  By default we don't persist the setting to disk, but to persist it in memory.  I'm worried perhaps somewhere we started depending on the persistence across procs...
=> Improvements to local, stop writing settings in local dir

.vscode/settings.json, wandb/stats.py
If a GPU is being used by the current process (or its parent, accounting for the forking off of our logging utility), all of its metrics will be logged a second time as `system/gpu.process.{index}.{metric}`.
You wind up with a whole bunch of metrics:
It would be better to log these metrics in a non-duplicative way, but this at least makes the data available.
=> Log metrics for GPUs in use by the training process separately

wandb/wandb_run.py
Access `watch` method directly from Run object.
Some frameworks use directly the Run object to run their experiments and don't import wandb within their callbacks. This will let them have access to the watch method.
=> Access watch method from run object

wandb/__init__.py
I think this is causing lots of log statments in certain environments.
=> Only make the wandb logger use debug

tests/test_meta.py
Due to some fixes of `ResourceWarning`s this test fails now.
Consider:
1. https://stackoverflow.com/a/12028682/963277
2. https://six.readthedocs.io/
> `six.BytesIO`
This is a fake file object for binary data. In Python 2, it’s an alias for `StringIO.StringIO`, but in Python 3, it’s an alias for `io.BytesIO`.
So we can't use `six.BytesIO` which is equal to `six.StringIO` in Python 2. We also can't use `io.BytesIO` because it works with bytes string and test will pass in Python 2 and fail in Python 3. The only way I see is too monkeypatch `six.StringIO` which works great both in Python 2 and Python 3.
=> Fix test_meta_cuda

wandb/data_types.py
Raises MAX_ROWS from 1000 to 10,000.
Makes ROC/PR curves less insane because we're less likely to chop them off. Requested by users in intercom.
=> raise table limit

wandb/sklearn/__init__.py
The docs for `model` argument in sklearn's `plot_outlier_candidates` and `plot_residuals` shows:
```python
Arguments:
model (regressor): Takes in a fitted classifier.
```
It is misleading and should instead be (as in `plot_regressor`):
```python
Arguments:
model (regressor): Takes in a fitted regressor.
```
=> docs reflects the usage of a regressor instead of a classifier

wandb/fastai/__init__.py
MultiCategoryList labels could not be logged as images.
fix #519
=> fix(fastai): handle MultiCategoryList labels

wandb/wandb_config.py
Allow logging slice as config parameter.
fix #952
=> fix: log slice as config parameter

wandb/data_types.py
Data that is binned in `wandb.Histogram`s init are converted into lists, but pre-binned data given through `np_histogram` was not which appears to cause some issues.
Now pre-binned data is also converted into lists.
Fixes #975.
=> fix: convert pre-binned histograms to lists

docs/markdown/data_types.md, tests/test_torch.py, wandb/data_types.py, wandb/wandb_torch.py
Check for nans when logging pytorch histograms. If a logged tensor contains nans or infs, I first try to remove them and bin the remaining element. If it's all nans/infs, we just don't log it.
Includes a test.
=> Add nan checks in pytorch histogram logging code

wandb/data_types.py
Binary image masks, image masks with a range of [0-1] were being converting to a range of [0-255] and breaking the mask data.
=> [Bugfix] Binary image masks

.github/workflows/docs.yaml, conftest.py, requirements_dev.txt, wandb/__init__.py, wandb/file_pusher.py, wandb/history.py, wandb/jupyter.py, wandb/meta.py, wandb/run_manager.py, wandb/wandb_config.py, wandb/wandb_run.py
I found some pretty glaring issues with our current jupyter integration.
1. We were starting multiple RunManagers because we didn't set paused=False until after initialization.  This caused multiple file_pushers to attempt to send metrics to wandb.  It was awful.
2. We spool up batches of files but don't de-dupe them before sending to wandb
3. We were closing the history after finishing our file streaming apis which would cause us to lose metrics
4. We would never save code in jupyter because our current logic assumed a separate process
As a bonus I snuck in internet connection detection in kaggle for @lavanyashukla
=> Mega changes for jupyter

wandb/wandb_torch.py
Fixes a crash when you try to log a non-contiguous pytorch tensor
=> Handle non contiguous pytorch tensor

tests/test_lightgbm.py, wandb/catboost/__init__.py, wandb/catboost/utils.py, wandb/lightgbm/__init__.py, wandb/lightgbm/utils.py
Again, the feature is related to issues #992, #981 and #965.
Implementation is similar to https://github.com/wandb/client/pull/1031.
- Add lightgbm plot feature importances functionality
- Also, **notebook to illustrate on how to use this feature: https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/cloud-devops-infra/wandb/feature-importance/lightgbm_feature_importance_tutorial.ipynb**
Works in the W&B Dashboard via local runs:
=> LightGBM: Plot Feature importances after model training (similar to sklearn & CatBoost) 

wandb/catboost/__init__.py, wandb/catboost/utils.py
On the back of the PR #1031 
- added an echo to assist users after plotting chart
- performing `test_fitted()` in quiet mode and over a copy of the model rather than the actual model
=> Add catboost plot feature importances functionality (minor modifications)

standalone_tests/artifact_storage.py, tests/test_artifacts.py, wandb/apis/public.py, wandb/artifacts.py, wandb/run_manager.py, wandb/wandb_run.py
Make name a required argument to wandb.Artifact(), no longer an argument to log_artifact() or use_artifact() (when using a local artifact).
Allow passing aliases to use_artifact for the local case, but default to None.
=> Artifact API update.

wandb/__init__.py
Running wandb with [py4j](https://www.py4j.org/), throws ValueError for signal
=> Value error handling to signal

wandb/__init__.py
This fixes the issue of us not showing urls in colab after the first init / login.
=> Load the viewer in jupyter if we just authed

CHANGELOG.md, docs/markdown/wandb_api.md, tests/test_cli.py, tests/test_internal_api.py, wandb/apis/internal.py, wandb/apis/public.py, wandb/cli.py
This would happen if you had two runs running in parallel with wandb version 0.9.0. UploadJob switched to calling upload_urls rather than push on the internal api. upload_urls defaulted to using the run set in settings which was always the string "latest". This is super legacy and we don't want it.
This switches upload_urls to use current_run_id instead of 'latest' when no run is provided, and gets rid of other uses of latest
=> Fix an issue where files sync'd to the wrong run.

docs/markdown/wandb_api.md, wandb/apis/public.py
User `vrodriguez` reported an issue where he could filter runs in the public API one at a time, but not at a project level. The issue is the parsing logic it used is wrong and assumes that there will be a run specified.
=> Fix project path parsing logic

docs/markdown/data_types.md, standalone_tests/image_masks.py, wandb/data_types.py
The `dtype` check was only working for uint8 arrays and causing a confusing error otherwise
=> [Bugfix] Add support for non uint8 types for segmentation masks

docs/markdown/data_types.md, standalone_tests/image_masks.py, wandb/data_types.py
Accidentally merged my last PR early, this one has is the same as https://github.com/wandb/client/pull/1109
But with a change to the numpy import.
=> [Bugfix] Fix for non uint8 numpy arrays in segmentation maps

docs/markdown/data_types.md, standalone_tests/test_point_cloud_scene.py, wandb/data_types.py
The lidar scene now supports a new subtype: `vectors`
Defined as a dictionary:
```
{start: vec3, end: vec3, color?: vec3}
type vec3 = [number, number, number] 
```
=> [Feature] Add vector support to the lidar scene

wandb/artifacts.py
In GCSHandler you return True instead of path, making shutils.copy2 silently fail and block in later phases.
=> Return path in GCS Handler on hit

wandb/util.py
This fixes an issue where a user was passing in `numpy.float32`'s which are non-encodable in the python json lib.
=> [Bugfix] Add encoding for numpy types in json uncompressed

tests/test_data_types.py, wandb/data_types.py
We can now use `wandb.Table(dataframe=df)` to directly log `Dataframe` objects.
=> feat: add support of DataFrame to wandb.Table

wandb/__init__.py
When using Jupyter notebooks, we always see this message when importing wandb.
=> fix: wrong comparison to string

docs/markdown/data_types.md, wandb/data_types.py
Metadata was not properly being set for images that were passed by path.
This also fixes logging multiple images by path, which before would fail when seq_to_json tried to read the metadata.
=> [Bugfix] Metadata for images created by path

wandb/data_types.py
This PR let `wandb.Table(dataframe=my_df)` work with python2
=> feat: make Table compatible with pandas df in python2

wandb/jupyter.py
https://wandb.atlassian.net/browse/WB-2444
https://wandb.atlassian.net/browse/WB-2862
`nbformat.v4.new_output` doesn't like values of type `bytes`. We're supposed to encode them into a `base64` string first.
=> jupyter: base64-encode byte values before saving session history

standalone_tests/rename_file.py, wandb/run_manager.py
the rename_file method was lost on file_pusher in the artifacts refactor. That method just updated the internal stats (which is actually the wrong thing to do, since we actually sync both the old and the new file). So I just deleted the call.
The script added to standalone_tests here reproduces the issue. The issue is gone with the fix.
=> Fix crash when file is renamed inside run.dir

docs/markdown/cli.md, wandb/cli.py
Confirmed that this doesn't happen in cling.
Context: https://wandb.atlassian.net/browse/WB-2852
=> Revert global PublicApi instantiation that causes an unconditional API key prompt

CHANGELOG.md, docs/markdown/data_types.md, wandb/data_types.py, wandb/util.py
Hacky as hell, but plotly seems like it wants to stop supporting matplotlib conversion :(
=> Bring back is_frame_like to spline

tests/test_artifacts.py, wandb/artifacts.py
We were accidentally including the `name=` argument as part of the ref when adding s3 prefixes as references. This results in artifacts with broken references.
Instead, we should be computing refs using a relative path anchored at the supplied reference.
=> Fix ref tracking s3 prefixes

wandb/artifacts.py
A user reported artifact uploads failing with 408s from GCS. The errors went away when he dropped the prepare batch size from 1000 to 100, which suggests that the client wasn't able to hit all the upload URLs in time.
=> Retry 408 errors on artifact uploads

docs/markdown/wandb_api.md, edgeml_tests/test_tensorflow2.py, tests/api_mocks.py, tests/test_cli.py, tests/test_internal_api.py, wandb/apis/internal.py, wandb/apis/public.py
These are two little fixes and some annoying formatting changes for OOCL.  Makes custom downloads work in Windows by ensuring we dont replace colons in drive seperators.  Also make run_config work when not logged in.
=> Fixes for OOCL

wandb/wandb_torch.py
fix typo "instuments" -> "instruments"
=> fix typo at wandb_torch.py

wandb/apis/public.py, wandb/artifacts.py
Gives the option to use `wb` mode (for example with torch.save)
ping @shawnlewis @annirudh 
When it gets merged, I can also add it to cling @raubitsj
=> feat: add custom mode to Artifact.new_file

wandb/run_manager.py
When running [this colab demo](https://colab.research.google.com/gist/borisdayma/919a3e4d30ba2221d8857123c0783160/fastai-wandbcallback.ipynb), we frequently get yaml errors as in [this run](https://app.wandb.ai/borisd13/fastai2/runs/3cp6duih/logs).
My suspicion is that the config file may not be completely written. Everything seems to look fine in the interface so I guess it's uploaded at some point.
This outputs long threads of errors in the console.
This PR minimizes the quantity of errors that appear. For example in [this run](https://app.wandb.ai/borisd13/fastai2/runs/2wy5qiko/logs) which only displays from time to time:
```bash
wandb: ERROR Error uploading "config.yaml": CommError, /tmp/tmpb1iobzf3wandb/3q90bbp5-config.yaml is an empty file
```
This message comes from `upload_file` …
=> fix: yaml error on config file

tests/test_artifacts.py, wandb/artifacts.py
Adds support for HTTP refs. If checksumming, we get the HTTP response headers and map them to the artifact manifest entry fields as follows:
`digest`: `Etag` if it exists, otherwise we just use the URL
`size`: `Content-Length`, otherwise we leave it empty
=> HTTP ref support for artifacts

wandb/apis/public.py
https://wandb.atlassian.net/browse/WB-2571
gorilla returns a `400` for the following request:
```
runs = api.runs("axel/absolute-legend", {'summary.epoch': 9}) # should be 'summary_metrics.epoch'
print(runs.next())
```
This is expected because `summary` is an invalid column for runs. What users want is `summary_metrics` instead. Let's tell them that.
This PR currently includes temporary copy. This is how the warning shows:
```
(wandb-3.6-dev) Axels-MacBook-Pro:tutorial axel$ python runs.py
Bad request
You included a 'summary' key in your filters, which should probably be 'summary_metrics' instead.
File "runs.py", line 6, in <module>
print(runs.next())
File "/Users/axel/go/src/github.com/wandb/client/wandb/apis/public.py", line 595, in …
```
=> Api.runs(): warn when user passes in 'summary' instead of 'summary_metrics'

wandb/internal/tb_watcher.py
- use tensorboard's compat gfile implementation
- parse the file names to get created timestamp, rather than
using stat, which isn't available in the gfile implementation.
=> WB-3521 Change logic for finding tfevent files to stream.

wandb/wandb_torch.py
`reshape()` is safer to use as it will return a view when possible and makes a copy when not. `view()` will fail if underlying buffer is not contiguous.
=> [WB-3536]  torch .view() -> .reshape()

Makefile, tox.ini
This will make:
`make proto` or `tox -e proto` work without other dependency requirements
=> move proto build into tox

tests/test_cli.py, tests/utils/mock_server.py, wandb/cli/cli.py, wandb/internal/internal_api.py
This makes `wandb restore` apply `diff.patch` if it exists.  Turns out we never implemented the [patch node](https://github.com/wandb/core/blob/master/services/gorilla/resolver/run.go#L1015) in the graph.  We did implement it in our mock_server though 🤣 .
=> [WB-3544] Apply diff.patch when calling wandb.restore

wandb/data_types.py
This reverts commit 928ddb5665f408691a5d23c89945c7ee5f5e31f2.
With the reverted PR we get:
```
Failed runs:
0: wandb-wandb-examples-pyt-data-parallel:init:py27,ptn
1: wandb-wandb-examples-pyt-data-parallel:init:py27,pt0.4.1
2: wandb-wandb-examples-pyt-data-parallel:init:py36,pt0.4.1
```
Reproduce with:
./do-main-regression.sh --spec wandb-wandb-examples-pyt-data-parallel:init:py36,pt0.4.1 --cli_branch my_branch
Seems to fail everytime, but there might be a timing component.
=> Revert "In Graph#bind_to_run, move is_bound check up before new file writing happens (#1340)"

wandb/internal/internal_api.py
We've had to patch these queries in the backend ever since we upgraded our GQL library. Let's also fix them directly so that one day we can remove the backend patching.
=> Fix GQL queries where params can be none

wandb/sklearn/__init__.py
`sklearn.plot_feature_importances()` fails when `feature_names` is not provided (default is None).
This PR fixes it and allows it to accept None or an empty list ([]).
(Supersedes #1337)
=> sklearn.plot_feature_importances() feature_names fix

wandb/sdk/wandb_init.py, wandb/sdk/wandb_login.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_login.py, wandb/sdk_py27/wandb_settings.py, wandb/sweeps/config/hyperopt/hp.py, wandb/sweeps/config/tune/schedulers/async_hyperband.py, wandb/sweeps/config/tune/suggest/hyperopt.py, wandb/sweeps/config/tune/tune.py
Looks like some debugger are doing some black magic stuff with locals() .
(I though at first it was Python 3.8.5 that introduced the bug, but it turned out it's something else).
The simple code 
```
def fun():
k = locals()
return "k" in k
```
Returns 'True' in this setup (Pycharm / pydev issue ???).
Still investing why, so you may wait before considering this PR.
=> Fix for Python 3.8 new locals() behavior.

wandb/internal/sender.py
This was reported in the context of a sweep here: https://app.intercom.com/a/apps/ec5tvc5j/inbox/inbox/conversation/106557000469576
We shouldn't be resuming in a sweep context...
=> [WB-3751] Handle nil summary metrics

tests/test_public_api.py, wandb/apis/public.py
Adds an `url` property to the `Sweep` class, based on the implementation of `Run.url`.
I added a basic test that the URL matches the expected form in `test_public_api.py`, please let me know if you would like me to add something else.
=> Add Sweep.url property analogous to Run.url

tests/test_cli.py, wandb/cli/cli.py, wandb/sdk/lib/apikey.py, wandb/sdk_py27/lib/apikey.py
This one was gnarly.  If a user logged in with `wandb login --host=https://my.local.host/` we would write an empty machine into the netrc.  We also clobbered all existing records in the netrc because `machine ` is "in" all other machines.
Additionally I create a logger for cli.py so we don't get stack traces sent to standard out.
=> Don't ever write innvalid netrc [WB-3785]

wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
Before:
After:
@raubitsj not sure if this is the proper solution or not. Maybe we should be ensuring that applying global state never overrides `settings.mode` instead?
=> fix offline mode getting overriden by global settings

.circleci/config.yml
https://wandb.atlassian.net/browse/WB-3723
Seems several minutes faster! I think we could improve it further with pytest-xdist.
I'm not caching the system-level deps anymore since it's only tox and it's really fast. For the tox environments, the cache strategy is to look for, in order:
* the most recent run in the current Python, on the current branch, with the same tox/requirements/setup files
* the most recent run in the current Python, on the current branch
* the most recent run in the current Python on the master branch
Caching works on OSX and Windows as well -- for cache purposes they're treated as separate Pythons.
Interesting note: these caches are huge! Saving a new cache can take around a minute, so it pays to minimize the number of things that generate a new cache file (per the …
=> [WB-3723] Cache tox environments in circle

wandb/sdk/wandb_config.py
Currently, `six.moves.collections_abc` does not exist.
This error was fixed by #860, but the error was recurring.
=> fix 'six.moves.collections_abc'

standalone_tests/artifact_object_reference_test.py, wandb/apis/public.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py, wandb/util.py
This change modifies the Artifact Encoding strategy to "undo" the base64 encoding first, then apply hex, as opposed to applying hex on top of b64.
=> Modified Artifact Encoding Strategy

wandb/sdk/internal/sender.py, wandb/sdk_py27/internal/sender.py
Converts float to int before passing to `ToSeconds` (this is also used elsewhere in the codebase when using the ToSeconds func).
=> [WB-3736] Convert floats to ints when passing to ToSeconds

wandb/filesync/dir_watcher.py
This PR simply checks if the denominator will be greater than 0 before conducting the divide. Else, it just returns 0. This was causing a division by zero issue when not checked: https://wandb.atlassian.net/browse/WB-3833.
=> [WB-3833] Added div-zero safeguard

tests/import_wandb_test.py, wandb/apis/__init__.py, wandb/util.py
https://wandb.atlassian.net/browse/WB-3874
Before this change, 3 new directories were added to the user's import path. These were our `vendor` directories. I modified the vendor import method to return a cleanup function and wrote a test to test for any leaks in the future.
=> [WB-3874] Fixed Import Path Mutation

wandb/sdk/lib/config_util.py, wandb/sdk_py27/lib/config_util.py
This fix checks if the json string is a dictionary and that dictionary contains a value attribute before attempting to access it.
=> [WB-3873] Graceful warning when config proto values are not wrapped

wandb/sdk/internal/sender.py, wandb/sdk_py27/internal/sender.py
This appears to be the root cause of: https://wandb.atlassian.net/browse/WB-3871.
If the send handlers raise an uncaught exception, it kills the `SendManager` and no further messages are processed. This results in the user process hanging indefinitely on any synchronous requests to the internal process.
Due to the severity of this issue when hit, it seems preferable to wrap the top level `send` functions with exception handling, in the event we add new handlers with uncaught exceptions.
=> [WB-3871] Exceptions raised in handlers should not hang the user process

wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
One liner to fix cross artifact comparison UI issues. Tim is fixing the tests.
=> Use target entry's digest as our digest for artifact->artifact refs

tests/test_data_types.py, wandb/data_types.py
Beginning to round out tests for features related to DSViz, found a bug in passing an Image to another Image's constructor if that first image was not an artifact_ref. This is not yet documented functionality, but certainly need to fix
=> Test for Image passed to Image Constructor

.circleci/config.yml
Matching master cache as a default was causing some builds to pass in a branch but fail once they got to master.
Also use a fix from david to speed up linux builds (mainly cache restore)
cache expires after 15 days, so when debugging strange failures, keep that in mind, any dependancies that were updated in 15 days should be suspects.
=> circleci improvements: dont match master cache, speed up linux builds

standalone_tests/artifact_object_reference_test.py, wandb/data_types.py
While testing detectron, the user requirement for having the images in a specific path, while also having those images in a wandb.Table arrose. This surfaced a bug which arises when the user explicitly adds an image path, gives it a specific new path name, then constructs a wandb.Image which uses this image. If logged to an artifact, and later logged again to another artifact, then the path reference is broken (as it is assumed to be in `/media/images/`. This PR adds a test for such cases and implements a fix.
=> Modified Image Path Resolution to Respect Original Source Path

tests/test_mode_noop.py, wandb/dummy.py
Pickle.dump looks for a method called `__getstate__`, which due to the way Dummy is implemented, returns a new Dummy object, which triggers a new call, etc... This fix just explicitly returns a value from `__getstate__`. Also added a test.
=> [WB-3981] Fixed wandb.Dummy() Recursion error when Pickling

standalone_tests/artifact_object_reference_test.py, standalone_tests/dsviz_demo.py, wandb/apis/public.py, wandb/data_types.py
In this PR, i updated the JoinedTable constructor to allow the user to pass in results from Artifact#get_path(TABLE_NAME). The motivation is to enable JoinedTable construction without actually downloading the table data itself. This involves a few changes:
1. Allow the user to `Artifact.get_path(NAME)` on objects which were added with `Artifact.add(obj, NAME)`. This returns an artifact entry object which can be passed to the table. Moreover, this maintains our current API schema where `get_path` returns a reference and `get` instantiates the object itself.
2. All the JoinedTable constructor to accept this kind of object
3. Update the `to_json` method to handle this object properly
4. Associated integration tests.
=> Ability to create a joined table without downloading tables assets

standalone_tests/artifact_tests.py, wandb/apis/public.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
This PR reduces chances of user error by checking the artifact type before performing the log operation. Without this change, the log operation fails silently in the background and the user is unaware of the failed log.
Given the above example, a value error will be thrown on line 9.
Note: it may be up for debate if we want to throw a runtime error. I lean on the side of notifying the user so that they can fix their script, but open to discussion here.
=> [CLI-534] Checks to see if an artifact about to be logged is of the correct type

wandb/sdk/lib/apikey.py, wandb/sdk/wandb_login.py, wandb/sdk_py27/lib/apikey.py, wandb/sdk_py27/wandb_login.py
Prior to this fix, the prompt for getting an authorization token did not respect the host param passed the the .login call. Now it does (:
Fixes https://github.com/wandb/client/issues/1551
=> [CLI-564] Fixed wandb.login to respect host param

.github/workflows/60-days-stale-check.yml
Due to the fact that the version was not mentioned the action could not trigger itself.
Here I have used the latest version of the `stale action`.
=> [GitHub action]: Use latest verssion

tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
Potentially scary change. Goal is to make artifact manifests platform independent. Within artifacts, always use Unix style paths. The upload / download codepaths will make sure that they are downloaded using platform appropriate path separators.
=> Convert manifest entries to unix paths

wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
In this PR the docstrings of the `wandb/sdk/wandb_run.py` are formatted so that they line up in accordance to the `google style guide`
The documentation would look something like this: https://arig23498.gitbook.io/aritra-documentation/docs/run
=> [Docstring] Changes made to `wandb_run.py`

tests/test_data_types.py, wandb/data_types.py
Keys with slashes and spaces highlighted that paths based on the raw key are dangerous. So, let's URL encode them!
- Added a one liner to url encode the key used in path creation
- Added a unit test which fails properly on windows (where there issue was originally observed)
=> [WB-3604] Should be able to use slashes in history keys

standalone_tests/artifact_object_reference_test.py, wandb/data_types.py
Allows logging Audio objects in an Artifacts-friendly way and adds tests for same. Support for Audio in the Artifacts UI is up next.
=> Add wandb.Audio support to Artifacts

tests/test_data_types.py, wandb/data_types.py
New Bug with 0.10.13: https://wandb.atlassian.net/browse/WB-4294- i had merged a PR (https://github.com/wandb/client/pull/1624) which breaks slash based categorization of media (and use of special characters). The test I wrote passes on the CLI side, but the rendering on the UI is broken. This reverts that above PR. I will reopen the previously closed bug.
=> [WB-4294] Reverted URL encoding of Log Keys

tests/wandb_config_test.py, wandb/sdk/wandb_config.py, wandb/sdk_py27/wandb_config.py
https://github.com/wandb/client/issues/1699
https://wandb.atlassian.net/browse/CLI-641
There was a large change in 0.10.13 improving how we manage Config object updates.  Unfortunately there were a few bugs,  this PR adds some more unittests (more are needed) and fixes a user reported bug as well as one found while testing.
=> [CLI-641] wandb.config.update() should not modify passed arg

wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
Description
-----------
Today, we locally cache artifact entries based on the runtime id of the object. However, if that object is no longer referenced, and therefore garbage collected, then the ID is recycled, causing a false cache hit. This change maintains a reference to the obj to prevent this issue.
Testing
-------
Ran Integration tests and local tests
=> Fixed Issue of Recycling IDs

wandb/data_types.py, wandb/sdk/interface/_dtypes.py, wandb/sdk_py27/interface/_dtypes.py
Description
-----------
This PR improves the type system error messages. The following example showcases the concepts.
Example Type Mismatch:
```
import wandb
table = wandb.Table(columns=["A"], data=[
[None],
[{
"a": [{
"b": 1,
"c": [[{
"d": 1,
"e": wandb.Image(np.random.randint(255, size=(10,10)))
}]]
}]
}],
[{
"a": [{
"b": 1,
"c": [[{
"d": 1
}]]
}]
}]
])
```
Before:
```
TypeError: Data column contained incompatible types. Expected type <WBType:dictionary | {'type_map': {'A': <WBType:union | {'allowed_types': [<WBType:dictionary | {'type_map': {'a': <WBType:list | {'element_type': <WBType:dictionary | {'type_map': {'b': <WBType:number | {}>, 'c': <WBType:list | {'element_type': <WBType:list | {'element_type': <WBType:dictionary | {'type_map': {'d': <WBType:number | …
```
=> Improved Type System Errors

tests/test_public_api.py, tests/utils/mock_server.py, wandb/apis/public.py
Description
-----------
Insitro wants to grab checkpoints directly from their S3 bucket.  If a run is renamed they want an easy way to get the actual path to the s3 bucket.  Currently we return a url which redirects to the signed url.  This allows them to access the url directly.
Testing
-------
Added a test!
=> Quick addition of direct_url to the public api

wandb/sdk/verify/verify.py, wandb/sdk_py27/verify/verify.py
https://wandb.atlassian.net/browse/WB-4413
Description
-----------
Fixes the wandb host check to be https://api.wandb.ai
Testing
-------
Tested on my machine by WANDB_BASE_URL=https://api.wandb.ai and http://api.wandb.ai
=> [WB-4413]: Fix wandb verify host

tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/wandb_artifacts.py
https://wandb.atlassian.net/browse/WB-4305
Description
-----------
Previously `add_reference` wasn't correctly considering the `name` argument. This PR fixes that and adds a unit test.
Testing
-------
=> [WB-4305] Fix add_reference with local directories and the name argument

mypy.ini, wandb/sdk/internal/handler.py, wandb/sdk/internal/settings_static.py, wandb/sdk_py27/internal/handler.py, wandb/sdk_py27/internal/settings_static.py
https://wandb.atlassian.net/browse/WB-4342
Description
-----------
Add type annotations for internal/handler in prep of error handling rework
Testing
-------
mypy
Current type coverage:
What is missing:
- logger complains about being imprecise (dunno)
- stats.py and tb_watcher.py need to be typed
- should turn on caller enforcement of types for handler.
=> [WB-4342] type annotate some of sdk/internal

mypy.ini, wandb/sdk/internal/internal.py, wandb/sdk/internal/internal_util.py, wandb/sdk/internal/settings_static.py, wandb/sdk_py27/internal/internal.py, wandb/sdk_py27/internal/internal_util.py, wandb/sdk_py27/internal/settings_static.py
https://wandb.atlassian.net/browse/WB-4342
Description
-----------
Types for:
Testing
-------
mypy: (find this in the circleci Lint check artifacts)
https://34996-86031674-gh.circle-artifacts.com/0/mypy-results/index.html
File | Imprecision | Lines
--- | --- | ---
wandb.sdk.internal.handler | 7.64% imprecise ✅  | 314 LOC
wandb.sdk.internal.internal | 6.21% imprecise ✅  | 338 LOC
wandb.sdk.internal.internal_api | 38.66% imprecise | 1958 LOC
wandb.sdk.internal.internal_util | 0.00% imprecise ✅  | 96 LOC
wandb.sdk.internal.meta | 59.92% imprecise | 247 LOC
wandb.sdk.internal.progress | 42.62% imprecise | 61 LOC
wandb.sdk.internal.run | 24.00% imprecise | 25 LOC
wandb.sdk.internal.sample | 72.60% imprecise | 73 LOC
wandb.sdk.internal.sender | 60.03% imprecise | 768 LOC …
=> [WB-4342] internal types

wandb/vendor/watchdog/observers/__init__.py
Description
-----------
Since we just vendored watchdog, it pumps out a bunch of ugly warnings:
```
it__.py:74: UserWarning: Failed to import fsevents. Fall back to kqueue
warnings.warn("Failed to import fsevents. Fall back to kqueue")
/Users/timothysweeney/workspace/wandb-client/wandb/vendor/watchdog/observers/__init__.py:74: UserWarning: Failed to import fsevents. Fall back to kqueue
warnings.warn("Failed to import fsevents. Fall back to kqueue")
/Users/timothysweeney/workspace/wandb-client/wandb/vendor/watchdog/observers/__init__.py:74: UserWarning: Failed to import fsevents. Fall back to kqueue
warnings.warn("Failed to import fsevents. Fall back to kqueue")
/Users/timothysweeney/workspace/wandb-client/wandb/vendor/watchdog/observers/__init__.py:74: UserWarning: Failed to import …
```
=> Commented out Watchdog Warning in Vendor

setup.py
https://wandb.atlassian.net/browse/WB-4468
Description
-----------
Added support to install all the dependencies for wandb.data_types.* by using the optional dependency style: `pip install 'wandb[media]'`. This installs `numpy', 'moviepy', 'pillow', 'bokeh', 'soundfile', 'plotly'`. I kept the versions open so that the pip installer can resolve the appropriate versions.
This is helpful for users who hit the install error for lazy loading modules with `util.get_module(...)`.
Testing
-------
- I tested the process on 2.7 and 3.9 as well as run the dsviz integration suite on both which requires these packages.
=> [WB-4468] Added Ability to Install Media Dependencies Directly

tests/conftest.py, tests/test_sender.py, tests/utils/__init__.py, tests/utils/mock_server.py, tests/utils/records.py, tests/wandb_integration_test.py, tests/wandb_run_test.py
Description
-----------
- Adds utility to assist in testing from user process to the publish_q
- Adds utility to assist in testing from (user process or publish_q) to mock_server
```
Users   .  Shared  .  Internal .  Mock
Process .  Queues  .  Process  .  Server
.          .           .
+----+  .  +----+  .  +----+   .  +----+
| Up |  .  | Sq |  .  | Ip |   .  | Ms |
+----+  .  +----+  .  +----+   .  +----+
|     .    |     .    |      .    |
| ------>  | -------> | --------> |    1
|     .    |     .    |      .    |
|     .    | -------> | --------> |    2
|     .    |     .    |      .    |
| ------>  |     .    |      .    |    3
|     .    |     .    |      .    |
1. Full codepath from wandb.init() to mock_server
Note: coverage only counts for the User Process and interface code …
```
=> Testing utilites for processing context + recordq

tests/utils/mock_server.py
https://wandb.atlassian.net/browse/WB-4251
Description
-----------
It should fix the flaky test_sender tests.  it is rare so hard to know this fixes it, but it is the only race i could see.
The bug was that the ctx["requested_file"] could get changed in the middle of handing this graphql request, in most cases the issue was with the upload_urls internal api command.  The file must have changed in the middle of processing this request.  The fix was to not let it change during the handling of the graphql response.
Testing
-------
how do you test a test?
=> [WB-4251] Fix sender test race

wandb/sdk/data_types.py, wandb/sdk_py27/data_types.py
Description
-----------
regression was failing:
```
./do-local-regression.sh --spec wandb-standalone-simpsons_data_frames:init:py27 tests/main/
File "simpsons_data_frames.py", line 155, in <module>
run.summary.update({ "results3": results_data_frame(test_datagen, model) })
File "/home/raubitsj/.pyenv/versions/v2713/lib/python2.7/site-packages/wandb/sdk_py27/wandb_summary.py", line 79, in update
self._update(record)
File "/home/raubitsj/.pyenv/versions/v2713/lib/python2.7/site-packages/wandb/sdk_py27/wandb_summary.py", line 133, in _update
self._update_callback(record)
File "/home/raubitsj/.pyenv/versions/v2713/lib/python2.7/site-packages/wandb/sdk_py27/wandb_run.py", line 670, in _summary_update_callback …
```
=> fix py27 regression in data_types.py

wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
In response to this slack thread, quick docstring fix
https://weightsandbiases.slack.com/archives/C0108SLEP6K/p1614801627101100
Tim Sweeney Today at 12:00
Is this a bug or working as intended? (logging after a summary assignment overwrites summary assignment?)
run.log({"A": 1})
run.summary["A"] = 2
run.log({"A": 3})
run.finish()
Screen Shot 2021-03-03 at 12.00.23 PM.png 
Screen Shot 2021-03-03 at 12.00.23 PM.png
Carey Phelps  6 hours ago
Ah, working as intended but perhaps worth changing? log updates summary so if you wanted to set summary to say the best value instead of the last value, you would do that at the end, outside of the loop that's calling log
Tim Sweeney  6 hours ago
ok, makes sense. FWIW, this is fine to me - just wanted to double check …
=> Docstring: Fix inaccurate documentation on how summary and log work together

tests/test_tb_watcher.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk_py27/internal/tb_watcher.py
https://wandb.atlassian.net/browse/WB-4895
Description
-----------
Adds one more check of the DirectoryWatcher during TBWatcher shutdown phase. So if new files are added right at the end of training, they aren't lost to the delay
Testing
-------
Using the regression test: `wandb-wandb-examples-tbx-example`
=> [WB-4895]: Check for new files during tb_watcher shutdown

wandb/sdk/internal/stats.py, wandb/sdk_py27/internal/stats.py
https://wandb.atlassian.net/browse/WB-4916
Description
-----------
Reverts the stats log frequency to the defaults from the old cli
Testing
-------
Just based on existing CI tests.
=> [WB-4916] - Revert cli stats logging to old cli defaults

tests/test_cli.py
https://wandb.atlassian.net/browse/WB-5014
Description
-----------
mark test flaky, reenable in:
https://wandb.atlassian.net/browse/WB-5015
Testing
-------
unittests should pass more reliably.
=> [WB-5014] Mark flaky: test_sync_tensorboard_big - tests.test_cli

tests/test_cli.py
https://wandb.atlassian.net/browse/WB-5014
Description
-----------
mark test flaky, reenable in:
https://wandb.atlassian.net/browse/WB-5015
Follow on from previous attempt:
https://github.com/wandb/client/pull/1958
py38 also failed. so mark all versions flaky
Testing
-------
unittests should pass more reliably.
=> [WB-5014] Mark flaky: test_sync_tensorboard_big - tests.test_cli (try 2)

tests/test_plot.py, wandb/plot/confusion_matrix.py
https://wandb.atlassian.net/browse/WB-4835
Description
-----------
Fixes an issue with confiusion matrixes where if a user had provided a list of class_names but neither data nor labels contained classes, would shuffle class numbers down.
Testing
-------
Units Tests!
=> [WB-4835] - Confusion matrix with missing values broken

tests/utils/mock_server.py, tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_artifacts.py, wandb/sdk_py27/wandb_run.py
Description
-----------
This PR fixes the issue where a LazyArtifact does not properly dispatch the underlying properties and methods. For a full discussion of the details, see https://weightsandbiases.slack.com/archives/C01ECAXNRTL/p1615801060042300.
TLDR: the `__getattr__` override does not effectively handle dispatching to non-property methods. This fix explicitly performs the mapping.
Testing
-------
Wrote unit tests for all the mappings
=> Directly Maps LazyArtifact Symbols to _instance

wandb/sdk/wandb_init.py
Description
-----------
There's two `sync_tensorboard` keys in the documented list of parameters, this removes one of them and properly formats the over.
It also fixes the formatting of the `resume` argument documentation here: https://docs.wandb.ai/ref/run/init
=> Fix documentation formatting and duplication

tests/utils/mock_server.py, tests/wandb_integration_test.py
https://wandb.atlassian.net/browse/CLI-781
Description
-----------
Sets up per file byte accounting on the mock server. Checks the policy bytes sent against specifically the file we care about
Testing
-------
On CI, and locally. No flakeyness seen on 10 runs locally. Hopefully no flakes in CI.
=> [CLI-781-Tests-2]: Deflaking the new policy test

tests/wandb_tensorflow_test.py
Description
-----------
A bunch of tests have hardcoded indices for graphql updates which will likely result in flaky tests
as things change over time.
This PR fixes just one test that has shown up in CI to be flaky with the context parser. 
There are still hardcoded indices but this time it is based on history row updates, not on filestream chunk updates which might change.
I am not totally sure what this test wants to verify so please make sure it is still valid.
Testing
-------
=> Make tblog with wandb log less flaky

tests/wandb_test.py, wandb/integration/sagemaker/__init__.py, wandb/integration/sagemaker/resources.py, wandb/sdk/internal/internal_api.py, wandb/sdk_py27/internal/internal_api.py
https://github.com/huggingface/transformers/issues/10486#issuecomment-814934156
Description
-----------
This makes InternalApi().api_key return the key in `secrets.env` if it's there for huggingface and any other integrations that may check for api key before calling wandb.init
Testing
-------
Unit test 😎
=> Make api key work with huggingface in SageMaker

tests/test_public_api.py, wandb/apis/public.py
https://wandb.atlassian.net/browse/WB-5055
Description
-----------
Adds a check that the keys argument is a list of strings if given.
Testing
-------
=> [WB-5055] - Better error message when keys arg is bad while downloading history

wandb/util.py
https://wandb.atlassian.net/browse/CLI-806
Description
-----------
Removes the content from a log info that was causing the filestream thread to crash.
Testing
-------
Tested using client against wandb local, turning off local mid run using `docker stop wandb-local` then restarting local.
No data dropped:
https://user-images.githubusercontent.com/13547142/114602656-b6e6ee80-9c4b-11eb-91e1-ccf019ba002c.mov
=> [CLI-806][WB-5300] - Runs marked as crashed but still running, not updating

tests/test_notebooks.py, wandb/sdk/lib/apikey.py, wandb/sdk/wandb_login.py, wandb/sdk_py27/lib/apikey.py, wandb/sdk_py27/wandb_login.py, wandb/util.py
https://wandb.atlassian.net/browse/WB-5264
Description
-----------
This PR fixes WB-5264. The issue was that databricks notebooks didn't return control of the terminal to the user (for api key input) during the execution of a cell, so when a user called `wandb.login()` with no arguments, the backend process on databricks would wait forever for input, but would be unable to consume any from stdin because stdin was not tty. 
Since there is no TTY on databricks notebooks, the solution I implemented here is to simply check if the current environment is a databricks notebook, then fail with more informative notty error message:
`"api_key not configured (no-tty). call wandb.login(key=...)"`
@raubitsj I couldn't find the `strip.sh` script used to auto-generate the py27 sdk, so I just modified …
=> [WB-5264] Fix api key prompt in databricks notebook

tests/test_cli.py, wandb/sync/sync.py
https://wandb.atlassian.net/browse/CLI-827
https://github.com/wandb/client/issues/2060
Description
-----------
We were using a temporary directory when we weren't supposed to.
Testing
-------
Added an assertion
=> [CLI-827] Fix syncing files when tensorboard detected

wandb/apis/public.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_run.py, wandb/sdk/wandb_summary.py, wandb/sdk_py27/wandb_artifacts.py, wandb/sdk_py27/wandb_run.py, wandb/sdk_py27/wandb_summary.py
https://wandb.atlassian.net/browse/DOCS-74
Description
-----------
Primary focus is to improve the "shortdocs": the first line of text in the docstring, which has special handling in our documentation website and some docs renderers.
Secondarily, a few minor corrections are made to the docstring contents, including malformed "Attributes" and "Examples" sections for the Sweeps class in the public API.
Testing
-------
Does not touch any code, only docstrings, which are not covered by tests. Weakly linted, but I haven't configured my local setup to match the org's linting.
=> [DOCS-74] Fixes shortdocs

README.md
Fixes tiny spelling error "Share insights **with with** Reports" in the README.
=> Fix spelling error 'with with' in README

wandb/sdk/internal/file_stream.py, wandb/sdk/internal/sender.py, wandb/sdk_py27/internal/file_stream.py, wandb/sdk_py27/internal/sender.py
Description
-----------
- names file_stream thread
- catches exceptions in file_stream and logs them to console and logger (debug-internal.log)
- reraises exception when file_stream is being finished from wandb.finish()
NOTE:
if an exception happens in the file_stream thread, we will now hang wandb.finish() as data is not synchronized....
Here is the output:
```
wandb: Waiting for W&B process to finish, PID 58888
wandb: Program ended successfully.
Thread SenderThread:.97MB uploaded (0.00MB deduped)
File "/Users/jeff/work/wandb/client/wandb/sdk/internal/internal_util.py", line 54, in run
self._run()
File "/Users/jeff/work/wandb/client/wandb/sdk/internal/internal_util.py", line 95, in _run
self._process(record) …
```
=> [WB-5300] Fix/filestream except handling

wandb/sdk/internal/file_stream.py, wandb/sdk_py27/internal/file_stream.py
Description
-----------
Fix exception handling logging in case where requests library has an error that is not:
Timeout, HttpError, or ConnectionError
Testing
-------
Injecting a RetryError with:
```
@@ -731,6 +731,9 @@ def request_with_retry(func, *args, **kwargs):
while True:
try:
response = func(*args, **kwargs)
+            response._content = None
+            raise requests.exceptions.RetryError()
response.raise_for_status()
return response
```
=> [WB-5300] whack-a-mole: another logging error

tests/conftest.py, wandb/sdk/interface/interface.py, wandb/sdk/internal/internal.py, wandb/sdk_py27/interface/interface.py, wandb/sdk_py27/internal/internal.py
Description
-----------
- Fixes poll_exit to timeout every 5 seconds 
- communicate() now checks for internal process like publish does (it should have been there)
- print a wandb.termerror() to the console when things go horribly wrong (internal process crashes)
Testing
-------
Manually creating internal process crashes
=> [WB-5300] Lets exit(-1) when the backend crashes

wandb/sweeps/test_bayes_search.py
Description
-----------
`test_runs_bayes_nan` has been failing for py38 and py39 and making CI red. Not sure what change introduced these failures but I don't think they are significant (I dont believe these codepaths are hit frequently if ever) and should be fixed in the upcoming sweeps refactor. So I am proposing to skip this test for now.
=> mark test_runs_bayes_nan flaky

wandb/integration/sagemaker/resources.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_settings.py
https://wandb.atlassian.net/browse/WB-5290
Description
-----------
stops overwriting the user-supplied run_id with the sagemaker-generated run_id so that users can use wandb resume as normal, see the right run_id in the wandb UI, etc. 
Testing
-------
tests on branch sage-resume of wandb-examples (https://github.com/wandb/examples/commits/sage-resume), resuming functionality works as normal
=> [WB-5290] sagemaker resume fix

wandb/apis/public.py
[CLI-133](https://wandb.atlassian.net/browse/CLI-133)
Description
Helps update the group of runs after the runs are complete.
The code to verify:
```python
runs = api.runs('<entity>/<project>')
runs[0].group = 'modified_group_name'
runs[0].update()
```
Fixes #753 
Testing
-------
`make test`
=> [CLI-133] Allow renaming groups of completed runs

wandb/integration/sagemaker/resources.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_settings.py, wandb/sdk_py27/wandb_init.py, wandb/sdk_py27/wandb_settings.py
https://wandb.atlassian.net/browse/WB-5290
Merging work from: https://github.com/wandb/client/pull/2149
Description
-----------
stops overwriting the user-supplied run_id with the sagemaker-generated run_id so that users can use wandb resume as normal, see the right run_id in the wandb UI, etc. 
Testing
-------
tests on branch sage-resume of wandb-examples (https://github.com/wandb/examples/commits/sage-resume), resuming functionality works as normal
=> [WB-5290] sagemaker resume fix (#2149)

tests/conftest.py, tests/test_file_stream.py, tests/utils/__init__.py, tests/utils/mock_requests.py, tests/utils/mock_server.py
Description
-----------
Add inject_requests fixture.
Features:
- match framework (only path_suffix supported now, will support time based matches, interation based, etc)
- works with mock_server (will work with live_mock_server eventually)
- can replace request responses (right now it is hard coded into mock_server, but should be posssible to be generic)
- eventually can add request side effect (raise exception, adding soon)
Example usage:
```
match = inject_requests.Match(path_suffix="/file_stream")
inject_requests.add(match=match, response='string to respond with")
```
```
inject = InjectRequestsParse(ctx).find(request=request)
if inject and inject.response:
response = inject.response
```
This will be extended with different types of inject actions, right now it is just the string …
=> Add start of request injection testing fixture

wandb/sdk/internal/file_stream.py, wandb/sdk_py27/internal/file_stream.py
Description
-----------
A few months back we started not retrying "context deadline exceeded" errors.  These can happen a bunch during database outages and will crash the user process.  This change could cause especially large or malformed file_stream posts to retry and hang the user process, but that should happen far less often than crashing during an outage.
Testing
-------
=> Retry context deadline exceeded

tests/conftest.py, tests/test_file_stream.py, tests/utils/mock_requests.py, tests/utils/mock_server.py
Description
-----------
Lots of new tests:
- status=429 rate limit, recovers
- status=500 internal server, recovers
- status=404 not found, we fail on this
- max retries= we fail at end of 30 retries
- internal request error (not http_status)
- coverage from <70 to ~85% for file_streaam
- fix fixtures to properly handle stop events
Future work:
- much of the internal testing could use more of internal.py rather than creating its own queues and threads
- make request inject work with live_mock_server (shouldnt be hard except dealing with context that might be modified in two places)
- add more matching criteria (and make it cleaner as it grows)
Testing
-------
unittests
=> Add file_stream error tests

wandb/sdk/wandb_run.py, wandb/sdk_py27/wandb_run.py
https://wandb.atlassian.net/browse/CLI-666
Description
-----------
If `stdout` doesn't support `UTF-8`, then we shouldn't print emoji to the console -- that breaks run logging.
Testing
-------
Can reproduce the issue with this minimal script:
```
import sys
import wandb
sys.stdout.reconfigure(encoding='ascii')
with wandb.init() as r:
r.log({})
```
=> UnicodeEncodeError: 'ascii' codec can't encode character '\u2b50'

wandb/filesync/step_checksum.py
https://wandb.atlassian.net/browse/CLI-902
Fixes #2182 in a generic way, replacing the [original PR](https://github.com/wandb/client/pull/2205) by @konstantinjdobler.  I decided to catch OSError instead of BlockingIOError as python 2 doesn't have that exception defined.
=> [CLI-902] Fall back on io error

wandb/cli/cli.py
Description
-----------
https://wandb.atlassian.net/browse/WB-5400
Cleans up the docstring for and remove explicit --help flag from `wandb docker-run` command. Instead, running `wandb docker-run --help` will now print the improved docstring. This should play more nicely with our doc exporter.
Testing
-------
By running `wandb docker-run --help`.
=> [WB-5400] Cleanup docstring for `wandb docker-run`

tests/wandb_test.py, wandb/cli/cli.py, wandb/sdk/wandb_login.py, wandb/sdk_py27/wandb_login.py
https://wandb.atlassian.net/browse/WB-5545
Description
-----------
This PR writes the host specified to `wandb.login()` to the global settings file just like `wandb login --host=XXX` does. This solves the following issue:
> Calling `wandb.login(host=XXX)` doesn't persist the host parameter anywhere. Any other callers who initialize `PublicApi` or `InternalApi` instances will NOT respect the specified host.
> This causes very confusing issues. Users hit an issue where they logged an artifact successfully, but using that artifact resulted in a 'not found' error because it was trying to fetch the artifact from our public site instead of their local install!
Testing
-------
Added a unit test and verified that it failed on master and passed on this PR
=> [WB-5545] write host to global settings file in wandb.login()

wandb/sdk/internal/tb_watcher.py, wandb/sdk_py27/internal/tb_watcher.py
https://wandb.atlassian.net/browse/WB-5495
Description
-----------
https://github.com/wandb/wandb-testing/tree/master/regression/tests/main/wandb-git/wandb-examples/tbx-example would occassionally fail in regression tests. I tracked it down to a race condition in comparing the time at which the tb directory watcher started and the creation time of the tfevents file. Because the latter is stored as an integer (this is set by the OS), while the former is stored as a float, the creation time could sometimes be numerically less than the start time, even though the tfevents file was actually created later, causing TB dir watcher to ignore relevant files. Example:
created_time 1622066374 start_time 1622066374.126205
(if the OS stored more digits of precision in file created at times, …
=> [WB-5495] fix tbx-example failing flakily in regression

debug/call-log-thread-stacks.py, wandb/util.py
Description
-----------
Allows you to print all threads stack traces in each process for debugging.
```
$ pip install --upgrade git+https://github.com/wandb/pyrasite.git
$ cat wandb/debug.log | grep "backend process with pid:"
2021-06-02 14:03:22,922 INFO    MainThread:1827997 [backend.py:ensure_launched():137] started backend process with pid: 1828067
$ pyrasite 1828067 debug/call-log-all-threads.py
$ pyrasite-shell 1828067
```
The above is a similar interface which pycharm provides: (but without the pycharm)
https://www.jetbrains.com/help/pycharm/attaching-to-local-process.html
Testing
-------
Manually tested on linux
=> Add debug function to dump all stacks

wandb/sdk/data_types.py, wandb/sdk_py27/data_types.py
This PR improves the documentation for image overlay Media logging, specifically image masks and bounding boxes.
related to https://wandb.atlassian.net/browse/DOCS-136
Description
-----------
- updates the docstrings for image overlays: image masks and bounding boxes to more fully and more precisely describe all the possible arguments
- adds examples of logging image masks and bounding boxes using wandb.log() and run.log() (specifically for wandb.Tables)
- fixes a few typos
Testing
-------
Tested locally with "tox". All changes are in strings only, no code (only docstrings or error messages).
=> Better docs for Media logs: image masks and bounding boxes

tests/test_mp_full.py, tests/utils/test_mod.py, wandb/sdk/backend/backend.py, wandb/sdk_py27/backend/backend.py
https://wandb.atlassian.net/browse/WB-5640
Description
-----------
This PR (https://github.com/wandb/client/pull/2057) caused a crash when a user tries to spawn a process via the "spawn' start method.
This code sample breaks in 0.10.30:
```
import wandb
import multiprocessing as mp
def mp_func():
print("hello from the other side")
def main():
wandb.init()
context = mp.get_context("spawn")
p = context.Process(target=mp_func)
p.start()
p.join()
if __name__ == "__main__":
main()
```
Whereas it works fine in 0.10.29. 
I bisected the PR branch and traced the issue to a commit that modified how mpmain was used to temporarily overwrite the main module when spawning the wandb backend process. Turned out that the way this overwrite was done to accommodate PDB, never set the main module back to the …
=> [WB-5640] Fix Multiprocessing Spawn PDB Regression 

requirements.txt
https://wandb.atlassian.net/browse/WB-5582
Description
-----------
User reported: 
> Hi, I just updated to wandb version 0.10.30 (which we were advised to do, due to some issues with the former version). However, since the update the `wandb sweep` command appear to be broken. Upon starting a sweep I get the following message
> 
> wandb sweep sweeper.yml
> wandb: Creating sweep from: sweeper.yml
> wandb: WARNING Unable to parse settings parameter
> wandb: Created sweep with ID: lldz246q
> 
> The warning above does not appear on older versions of wandb. Also this warning happens when I start a sweep using an example found in the documentation.
> 
> Although it is just a warning, the sweep seems to be wrongly created. When trying to run a sweep job I observe the following:
> - Looking on the …
=> [WB-5582] Fix requirements.txt to not allow version of Click that breaks CLI

tests/utils/mock_server.py, tests/wandb_artifacts_test.py, wandb/data_types.py, wandb/sdk/data_types.py, wandb/sdk/wandb_artifacts.py, wandb/sdk_py27/data_types.py, wandb/sdk_py27/wandb_artifacts.py
Description
-----------
Increases the hash to use 16 hex characters.
Currently we use the first 8 hex characters to create a unique path for artifact assets. At 60k rows, this has a 34% chance of collision. Quite high - creating issues in user scripts. Worse, at the 200k limit, we would hit 99% chance of collision. Upping to 16 characters reduces collision rate for even 20M items to 0.001% chance, which is plenty of room (:
Thread: https://weightsandbiases.slack.com/archives/CGK07QYR3/p1623198976137100?thread_ts=1623179079.122100&cid=CGK07QYR3
Testing
-------
=> Reduce Collisions Probability to Near 0

tox.ini
Description
-----------
mypy made some change that isnt compatible with our proto stub generation.  Lets pin to a known working version for now and debug more later.
Testing
-------
unittests now pass
=> pin mypy, proto stubs dont seem to work with mypy>=0.900

tests/test_offline_sync.py, wandb/sdk/lib/redirect.py, wandb/sdk_py27/lib/redirect.py
Description
-----------
Fix:
- Use before initialization for _queue attribute on pipe_relay_thread (used for console redirection)
- Mark a test flaky on py27
Testing
-------
unittests pass more often :)
=> fix issue where _queue not set before thread start

wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/agent/__init__.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/runner/local.py
https://wandb.atlassian.net/browse/WB-5793
Description
-----------
Sets the run_id in the Project, uses that to populate an env var in the docker container. Used so the agent can ack something off the run queue with the correct run_id.
Testing
-------
Tested locally. Unit tests for agent are in the works but were coming along slow and I wanted to get the core functionalities merged in to be ready for Monday
=> [WB-5793]: Launch - Ack with a run_id when a run is popped.

wandb/sdk/internal/internal.py, wandb/sdk_py27/internal/internal.py
https://wandb.atlassian.net/browse/WB-5889
Description
The backend is getting hit with a large number of config updates, this PR debounces them with an interval of 30s. 
Testing
Load tests.
=> [WB-5889] make sender thread debounce interval be 30s

wandb/sdk/internal/internal.py, wandb/sdk_py27/internal/internal.py
https://wandb.atlassian.net/browse/WB-5889
Description
The backend is getting hit with a large number of config updates, this PR debounces them with an interval of 30s.
Testing
Load tests.
=> [WB-5889] make sender thread debounce interval be 30s (#2335)

wandb/filesync/step_checksum.py, wandb/filesync/step_upload.py, wandb/sdk/internal/file_pusher.py, wandb/sdk/internal/sender.py, wandb/sdk_py27/internal/file_pusher.py, wandb/sdk_py27/internal/sender.py
Description
-----------
Defers FLUSH_FS state transition till when the file pusher is finished
Testing
-------
Run this with lots and lots of files to make sure that the progress polling works
=> Defer FLUSH_FS state transition

tests/test_sender.py, wandb/filesync/step_checksum.py, wandb/filesync/step_upload.py, wandb/filesync/upload_job.py, wandb/sdk/internal/file_pusher.py, wandb/sdk/internal/file_stream.py, wandb/sdk/internal/sender.py, wandb/sdk_py27/internal/file_pusher.py, wandb/sdk_py27/internal/file_stream.py, wandb/sdk_py27/internal/sender.py
Description
-----------
To support an on-prem deploy that uses a filestore with no file metadata subscriptions available, we're updating the client to inform the server about successfully completed file uploads as part of the files heartbeat. The server will use this list of filenames to fetch and populate file metadata.
Note: while this change is safe to deploy (the server ignores unknown json keys), it will require a server side change to make this work end to end
Testing
-------
* adding assertion in existing unit test
* manual integration test with local development server (for server side changes)
=> Also tell the server about uploaded files on file heartbeats

wandb/sdk/integration_utils/data_logging.py, wandb/sdk_py27/integration_utils/data_logging.py
Description
-----------
Handles strings more effectively and reorders columns for better default view.
Example Code:
```
import wandb
import datasets
from wandb.sdk.integration_utils.data_logging import ValidationDataLogger
eval_dataset = datasets.load_dataset("common_voice", "tr", split="test")
eval_dataset = eval_dataset.select(range(10))
validation_inputs = eval_dataset.remove_columns('sentence')
validation_targets = eval_dataset['sentence']
run = wandb.init(project="example_2")
validation_logger = ValidationDataLogger(
inputs = validation_inputs[:],
targets = validation_targets,
)
validation_logger.log_predictions(validation_targets)
run.finish()
```
New Output: https://wandb.ai/timssweeney/example_2/runs/2pjnt5fx?workspace=user-timssweeney
Old Output (WTF?): …
=> Improves data logger inference

wandb/cli/cli.py, wandb/sdk/launch/__init__.py, wandb/sdk/launch/agent/__init__.py
Description
-----------
Uses the set_project_entity_defaults in agents, and adds safer checks for launch_config values.
Launch config json schema for ref:
```
{
"$schema": "http://json-schema.org/draft-07/schema#",
"$id": "http://dev.wandb.com/schema/launch_config.json",
"title": "LaunchConfig",
"description": "Weights & Biases Launch Configuration.",
"type": "object",
"properties": {
"uri": {
"type": "string",
"description": "URI of the run you intend to launch"
},
"entity": {
"type": "string",
"description": "The target entity for the launched run"
},
"project": {
"type": "string",
"description": "The target project for the launched run"
},
"name": {
"type": "string",
"description": "The run name for the launched run, displayed in th W&B UI"
},
"resource": {
"type": "string", …
```
=> Launch: better handling of launch configs

wandb/data_types.py
Description
-----------
In this PR, we remove the warning about 10k rows when logging a Table to a run. The run file logging is now the "ghost" logging - as Tables are all logged to artifacts. So this warning is just noisy confusion.
Testing
-------
=> Removed 10k Limit Warning from Tables

.circleci/config.yml, .gitignore, .yearc, functional_tests/.coveragerc, functional_tests/script-fail.py, functional_tests/with-finish.py, functional_tests/without-finish.py, functional_tests/without-finish.yea, tox.ini
Description
-----------
Many yea updates, the primary visible ones are:
- external .yea files supported
- improved error handling
- improved coverage management
- junit test report generated
Changed names of circle jobs because circle suggests only using alpha numerics in cache keys.
(This does not fix the caching problems, but it will make things cleaner as we get more jobs defined)
Testing
-------
Unittests and functional tests run.
Circle/github required checks will be updated when this gets merged.
=> Update to yea 0.3.0 -- rename circle jobs

requirements.txt
Description
-----------
CVE-2021-33503 requires urllib3 >= 1.26.5
Testing
-------
=> Pin urllib3 >= 1.26.5 to address CVE-2021-33503

tests/test_tb_watcher.py
`test_tb_watcher_save_row_custom_chart` requires tensorflow but tensorflow is not required for the py39 test suite. this  causes `lin-py39` to fail ci, this pr simply skips that test in that CI suite.
=> fix py39 test

functional_tests/mnist_convnet.py, functional_tests/mnist_convnet.yea, tox.ini
https://wandb.atlassian.net/browse/WB-6113
Description
-----------
- Comment out an assertion to make sure files are overwritten from offset 0 or appended
(this doesn't appear to be true for output.log, likely due to tqdm console logging)
NOTE: this is in yea-wandb==0.4.0 (not in this PR, though this PR updates client to use that version)
- Updates yea to support more generic checking of data.
- Adds keras magic functional test to give us some sweet sweet coverage.
Here is an example of the two newly supported clauses in the yea yaml file:
```
var:
- runs: :wandb:runs
- run: :runs[0]
- summary: :run[summary]
- config: :run[config]
- exitcode: :run[exitcode]
assert:
- :wandb:runs_len: 1
- :summary[s1]: 1
- :op:<=:
- :summary[s2]
- 2
- :config:
c1: 1
c2: 2
- :exitcode: 0
```
There are two …
=> [WB-6113] Add keras magic test, update to yea=0.4.0

tests/launch/test_launch.py, tests/launch/test_launch_cli.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/docker.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py
Description
-----------
splits the concept of `project_spec.dir` into a dir where the code to run lives (either pulled from remote or pointing to the user's local dir) and then an auxiliary dir to load config files, etc. also adds a LaunchSource enum which idk how necessary this is but it feels cleaner than relying on regexes over and over again.
Testing
-------
added a test
Release Notes
-------------
=> some restructuring to support local directories

tests/test_mode_disabled.py, wandb/sdk/wandb_init.py, wandb/sdk_py27/wandb_init.py
https://github.com/wandb/client/issues/2440
https://wandb.atlassian.net/browse/WB-6174
Description
-----------
When a run is disabled still set the dir to something reasonable.  We don't create the dir as the user asked us to run in disabled mode.
Testing
-------
Release Notes
-------------
* set run.dir to the generated directory name in disabled mode
=> Set the disabled runs dir to something reasonable

tests/conftest.py, tests/test_file_upload.py, tests/utils/mock_requests.py, tests/utils/mock_server.py
Description
-----------
Coverage for fault injection case which is being changed in base branch
Bonus, enable per run mock_server context for users of `publish_util`.
Added `artifact_manifest` per run tracking (there is more to add, but just adding things that are currently tested)
Testing
-------
These are tests!
Release Notes
-------------
=> Add fault injection for upload_file

Makefile
This PR updates the `make dist` target to ensure the `sweeps_engine` submodule is checked out before attempting to call `python setup.py sdist`. This ensures that `sweeps_engine` is bundled into the distro. 
=> make sure sweeps_engine is captured by make dist

wandb/util.py, wandb/wandb_controller.py
Fixes these two bugs related to local controller refactor:
`$ wandb sweep sweep-local.yaml`
fails for 
```
program: train-dummy.py  
method: random
controller:
type: local
parameters:
param1:
min: 2
max: 20
```
with
```
File "/Users/jeff/work/wb/client/wandb/cli/cli.py", line 798, in sweep
err = tuner._validate(config)
AttributeError: '_WandbController' object has no attribute '_validate'
```
and 
```
wandb sweep --controller sweep-local2.yaml
```
fails for
```
program: train-dummy.py  
method: random
parameters:
param1:
min: 2
max: 20
```
Testing
-------
Manually :\ 
Release Notes
-------------
=> Add `_validate` to `WandbController`

.flake8-docstrings, wandb/sdk/wandb_init.py
https://wandb.atlassian.net/browse/DOCS-186
https://wandb.atlassian.net/browse/DOCS-187
Description
-----------
This PR fixes issues with the docstrings in wandb_init.py and adds that file to the list of docstring-linted files. Changes include:
- fixing several broken links,
- using a more consistent style for links,
- docstring style linting,
- better markdown formatting inside the docstrings,
- a better module-level docstring, and
- adding links to [our guide page for wandb.init](https://docs.wandb.ai/guides/track/launch).
Testing
-------
Only touches docstrings, so no extra testing.
Ran `make test`.
Release Notes
-------------
If your change is not user-visible, write `NO RELEASE NOTES` instead, with no bullet …
=> [DOCS-186] [DOCS-187] Docstring cleanup for wandb_init.py

.flake8-docstrings, wandb/sdk/wandb_run.py
https://wandb.atlassian.net/browse/DOCS-185
Description
-----------
This PR fixes issues with the docstrings in wandb_run.py and adds that file to the list of docstring-linted files. Changes include:
- docstring style linting,
- better markdown formatting inside the docstrings,
- a better module-level docstring, and
- adding links to our guide pages for logging.
Testing
-------
Only touches docstrings. ran `make test`.
Release Notes
-------------
=> [DOCS-185] Docstring cleanup for wandb_run.py

tests/wandb_run_test.py, wandb/sdk/wandb_settings.py
[https://wandb.atlassian.net/browse/WB-6301](https://wandb.atlassian.net/browse/WB-6301)
Description
-----------
Changes the standardization of the `resume` setting. We are using the `truthiness` concept of python instead of explicitly comparing the `resume` value against `None`. When we do this, we avoid a case like the following:
```
run_id = run.id
run.finish()
run = wandb.init(id=run_id, resume="")
run.finish()
```
With the previous condition empty string for `resume` would default to `allow`. However, since it's an empty string we would assume the desired behavior is to ignore it.
Testing
-------
This fix shouldn't break any thing, since it disables an undesired behavior.
Release Notes
-------------
Below, please enter …
=> [WB-6301] Ignore empty string for resume setting

tests/utils/mock_server.py, tox.ini
Description
-----------
Update to yea==0.5.3, notable fixes:
- Adds "command-args:" key to yea spec.
- fixes issue where wandb mock server ctx parser fails if there is no summary
Example:
```
id: blah.0.1
command-args:
- junk2
- junk3
check-ext-wandb: {}
```
This will run your command as:
`python this-is-my-script.py junk2 junk3`
Testing
-------
Manually tested.
Release Notes
-------------
=> Update to yea==0.5.3 (sync small fix from yea)

tests/utils/artifact_emu.py, tests/utils/mock_server.py, wandb/sdk/wandb_run.py
Description
-----------
Sync with the artifact emulator added in yea-wandb==0.7.1
Adds an artifact (storage) emulator mode to mock_server.
It is used by yea tests for now, but could likely be used in pytest if it makes sense to do less hardcoding of conditions.
Currently only supports a subset of functionality but it will continue to be extended as needed.
Testing
-------
Not very well tested, there are still some known issues (no reset between tests) -- but this should start making testing artifacts a bit easier.
Release Notes
------------- …
=> Testing: Add artifact emulator to mock server (from yea 0.7.1)

.circleci/config.yml, requirements_dev.txt
Description
-----------
Pins tensorflow tests to < 2.6.0 because of keras changes
(Needs to be investigated and pin removed)
Testing
-------
CircleCI
Release Notes
-------------
=> Temorarily pin tensorflow<2.6.0 (test breakage)

wandb/integration/keras/keras.py
Description
-----------
Corrects argument in docstring from `validate_data` to `validation_data`.
Testing
-------
N/A
Release Notes
-------------
- Corrected typo in Keras WandbCallback docstring
=> fixes typo in docstring of Keras WandbCallback

tox.ini
Description
-----------
yea==0.7.1 / yea-wandb==0.7.3 allows a .yea file to point to a specific program.
This allows multiple yea files to test different configurations.  This isnt ideal as yea
files should offer more features to vary the inputs. but this is a good workaround for now.
Added feature is:
```
command:
program: mytest.py
```
Testing
-------
Manual testing of the new feature.
Release Notes
-------------
=> Update to yea-wandb==0.7.3

functional_tests/mnist_convnet.yea, tests/utils/mock_server.py, tox.ini
Description
-----------
yea-wandb 0.7.4 adds:
- New functions: sort, keys, len
- New ops: contains, not_contains
- New run attributes: metrics, telemetry, config_wandb, summary_wandb
- `yea --debug` now prints out all builtin variables and their values (artifacts, runs, runs_len)
- runs_len will be deprecated eventually as there is a len function now
Other changes:
- sync mock_server with a fix from yea-wandb
- add telemetry check to mnist/kerass yea test
yea changes are at: https://github.com/wandb/yea-wandb/commit/815adf36dff535ef0db9ca3c624ef8e28bfa2fb5
See https://github.com/wandb/yea-wandb/blob/main/README.md for an updated example
Testing
-------
Manual testing
Release Notes
-------------
If your change is …
=> Update yea-wandb to 0.7.4

.circleci/config.yml, setup.py, tests/launch/test_launch.py, tests/launch/test_launch_cli.py, tox.ini, wandb/cli/cli.py
Description
-----------
repo2docker put out a new release today that requires a new package: `iso8601` this adds the requirement so tests will pass on circle.
Testing
-------
Release Notes
-------------
=> fix new requirement for r2d on circle

.flake8-docstrings, wandb/integration/metaflow/metaflow.py
https://wandb.atlassian.net/browse/WB-6521
Description
-----------
- Add docstrings to user-facing part of integration
- Add import guards for metaflow and fastcore dependencies
Testing
-------
n/a
Release Notes
-------------
`NO RELEASE NOTES`
[WB-6521]: https://wandb.atlassian.net/browse/WB-6521
=> Add docs and import guard to Metaflow integration

wandb/cli/cli.py
https://wandb.atlassian.net/browse/WB-6594
Fixes #2617 
Description
-----------
This PR tames the stack trace from nil project/entity issues on `wandb sweep --update`. It checks for the condition that causes this inside the CLI callsite and prints a much nicer error using `termerror`. 
Before:
```
jsm81$ python3 -m wandb sweep <sweep_id> --update dim_latent_space=15
400 response executing GraphQL.
{"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
wandb: ERROR Error while calling W&B API: name required for project query (<Response [400]>)
File "/home/home4/jsm81/.local/lib/python3.6/site-packages/wandb/apis/normalize.py", line 24, in wrapper
return func(*args, **kwargs)
File …
```
=> [WB-6594] Improve error message from `wandb sweep --update`

.circleci/config.yml
remove keys from circle ci cache so changes to requirements*.txt are propagated to circle
Description
-----------
Testing
-------
Release Notes
-------------
=> remove keys so changes to requirements*.txt are seen in circle

tests/test_login.py, wandb/sdk/wandb_login.py
https://wandb.atlassian.net/browse/WB-6565
Description
-----------
Do not save relogin parameter into the session settings object as it should only be used for the first login attempt.
bonus fix, increase timeout on new login-timeout tests, they were a bit flaky with existing timer slop values.
Testing
-------
Manual, and unittests
Release Notes
-------------
When relogin is specified, only force login once
=> [WB-6565] Fix relogin to only relogin once

wandb/apis/public.py
Description
-----------
Makes `run.state` read only  in the public API to better support https://github.com/wandb/core/pull/7823.
Testing
-------
Release Notes
-------------
=> make run.State read only in the public api

wandb/sdk/wandb_run.py
https://wandb.atlassian.net/browse/WB-6723
Description
-----------
kaggle has source as a string intead of a list of strings. for example:
```
{'metadata': {'kernelspec': {'language': 'python',
'display_name': 'Python 3',
'name': 'python3'},
'language_info': {'pygments_lexer': 'ipython3',
'nbconvert_exporter': 'python',
'version': '3.6.4',
'file_extension': '.py',
'codemirror_mode': {'name': 'ipython', 'version': 3},
'name': 'python',
'mimetype': 'text/x-python'},
'name': 'kaggle.ipynb'},
'nbformat_minor': 4,
'nbformat': 4,
'cells': [{'cell_type': 'markdown',
'source': '\nThis is a cell',
'metadata': {}},
{'cell_type': 'code',
'source': 'wandb.init()\n',
```
Testing
-------
Manually tested and trivial.
Release Notes
-------------
Below, please enter user-facing release notes as one or …
=> [WB-6723] Fix wandbcode in kaggle

tests/test_internal_api.py, wandb/sdk/internal/internal_api.py
https://wandb.atlassian.net/browse/WB-6920
Description
-----------
there was an error spike in graphQL errors recently,  caused by an agent with `agent_id = None` trying to heartbeat:
this pr updates `agent_heartbeat` to raise a ValueError when called with `agent_id=None`.
Testing
-------
Unit test
Release Notes
-------------
Prevents agent_heartbeat with agent_id=None from retrying forever
=> [WB-6920] Raise `ValueError` when `agent_heartbeat` is called with `agent_id=None`

functional_tests/keras/tf_2_6.yea, functional_tests/mp/13-synctb-gradienttape.yea, requirements_dev.txt
https://wandb.atlassian.net/browse/WB-7310
Description
-----------
Temporary pinning of keras until tensorflow resolve versioning.
https://github.com/keras-team/keras/issues/15579
Testing
-------
Release Notes
-------------
=> [WB-7310] pin Keras version to 2.6

tests/launch/test_launch.py, tests/utils/mock_server.py, wandb/integration/metaflow/metaflow.py, wandb/sdk/launch/agent/agent.py
https://wandb.atlassian.net/browse/WB-7305
Description
-----------
Prevents the agent from sending runs to different entity or projects.
Testing
-------
Unit tested
Release Notes
-------------
- prevent agent from sending runs to a different project or entity
=> [WB-7035] Launch: prevent different project entity in agent context

wandb/sdk/data_types.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/wandb_run.py
https://wandb.atlassian.net/browse/WB-7188
Description
-----------
Adds some functionality so the internal run in the TBWatcher can send artifacts for logged custom chart tables.
Result (with the front end PR):
Testing
-------
Locally
Release Notes
-------------
- fix logging pr_curves through tensorboard
=> [WB-7188]: send custom chart table artifacts through internal interface

functional_tests/sklearn/plot_classifier-basic.py, functional_tests/sklearn/plot_clusterer-basic.py, functional_tests/sklearn/plot_learning_curve-basic.py, functional_tests/sklearn/plot_regressor-basic.py, functional_tests/sklearn/plot_summary_metrics-basic.py, tests/integrations/test_sklearn.py, wandb/sklearn/__init__.py
Description
-----------
Adds tests for `wandb.sklearn`. See closed PR https://github.com/wandb/client/pull/2867 for details.
Testing
-------
I ran the tests locally with `yea`.
Release Notes
-------------
=> add tests for wandb.sklearn

wandb/agents/pyagent.py
https://wandb.atlassian.net/browse/WB-7432
Description
-----------
`wandb.agent()` currently heartbeats 50-100 times per second, when only 1 heartbeat per 5 seconds is needed. This is because the heartbeat is in the path of a `while/continue` loop with no sleep. This PR adds a 5 second sleep to this path to ensure that heartbeats are emitted no more than once per 5 seconds in this path
Testing
-------
Manually
Release Notes
-------------
Fixes an issue where `wandb.agent()` sent too many heartbeats to the server, sometimes leading to rate limits …
=> [WB-7432] reduce pyagent heartbeat rate

wandb/apis/public.py
https://wandb.atlassian.net/browse/WB-7210
Description
-----------
This example mirrors the use cause where users would filter the displayed runs in the UI with a regular expression, using `wandb.Api().run(...)`
Testing
-------
This following snippet produces the expected output:
```python
>>> 
>>> 
>>> wandb.init(
>>>     project="wb7210",
>>>     name="myrun_20211115_161401",
>>> )
>>>
>>> api = wandb.Api()
>>> runs = api.runs(
>>>     path="dimaduev/wb7210",
>>>     filters={"display_name": {"$regex": ".*20211115.*"}},
>>> )
>>> for run in runs:
>>>     print(run, run.name, run.id)
<Run dimaduev/wb7210/3n8yj9e1 (finished)> myrun_20211115_161401 3n8yj9e1
```
Release Notes
-------------
If your …
=> [WB-7210] Add example on how to find runs with wandb.Api().runs(...) where run name matches a regex

tests/integrations/test_torch.py, wandb/integration/magic.py, wandb/wandb_torch.py
https://wandb.atlassian.net/browse/WB-6700
Description
-----------
This PR addresses an issue where a model parameter was being duplicated multiple times, using up GPU memory, when filtering out `inf` and `nan` values in order to find its minimum and maximum finite values for the purpose of building a histogram from its weights. Now, when no `inf` or `nan` values are present, this filtering step is skipped, avoiding any memory overhead. Additionally, when `inf` and `nan` values need to be removed, only one additional copy of the tensor exists memory at a time instead of two. While this is an improvement, a perfect fix would only require constant memory overhead. However, this will most likely require a custom implementation with ATen.
This PR is a correction of an earlier, rolled-back PR …
=> [WB-6700] reduce GPU memory usage when generating histogram of model weights

tests/test_data_types.py, wandb/sdk/data_types.py
Description
-----------
Function `_numpy_arrays_to_lists` resulted in traceback when 0-dim numpy array was passed as a parameter. How to reproduce:
```python
>>> from wandb.sdk.data_types import _numpy_arrays_to_lists
>>> import numpy as np
>>> x = _numpy_arrays_to_lists(np.array(4.0))
File "<stdin>", line 1, in <module>
File "/Users/rpitonak/workspace/github/client/wandb/sdk/data_types.py", line 2713, in _numpy_arrays_to_lists
return [_numpy_arrays_to_lists(v) for v in payload.tolist()]
TypeError: 'float' object is not iterable
```
The problem is the `.tolist()` call. Explanation is in the [numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html):
> If a.ndim is 0, then since the depth of the nested list is 0, it will not …
=> fix: traceback in _numpy_arrays_to_lists when 0 dim np array is provided

tests/utils/mock_server.py, tools/circleci-tool.py, tox.ini
Description
-----------
- mock_server is failing when there is no private _wandb in summary
- hack in the ability to run CI functional test jobs
- update yea-wandb and yea with small fixes
Testing
-------
All testing related
=> Fix mock_server issue causing key error, improve citool

wandb/sdk/launch/templates/_wandb_bootstrap.py
Fixes [WB-7688](https://wandb.atlassian.net/browse/WB-7688)
Description
-----------
Fixes a check in `_wandb_bootstrap.py` that didn't account for a potential newline in the req.
Testing
-------
Locally
Checklist
-------
=> [WB-7688] Fix bad check in bootstrap for wandb dev branches

wandb/sdk/internal/internal_api.py, wandb/sdk/internal/progress.py
https://wandb.atlassian.net/browse/WB-7667
Description
-----------
Customers from Absci to ZipRecruiter have reported that S3 file uploads aren't working for artifacts. The issue appears to be that regular file uploads pass in a `click` progress bar, which implements `__len__` but the default progress bar in `upload_file` does not.
For versions of `requests>=2.9.0`, if `__len__` is not implemented then it doesn't know how to set `Content-Length` and instead attempts a streaming uploading, which S3 does not support.
Testing
-------
=> [WB-7667] Fix artifact file uploads to S3 stores

tests/wandb_tensorflow_test.py, wandb/sdk/internal/file_stream.py, wandb/sdk/internal/internal_api.py
https://wandb.atlassian.net/browse/WB-7656
Description
-----------
Tinkoff reported an issue where their runs are successfully uploading files, but they aren't showing up in the UI until the run terminates. They are using the `internal://` queue which relies on the CLI signaling when files are uploaded. Currently, due to a bug in `file_stream` we never actually publish this signal until we receive a `Finish` signal.
Testing
-------
- Tested on a local install (deploy-10.wandb.io), with this script:
```
import numpy
import time
import wandb
from PIL import Image
for i in range(200):
imarray = numpy.random.rand(100,100,3) * 255
im = wandb.Image(Image.fromarray(imarray.astype('uint8')).convert('RGBA'))
run.log({'a': im})
print('uploaded ' + str(i)) …
```
=> [WB-7656] Send uploaded file list on file stream heartbeats

wandb/sdk/wandb_setup.py
Description
-----------
The current code uses a connection uuid in the socket server to determine which connection to send results back to over the socket.   The assumption was that each wandb.init() call was going to connect to the socket server and get a unique id.   This is not what happens when a user process starts a run before forking a new process that also starts a run.   The forked copy has an exact copy of the wandb_manager object which was responsible for making this socket connection.
This in general is a common issue with fork and data-structures and we will have more issues like this to fix.   The cleanest solution to this issue was to make the wandb_setup singleton object a "process local singleton" (i dont know if that is a term, but it is now).   This will make sure that …
=> Fix support in wandb-service for forked processes.

tests/test_dtypes.py, wandb/data_types.py
Description
-----------
Fixing part of https://github.com/wandb/client/commit/a4de1b19ae659d478ff26c474eb0f65392f4c2ee. I was using the set() operator to enforce uniqueness when merging lists of strings. However, json does not support sets, so they are converted to lists, which makes need to be transformed back into sets on deserialization. Note: also fixed an issue with strings in dictionary keys.
=> [Release Patch] Image Set <> List Mismatch 

functional_tests/lightgbm/lightgbm.py, functional_tests/lightgbm/lightgbm.yea, functional_tests/lightgbm/test_lightgbm.py, wandb/integration/lightgbm/__init__.py, wandb/lightgbm/__init__.py
https://wandb.atlassian.net/browse/WB-7575?atlOrigin=eyJpIjoiYzk4NTcwOWFmZGJkNGNiMDkwMzhmOTkwYWQwNDhhZTAiLCJwIjoiaiJ9
Description
-----------
This PR extends some functionality of the `wandb_callback` for LightGBM. It also adds `yea` test for the same. The improvements are:
- Automatically log the `params` as config. 
- Use `wandb.define_metric`. 
Update: Added a few more improvements.
- Added a `log_summary` function which can be imported like `from wandb.lightgbm import log_summary`.
- The `log_summary` can be used to save the best model as artifacts. (default=False)
- It can be used to log feature importance. (default=True)
Testing
-------
`yea` test. 
Release Notes
-------------
Below, please enter user-facing release notes as one or more …
=> [WB-7575] Improving wandb_callback for LightGBM

standalone_tests/grpc_server_test.sh
Description
-----------
regression suite was failing on this due to a change in how port parameters were passed.
Also needed:
https://github.com/wandb/wandb-testing/commit/ffb27ed5c7bb463afbdd447233cdb6256165f9a1
Testing
-------
Checklist
-------
=> Fix grpc standalone test

functional_tests/mp/16-offline.py, functional_tests/mp/16-offline.yea, wandb/sdk/internal/handler.py
Description
-----------
Offline mode was not working because wandb-service added a new status request to check to see if the internal threads were functioning.   The status message was meant to flow from handler to sender then generate a response.
Due to an oversight -- the dispatch was not sending to the sender when in offline mode.   always_send is required.
clearly this is a pretty fragile interface.  it should probably be cleaned up as part of adding a dispatch thread:
https://github.com/wandb/client/pull/2742
Testing
-------
yea
This was failing in the regression:
```
WANDB_REQUIRE_SERVICE=True ./do-cloud-regression.sh --spec wandb-standalone-offline-sync:init:py37 tests/main/
```
Verified it works with this branch:
```
WANDB_REQUIRE_SERVICE=True ./do-cloud-regression.sh --spec …
```
=> Fix offline mode with wandb service

.circleci/config.yml, Makefile, functional_tests/keras/keras_nonnumeric_tf_2_6.yea, tox.ini, wandb/sdk/interface/interface_sock.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
```
```
This can happen with this sequence of events with wandb service:
```
wandb.require("service")
wandb.init()
sys.exit()
```
Note there is no explicit finish call.
with wandb service this gets handled by shutting down the internal process in the atexit handler.
The atexit handler has no clean way to shutdown the daemon threads in the user process.   In the above case 
it could shut them down -- but we dont, so we keep the atexit as simple as possible.   The cases where it would
not be possible to shutdown the threads is if the above wandb.init() and no finish was called from a child process.
Testing
-------
Not really tested for this PR..  Will run in the regression and see if it fails again.  This was seen at least a few times in the …
=> Fix broken pipe when shutting down due to daemon threads

wandb/sdk/launch/docker.py
[Fixes WB-7777](https://wandb.atlassian.net/browse/WB-7777)
Description
-----------
Chowns the copied code when copying to prevent permission errors
Testing
-------
Locally with launch
Checklist
-------
=> [WB-7777] Fix launch permission error

wandb/sdk/interface/router.py, wandb/sdk/interface/router_sock.py, wandb/sdk/lib/sock_client.py, wandb/sdk/service/server.py, wandb/sdk/service/server_sock.py, wandb/sdk/service/streams.py
Fixes WB-7723
Description
-----------
Implements a couple important changes:
- Fixes the `SockSrvRdThr` to handle the case where the socket was shutdown by the client process.  Before this would spin in a tight loop receiving nothing from the socket.  When a socket is shutdown it returns 0 bytes so now we treat that differently than a timeout
- Add a check in the mux loop checking to see if the parent process (if set) has gone away.   We dont want to leave `wandb-service` processes around.   There are better ways we might want to explore, but this is a good safety check if other ways fail so we might want to keep it for good.
Testing
-------
Manual testing on linux (child-orphan.py -- will be added as a yea test in a later PR)
Also ran:
```
WANDB_REQUIRE_SERVICE=True …
```
=> [WB-7723] Shutdown wandb-service if it is orphaned

wandb/sdk/service/streams.py
Description
-----------
Fix a case where we were monitoring pid==0. (oops)
Testing
-------
standalone_tests/grpc-server-test
Checklist
-------
=> Handle grpc mode without a pid to monitor

tests/test_public_api.py, tests/utils/mock_requests.py, wandb/sdk/internal/internal_api.py
Fixes WB-7843
Description
-----------
We were accidentally raising an exception during the an exception handler where we were inspecting whether it was a class of network error where we wanted to retry.
Testing
-------
Added an injection test producing a ConnectionError exception which will not have response attribute on the exception.
=> [WB-7843] Fix upload_file exception handler

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Release 0.12.9
Testing
-------
Minimal testing as this is an emergency release to fix a regression introduced just a few hours ago.
=> Bump version: 0.12.9.dev1 → 0.12.9

requirements_dev.txt
Description
-----------
`lin-py39` tests are failing on master, this is an attempt to fix that.
Update: the CI is green everywhere so I'd guess that whatever was the issue with mpl 3.3.3, it is now solved.
Testing
-------
Tried recreating the `py39` `tox` env locally, but can't reproduce. Ssh'd into the `CircleCI` instance with the failing test: upgrading `matplotlib` to the latest version resolves it.
=> Bump matplotlib to <3.5.2 to fix tests in py39 env

tests/test_tables.py, wandb/data_types.py
Fixes WB-7995
Description
-----------
This PR fixes the loading codepath of a Table saved with mixed types. It instantiates the Table with the proper column types if present. 
Testing
-------
Unit test to simulate instantiation from `json_obj`. 
Checklist
-------
=> [WB-7995] Loading table saved with mixed types fails

wandb/data_types.py, wandb/sdk/data_types.py
Fixes WB-7221
https://wandb.atlassian.net/browse/WB-7221
Description
-----------
`codecs.open` returns a `StreamReaderWriter`. This class has an `__exit__` method which closes the file pointer/stream. A simple `with` here uses this hook to explicitly close the file. 
Testing
-------
n/a
Checklist
-------
=> [WB-7221] ResourceWarning when calling wandb.log

functional_tests/sklearn/01-plot-calibration-curve-nonbinary.py, wandb/sklearn/plot/classifier.py
Description
-----------
This patch addresses a bug that would cause `wandb.sklearn.plot_classifier`
to error out during the calibration curve generation if a list of string labels is
provided (the element-wise comparison fails in this case, and returns a scalar
boolean). Instead of erroring out, we now warn that this plot is being skipped.
Testing
-------
Checklist
-------
=> Gracefully handle string labels in wandb.sklearn.plot.classifier.calibration_curve

functional_tests/lightning/train-ddp.py
Description
-----------
Fixes the PL test to use `ddp_cpu` accelerator. It was changed to use `ddp` to avoid an issue with the latest PL changes, but currently we pin it to a version that works as expected.
Testing
-------
Checklist
-------
=> Revert Pytorch-Lightning test to use ddp_cpu

wandb/sdk/wandb_sweep.py
Description
-----------
Avoid term-logging `wandb: WARNING Calling wandb.login() after wandb.init() has no effect.`
every time `wandb.sweep()` is called.
Testing
-------
Checklist
-------
=> Do not display login warning when calling wandb.sweep()

wandb/sdk/wandb_settings.py
Description
-----------
Settings had `_cuda` defined as bool before but it was not actually checked... it should have been a string because it is taken from a file like:
```
$ cat /usr/local/cuda/version.txt 
CUDA Version 10.0.130
```
Testing
-------
tested on one machine with cuda.
Checklist
-------
=> Hotfix update cuda type to string

wandb/sdk/wandb_run.py, wandb/util.py
Description
-----------
Fix a regression in user experience that we were checking the wrong value of utf-8 encoding.
There are some refactors we should do in this area because we do this check differently in many different places.
@kptkin has a refactor coming so this is just fixing the one case that is the cause of the regression.
Testing
-------
Manually
Checklist
-------
=> Fix missing emoji

tools/setup_dev_environment.py
The file contains f-string syntax, but `python` on Macs still means (and perhaps will (and perhaps _should_) always mean) `python2.7`:
```bash
~ $ python --version
Python 2.7.18
~ $ cd src/client
~/s/client (master) $ ./tools/setup_dev_environment.py
File "./tools/setup_dev_environment.py", line 48
f"Requested invalid python versions: {invalid_versions}.\n"
^
SyntaxError: invalid syntax
```
=> run setup_dev_environment.py with python3

tests/test_data_types.py, wandb/sdk/internal/meta.py, wandb/sdk/internal/tb_watcher.py, wandb/sdk/wandb_run.py
Fixes WB-6076
Description
-----------
Escapes filenames that are passed into [InterfaceBase.publish_files](https://github.com/wandb/client/blob/e6445cdc6b032ba8b5df0807099b57a94780c84a/wandb/sdk/interface/interface.py#L348), which expects _globs_, not filenames, and therefore misbehaves when filenames contain `*` or `[...]`.
Testing
-------
Currently working on unit tests.
Manual testing: [repro](https://wandb.atlassian.net/browse/WB-6076?focusedCommentId=43246) before this change:
```bash
~/tempdir $ (cd ~/src/client/ && git checkout master)
~/tempdir $ python repro.py
<...wait a bit...>
^Z
[2]+  Stopped                 python repro.py
~/tempdir $ grep inoffensive_0 wandb/debug-internal.log
2022-01-28 12:21:22,517 INFO    SenderThread:85370 [sender.py:_save_file():944] saving file …
```
=> [WB-6076] escape filenames passed to publish_files, which expects globs

tests/conftest.py, tests/wandb_settings_test.py, wandb/sdk/wandb_settings.py
Description
-----------
`json.dumps()` was having an issue with a subclass of `enum.Enum`. Changed that to `enum.IntEnum` and it now works.
Testing
-------
Added a relevant test to `wandb_settings_test.py`.
=> Make static Settings json-dumpable

wandb/sdk/wandb_run.py
Fixed `direections` to `directions` in a doc string
=> Fixed typo - direections

tests/conftest.py, tox.ini
Fixes WB-8309
Description
-----------
Seeing a lot of similarly-looking flake recently:
git.exc.GitCommandNotFound: Cmd('git') not found due to: OSError('[WinError 6] The handle is invalid')
(then the worker would crash).
My feeling is that we're dealing with some sort of a test isolation issue, so added a bunch of context managers when dealing with `git` repo stuff in our test fixtures.
Testing
-------
Re-ran the CI a few times :) Success multiple times in a row!
=> [WB-8309] Address test flakiness on Windows

tests/wandb_run_test.py, wandb/sdk/wandb_settings.py
Description
-----------
This is a bugfix for https://github.com/wandb/client/pull/3180 to make sure information about unexpected arguments in `wandb.Settings` is passed on in situations like this:
```python
wandb.init(settings=wandb.Settings(blah=3))
```
Testing
-------
Added a relevant test to `wandb_run_test.py`
=> Pass on info on unexpected args in Settings._apply_settings()

CONTRIBUTING.md
Description
-----------
Add a note to `CONTRIBUTING.md` on using `@property` vs `wandb.sdk.wandb_settings.Property` for new settings in the `Settings` object.
Testing
-------
N/A
=> Add a note on @property vs Property in Settings

wandb/sdk/service/server_sock.py
Description
-----------
When we shutdown a run we force close the queues and sockets so that reader threads do not hang.
The code as written was basically in a tight loop of error handling..  This should behave more as intended.
This shutdown of queues and sockets could still be cleaner in the future.
There is another performance issue still being tracked down, but this is the primary culprit.
Regarding coverage... normally the ValueError case should not be hit, typically you get a handle error (OSError) first but i think there are some cases where you could get the ValueError first, would have to do some careful error injection to hit all these cases.
Testing
-------
Manually confirmed fix in regression
Checklist
-------
- Name PR "[WB-NNNN][WB-MMMM] Add support for..." similar to …
=> Fix service performance issue during run shutdown

functional_tests/mp/17-service-crash.py, functional_tests/mp/17-service-crash.yea, wandb/sdk/internal/internal.py, wandb/sdk/service/service.py, wandb/sdk/wandb_manager.py, wandb/sdk/wandb_run.py, wandb/sdk/wandb_setup.py
WB-8532
Description
-----------
When an internal "process" dies for a run, lets force an exit of the entire service process for now so that the user process does not hang waiting on a message that will never get handled.
There are better ways to do this, but this is the simplest way to make sure we always die.
The issue was we were calling sys.exit(1) from a non mainthread in the service process which is a no no.
TODO:
Testing
-------
Checklist
-------
=> [WB-8532] Quick fix for service hang

CONTRIBUTING.md, functional_tests/mp/18-multiple-crash.py, functional_tests/mp/18-multiple-crash.yea, tests/utils/mock_server.py, tox.ini
Description
-----------
Add a new test to make sure we dont hang with mult processes.
Currently we shut down the entire wandb service when one run crashes due to an internal exception... We could do better in the future.   This test makes sure that we at least don't hang in this case for now.. but in the future you could check for the other processes exiting cleanly.
Also fix a few bugs and add some features in yea:
- bug: yea-doc was using current dir instead of testdir
- bug: yea-wandb was not allowing null values to be compared
- feature: added plugin parameters to allow overriding normal mockserver addresses
New yea feature:
```
yea -p wandb:mockserver-bind=0.0.0.0 -p wandb:mockserver-host=myexternalhost run --all
```
TODO:
Testing
-------
This is a test!
Checklist
-------
- Name PR …
=> Update yea and yea/wandb to fix bugs add features and add a service test

.circleci/config.yml, tests/integrations/test_keras.py, tests/test_mp_full.py, tests/wandb_artifacts_test.py
Description
-----------
Using my recently acquired superpower of being able to run tests on Windows *locally*, I found that certain tests that flake out on Win simply sometimes take slightly longer than the default timeout of 1 minute; and `pytest` killing a running test on Win, especially one involving multiprocessing, crashes the worker in a potentially unclean manner. 
Cranking it up, hopefully it's that simple.
Testing
-------
Done locally!
=> Crank up timeouts on a number of tests

wandb/util.py
Fixes WB-8653
Description
-----------
Testing
-------
Checklist
-------
=> Fix encoding exception when using %%capture magic

requirements.txt, setup.py
Description
-----------
looks like this is no longer used in launch.  conda was complaining about an unused dep (thanks conda)
Testing
-------
untested
Checklist
-------
=> Remove yaspin from requirements

wandb/sdk/service/service_base.py, wandb/sdk/wandb_settings.py
Fixes WB-8897
Fixes #3370 
Description
-----------
When command line arguments are resolved we save them as list in `Settings`, but when we convert the `Settings` to protobuf message to send over the socket we only converted tuples, meaning all list types of `Settings` will be `None`. To avoid this we fix the utility function in `service_base` to convert lists. As well as convert the command line arguments to tuples (we don't need this change since we already addressing list with the fix to the utility function - consider to remove)
Testing
-------
Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if …
=> [WB-8897] Properly handle command line args with service

wandb/deploys/launch-agent.yaml, wandb/deploys/launch-config.yaml
Fix role binding name to prevent collision if set to be the same namespace as `wandb`
=> fix config typo

functional_tests/login/03-login-cloud-local-key.py, functional_tests/login/03-login-cloud-local-key.yea, wandb/sdk/wandb_settings.py
Fixes WB-8618
Description
-----------
Raise a verbose error when the user tries to connect to the cloud app with a local API key.
Testing
-------
Added a yea test for this scenario.
=> [WB-8618] additional api_key validation

setup.py, wandb/docker/www_authenticate.py, wandb/sdk/interface/interface.py, wandb/sdk/internal/handler.py
Description
-----------
@raubitsj @kptkin, and I discovered this bug while investigating several reported performance issues (e.g. WB-8765). This seemingly minor change delivers a massive performance gain. (Surprisingly, Python instantiates `sample.UniformSampleAccumulator` in `self._sampled_history.setdefault(k, sample.UniformSampleAccumulator())` on _every_ call.)
For example, below are parts of the profiling results for this simple script
Before the change:
After the change:
UPD:
Removed some more `setdefault`s and got another performance bump: 
Testing
-------
"Triplet" coding!
Checklist
-------
=> Use `collections.defaultdict` for `HandleManager._sampled_history`

tests/tests_launch/test_launch.py, wandb/cli/cli.py, wandb/sdk/launch/agent/agent.py
Fixes WB-8967
Description
-----------
enables `--max-jobs -1` to remove the cap on max jobs for the launch agent
Testing
-------
Checklist
-------
=> [WB-8967] Enable inf max jobs on launch agent

tests/tests_launch/test_launch.py, wandb/sdk/launch/runner/local.py, wandb/sdk/launch/utils.py
[Fixes WB-9007](https://wandb.atlassian.net/browse/WB-9007)
Description
-----------
Docker needs the gpus flag to access GPUs on the machine, this adds them for the local runner
Testing
-------
Checklist
-------
=> [WB-9007] Add gpus flag for local launch runner with cuda

wandb/jupyter.py, wandb/sdk/launch/_project_spec.py, wandb/sdk/launch/utils.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Before this PR, the command on colab notebooks would show up as the below (example for a notebook named `Launch Quickstart`):
The changes in jupyter.py (just adding .ipynb to the filename) result in the command below:
I'm not actually sure why this makes the extra `-f /root/.local/.../.json` arg go away, but I'm assuming this is not actually a useful arg for the user to see. Adding .ipynb seems reasonable to me as well, since if you download the colab notebook, the resulting filename is [name].ipynb.
Also some changes on the launch side so we detect colab notebooks.
Testing
-------
updating tests
Checklist
-------
- Include reference to internal ticket …
=> fix colab command to work with launch

wandb/sdk/wandb_init.py
Description
-----------
Ignore WANDB_SERVICE env var in env check in `wandb.init`.
Testing
-------
`yea run functional_tests/mp/06-1-share-child-base.py`
=> Ignore WANDB_SERVICE env var in env checks in wandb.init

requirements_dev.txt, tests/conftest.py, tests/utils/mock_server.py, tox.ini
[Fixes WB-9079](https://wandb.atlassian.net/browse/WB-9079)
Fixes #NNNN
Description
-----------
- for python <=3.6 installs fastcore 1.3.29 
- flask 2.1.0 crashes mock server, this fixes that
Testing
-------
Checklist
-------
=> [WB-9079] Fix fastcore and new Flask releases

.github/workflows/generate-documentation.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
I've cut a new release of the docugen action that supports the new Weave op documentation from core -- we need to update on this end so that doc updates from client don't overwrite the new Weave docs.
Testing
-------
Checklist
-------
=> Update docugen to 0.2.0 (supports weave docs from core)

wandb/sdk/wandb_manager.py
Fixes WB-7841
Description
-----------
Fix pyagent when using wandb service.
For now, pyagent is aggressively reseting the setup object between training attempts.. This makes some things work but it was breaking the service session.   For now we will teardown and restart the service session.
Testing
-------
Manually tested with sweep_check.py when enabling service... I think it is time to add a mockserver for pyagent.
Checklist
-------
=> [WB-7841] Remove service env on teardown

wandb/sdk/internal/internal_api.py
Description
-----------
Disables history step until we can better test this feature.
This change is on top of:
https://github.com/wandb/client/pull/3495
Testing
-------
Manually
Checklist
-------
=> Disable history step logging for now

CONTRIBUTING.md, standalone_tests/history_step_guardrail_log_artifact.py, wandb/sdk/internal/internal_api.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
What does the PR do? 
For context, we added the latest history step to the mutation that creates an artifact. This change was put in less than a month ago in the backend.  The corresponding SDK PR was merged at the same time. 
A Local user reported the following error when they switched to SDK versions 0.12.12 or 0.12.13. They stated that the error did not happen with 0.12.11:
```python
ValueError: error logging artifact "{user-specific data}": {'message': 'Argument "input" has invalid value {artifactTypeName: $artifactTypeName, artifactCollectionNames: $artifactCollectionNames, entityName: $entityName, projectName: $projectName, ru
nName: $runName, description: $description, digest: $digest, digestAlgorithm: MANIFEST_MD5, labels: $labels, …
```
=> history max_cli_version guardrail

.flake8-base, CHANGELOG.md, pyproject.toml, tools/locate-py-files.py
Description
-----------
- Fix pyupgrade to ignore wandb run and offile run dirs
- Fix black to ignore tests logs and pyc files
- Fix flake8 to ignore wandb run dir code directories
- fix changelog
Testing
-------
Checklist
-------
=> Fix checker to ignore more files

requirements.txt
Fixes WB-9225
Description
-----------
Somehow we've never explicitly required `setuptools` despite having relied on it for a bit:
https://github.com/wandb/client/blame/master/wandb/sdk/internal/internal_api.py#L12
Testing
-------
=> [WB-9225] Add `setuptools` to `requirements.txt`

wandb/sdk/wandb_run.py
Description
-----------
Typo in the docstring for `wandb.log()`
Testing
-------
PR only involves docstring
Checklist
-------
PR does not follow naming scheme. What would be the correct name for commit?
=> Fix typo in wandb.log() docstring.

wandb/apis/public.py
Fixes DOCS-365
Description
-----------
Reference Docs update to give context regarding `api.viewer`.`api.user()`/`api.users()` do not work for any users other than local admins.
=> [DOCS-365] Note about api.viewer in api.user() and api.users()

tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py
https://wandb.atlassian.net/browse/WB-8246
https://wandb.atlassian.net/browse/WB-8572
Description
-----------
Allows users to add a specific version of an object if bucket versioning is enabled:
- `s3://bucket/key?versionID=...` ([docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RetrievingObjectVersions.html))
- `gs://bucket/key#generation` ([docs](https://cloud.google.com/storage/docs/using-versioned-objects#prereq-rest))
Fixes a bug with artifact references in Windows where they are populated with `os.path.join`, which uses the incorrect separator for S3/GCS references.
Testing
-------
=> [WB-8246,WB-8572] Support version IDs in artifact refs, fix s3/gcs references in Windows

functional_tests/mp/22-1-multiple-finish-single-proc.py, functional_tests/mp/22-1-multiple-finish-single-proc.yea, wandb/sdk/service/streams.py
Fixes WB-9394
Description
-----------
This PR adds a check to verify we don't try to drop a run that was already finished. This fixes the issue for the `service` case.
Testing
-------
Add a functional test with multiple `finish` calls.
=> fix(service): support for multiple finish for single run

wandb/sdk/wandb_run.py
Fixes #3584 
Description
-----------
While looking through the documentation at https://docs.wandb.ai/ref/python/log, I noticed the `data` argument and the `row` argument in the docstring didn't match.  When I followed the source code link at the top of the page (https://github.com/wandb/client/blob/16658d63aa0f91dd8e98f51d766334af9b404d2b/wandb/sdk/wandb_run.py#L1361-L1420) I saw discrepancy between the argument name(L1363) and docstring(L1416 and L1420).
Testing
-------
Did not test because it's 2 word changes.
Checklist
-------
- Name PR "[WB-3584][WB-MMMM] Add support for..." similar to entries in CHANGELOG.md
[WB-3584]: https://wandb.atlassian.net/browse/WB-3584?atlOrigin=eyJpIjoiNWRk …
=> Changed wandb.log() docstring to use the  argument instead of  argument.

tests/wandb_artifacts_test.py, wandb/data_types.py
https://wandb.atlassian.net/browse/WB-7408
Description
-----------
This PR fixes a weave bug that caused this block of code 
```python
import wandb
import pandas as pd
import math
from datetime import datetime
from datetime import timedelta
current_time = datetime.now()
df = pd.DataFrame(data=[[current_time + timedelta(days=i), math.sin(2* i/(math.pi))] for i in range(10)], columns=["date", "val"])
wandb.init()
wandb.log({'data': df})
``` 
to appear as 
It now appears as 
The issue was that `np.datetime64` objects' `.tolist()` method returned an epoch in ns instead of ms, causing the `moment` library on the frontend to overflow
Testing
-------
Unit test.
=> [WB-7408] fix(weave): Natively support timestamps in Python Table Types

README.md
Added a new section to the readme highlighting how users can get started using W&B Locally.
=> Docs[Local]: add local quickstart to the wandb/client README

tox.ini
Description
-----------
adds verbosity flag to pytest command
Before:
After:
Testing
-------
N/A
Checklist
-------
=> Adds verbosity to the tox.ini pytest

tests/test_library_public.py, tests/test_mode_disabled.py
Description
-----------
Adds the service symbols (`attach`, `detach` and `teardown`)
Adds setup for the `test_disabled_dir` to be compatible with service (shouldn't change behavior) 
Testing
-------
In the non-service case it should just be a no-op
Checklist
-------
=> Modify test to work by default with service

wandb/filesync/dir_watcher.py
Fixes WB-9335
Description
-----------
Pictured below:
- **Blue:** how quickly files get uploaded by making repeated calls to `run.log({'img': wandb.Image(...)})`. Note that (a) it's slow, and (b) each image takes longer to upload than the one before.
- **Orange:** how quickly files get uploaded after this fix. (Specifically, at commit 7d4659820671f.)
**Explanation of the fix:**
- The `DirWatcher` maintains a set of filepath-globs, each associated with a "policy" indicating when the file should be uploaded. For example, there might be a glob `*.png` associated with the policy "upload when the run ends," or a glob `my-cool-metadata.json` associated with the policy "upload whenever this file changes." (Yes, that second "glob" just matches a single file, since it lacks any wildcard …
=> [WB-9335] make DirWatcher.update_policy O(1) instead of O(num files ever uploaded)

tests/wandb_integration_test.py, wandb/filesync/dir_watcher.py, wandb/sdk/internal/sender.py, wandb/sdk/internal/settings_static.py, wandb/sdk/wandb_settings.py
Fixes WB-9396
Description
-----------
This PR adds settings for live policy to allow to override default RATE_LIMIT and min_wait_time.
Testing
-------
This PR is not changing functionality so the expected behavior is for all tests to pass.
Checklist
-------
=> [WB-9396] Adds timing settings for live policy upload

.github/workflows/60-days-stale-check.yml
Description
-----------
Stale bot marks issues which are being worked on in Engineering as stale. This annoys some of our users as it feels like the issue is not being considered. Github issues are tracked in Zendesk which has its own "stale" functionality.
This change turns off Stale Bot.
=> Turning off Stale Bot

mypy.ini, wandb/integration/sb3/sb3.py
Description
-----------
This PR simply add an argument `gradient_log` in the SB3 callback in order to have more control over what is logged by `wandb.watch()`.
Testing
-------
Not tested.
=> Add argument `gradient_log` to control what to log in SB3 callback

tests/test_tpu.py
Description
-----------
Fix crash if the user happens to have process 1000 owned by root on the machine :)
Error seen:
```
/Users/jeff/work/wb/client/tests/test_tpu.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/jeff/work/wb/client/wandb/sdk/internal/stats.py:261: in stats
stats["proc.memory.rssMB"] = self.proc.memory_info().rss / 1048576.0
/Users/jeff/work/wb/client/.tox/py38/lib/python3.8/site-packages/psutil/_common.py:444: in wrapper
return fun(self)
/Users/jeff/work/wb/client/.tox/py38/lib/python3.8/site-packages/psutil/__init__.py:1061: in memory_info
return self._proc.memory_info() …
```
=> Fix tpu test to not hardcode pid

tests/test_public_api.py, wandb/apis/public.py
Description
-----------
Lets you specify an API key directly as a kwarg when constructing a `PublicApi` object. 
Testing
-------
UnitTest.
Checklist
-------
=> feat: add ability to directly specify api key to public api

wandb/sdk/internal/tb_watcher.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
`TBDirWatcher._process_events` is being call in `_thread_body` and in `finish`. Anecdotally, it does seem safe to call `self._generator.Load` concurrently. So, this PR adds a lock around that section of code to ensure that there's only one thread iterating over the tensorboard events.
Testing
-------
Checklist
-------
=> fix: not generating/consuming all tfevents

setup.cfg, tools/bumpversion-tool.py, tox.ini
Description
-----------
Adds prerelease part to `bumpversion`. 
So if you want to go from:
running: `bumpversion devkind` (on  `0.12.17`) will result in: 0.12.17 → 0.12.17.dev1
running: `bumpversion prekind` (on `0.12.17.dev1`) will result in: Bump version: 0.12.17.dev1 → 0.12.17rc1
running: `bumpversion devkind` (on `0.12.17rc1`) will result in: Bump version: 0.12.17rc1 → 0.12.17rc1dev1
running: `bumpversion pre` (on `0.12.17rc1`) will result in: Bump version: 0.12.17rc1 → 0.12.17rc2 [same for `dev`]
you can also go to new patch/minor/major from pre-realse version for example:
running: `bumpversion minor` (on `0.12.17rc2`) will result in: Bump version: 0.12.17rc2 → 0.13.0
Move from bumpversion to bump2version (bumpversion is not supported anymore and bump2version is …
=> add prekind part and pre counter <- allow skip kindversions from cmdline

.circleci/config.yml, functional_tests/fastai/01-v1.yea, functional_tests/lightgbm/01-regression.yea, functional_tests/lightning/train-gpu-ddp.yea, functional_tests/lightning/train-tpu-ddp.yea, functional_tests/login/03-login-cloud-local-key.yea, functional_tests/metaflow/wandb-pytorch-flow.yea, functional_tests/mp/01-2-simple-no-finish.yea, functional_tests/profiler/profiler.py, functional_tests/profiler/profiler.yea, requirements_dev.txt, standalone_tests/artifact_tests.yea, standalone_tests/shards/gke_gpu/Dockerfile, tests/utils/mock_server.py, tox.ini, wandb/sdk/internal/tpu.py
Description
-----------
We've had an odd `pytorch` version requirement that has been making the CI happy, but me (and more recently also [the nightly suite](https://github.com/wandb/client/runs/6487772258)) -- unhappy.
Landed on the following solution:
- Followed [the official instructions](https://pytorch.org/get-started/locally/#start-locally) from `pytorch` :rofl:
- Used `cpu` for the compute platform everywhere by default (without pinning any particular version - we were pinning an outdated version in the tests) + `sed`'ing in `cu113` in the Dockerfile for the standalone GPU shard.
Also, while looking for a solution, stumbled upon the `wandb.sdk.internal.tpu.is_tpu_available` function, which unnecessarily imports and calls some `tf` functions -- refactored it, which yields a …
=> Update `pytorch` version requirements in dev environments

.circleci/config.yml, tests/utils/mock_server.py, tools/circleci-tool.py, tox.ini
Description
-----------
This PR implements the ability to manually trigger nightly CI runs.
To use it:
First, generate a token to use the CircleCI API at https://app.circleci.com/settings/user/tokens.
Then you can trigger the nightly workflow specifying which shards (such as `cpu` and/or `gpu`) you want to build and run, and whether to post notifications to `#sdk-ci-nightly`:
```shell
CIRCLECI_TOKEN=<token> python tools/circleci-tool.py --branch=<branch> \
trigger-nightly --slack-notify --shards=cpu,gpu 
```
Also, pinned latest `yea/yea-wandb`.
Testing
-------
CI!
Checklist
-------
=> Trigger nightly CI runs manually

.circleci/config.yml
Description
-----------
Do not add Slack @mentions on successful completion of nightly jobs. Too much noise otherwise.
Testing
-------
Checklist
-------
=> Do not add Slack @mentions on successful completion of nightly jobs

requirements_dev.txt, tests/integrations/test_keras.py, tests/integrations/test_metaflow.py, tests/integrations/test_monkeypatch_keras.py, tests/integrations/test_torch.py, tests/test_cli.py, tests/test_data_types.py, tests/test_dtypes.py, tests/test_plot.py, tests/test_plots.py, tests/test_profiler.py, tests/test_redir.py, tests/test_tb_watcher.py, tests/test_telemetry_full.py, tests/test_tpu.py, tests/test_util.py, tests/wandb_artifacts_test.py, tests/wandb_tensorflow_test.py, wandb/sdk/internal/tb_watcher.py
Fixes WB-9884
Description
-----------
This PR removes the skip logic from tests since the conditions for the skips were resolved
Testing
-------
The un-skipped tests need to pass
=> [WB-9884] remove skips from test for python versions >= 3.9

.circleci/config.yml, tests/test_plot.py, wandb/plot/pr_curve.py
Fixes WB-9881
Description
-----------
Looks like `sklearn.metrics.precision_recall_curve` was misbehaving prior to `sklearn~<1.1`. Consider the following example:
```python
from sklearn.metrics import precision_recall_curve, precision_score, recall_score
y_true = [0, 1]
y_predict_proba = [0.25, 0.75]
precision, recall, thresholds = precision_recall_curve(y_true, y_predict_proba)
```
On `sklearn==1.0.2` this yields
while on `1.1.1`:
This issue was likely fixed in these two PRs:
https://github.com/scikit-learn/scikit-learn/pull/19085
https://github.com/scikit-learn/scikit-learn/pull/23214
This function is used in `wandb/plot/pr_curve.py` so that `tests/test_plot.py::test_pr` fails.
I believe things should behave correctly now. However in tests, since we install sweeps and it depends on …
=> Address precision-recall curve updates in `sklearn`

wandb/data_types.py
Fixes DOCS-382
Description
-----------
Added deprecated doc string to `Table.add_row` in wandb/data_types.py
Testing
-------
Checklist
-------
=> Added deprecated string to Table.add_row

setup.cfg, setup.py, wandb/__init__.py
Description
-----------
Release 0.12.18
Testing
-------
regression runs:
- cloud
- local(server)
- cloud with service enabled -- partial
Checklist
-------
=> Bump version: 0.12.18.dev1 → 0.12.18

wandb/sdk/wandb_helper.py
Fixes WB-9927
Description
-----------
Sentry Issue: [SDK-FR](https://sentry.io/organizations/weights-biases/issues/1911906801/?referrer=jira_integration)
```python
TypeError: vars() argument must have __dict__ attribute
File "wandb/sdk/wandb_init.py", line 996, in init
wi.setup(kwargs)
File "wandb/sdk/wandb_init.py", line 186, in setup
init_config = parse_config(
File "wandb/sdk/wandb_helper.py", line 14, in parse_config
params = _to_dict(params)
File "wandb/sdk/wandb_helper.py", line 41, in _to_dict
elif "__flags" in vars(params):
```
Testing
-------
Checklist
-------
=> Fix minor bug in `wandb_helper.py`

tests/utils/artifact_emu.py, tests/utils/mock_server.py, tox.ini, wandb/apis/public.py
[Fixes WB-9938](https://wandb.atlassian.net/browse/WB-9938)
[WB-9939](https://wandb.atlassian.net/browse/WB-9939)
Description
-----------
Fixes the query for the QueuedJob api, and in the mock server.
Updates artifact emulator to support UpdateArtifact, and sends back an artifact version.
Testing
-------
Checklist
-------
=> [WB-9938] [WB-9939] Fix QueuedJob Api query, update mock server and artifact emulator

tests/tests_launch/test_launch.py, tests/wandb_run_test.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py
[Fixes WB-9670](https://wandb.atlassian.net/browse/WB-9670)
Fixes #NNNN
Description
-----------
Handles all configs by pulling artifacts/artifact strings out of the init config and calling use artifact on these later in the init process once the run exists. Config debouncing was causing the server side config to not be updated until the run finished sometimes.
Testing
-------
Checklist
-------
=> [WB-9670] pull artifacts out of init configs, and use sweep init config during upsert run

tests/test_dtypes.py, wandb/sdk/data_types/_dtypes.py, wandb/sdk/wandb_artifacts.py, wandb/util.py
[Fixes WB-9962
](https://wandb.atlassian.net/browse/WB-9962)Fixes #NNNN
Description
-----------
Adds support for artifact strings and dictionaries representing artifacts to the TypeRegistry. This way, we can use the TypeRegistry on the run config inputs in a generic manner to match the types.
For example, I have a run with an artifact in the config, and now I want to assign a new artifact to it, rather than using 
```
artifact = wandb.Artifact()
config={"key": artifact}
input_types.assign(config)
```
I can use the string `wandb-artifact://...` as an input. This will work because the config automatically turns that into an artifact.
```
config={"key": "wandb-artifact://..."}
input_types.assign(config)
```
Similarly, in the server a run config is stored as a dictionary with an `_type` key …
=> [WB-9962]: Dtype changes for handling artifact objects in jobs and run configs

.circleci/config.yml
Description
-----------
I suggest moving KFP tests to nightly runs on master. We very rarely touch this part of the code base, and I think we don't need to run these tests on every commit given how many resources we spend on it:
When working on new relevant features, the tests could be temporarily moved to the main workflow in Circle (and then put back to nightly).
Testing
-------
- Staring at the diff.
- Triggering manual-nightly workflow:
Checklist
-------
=> Move KFP tests to nightly

tests/test_public_api.py, tests/utils/artifact_emu.py, tests/utils/mock_server.py, tox.ini
[Fixes WB-9964](https://wandb.atlassian.net/browse/WB-9964)
Fixes #NNNN
Description
-----------
Adds support so the mock_server can support several artifact file sets and retrieve them separately.
Associated yea-wandb PR: https://github.com/wandb/yea-wandb/pull/69
Testing
-------
Checklist
-------
=> [WB-9964] Support for multiple artifact filesets in mock_server

.circleci/config.yml, tools/circleci-tool.py
Description
-----------
This is useful when doing manual testing, e.g. you don't always want to run the KFP tests when adding a new GPU test.
TODO: once this is merged, update the [docs](https://www.notion.so/wandbai/Nightly-testing-infra-for-the-SDK-904e273220ec47b8aa51c3c6af047750#ff74e3fed8ea4597a0d348155ae78179), bc I made the shard names more verbose/consistent, i.e.:
```shell
CIRCLECI_TOKEN=<YOUR_TOKEN> python tools/circleci-tool.py --dryrun trigger-nightly --shards=kfp,standalone-gpu
```
Testing
-------
How was this PR tested? On the CI, obviously :)
Checklist
-------
=> Allow requesting different shards in manual_nightly workflow on Circle

mypy.ini, tests/unit_tests/test_retry.py, tests/unit_tests/test_util.py, wandb/sdk/internal/internal_api.py, wandb/sdk/lib/retry.py, wandb/util.py
Fixes WB-9585
Description
-----------
- Add tests and type annotations for `retry.Retry`.
- Retry `commit_artifact` on HTTP code 409: if two artifacts are committed to the same collection at the same time, they can race for a version number and one of them can fail with a conflict. The server _shouldn't_ let this happen -- it should have better transaction isolation -- but it's _so_ much easier to band-aid over the problem with a retry... 😬 
Testing
-------
Ran a repro script against my dev W&B instance, running 5 processes that all commit artifacts at the same time. Verified that there are lots of conflict-errors before this PR. Verified that there are retry-loops that terminate successfully after this PR.
Also tested against production, running 15 processes that all simultaneously …
=> [WB-9585] Retry commit_artifact on conflict-error

wandb/util.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
e.response has been known to be None, you can find those checks in other parts of the code including the no auth retry logic above this function.   I think it is a good safety check..  There is an injection fixture `InjectRequestsParse` can hit this case - but this should be safe without the test.
Follow on to https://github.com/wandb/client/pull/3843
Testing
-------
Not tested
Checklist
-------
=> Add safety check to retry logic (response could be None)

.circleci/config.yml, tox.ini, wandb/filesync/upload_job.py
Description
-----------
Problem: downstream steps/jobs could fail like here, but we were not reporting that to slack:
Also:
- pinned `yea-wandb==0.7.61` and rm'ed a todo comment
Testing
-------
Checklist
-------
=> Add more Slack notifications on possible failures in nightly testing

tests/utils/mock_server.py, tox.ini
Description
-----------
Update yea-wandb and mockserver to handle filestream data more correctly
The main fix is that filestreams have an offset and that should be respected.
For example
updates:
- off=0 line="a\n"
- off=1 line="b\n"
- off=1 line="c\n"
- off=2 line="d\n"
- off=0 line="e\n"
should result in:
```
e
c
d
```
The old code was doing a mix of:
- blindly appending lines
- and reseting all lines when a off=0 was received
Corresponding yea-wandb change:
https://github.com/wandb/yea-wandb/pull/78
Testing
-------
=> Fix filestream offset handling in mockserver

setup.cfg
Description
-----------
This PR fixes the to `bumpversion` config to allow  transition from `dev` to empty and from `pre` to empty
Testing
-------
Few examples locally:
- `bump2version devkind`: `0.13.0rc5.dev2` -> `0.13.0rc5`
- `bump2version prekind`: `0.13.0rc5` -> `0.13.0`
- `bump2version prekind`: `0.13.0rc5.dev2` -> `0.13.0`
=> fix up the `bumpversion` config

.yearc, tests/functional_tests/t0_main/.yearc, tests/functional_tests/t0_main/code_save/log_code/log_code.yea, tests/functional_tests/t0_main/doctest/.yearc, tests/functional_tests/t0_main/doctest/log-image-numpy.yea, tests/functional_tests/t0_main/doctest/log-image-pil.yea, tox.ini, wandb/sdk/data_types/image.py
Description
-----------
- Update yea to 0.8
- Fix some broken yeadoc tests
```
$ yea list
$ yea list --all
$ yea run
$ yea run *.yea
$ yea run --all
$ yea --yeadoc run --all
```
These are needed first:
- https://github.com/wandb/yea/pull/29
- https://github.com/wandb/yea-wandb/pull/79
Yea 0.8.0 features:
Later:
- Add time to assert dict
- save assert dict to yea_cache
- turn on live mode
- support profiling
- rework all testids so we can make them more stable and track them overtime
- More
Testing
-------
Checklist
-------
=> Update to yea 0.8 - fix yea / yeadoc issues

.circleci/config.yml, .codecov.yml, tools/coverage-tool.py, tox.ini
Description
-----------
We set `after_n_builds` for codecov so that we can get a final coverage count and not partial info.
We never seem to count right -- so lets automate.
The values are checked  in circle during the `code-check` phase
This should make it easier for us to add more parallelism in circleci
NOTE: there are some assumptions about the format and naming of the circleci config file but the rules hold true for now and it wont be too hard to extend.  When assumptions were made, the tool tries to check assumptions and assert so we can be alerted.
Testing
-------
Tested manually by creating a few circleci yaml files (including some cross products using matrix with multiple keys -- incase we start to do that)
=> Add tool to compute number of codecov calls

.circleci/config.yml, tools/circleci-tool.py
Description
-----------
update a package and update scripts to use the renamed circleci pipelines
There are more references to change for the repo name, this PR just fixes things that were obviously broken and failing due to the rename.
Testing
-------
Test with circleci-tool. (See: https://app.circleci.com/pipelines/github/wandb/wandb/14164/workflows/ad149c4d-cb82-4fd1-b88b-1ab608abb45e)
=> Fix nightly and some repo name change breakage

.flake8-base, tests/functional_tests/t0_main/console/test_emoji.py, tests/functional_tests/t0_main/console/test_tqdm.py, tests/functional_tests/t0_main/console/test_tqdm_nested.py, tests/functional_tests/t0_main/imports/03-batch3-requirements.txt, tests/functional_tests/t0_main/perf/log_data.py, tests/functional_tests/t0_main/perf/t1_basic.py, tests/functional_tests/t0_main/perf/t1_basic.yea, tests/functional_tests/t0_main/perf/t2_log_scalers_offline.yea, tests/standalone_tests/log_large_data.py, tests/standalone_tests/table_mem_test.py, tox.ini
Description
-----------
Changes:
- Update to yea 0.8.1 / yea-wandb 0.8.1 (waiting on approvals before changing tox.ini)
- Add yea profile support
- Add some base nightly tests to start establishing baseline performance
- flake8 was accidentally turned off for test files -- turn back on and fix some tests
Will eventually replace this draft PR:
- https://github.com/wandb/wandb/pull/3652
Future:
- Add more tests
- Figure out the best way to track historical data
- add yea offline support and assert on records
Required PRs:
- https://github.com/wandb/yea/pull/31
- https://github.com/wandb/yea-wandb/pull/81
Testing
-------
These are tests
=> Add performance profiling to nightly yea tests

tests/unit_tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py
Fixes WB-6275
Description
-----------
- in `Artifact(metadata=...)`, and `my_artifact.metadata = ...`, verify that the metadata is a JSON-serializable dict (or None); raise TypeError if not
- previously, `Artifact(metadata=None)` resulted in metadata `{}`, while `a = Artifact(); a.metadata = None` resulted in metadata `None`; changed the second case to `{}`
- while I was in the neighborhood, I changed both metadata (`Artifact(metadata=...)` and `art.metadata = ...`) to deepcopy the given`metadata`; I doubt we want to pick up future modifications
Testing
-------
Unit tests!
=> ensure `metadata` passed to `Artifact()` is a legal dict

tests/unit_tests/tests_launch/test_launch.py
Description
-----------
Attempt to fix:
- https://app.circleci.com/pipelines/github/wandb/wandb/14248/workflows/cce6c5ac-c1f1-4d45-b887-f024e3171881/jobs/244087/steps?invite=true#step-106-564
Testing
-------
circleci
=> Deflake: bump timeout for another launch test

wandb/sdk/launch/_project_spec.py
[Fixes WB-10429](https://wandb.atlassian.net/browse/WB-10429)
Fixes #NNNN
Description
-----------
Fixes a type error where we can try to add a None type to a string if the git repo had no patch file
Testing
-------
Checklist
-------
=> [WB-10429] Fix issue where patch is none

CONTRIBUTING.md, requirements.txt
Description
-----------
One of our requirements is probably pulling this in and saving us, but we should be explicit if we use it, which we do in sweeps on launch.
Bonus: update contributing with a new m1 issue that popped up (might not be strictly required)
Testing
-------
not tested
=> Add dataclasses to requirements for py3.6

.circleci/config.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
We added `dataclasses` for py<3.6. We'll remove it once we sunset py3.6 support hopefully later this year.
Testing
-------
Ran nightly manually:
https://app.circleci.com/pipelines/github/wandb/wandb/14325/workflows/119b1c47-de21-410d-87a9-db434603bae9
Checklist
-------
=> Fix requirements.txt parsing in nightly SDK installation checks

tests/utils/mock_server.py, tox.ini
Description
-----------
Updates yea and yea-wandb:
- add "--noskip" option
- fixes mockserver relay mode to return the right status message
- fix parse context to handle None in config and upsert bucket run
Corresponding yea-wandb change:
https://github.com/wandb/yea-wandb/pull/82
Testing
-------
circle
=> Update yea-wandb 0.8.2

tests/functional_tests/t0_main/resume/t3_deleted.yea, tests/functional_tests/t0_main/resume/two_runs.py, tests/unit_tests/test_retry.py, tests/unit_tests/test_util.py, wandb/sdk/internal/internal_api.py, wandb/sdk/lib/retry.py, wandb/util.py
Fixes WB-10408
Description
-----------
- Fixes cases where the backend returns `409 Conflict` errors for some GraphQL requests.
- Added new handling for HTTP status `410 Gone` to never retry with the anticipation that this will be returned in the future so we don't have two classes of failures aliasing to the same code.
The scenario is:
```mermaid
sequenceDiagram
participant SDK
participant Server
participant DB
SDK->>Server: GraphQL(upsert_run)
Server->>DB: INSERT run
activate DB
note right of DB: Database is slow as large project\nneeds to be loaded into cache
note right of SDK: Client request timeout
SDK->>Server: GraphQL(upsert_run) Retry
Server->>DB: INSERT run
DB->>Server: Duplicate entry for key 'PRIMARY'
Server->>SDK: 409 Conflict
DB->>Server: inserted
deactivate DB
```
This …
=> Fix 409 Conflict handling when GraphQL requests timeout

tests/assets/notebooks/magic.ipynb, tests/assets/notebooks/one_cell.ipynb, tests/functional_tests/t0_main/keras/test_keras_subclassed_model.py, tests/functional_tests/t0_main/perf/t1_basic.py, tests/functional_tests/t0_main/perf/t1_basic.yea, tests/unit_tests/tests_s_nb/test_notebooks.py, tox.ini
Description
-----------
changes:
- notebook tests were leaking into the next test, there should be a better way to shutdown runs between notebook tests but for now, i added an explicit finish
- keras subclass test was not sorting a list from the fs..
- perf tests were too strict right now..  relaxed and logged more data so we can get a mean rather than a single log which might have warm up time?
Not fixed:
- the following test is wrong as it might not improve on the second epoch so only 1 artifact wil be saved:
https://github.com/wandb/wandb/blame/master/tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea#L15
Testing
-------
circle, manual flake repro with different xdist settings in a loop
=> Fix flaky tests (notebook, keras, perf oh my)

tests/functional_tests/t0_main/keras/keras_subclassed_test_tf_2_6.yea
Description
-----------
temporary workaround for a non deterministic test which might not improve on the second epoch so it will only store 1 artifact.
Testing
-------
Ran yea test in a loop.
=> Fix flake in keras subclass test (workaround)

tests/functional_tests/t0_main/perf/t2_log_scalers_offline.yea, tests/functional_tests/t0_main/perf/t3_console_wrap_offline.yea, tests/functional_tests/t0_main/perf/t4_console_wrapemu_offline.yea, tests/functional_tests/t0_main/perf/t5_console_redirect_offline.yea, tests/utils/mock_server.py, tox.ini
Description
-----------
- Give lots of slop for wandb.init() perf timing for now.
- Update yea-wandb to fix incompatibility with running yea kfp tests
Requires yea-wandb 0.8.4:
https://github.com/wandb/yea-wandb/pull/84
Testing
-------
- manually triggered nightly
- manual testing
- circleci
=> Update perf wandb.init() timings and yea-wandb

wandb/sdk/service/streams.py
Description
-----------
Fix orphaned wandb-service process by shutting down if the parent process has been terminated.
Walk through of what can happen (one case is control-C):
- wandb.init() spins up wandb-service
- user process is in the process of crashing, handling control-c, etc
- atexit of the wandb_manager is called
- wandb_manager attempts to finish all runs that are active
- wandb-service is handling this finish_all request
- while trying to finish syncing all runs the parent process gets killed somehow
- if the parent process is gone, there is no reason to continue syncing, we could be in a network retry loop of up to 7 days.
We have other places where we check for orphaned... namely in the stream mux loop.  But since we are handling a request on behalf of the mux, the mux doesnt …
=> Fix service teardown handling if user process has been terminated

setup.cfg, setup.py, tests/utils/mock_server.py, tox.ini, wandb/__init__.py
Description
-----------
Bump to dev version
Requires:
https://github.com/wandb/yea-wandb/pull/88
Testing
-------
None
=> Bump version: → 0.13.1.dev1

wandb/sdk/wandb_init.py
Description
-----------
thread mode and fork mode are often not useful right now.. wandb service should solve most of the conditions where this was required so lets not give an outdated suggestion but still point to the URL where we can update the content.
NOTE start_method != fork is the normal case.   We are not adding any more messaging for this release, instead just removing outdated messaging.
Testing
-------
Not tested
=> Improve wandb.init() error message

package_readme.md
Description
-----------
We have two separate files for our readme,  update shields for the other one.
Note, this only updates the shields.  there were other things that are different in the readme that we should sync up or consolidate the files in the future.
I noticed the broken images here:
https://pypi.org/project/wandb/0.12.21/
Testing
-------
Not tested
=> update pypi package readme shields

tests/functional_tests/t0_main/lightning/train_gpu_ddp.py, tests/standalone_tests/artifact_tests.py, tests/standalone_tests/basic.py, tests/standalone_tests/basic_plots.py, tests/standalone_tests/mixed_keras.py, tests/standalone_tests/pytorch_cuda.py, tests/standalone_tests/table_mem_test.py, tests/standalone_tests/tweets.py
Description
-----------
This is triggered by this failure: https://app.circleci.com/pipelines/github/wandb/wandb/14444/workflows/5d5690eb-965b-4610-b388-cde425f3a81a/jobs/251907?invite=true#step-117-1693
Separately from this, this commit in PL https://github.com/Lightning-AI/lightning/commit/749709fb4fd467474b610cab7b70d6d02aa4789c would create pain for those using, say, slashes in their run names, so we should submit a PR to PL with a fix.
Testing
-------
Checklist
-------
=> Improve naming of standalone tests

tests/unit_tests/wandb_artifacts_test.py, wandb/sdk/wandb_artifacts.py
Description
-----------
Repro:
```python
import wandb, numpy as np
with wandb.init() as r:
art = wandb.Artifact("foo", "bar", metadata={"a": np.arange(3)})
r.log_artifact(art)
```
In v0.12.9: works as you’d expect, with the ndarray being turned into a… a list, I think ([example](https://wandb.ai/spencerpearson-wandb/client/artifacts/bar/foo/65cab3d178cdaa45648d)).
In v0.13.0rc6: `TypeError: Object of type ndarray is not JSON serializable`
This is because #3975 simply calls `json.dumps(metadata)` when it's normalizing the artifact metadata, which can't handle ndarrays; the "canonical" way for the metadata to get serialized is [here](https://github.com/wandb/client/blob/30f647881c3f46397fd90461b14a2531a9e04188/wandb/sdk/interface/interface.py#L380), using our `json_friendly_val` …
=> fixup to #3975: make Artifact metadata JSON-encoding accept more types

wandb/sdk/wandb_init.py, wandb/sdk/wandb_settings.py
Description
-----------
Found in Sentry: https://sentry.io/organizations/weights-biases/issues/3167782210/?project=5288891&query=is%3Aunresolved+release%3A0.13.0&statsPeriod=14d
Apparently, two independent issues:
- We could be more forgiving and preprocess root_dir as a str so that people can use, e.g., pathlib.Path's
- We have some dubious logic in how we set up the default value for root_dir in Settings.
Repro:
```python
import pathlib
import wandb
run = wandb.init(dir=pathlib.Path("/Users/dimaduev/dev/rubbish"))
run.finish()
run = wandb.init(settings=wandb.Settings(root_dir=pathlib.Path("/Users/dimaduev/dev/rubbish")))
run.finish()
```
Testing
-------
Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if …
=> Adjust root_dir setting processing logic

wandb/sdk/launch/utils.py
Fixes WB-10302
Description
-----------
One-Liner improved error messaging for entering both a URI and docker image path
Testing
-------
Sending both or one or none and getting my fancy new error message.
=> Added explicit error message for double uri/docker-image [WB-10302]

tests/unit_tests/test_wandb.py
Description
-----------
A follow-up PR on 4066.
Testing
-------
Checklist
-------
=> Test that the wandb_init fixture args are in sync with wandb.init()

.circleci/config.yml
Description
-----------
This PR reduces the `pytest` parallelism from 10 to 6 in the hopes to make CircleCi happier
Testing
-------
Hopefully over time the flake should be reduced
=> Reduce the `pytest` job parallelism from 10 to 6

tests/unit_tests_old/tests_launch/test_launch_kubernetes.py, wandb/sdk/launch/runner/kubernetes.py
[Fixes WB-10593](https://wandb.atlassian.net/browse/WB-10593)
Fixes #NNNN
Description
-----------
Adds handling for a tolerations key in the kubernetes runner which can be used for taints and tolerations
Testing
-------
Checklist
-------
=> [WB-10593] Launch kubernetes support taints and tolerations

tests/functional_tests/t0_main/sacred/t1_regression.py
Description
-----------
Fix failure due to sklearn update:
```
INFO - iris_rbf_svm - Running command 'run'
INFO - iris_rbf_svm - Started
ERROR - iris_rbf_svm - Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
File "./t1_regression.py", line 23, in run
clf = svm.SVC(c, "rbf", gamma=gamma)
TypeError: __init__() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
```
Testing
-------
Tested manually:
```
Results:
--------
0.sacred.1: 😃
Test durations (sec):
---------------------
0.sacred.1: 21.1
```
=> Fix func sklearn (need kwargs)

wandb/cli/cli.py
Fixes WB-10606
Description
-----------
When running a sweep via the CLI, the `job` field can now be specified both in the sweep config and the launch config (with the sweep config taking precedence).
Testing
-------
Checklist
-------
=> feat(sweeps): Look for launch job in sweep config

.github/CODEOWNERS, tests/unit_tests/test_library_public.py
Description
-----------
Lock more stuff down!
Testing
-------
Not tested
=> Require sdk-team to approve API changes

wandb/sdk/lib/sock_client.py
Description
-----------
We were reading in very small chunks... This change prefers reading in 128kB size chunks.
Testing
-------
See https://github.com/wandb/wandb/pull/4119 for testing notes
=> Improve performance by increase recv size on service socket

tests/unit_tests/conftest.py
Description
-----------
This PR fixes an oversight from the unit test conftest, so the default value of the dev test container point to the lates version from master (affected only tests locally)
Testing
-------
Shouldn't make a difference
=> fix default test container tag

tests/unit_tests/conftest.py, tests/unit_tests/test_keras_full.py, tests/unit_tests/test_metric_full.py, tests/unit_tests/test_metric_internal.py, tests/unit_tests/test_mp_full.py, tests/unit_tests/test_runtime.py, tests/unit_tests/test_start_method.py
Description
-----------
This PR addresses a major source of flake in the refactored (`pytest`) unit tests.
TLDR:
Run summary may be updated multiple times during a test, but we are only interested in the last one.
We can have multiple runs saved to the relay server context, so we need to group by run id and take the last one for each run.
The `pandas` magic applied is the following:
```python
>>> import pandas as pd
>>> df = pd.DataFrame.from_records([{"_run": 1}, {"_run": 1, "a": 1}, {"_run": 2},{"_run": 2, "a": 2}])
>>> df
_run    a
0     1  NaN
1     1  1.0
2     2  NaN
3     2  2.0
>>> df.groupby("_run").last().reset_index(level=["_run"])
_run    a
0     1  1.0
1     2  2.0
```
Finally, run summary DataFrame must have only one row for the given run id, so in `Context.get_run_summary` …
=> Fix summary handling in conftest.py

.pre-commit-config.yaml, pyproject.toml, setup.py, tox.ini
Description
-----------
Follow up to tie some loose ends from this PR: https://github.com/wandb/wandb/pull/4136
This PR, cleans up the configuration file and makes the tox command more generic - do we want to format the entire folder?
This PR also re-enables the pre-commit hooks
Testing
-------
This is just formatting, hence expecting test to pass as a sign that all worked correctly!
=> configure tox with dynamic resolution

.circleci/config.yml
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Ran the manual nightly suite and it worked! :)
https://app.circleci.com/pipelines/github/wandb/wandb/15065/workflows/57f66cc8-bd8f-4843-8848-ac6a30b42356
Checklist
-------
=> Remove `buildx` version pin for nightly builds

wandb/jupyter.py
Description
-----------
Colab internals have changed and there were calls that were not robust to these changes.
Quick fix is to catch this exception.  Longer term fix is to be more strict about assumptions made about external interfaces.
Log will have:
```
2022-08-22 16:24:05,105 INFO    MainThread:56 [jupyter.py:save_ipynb():384] Problem saving notebook: KeyError('name')
```
Testing
-------
Manual:
```shell
pip install --upgrade git+https://github.com/wandb/wandb.git@fix-colab#egg=wandb
```
=> Fix issue triggered by colab update by using default file and catching exceptions

.circleci/config.yml, tests/functional_tests/t0_main/perf/t1_basic.yea, tests/standalone_tests/shards/gke_cpu/Dockerfile, tests/standalone_tests/shards/gke_cpu/attach.yaml, tests/standalone_tests/shards/gke_cpu/pod.yaml, tests/standalone_tests/shards/gke_gpu/Dockerfile, tests/standalone_tests/shards/gke_gpu/attach.yaml, tests/standalone_tests/shards/gke_gpu/pod.yaml, tox.ini
Description
-----------
We want to save the junit-xml files for nightly tests so we can use circleci test insights and we want to push it as an artifact so we can do our own test insight pipeline.
To accomplish this:
- A Persistent volume needed to be created for cloud-test pods
- At the conclusion of the test in tox.ini we run `pod-store` which copies data to the persistent volume
- The circleci job needs to grab this data to a local dir but the pod is already complete so it has to launch a new `attach-pod` to access the persistent volume
- Use kubectl to copy data out
- Use circleci store_* flows to save the test results and the artifacts
- profit
Testing
-------
Tested with:
```
./tools/circleci-tool.py trigger-nightly --shards standalone-cpu
```
Successful nightly full trigger: …
=> Push test-results to circle for nightly tests

wandb/sdk/launch/sweeps/scheduler.py, wandb/sdk/launch/sweeps/scheduler_sweep.py
Fixes WB-10661
Description
-----------
Moves run configs from going through entrypoint in `launch_add` to going through the `params` kwarg.
Testing
-------
Checklist
-------
=> feat(sweeps): Move run configs from entrypoint into params

.circleci/config.yml
Description
-----------
...because Windows is currently not supported by the Slack orb, see https://github.com/CircleCI-Public/slack-orb/pull/282.
Testing
-------
Checklist
-------
=> Remove Slack orb usage from Win job on CircleCI

wandb/sdk/launch/sweeps/scheduler_sweep.py, wandb/wandb_agent.py
Description
-----------
Fixes an issue where `run.args` coming from an AgentHeartbeat call were not formatted correctly for launch agents. Uses legacy sweep function to parse (to avoid code duplication).
Testing
-------
Checklist
-------
=> fix(sweeps): Parse heartbeat run args using legacy agent

tests/unit_tests/conftest.py, tests/unit_tests/test_keras_full.py, tests/unit_tests/test_torch_full.py
Description
-----------
In this PR:
- Provision an admin user to use with the app when running `pytest` tests. Users generated per requesting test are not removed at the end of the test so that developers can inspect the app with the admin account at the end of the test session.
- Unset global wandb objects at the end of each test to improve isolation.
Testing
-------
Checklist
-------
=> Adds debug mode for `pytest` unit tests

.pre-commit-config.yaml, tests/functional_tests/t0_main/debug/t3_sentry_userproc_win.yea
Description
-----------
Some sketchy flake has been going on with it in Circle since we updated the base Win worker used for the functional tests. Spent a lot of time debugging it already, which might not even be necessary once yea is transferred onto the unmock server rails.
Also: comment out the isort pre-commit hook as takes up to 10 seconds to run, which is too much for a pre-commit hook. (we don't have mypy there for the same reason).
Testing
-------
Checklist
-------
=> Skip the `t3_sentry_userproc` functional test on win

wandb/sdk/launch/builder/build.py, wandb/sdk/wandb_init.py, wandb/sdk/wandb_run.py, wandb/util.py
[Fixes WB-10747](https://wandb.atlassian.net/browse/WB-10747)
[Fixes WB-10746](https://wandb.atlassian.net/browse/WB-10746)
Fixes #NNNN
Description
-----------
Puts the job in the artifacts dict and automatically uses it.
so 
1. We can now filter by jobs using this job
2. We dont try to produce a new job version when sourced from a job
Testing
-------
Checklist
-------
=> feat(launch): put job into artifact slot, have run use it, dont produce a job in a launched run that is sourced from a job

tests/standalone_tests/artifact_tests.py, wandb/sdk/wandb_run.py
Fixes WB-10394
Testing
-------
Shouldn't affect anything, so, relying on the existing test suite!
=> [WB-10394] add detail to error message when uploading an artifact with the wrong type

wandb/sdk/wandb_init.py
Addresses this StackOverflow question: https://stackoverflow.com/questions/73373004/is-there-any-symbols-forbidden-in-run-id
Description
-----------
Small change to `wandb.init` reference docs to add which characters are forbidden in `id` within `wandb.init`.
> The ID cannot contain the following special characters: `/\#?%:`.
=> Docs: Update ref docs for wandb.init to give more info on special characters

wandb/apis/public.py
Fixes the incorrect type hint introduced in https://github.com/wandb/wandb/commit/643b25da062e79abf498b4eaf33c09f2c462837e
=> Fix type hint for `filters` argument

.github/workflows/pr.yml, CONTRIBUTING.md
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
I realized that it best describes the third-party-related stuff while working on the protobuf version upgrade stuff.
Testing
-------
Checklist
-------
=> chore(sdk): add the 'build' type to our CC setup

wandb/sdk/internal/internal_api.py
Fixes WB-11059
Fixes #NNNN
Description
-----------
Instead of the standard `408` status code, S3 will respond with [code `400` and an XML payload](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) containing an error string and detailed error message. This has been observed to happen intermittently for `PUT` (upload) requests, and more consistently when uploading larger artifacts.
This PR attempts to detect these out-of-band `RequestTimeout` errors and correctly retry the request.
Testing
-------
How was this PR tested? TBD
Checklist
-------
=> fix(artifacts): Catch retryable request timeout when uploading artifacts to AWS

tests/functional_tests/t0_main/imports/12-batch12.py
Description
-----------
Add `tensorflow_datasets` requirement to imports12.
Testing
-------
`func-s_imports12-lin-py37`
Checklist
-------
=> fix(sdk): Add tensorflow_datasets requirement to imports12

tests/functional_tests/t0_main/sb3/t1_stable_baselines3.yea
Description
-----------
A recent `importlib-metadata` release (5.0.0) removed a deprecated API that `sb3` has been apparently using. Fixed our test by pinning a corresponding requirement until they fix it upstream.
Testing
-------
Checklist
-------
=> test(integrations): fix sb3 test by pinning upstream requirement

tox.ini
Description
-----------
`flake8-color` has been integrated upstream and is now obsolete; they also changed some formatting so that our old format broke.
Testing
-------
"Well, it works on my machine..."
Checklist
-------
=> chore(sdk): fix flake8 output coloring

.github/release.yml, .github/workflows/conventional-label.yml
Description
-----------
- Use the `bcoe/conventional-release-labels` GitHub Action to auto-assign labels to PRs based on the conventional commits types.
- Reorganize the automated release note generation based on that.
Testing
-------
Tested manually, but thoroughly ;)
Checklist
-------
=> ci(sdk): test a GH action to automate parts of the release process

tests/unit_tests/test_data_types.py, tests/unit_tests/test_data_types_full.py, wandb/sdk/data_types/object_3d.py
Description
-----------
The W&B service relies on the pts.json suffix of the file when it's uploaded to the wandb server to recognize files as point clouds. In some code paths of the existing code, we were not properly setting the extension, which results in files not having the proper suffix. 
Point cloud uploaded previously worked *sometimes* depending on: a) how the point cloud was created (eg filenames failed but numpy arrays succeeded) b) how the point cloud was included in the workspace (individually as file or as part of a table)
This change ensures that all calls to _set_file include the extension, and also ensures that the extension includes a starting `.`.
Testing
-------
Updated existing unit tests to verify paths are correct now that we know this is important. Also manually …
=> fix(media): 3D Point Clouds now viewable in UI in all situations

wandb/apis/internal.py, wandb/sdk/launch/builder/build.py
Fixes WB-11072
Description
-----------
Git now has an option to use a built-in filesystem monitor, which can improve performance. 
It can be enabled with `git config core.fsmonitor true`
When enabled, running launch with a git url would throw an exception while executing shutil.copytree:
`[Errno 102] Operation not supported on socket`
This change ignores the socket file.
Also fixed a typo.
Testing
-------
Checklist
-------
=> fix(launch): Git URLs were failing if fsmonitor is enabled

.circleci/config.yml
Description
-----------
Fix race in nightly testing where we could shutdown the cluster before getting a chance to grab results.   This makes the race much less likely.
Testing
-------
Manually
https://app.circleci.com/pipelines/github/wandb/wandb/15966/workflows/52e33dc6-d28c-414e-bcc7-a37a441dcf36
Checklist
-------
=> ci(sdk): make sure we dont shutdown test cluster before grabbing results

tests/standalone_tests/artifact_tests.yea
Partially Fixes WB-11204
Description
-----------
Adds artifact test to nightly
https://app.circleci.com/pipelines/github/wandb/wandb/15962/workflows/07b79a66-3fb7-4d36-b404-a85579d9ac6f
Testing
-------
Run manually.
Checklist
-------
=> test(artifacts): add standalone artifact test to nightly cpu suite

tests/unit_tests/test_util.py, tests/unit_tests_old/tests_launch/test_launch_docker.py, wandb/util.py
Fixes WB-11092
Description
-----------
docker image names are automatically generated by launch. These names must conform to a few requirements, e.g. uppercase letters are not permitted. The previous algorithm for name generation just removed all invalid characters. This revised approach handles a few cases that could have led to invalid names being generated and generates more readable names.
Testing
-------
Tests added.
Checklist
-------
=> fix(launch): generate more readable image names

tests/unit_tests/test_wandb_artifacts.py, tests/unit_tests/test_wandb_artifacts_cache.py, wandb/sdk/interface/artifacts.py, wandb/sdk/wandb_artifacts.py
Fixes WB-11066
Fixes WB-11042
Description
-----------
Our handling of ETags has problems:
- We cache the resource at `/path/to/cache/obj/etag/{etag}`.  This is super unsafe, since the ETag can contain arbitrary characters! We should hash it first.
- ^This scheme also assumes that two resources with the same ETag have the same content. This is not necessarily the case: the ETag is _often_ a hash of the resource content, but other times it's just, like, a version number, which might collide between different resources.
This PR changes the resource-cache location to `sha256(sha256(url) + sha256(etag))`. This should solve both problems at once.
Testing
-------
Existing unit tests; and ran the repro script in [WB-11042](https://wandb.atlassian.net/browse/WB-11042) to verify that I can now …
=> fix(artifacts): in artifacts cache, use hash(etag+url) as key, not just etag

tests/unit_tests_old/test_cli.py, wandb/cli/cli.py
Fixes WB-11275
Description
-----------
wandb artifact put ... prints out “Artifact uploaded” after the artifact is created, but before it’s committed (and therefore visible to the rest of the world):
If I try to use ^that artifact before the process completes, I get:
```
CommError: Project wandb/spencerpearson-artifacts does not contain artifact: "benchmark-251:latest"
```
Testing
-------
I ran `wandb artifact put <...snip...> /tmp/10e3-10B-files/` and verified that the `Artifact uploaded, use this artifact in a run by adding` message doesn't get printed until right before the process exits.
=> fix(artifacts): in `wandb artifact put`, wait for artifact to commit before telling the user it's ready

wandb/sdk/verify/verify.py
Description
-----------
We're using `wandb verify` in CI and I noticed flakiness in one of the checks.  There's a race where a file has been uploaded but it hasn't yet been processed from the filemeta queue.  This wraps those download calls in our regular retry logic.
As a bonus, I also made the ids of the runs human readable for better debugging when they flake.
Testing
-------
Checklist
-------
=> fix(cli): Deflake wandb verify

wandb/sdk/launch/utils.py
https://wandb.atlassian.net/browse/WB-11392
Description
-----------
Changes the origin.fetch command to only look for specific head object. master, main, and the optional passed in version.
This leads to 2-10x improvement in clone speed, depending on how many branches the target remote repo has and if the version is specified. 
For example, using the wandb/examples repo had the following results. 
| branch | command     | origin.fetch duration (s) |
| ----------- | ----------- | ----------- |
| master | `wandb launch https://github.com/wandb/examples`      |  85.6     |
| this PR | `wandb launch https://github.com/wandb/examples`      |  22.5     |
| this PR | `wandb launch https://github.com/wandb/examples --git-version=xyz`      |  10.5     |
Testing
------- …
=> chore(launch): improved git fetch time by specifying a `refspec` and `depth=1`

.gitattributes
Description
-----------
gRPC files did not match wildcard for generated files
Testing
-------
Not tested.
=> chore(sdk): fix linguist rule to ignore grpc generated files

wandb/sdk/launch/utils.py
Description
-----------
Removes an extra colon from log output.
Testing
-------
Checklist
-------
=> fix(launch): remove extra colon from log prefix

wandb/sdk/internal/system/assets/ipu.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Fix a bug in the IPU probe.
Testing
-------
CI + manual.
Checklist
-------
=> fix(sdk): fix probing static IPU info

wandb/sdk/launch/_project_spec.py
Description
-----------
Removes an attribute that appears to be unused.
Testing
-------
Checklist
-------
=> refactor(launch): remove unused attribute

requirements_dev.txt
Addresses (but **does not** fix) [WB-11570](https://wandb.atlassian.net/browse/WB-11570)
Description
-----------
CI is failing for all new PRs because of a change in the recently-released tensorflow 2.11.
There is probably a real issue here that we need to look into and most likely fix, but in the meantime this pins tensorflow in `requirements_dev.txt` to avoid installing the newest release to unblock unrelated PRs.
Testing
-------
CI actually passes for the PR, unlike for all the others 😅 
Albeit with a few re-runs to deal with flaky tests 😕 
Checklist
-------
=> fix(sdk): pin tensorflow<2.11.0 to prevent errors caused by API changes

.github/workflows/check-mocks-synced-with-yea-wandb.yml, .github/workflows/pr.yml
GitHub has deprecated Node 12 based Actions; the two actions we need to update to comply with this are:
- Update semantic-pull-requests to v5.0.2
- Checkout to v3 (actually 2.5.0 which is called v3 🙃 )
Checklist
-------
=> chore(public-api): Upgrade Node 12 based GitHub Actions

tests/unit_tests/test_wandb_artifacts_cache.py
Description
-----------
Replace flaky calls to `time.sleep(0.1)` with calls to `flush` when waiting on a file to write.
For some reason on my machine the calls to `time.sleep` often do nothing. Regardless, this is a faster and more reliable way to ensure files are written with sequential c/m/a times.
Testing
-------
[test only PR, no behavior change]
Checklist
-------
=> test(artifacts): flush writes instead of sleeping to wait on file writes

tests/unit_tests/test_wandb_artifacts_cache.py
Description
-----------
Replace `os.mkdir` calls inside test functions with accepting the pytest built-in `tmp_path` fixture.
Checklist
-------
=> test(artifacts): Use `tmp_path` fixture instead of writing local files during tests

wandb/sdk/interface/artifacts.py
docs(artifacts): corrected parameter name in docstring example for `.add_dir` method. The correct paramater name is `name`, not `path`.
Fixes: https://github.com/wandb/wandb/issues/4443
Description
-----------
Corrects parameter name in docstring example for `.add_dir` method. The correct paramater name is `name`, not `path`.
Testing
-------
Checklist
-------
- [ X] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ X] Ensure PR title compliance with the [conventional commits standards](https://github.com/wandb/wandb/blob/master/CONTRIBUTING.md#conventional-commits)
=> docs(artifacts): correct parameter name in docstring example

tests/unit_tests/tests_launch/test_github_reference.py, tests/unit_tests/tests_launch/test_wandb_reference.py, wandb/sdk/launch/github_reference.py, wandb/sdk/launch/utils.py, wandb/sdk/launch/wandb_reference.py
Part of https://wandb.atlassian.net/browse/WB-7626
Description
-----------
Breaking up some changes into multiple PRs for easier review. This one adds some classes that parse W&B and GitHub URLs into constituent parts. A subsequent PR will use these to make more URI formats launchable.
Testing
-------
Includes unit tests.
Checklist
-------
=> refactor(launch): Add more robust uri parsing

tests/unit_tests/test_wandb_artifacts_full.py
Follow-up to #4463 . This test is consistently failing CI on #4539, despite being marked `xfail`, so I'm reluctantly upgrading it to `skip`. :(
=> test(artifacts): skip mysteriously flaky test

wandb/apis/public.py
Implemented fallback for older servers w.r.t. changes introduced here: https://github.com/wandb/wandb/pull/4531/files
=> chore(artifacts): Artifact Sequence Fallbacks

requirements.txt, wandb/sdk/wandb_init.py, wandb/vendor/gql-0.2.0/wandb-vendor.diff, wandb/vendor/gql-0.2.0/wandb_gql/dsl.py, wandb/vendor/gql-0.2.0/wandb_gql/gql.py, wandb/vendor/graphql-core-1.1/wandb-vendor.diff, wandb/vendor/graphql-core-1.1/wandb_graphql/error/base.py, wandb/vendor/graphql-core-1.1/wandb_graphql/execution/executor.py, wandb/vendor/graphql-core-1.1/wandb_graphql/execution/experimental/resolver.py, wandb/vendor/graphql-core-1.1/wandb_graphql/execution/values.py, wandb/vendor/graphql-core-1.1/wandb_graphql/language/lexer.py, wandb/vendor/graphql-core-1.1/wandb_graphql/language/parser.py, wandb/vendor/graphql-core-1.1/wandb_graphql/language/visitor.py, wandb/vendor/graphql-core-1.1/wandb_graphql/type/definition.py, wandb/vendor/graphql-core-1.1/wandb_graphql/type/directives.py, wandb/vendor/graphql-core-1.1/wandb_graphql/type/scalars.py, wandb/vendor/graphql-core-1.1/wandb_graphql/type/schema.py, wandb/vendor/graphql-core-1.1/wandb_graphql/type/typemap.py, wandb/vendor/graphql-core-1.1/wandb_graphql/utils/ast_from_value.py, wandb/vendor/graphql-core-1.1/wandb_graphql/utils/is_valid_value.py, wandb/vendor/graphql-core-1.1/wandb_graphql/utils/type_info.py, wandb/vendor/watchdog_0_9_0/wandb_watchdog/utils/bricks.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
This PR removes dependency on `six` by modifying vendored libs `gql` and `graphql-core`.
Concretely what I did was:
- Downloaded the vendored versions of the libraries from PyPI (tar balls)
- Initialized git in the uncompressed directories, applied our wandb-vendor diff's (manually)
- Identified all files that used six with `git grep " six"` (to catch `import six` and `from six import ...`)
- Ran `pyupgrade --py36-plus <filename>` on each identified file and manually made sure the result was good.
- Generated new diffs with `git diff > wandb-vendor.diff`, ensured they looked good
- Copied stuff over to the SDK and checked the diffs once again.
Testing
-------
CI!
Checklist
-------
=> build(sdk): remove dependency on six by modifying vendored libs

wandb/sdk/internal/handler.py, wandb/sdk/internal/system/system_monitor.py
Fixes WB-11669
Description
-----------
In jupyter-based environments, we pause system metrics collection when no cell is being executed. Resuming SM collection was broken in 0.13.5 because the internal `_shutdown_event` was never reset and the attempt to restart the system monitor didn't do anything. This PR fixes this.
Testing
-------
Tested locally in jupyter lab and in colab. Square brackets denote a cell
- [init + log a few steps] [log a few more steps] [finish]
- [init] [log a few steps] [log a few more steps] [finish]
- [init] [log a few steps, forcefully stop cell execution midway] [log a few more steps] [finish]
Checklist
-------
=> fix(sdk): resume collecting system metrics on object restart

tests/unit_tests_old/tests_launch/test_launch.py, wandb/sdk/launch/agent/agent.py
[Fixes WB-11511](https://wandb.atlassian.net/browse/WB-11511)
Fixes #NNNN
Description
-----------
Removes the requirement to send the project to the same project as the queue
Testing
-------
Checklist
-------
=> chore(launch): remove requirement to make target project match queue

requirements_dev.txt
Description
-----------
jax 0.4.1 changed something which is breaking our tests... temporarily pin so we can keep tests passing while we figure it out
Testing
-------
circleci
=> build(sdk): temporarily pin jax in tests because of breaking changes

.github/pull_request_template.md
Description
-----------
We were still referencing master instead of main... and the redir looses the anchor point so it doesnt go directly to conventional commit info
Testing
-------
Untested
=> chore(sdk): update pull request template

wandb/cli/cli.py, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/launch_add.py
misplaced return statement allow for double queries, adding TWO instead of ONE to the queue
=> chore(launch): fix for run spec handling in sdk

tests/unit_tests/tests_launch/test_job.py, wandb/apis/public.py
Job uses queue_name keyword arg (instead of queue) when calling launch_add
Fixes WB-11748
Description
-----------
Fixes `Job.call()` using the wrong keyword (`queue` vs `queue_name`) when calling launch_add.
Testing
-------
Unit test was added to verify `Job.call()`. Run `tox -e pylaunch38 tests/unit_tests/tests_launch/test_job.py`
=> fix(public-api): Job uses queue_name keyword arg (instead of queue) when calling launch_add

wandb/cli/cli.py
Fixes https://wandb.atlassian.net/browse/WB-11742
Description
-----------
We slightly modify an existing hack-y parameter ingesting mechanism to support multi-word params, exposed when pushing to a queue that had spaces in the name. 
This does not solve the case where backslashes are in the name, we escape them properly on the backend, but then assume they are already escaped when printing, resulting in half as many backslashes. We should probably just tell users in the frontend they can't use backslashes. I don't think XSS is possible here but why would anyone want a backslash in the name if they weren't doing something nefarious?
=> fix(sweeps): sweeps schedulers handles multi word parameters

tox.ini
Description
-----------
fastparquet is having trouble installing on some systems and it looks like it isnt really needed anymore.
Testing
-------
CircleCI
=> chore(sdk): remove test dependency on old fastparquet package

.pylintrc
Description
-----------
The current line in `.pylintrc` is incorrect, and causes an error
```
pylint: error: ambiguous option: --exclude could match --exclude-protected, --exclude-too-few-public-methods
```
when `pylint` runs and tries to pick up its config from that file; this just fixes that.
Testing
-------
Tested locally, that `pytest` is able to run correctly.
Checklist
-------
=> chore(sdk): Correct 'exclude'->'ignore-paths' in .pylintrc

tests/unit_tests/conftest.py
Description
-----------
Once this pytest feature gets out, then we can use temp dir retention policies based on failures etc:
https://github.com/pytest-dev/pytest/pull/10442
Testing
-------
Manual test to make sure directory exists after pytest exit
By default pytest keeps around 3 sessions.
Checklist
-------
=> chore(sdk): use pytest tmp_path so we can inspect failures

tests/unit_tests_old/test_summary.py, wandb/__init__.py, wandb/apis/public.py, wandb/data_types.py, wandb/sdk/internal/internal.py, wandb/util.py
Fixes WB-11427 (probably not fully, but this should be a good starting point)
Description
-----------
Reduce the default number of open file descriptors: 
- default to lazily loading optional external modules:
- make `wandb.util.get_module` lazily load modules by default
- `wandb.old.summary` was loading `h5py`, which many users will never need. It was accounting for ~40% of open file descriptors when you simply say `import wandb`.
With the above two improvements, for a simple script `junk.py` like this:
```python
import time
import wandb
time.sleep(5)
run.finish()
```
```shell
p=`ps -ef | grep "junk" | awk 'NR==1 {print $2}'`
lsof -p $p | wc -l 
```
goes down from ~115 to ~70.
- Make sure to close the internal log file when finishing the internal process
Currently, for …
=> chore(sdk): improve file descriptor management

wandb/data_types.py
Fixes [WB-11885](https://wandb.atlassian.net/browse/WB-11885)
Description
-----------
Fixes missed field from #4649 causing regression error in the standalone test suite
Testing
-------
Checklist
-------
=> fix(artifacts): get digest directly instead of from the manifests' manifest

wandb/sdk/data_types/object_3d.py
Fixes [DOCS-458](https://wandb.atlassian.net/browse/DOCS-458?atlOrigin=eyJpIjoiOTY0MWI4ZDdjZjE0NDI2Yjk3NGMyZDlhYmMwMGM0YWIiLCJwIjoiaiJ9)
Fixes #NNNN
-----------
Fixed typo in python docstring for data_types.Objects3D
Testing
-------
How was this PR tested? 
N/A
Checklist
-------
=> docs(sdk): Fixed typo in docstring for data_types.Objects3D

requirements_dev.txt, wandb/util.py
Description
-----------
See https://github.com/wandb/wandb/pull/4632#issuecomment-1368286125 -- the sdk is currently not working with `jax==0.4.1` bc of a jax API change.
Testing
-------
Checklist
-------
=> fix(integrations): fix type check for jax.Array introduced in jax==0.4.1

README.md, tests/unit_tests/test_system_metrics_trainium.py, wandb/sdk/internal/system/assets/trainium.py
Description
-----------
- `tests/unit_tests/test_system_metrics_trainium.py::test_trainium` was causing trouble on the CI apparently bc I wasn't shutting down `neuron_monitor_mock` properly. 
- added more guardrails around the Trainium monitor internals.
Testing
-------
Checklist
-------
=> test(sdk): fix AWS Trainium test

wandb/sdk/wandb_run.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Testing
-------
Checklist
-------
=> chore(sdk): fix status checker thread issue when user process exits without finish()

setup.cfg
Description
-----------
We dont need a universal package as we dont support py2 anymore.
Testing
-------
Checklist
-------
=> chore(sdk): dont create universal py2/py3 package

.circleci/config.yml
Description
-----------
The action of updating the gcloud sdk that is a part of the Circle orb seems to have been fixed to use the latest version, so this PR undoes a previous fix.
Testing
-------
Checklist
-------
=> test(sdk): fix gcloud sdk version requested in nightly tests

tests/pytest_tests/system_tests/tests_launch/test_launch_kubernetes.py
Fixes [WB-11968](https://wandb.atlassian.net/browse/WB-11968?atlOrigin=eyJpIjoiNTkzMTA5NWE2NjcyNGUyNjhjNmJkM2MzMTY2NmFkYTYiLCJwIjoiaiJ9)
Description
-----------
Added a unit test ensuring annotations are supported by the kubernetes runner
Testing
-------
Run `tox -e pylaunch38 -- tests/unit_tests/tests_launch/test_launch_kubernetes.py`
[WB-11968]: https://wandb.atlassian.net/browse/WB-11968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(launch): Add unit test for kubernetes runner with annotations

tests/pytest_tests/system_tests/conftest.py
Description
-----------
Pull x86 image until core publishes amd64 images reliably.
Future:
- revert this when core is updated
Testing
-------
locally tested
=> chore(sdk): fix docker testimage to pull amd64 version

tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py, wandb/sdk/launch/builder/build.py
Fixes [WB-11750](https://wandb.atlassian.net/browse/WB-11750)
Description
-----------
Pull the "Author" key from the launch spec to populate the "WANDB_USERNAME" environment variable
Testing
-------
A new unit test, `test_get_env_vars_dict`, was added to ensure all the environment variables are fetched correctly. 
[WB-11750]: https://wandb.atlassian.net/browse/WB-11750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(launch): Include username of run author in environment variables

wandb/sdk/interface/artifacts.py
Fixes [WB-12210](https://wandb.atlassian.net/browse/WB-12210)
Description
-----------
Expand the `try/except` block in `ArtifactsCache.cleanup` to ensure that if the file has been deleted by another process cleanup will skip over it rather than crashing.
Checklist
-------
[WB-12210]: https://wandb.atlassian.net/browse/WB-12210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artifacts): catch FileNotFoundError and PermissionError during cache.cleanup()

tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py, wandb/sdk/launch/agent/agent.py
Fixes [WB-11745](https://wandb.atlassian.net/browse/WB-11745)
Description
-----------
Previously, when an agent catches an exception, it would only log the error itself. Now it outputs a more comprehensive stack trace, showing where the error came from.
Testing
-------
A unit test was added, `test_loop_capture_stack_trace`, to ensure that the stack trace is being logged
[WB-11745]: https://wandb.atlassian.net/browse/WB-11745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): Agent logs full stack trace when catching exception

tools/setup_dev_environment.py
Fixes [WB-12228](https://wandb.atlassian.net/browse/WB-12228)
Description
-----------
Pin `pip` to 21.1.2 and `tox` to 3.24.0 in each virtual environment installed by `setup_dev_environment.py`
Testing
-------
It works on my machine!
Checklist
-------
[WB-12228]: https://wandb.atlassian.net/browse/WB-12228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build(sdk): pin pip and tox in development environments

tests/pytest_tests/unit_tests/test_job_builder.py, wandb/sdk/internal/job_builder.py, wandb/util.py
Fixes WB-NNNN
[Fixes #4888](https://github.com/wandb/wandb/issues/4888)
Description
-----------
- truncates the job artifact names to 128 characters
Testing
-------
Checklist
-------
=> fix(launch): Ensure job names do not exceed maximum allowable for artifacts

requirements_dev.txt, tests/functional_tests/t0_main/sb3/t1_stable_baselines3.yea, wandb/sdk/wandb_init.py
Description
-----------
Newer versions of `setuptools==67.0.0` has new enforcements on `extras` that seem to break with gym. The gym project is not maintained anymore and currently the gym project suggests moving to [gymnasium](https://github.com/openai/gym#the-team-that-has-been-maintaining-gym-since-2021-has-moved-all-future-development-to-gymnasium-a-drop-in-replacement-for-gym-import-gymnasium-as-gym-and-gym-will-not-be-receiving-any-future-updates-please-switch-over-to-gymnasium-as-soon-as-youre-able-to-do-so-if-youd-like-to-read-more-about-the-story-behind-this-switch-please-check-out-this-blog-post). 
Until we move to  gymnasium, we remove the gym requirement from `requirement_dev.txt` as it only tested in yea where we have isolated env. We also remove …
=> test(sdk): fix broken dependencies in tests

wandb/sdk/lib/ipython.py
Fixes WB-5263
Description
-----------
This PR suppresses IPython's widget deprecation warning.
Before:
After:
Testing
-------
Checklist
-------
=> fix(sdk): clean up IPython's widget deprecation warning

wandb/errors/__init__.py, wandb/sdk/service/service.py, wandb/sdk/wandb_manager.py, wandb/sdk/wandb_settings.py
Fixes WB-12268
Description
-----------
- Adds more fine grained errors to the manager to help debug cases where the token is stale (since the service closed) vs real manager issues
- capture error context more cleanly and verbose 
- add validators to time-based settings
Testing
-------
Checklist
-------
=> fix(sdk): add special Exceptions for the manager logic, when trying to connect to a gone service

tests/pytest_tests/system_tests/test_sender.py, tests/pytest_tests/unit_tests/test_util.py, wandb/sdk/internal/sender.py, wandb/util.py
Fixes WB-7611
Fixes WB-7854
Fixes WB-11936
Description
-----------
This PR catches a `CommError` when trying to init a run, before we would raise an Exception that would cause the socket to close and the entire program failed. Now we sends it the error as part of the message to the user process, so it could be printed for the user. The error message is now more informative and actionable including the information about local installs as was the case in this ticket. 
Screenshot (before the fix):
Screenshot (after the fix):
Screenshot (with rich installed - future):
Testing
-------
Checklist
-------
=> fix(sdk): make error message during run initialization more actionable and fix uncaught exception  

tests/pytest_tests/unit_tests/test_wandb_run.py, wandb/sdk/wandb_run.py
Fixes WB-12270
Description
-----------
This PR adds `__deepcopy__` dunder method to the `Run` class, for cases when the Run is part of another object that being copied. Currently, that would fails since python would resolve to the pickling mechanism (we don't allow to pickle/un-pickle in the same process, to avoid a case where we have 2 runs in the same process, not supported). With change cases like described above would work.
Testing
-------
Added simple test (in `unit_tests/test_wandb_run.py`) that checks that we can deepcopy the Run object and that it returns the same instance of the Run.
Checklist
-------
=> fix(sdk): add deepcopy dunder method to the Run class

wandb/sdk/lib/filesystem.py
Fixes WB-12199
Description
-----------
Launch relies on `run.log_code()` to create jobs, recent refactor breaks this when artifacts directory doesn't have the correct permissions. 
TODO: Figure out how to surface the actual directory that isn't writable. 
Current:
=> fix(launch): mkdir_exists_ok now (again) checks permission on existence

wandb/sdk/launch/_project_spec.py
[Fixes WB-12200
](https://wandb.atlassian.net/browse/WB-12200)Fixes #NNNN
Description
-----------
Only log the job that's going to be launched if a job was received
Testing
-------
Checklist
-------
=> fix(launch): Only log the received job when launching something sourced from a job

wandb/cli/cli.py, wandb/settings
Fixes WB-12396
Fixes WB-12397
Fixes WB-12400
Description
-----------
Small CLI tweaks. We now error if a user doesn't input a queue. The weird shlex quoting thing should also be alleviated. Also adds a `-q` alias to `--queue` to mirror the launch-agent command.
Testing
-------
silly griffin, tests are for kids!
=> chore(sweeps): remove queue=default and add -q shortcut

.github/CODEOWNERS
Fixes [WB-11835](https://wandb.atlassian.net/browse/WB-11835?atlOrigin=eyJpIjoiNGU2NTYyZTQ2ZmU0NGViNTlkMzgyNDYzODYzZGRjZTciLCJwIjoiaiJ9)
Description
-----------
See title. With this change, any PRs to `/tests_launch/` will automatically tag mlw-team as a reviewer.
Testing
-------
N/A
[WB-11835]: https://wandb.atlassian.net/browse/WB-11835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(sdk): Add mlw-team as codeowners of tests_launch folders

wandb/apis/public.py
Fixes https://wandb.atlassian.net/browse/DOCS-534
Description
-----------
Fixes docstring format for [wandb.apis.public.Runs history](https://docs.wandb.ai/ref/python/public-api/run#history) Arguments and Returns. Re: The autogenerated docs requires specific format for it to properly render. 
Testing
-------
N/A . Changed a docstring.
Checklist
-------
=> docs(cli): Formatted wandb.apis.public.Run.history docstring

tests/pytest_tests/unit_tests_old/tests_s_nb/test_notebooks.py, wandb/jupyter.py
Fixes WB-11023
Potentially fixes WB-12217 (@KyleGoyette could you verify please?)
Fixes #4962
Description
-----------
The API we've been relying on when detecting the notebook name in Colab has changed resulting in:
- The annoying `Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.` message
- Broken code saving in Colab.
This PR fixes it. Turns out, the standard way of detecting the nb name now works in Colab, so just using that.
Testing
-------
[Manually](https://wandb.ai/dimaduev/colab/runs/41usa6l8/)
Checklist
-------
=> fix(sdk): correctly detect notebook name and fix code saving in Colab

wandb/sdk/wandb_artifacts.py
Fixes [WB-11979](https://wandb.atlassian.net/browse/WB-11979)
Description
-----------
Allow up to `max_objects`, rather than `max_objects - 1`
Checklist
-------
[WB-11979]: https://wandb.atlassian.net/browse/WB-11979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artifacts): allow up to max_artifacts (fix off by 1 error)

wandb/sdk/internal/system/assets/interfaces.py
Fixes #4903
Description
-----------
When starting/stopping asset monitoring threads, especially in notebook-based environments, some unfortunate timing could produce errors (where MetricsMonitor._process would be flipped to None, but some code in a different thread would try to access its attribute such as the name). 
Testing
-------
Checklist
-------
=> chore(sdk): exercise extra caution when starting asset monitoring threads

tests/pytest_tests/unit_tests/test_step_prepare.py, wandb/filesync/step_prepare.py, wandb/sdk/internal/system/assets/interfaces.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/wandb_artifacts.py
Possible solution where we allow as many schedulers as we allow max_jobs, counted separately.
If a user specifies nothing, we would allow 1 scheduler and 1 job. 
If a user specifies -1, we would allow inf schedulers and inf jobs. 
if a user specifies 4, we would allow 4 schedulers AND 4 jobs.
=> chore(launch): let max_schedulers shadow max_jobs, 1:1 relationship

CONTRIBUTING.md, tools/loop.sh
Description
-----------
Update a bunch of references to files that have moved, e.g. `tests/test_sender.py` to `tests/pytest_tests/system_tests/test_sender.py`.
I updated a few other things, but definitely left a lot alone that's still out of date, mostly just because I'm unfamiliar with it myself.
Testing
-------
No tests, documentation-only change.
Checklist
-------
=> docs(sdk): update references to test file locations in documentation

pyproject.toml, tools/setup_dev_environment.py
Fixes WB-11443
Description
-----------
Adds a build system section to workaround an issue introduce by setup tools (in version 64.0.0). The change broke the editable mode. 
Pinning the version based on the discussion here: https://github.com/pypa/setuptools/issues/3548
Testing
-------
tested locally on my machine and was able to work in editable mode with this change (with the latest version of pip)
Checklist
-------
=> build(sdk): fix editable mode with latest version of pip

.pre-commit-config.yaml, pyproject.toml, tests/standalone_tests/grpc_client.py, wandb/cli/cli.py, wandb/sdk/launch/utils.py
Description
-----------
- add the "UP" ruleset to Ruff's configuration to replace pyupgrade
- fix 3 lint errors that would otherwise appear
- disable the warnings that require 3.7 syntax
- remove commented-out isort block in pre-commit (ruff gets us this basically for free!)
- remove pyupgrade in pre-commit now that ruff handles that too
- upgrade black in pre-commit and let it check Jupyter notebooks*
\* mostly just so I stop being annoyed by the warning that there are ipynb files it can't check 
Checklist
-------
=> chore(sdk): add ruff rules to replace pyupgrade

.gitignore, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py, tests/pytest_tests/unit_tests_old/test_wandb_artifacts.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_run.py
Fixes WB-NNNN
Description
-----------
Define `ArtifactNotLoggedError` and raise it rather than a generic `ValueError` when an attribute that requires a logged artifact is accessed. Minimal change, though it does alter error messages.
Checklist
-------
=> feat(artifacts): raise ArtifactNotLoggedError instead of ValueError

tests/pytest_tests/unit_tests/test_launch/test_environment/test_aws.py, tests/pytest_tests/unit_tests/test_library_public.py, tests/standalone_tests/artifact_load.py, wandb/apis/internal.py, wandb/sdk/launch/agent/agent.py
Description
-----------
#5036 was big enough that a bunch of its changes either got dropped in the merge queue or were overwritten by PRs inflight, so this fixes 12 lint errors that should have been covered by it but weren't. Gotta catch 'em all.
Testing
-------
Small documentation-only changes.
Checklist
-------
=> docs(sdk): fix missed docstring lint errors reported by ruff

wandb/apis/public.py, wandb/sdk/interface/artifacts.py, wandb/sdk/internal/artifacts.py, wandb/sdk/wandb_artifacts.py
Fixes [WB-11904](https://wandb.atlassian.net/browse/WB-11904)
Description
-----------
Just remove the `artifact` parameter and all the places it was provided. It was never used 🙃 
Testing
-------
Waiting for functional testing still, I don't trust how easy this was.
Checklist
-------
[WB-11904]: https://wandb.atlassian.net/browse/WB-11904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(artifacts): remove the artifact from the manifest

mypy.ini, wandb/sdk/interface/artifacts.py, wandb/sdk/interface/interface.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_run.py, wandb/util.py
Fixes [WB-12645](https://wandb.atlassian.net/browse/WB-12645)
Description
-----------
Remove the guard disabling `sdk/inferface/artifacts.py` from mypy checks, and add type hints, casts, and adjust signatures until we can pass typechecking.
Note that this involves a large number of changes in `wandb_artifact.py` as well, and reveals very tight coupling between them (e.g. the artifact cache defined in artifacts.py is imported into wandb_artifacts.py, but wandb_artifacts.py defines the only Artifact subclass that the cache relies on).
Testing
-------
CI. Should be almost no functional change, though there are a few casts added. Code that doesn't pass them should be invalid anyway though (e.g. passing a non-URI string to `add_reference`).
Checklist
-------
[WB-12645]: …
=> style(artifacts): enable typechecking for interface.artifacts and add type hints / casts

.circleci/config.yml, .pre-commit-config.yaml, pyproject.toml, tox.ini, wandb/sdk/internal/artifacts.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/wandb_settings.py
Fixes WB-NNNN
Description
-----------
- Add `ruff` and `ruff-fix` commands to tox
- Make ruff checks part of the code-check CI task
Eventually ruff should be able to replace isort, pyupgrade, and all of the flake8-* checks, but adding this as a parallel check should pave the way for that.
Testing
-------
If this is set up correctly then ruff should emit lint errors in parallel to pyupgrade and isort (and some but not all of flake8 errors). Once we're satisfied with that we can remove the other more expensive linters.
[9ae5d49](https://github.com/wandb/wandb/pull/5028/commits/9ae5d497bdfe94151420541773c48e1c2a4a8533) added in three errors that should have been caught, which they successfully were: [code-check job](https://app.circleci.com/pipelines/github/wandb/wandb/19638/workflows/6b2ef55 …
=> chore(sdk): Add tox sections for ruff check/fix

wandb/sdk/data_types/image.py
It's pretty common to pass `Path` objects around instead of `str`s these days, and as of right now you get a cryptic error, since the SDK tried to parse it as a tensor.
Description
-----------
Allows a user to pass a `Path` in (which can be safely cast to a `str`).
Checklist
-------
=> fix(sdk): Allow pathlib.Path in ImageDataOrPathType

tests/pytest_tests/unit_tests/test_wandb_save.py, wandb/sdk/wandb_run.py
Fixes WB-4898
Fixes #4898
Description
-----------
* Updated the `.save()` method to accept `pathlib.Path` object along with string
* Update typing
* Add test, to verify the functionality
Testing
-------
* Added a test and ran `tox -e py39 -- tests/pytest_tests/unit_tests/test_wandb_save.py` and it completed successfully.
Checklist
-------
=> feat(sdk): update .save method to accept pathlib.Path object

wandb/integration/tensorboard/monkeypatch.py
Description
-----------
This PR disables lazy loading for tensorboard patching, since it causes a regression when using in a notebook environment. 
Testing
-------
Manually :/
Checklist
-------
=> fix(sdk): avoid lazy loading for tensorboard patching

wandb/cli/cli.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
We'll eventually switch to connecting new agents with this `--url` option.  Adding it now so users get a better error message if they attempt to use it on older SDK versions once we release it.
Testing
-------
Checklist
-------
=> docs(launch): Add hidden --url option ahead of implementing the actual feature

wandb/sdk/launch/agent/agent.py
Fixes [WB-12816](https://wandb.atlassian.net/browse/WB-12816)
Description
-----------
Don't just check the image UI for the scheduler placeholder, which can be easily scammed, also check the actual command being run. This ensures local process execution is limited to a `wandb scheduler` command, rather than arbitrary execution. 
[WB-12816]: https://wandb.atlassian.net/browse/WB-12816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): agent extra check when running sweep scheduler local-proc

wandb/sdk/launch/sweeps/scheduler.py
Fixes: [WB-12864](https://wandb.atlassian.net/browse/WB-12864)
Description
-----------
When runs fail before they start, runstatus doesn't change, so we should check the runqueueitem state.
Master:
This branch:
[WB-12864]: https://wandb.atlassian.net/browse/WB-12864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): clean up run when rqi-state is failed

wandb/sdk/launch/_project_spec.py
Slightly modifies the job-not-found error to include the format: `<entity>/<project>/<name>:<alias>"`
=> chore(launch): better job not found error msg

wandb/sdk/wandb_run.py
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Removes some ugly term warns on runs running in the launch context. While the underlying behavior is still there, it is unused. 
Testing
-------
Checklist
-------
=> fix(launch): Remove confusing warning when using artifacts in launch context

wandb/sdk/launch/builder/templates/_wandb_bootstrap.py
Description
-----------
This PR adds an extra index URL for specific pytorch wheels in our launch dependency installer when we encounter frozen dependency strings of the form torch(vision|audio)==0.0.0+cu116 for example.
Testing
-------
I created a job with weird dependency strings https://wandb.ai/bcanfieldsherman/fmnist/artifacts/job/fmnist-cu116/v3 and was able to successfully reinstall the correct dependencies and run with gpu on local container runner. The changes didn't break any old pytest tests and I haven't added any new pytest tests.
Checklist
-------
=> fix(launch): torch installs fixes

tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py, wandb/sdk/internal/artifacts.py, wandb/sdk/internal/sender.py
Supports [WB-12644](https://wandb.atlassian.net/browse/WB-12644)
Description
-----------
`_manifest_json_from_proto` is only used in `sender.py`, so move it there.
Testing
-------
Local/CI
Checklist
-------
[WB-12644]: https://wandb.atlassian.net/browse/WB-12644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(artifacts): move _manifest_json_from_proto to sender.py

wandb/sdk/internal/artifacts.py, wandb/sdk/internal/sender.py, wandb/sdk/wandb_artifacts.py
Description
-----------
Stops using local/relative imports (`from ..foo import ...`) in favor of absolute imports (`from wandb.sdk.foo import ...`)
Separating out these changes rather than lump them in with my other refactoring PRs.
=> chore(artifacts): use absolute imports

tests/functional_tests/t0_main/debug/sentry_third_party.py, tests/functional_tests/t0_main/debug/t5_sentry_third_party.yea, tests/functional_tests/t0_main/debug/t8_sentry_session_no_finish.py, wandb/analytics/sentry.py
Description
-----------
Issue: if the user does not explicitly call `run.finish()`, a successful sentry session won't always get published, which would screw our success rate stats.
Fixed by adding an atexit hook to the `wandb.analytics.sentry.Sentry` object that ensures the session always gets closed.
Caught by a failed test in nightly: https://app.circleci.com/pipelines/github/wandb/wandb/20776/workflows/c2960373-84cd-43ab-af96-54459ef6f813/jobs/499038
Also cleaned up the adjacent code a bit as I was looking at it :)
Testing
-------
- Verified using the junk project in sentry that it now works correctly!!
- Removed the now unnecessary long sleep in the relevant yea tests.
- Test that 2 sentry sessions are created both when the calls run.finish() and when doesn't do so.
- Added the test …
=> fix(sdk): ensure sentry sessions are always ended

tests/pytest_tests/system_tests/test_core/test_wandb.py, wandb/sdk/data_types/utils.py
Description
-----------
Currently logging `wandb.log({"somekey": ""})` sends the value of somekey to gorilla as `[]` instead of `""`. This fixes that and adds a test. 
Testing
-------
How was this PR tested? Unit test
Checklist
-------
=> fix(sdk): Ensure empty string logs as empty string and not list

wandb/integration/keras/callbacks/model_checkpoint.py
Description:
There used to be two copies of `save_weights_only` and its description, now there is only one.
Fixes WB-NNNN
Fixes #NNNN
Description
-----------
Fixes this ticket:
https://github.com/wandb/wandb/issues/5241
This pr removes duplicate entries of docstring for `save_weights_only` located in `wandb/wandb/integration/keras/callbacks/model_checkpoint.py`. There used to be two entries and now there is one. 
Testing
-------
- This pr wasn't tested since, it only edits the documentation in this case
Checklist
-------
- [✓] Include reference to internal ticket "Fixes WB-NNNN" and/or GitHub issue "Fixes #NNNN" (if applicable)
- [✓] Ensure PR title compliance with the [conventional commits …
=> chore(sdk): removing duplicate docstring

wandb/sdk/internal/internal_api.py, wandb/sdk/internal/settings_static.py, wandb/sdk/lib/_settings_toposort_generated.py, wandb/sdk/wandb_settings.py
Description
-----------
Provide a temporary way to pass extra headers to the GraphQL Client init.
TODO: Shall be refactored once the Settings refactor is complete.
Testing
-------
Checklist
-------
=> feat(sdk): allow setting of extra headers for the gql client

tests/pytest_tests/unit_tests/test_system_metric/test_system_metrics_open_metrics.py, wandb/sdk/internal/system/assets/open_metrics.py, wandb/sdk/wandb_settings.py
...in SystemMonitor
Description
-----------
This PR slightly changes the meaning of the `_stats_open_metrics_filters` setting: it will now assume that the OpenMetric metric name is prefixed with the OM endpoint name, in line with how the consumed metrics are displayed in the app (`<endpoint name>.<metric name>...`). For example,
```python
run = wandb.init(
project="dcgm",
settings=wandb.Settings(
_stats_sample_rate_seconds=1,
_stats_samples_to_average=1,
_stats_open_metrics_endpoints={
"node1": "http://172.0.0.1:9400/metrics",
"node2": "http://172.0.0.2:9400/metrics",
"node3": "http://172.0.0.3:9400/metrics",
},
_stats_open_metrics_filters={
"node[1-2].DCGM_FI_DEV_(POWER_USAGE|MEM_COPY_UTIL|TOTAL_ENERGY_CONSUMPTION)": {
"gpu": "[0,1]",
},
"node3.DCGM.*": {},
},
),
)
```
The first filter …
=> feat(sdk): namespace filters applied by OpenMetrics endpoint consumer

wandb/analytics/sentry.py, wandb/sdk/data_types/plotly.py, wandb/sdk/data_types/utils.py
Description
-----------
Revert "weird mypy demands"
This reverts commit https://github.com/wandb/wandb/commit/12e2905c311203dba7bd2669443e5a91f7cfdbf8.
Revert "safer access to settings attributes in sentry"
This reverts commit https://github.com/wandb/wandb/commit/b440c0be9d750445949939145bcc66b7b41e4ec9.
Testing
-------
Checklist
-------
=> revert(sdk): accidental checkin of two fixes without a PR

wandb/sdk/launch/builder/kaniko_builder.py
Fixes [WB-12913](https://wandb.atlassian.net/browse/WB-12913)
Description
-----------
Set `backoff_limit` to 0 when attempting to build a Kaniko job
[WB-12913]: https://wandb.atlassian.net/browse/WB-12913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(launch): Disable kaniko builder retry

wandb/sdk/data_types/image.py, wandb/sdk/internal/system/assets/open_metrics.py, wandb/sdk/lib/hashutil.py, wandb/sdk/wandb_artifacts.py
Fixes [WB-13199](https://wandb.atlassian.net/browse/WB-13199)
Description
-----------
For Python >=3.9, FIPS-compliant Python needs `usedforsecurity=False` in order to allow the use of MD5 hashes.
Testing
-------
Checklist
-------
[WB-13199]: https://wandb.atlassian.net/browse/WB-13199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(sdk): pass usedforsecurity=False when possible for FIPS support

tools/build_launch_agent.py, wandb/docker/__init__.py, wandb/sdk/launch/builder/docker_builder.py
Fixes
-----
Fixes [WB-11692](https://wandb.atlassian.net/browse/WB-11692)
Description
-----------
Allow specifying the build platform using the `platform` key when using the Docker builder. See below for an example agent config that sets this value.
Testing
-------
- Start an agent on a Mac M1 with config:
```
{
"builder": {
"type": "docker",
"platform": "windows/amd64"
}
}
```
- Give the agent a job, confirm the job fails to start
- Start another agent, replacing `windows/amd64` with `linux/arm64`
- Give the agent a job and confirm it succeeds
[WB-11692]: https://wandb.atlassian.net/browse/WB-11692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(launch): Allow platform override for docker builder

tests/pytest_tests/unit_tests/test_launch/test_builder/test_build.py, wandb/sdk/launch/builder/build.py
Fixes
-----
Second half of [WB-13355](https://wandb.atlassian.net/browse/WB-13355), [PR](https://github.com/wandb/core/pull/14342)
Description
-----------
Make use of `_wandb_api_key` if present, to override the `WANDB_API_KEY` environment variable.
Testing
-------
Added unit test
[WB-13355]: https://wandb.atlassian.net/browse/WB-13355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): Use _wandb_api_key to set env var

tests/pytest_tests/unit_tests/test_launch/test_agent/test_agent.py, wandb/sdk/launch/agent/agent.py
Fixes
-----
Fixes [WB-13380](https://wandb.atlassian.net/browse/WB-13380)
Description
-----------
Add a "secure mode" key that can be supplied to an agent. If present, it locks some potentially vulnerable pod and container configs to arbitrary code execution. Attempting to override those configs raises a validation error.
Testing
-------
A unit test was added to make sure safe mode raises an error when specific keys are present.
[WB-13380]: https://wandb.atlassian.net/browse/WB-13380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(launch): Add secure mode for launch agent

setup.py, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py, tests/pytest_tests/unit_tests/test_artifacts/test_storage.py, wandb/sdk/interface/artifacts/artifact.py, wandb/sdk/interface/artifacts/artifact_storage.py, wandb/sdk/wandb_artifacts.py
Fixes WB-13212
Added Azure storage handler to allow adding references to Azure storage blobs to artifacts.
Azure storage blobs summary:
- Organized into storage accounts, containers, blobs
- Example blob URLs:
- https://tmpszymon.blob.core.windows.net/tmp-szymon/test.txt
- https://tmpszymon.blob.core.windows.net/tmp-szymon/test.txt?versionId=2023-04-11T18:55:32.1517815Z
- https://tmpszymon.blob.core.windows.net/tmp-szymon/test.txt?snapshot=2023-04-11T21:27:44.5716794Z
- [Quickstart](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python)
- [API](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob)
- Created `tmpszymon/tmp-szymon` container in Azure with:
- `a/b/test.txt`
- `test.txt` with multiple versions
- Started a Jupyter …
=> feat(artifacts): add Azure storage handler in SDK

wandb/apis/public.py
Fixes WB-13393
When creating an artifact, we default to project "uncategorized". When fetching an artifact, we default to project "None".
I changed the latter to also use "uncategorized".
- Started a Jupyter notebook:
```
$ tox -e py39 --notest
$ source .tox/py39/bin/activate
$ pip install jupyter
$ jupyter notebook
```
- Fetched an artifact from "uncategorized" project:
=> fix(artifacts): default to project "uncategorized" instead of "None" when fetching artifacts

wandb/data_types.py
Description
-----------
Adding functionality to wandb.Table to access the contents of the table though a pandas DataFrame. This is useful not to rely on the wandb.joinTable functionality,...
Testing
-------
Not tested. I was hoping you have your pipelines set up ;)
Checklist
-------
=> feat(media): add method to convert wandb.Table to pandas.DataFrame

wandb/apis/public.py
Fixes WB-12549
Added the ability to create a new draft artifact bootstrapped with an existing artifact.
Note on API design:
I decided to create a new `Artifact` instance instead of modifying an existing instance. Changing the identity of an existing instance would be error prone. Note that we keep references to `Artifact` instances in various places (e.g. [here](https://github.com/wandb/wandb/blob/8f9d25fee7df3cb5bd52a5d732d72486d306cedd/wandb/apis/public.py#L4127) and [here](https://github.com/wandb/wandb/blob/a87fb976c939052656e2cf6c1bcf885d03afdfbb/wandb/sdk/data_types/base_types/wb_value.py#L43)) and assume their identity doesn't change over time.
=> feat(artifacts): Artifacts: allow saved artifacts to be modified and logged as a new version

tests/pytest_tests/unit_tests_old/test_wandb_run.py, wandb/apis/public.py, wandb/sdk/interface/artifacts/artifact.py, wandb/sdk/wandb_artifacts.py, wandb/sdk/wandb_run.py, wandb/util.py
Fixes WB-13706
- added `artifact.source_entity`
- added `artifact.source_project`
- added `artifact.source_name`
- made `artifact.source_version` raise `ArtifactNotLoggedError` instead of returning `None` when the artifact is not saved. This is consistent with the other properties, in particular `artifact.version`.
See discussion [here](https://weightsandbiases.slack.com/archives/C04MNBGJDBN/p1683275620778489).
=> feat(artifacts): Artifacts: add .source_entity et al.

mypy.ini, tests/pytest_tests/unit_tests/test_artifacts/test_storage.py, tests/pytest_tests/unit_tests_old/test_public_api.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_download_logger.py, wandb/sdk/artifacts/artifact_manifest_entry.py, wandb/sdk/artifacts/downloaded_artifact_entry.py, wandb/sdk/artifacts/lazy_artifact.py, wandb/sdk/artifacts/local_artifact.py, wandb/sdk/artifacts/public_artifact.py, wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py, wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py, wandb/sdk/artifacts/storage_policy.py, wandb/sdk/data_types/helper_types/classes.py, wandb/sdk/data_types/image.py, wandb/sdk/data_types/saved_model.py
Fixes WB-13437
Type checking is disabled under `wandb/apis/`. I moved code from there in https://github.com/wandb/wandb/pull/5534. In this PR, I added missing type annotations and enabled type checking for the code I moved.
mypy in CI
=> refactor(artifacts): Artifacts: add missing type annotations

tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py, wandb/sdk/launch/sweeps/scheduler.py
Fixes
-----
https://wandb.atlassian.net/browse/WB-13456
Description
-----------
Sweeps that end without the agent hitting the AgentHeartbeat path in gorilla end up stuck in "running" or starting state, this manually sets the sweep state to FINISHED when the sweep exits.
=> chore(sweeps): set sweep state on scheduler exit

wandb/cli/cli.py
=> chore(sweeps): correct typo in method assignment

wandb/util.py
Fixes WB-13942
We use `multiprocessing.util.LazyLoader` to import modules lazily, i.e. when an attribute of the module is accessed. However, `LazyLoader` is not thread-safe: while one thread is loading the module, another thread will see a partially-loaded module. I replaced it with a custom implementation that is thread-safe.
Before:
After:
=> fix(sdk): improve lazy import to be thread-safe

wandb/sdk/artifacts/artifact.py
Fixes WB-14064
- the SDK allows alphanumeric, dash, underscore, dot characters in artifact name ([code](https://github.com/wandb/wandb/blob/936aaf58f8e2d400894bb3997ead2809d1783783/wandb/sdk/artifacts/artifact.py#L148))
- the server allows any characters except slash, colon ([code](https://github.com/wandb/core/blob/c330e0fb922fbff9ce8f7da172a87c93cefc1df3/services/gorilla/validate.go#L77))
- after https://github.com/wandb/wandb/pull/5454 we started validating the name when loading an artifact in the SDK. This means that some artifacts created via the web app could not be loaded. In this PR, I'm removing that validation.
- created an artifact `my_artifact` from the SDK
- renamed the artifact to `my artifact 🙀` from the web app
- loaded the artifact from the SDK
=> fix(artifacts): don't validate name of existing artifacts

wandb/sdk/artifacts/storage_handlers/azure_handler.py, wandb/sdk/lib/_settings_toposort_generated.py, wandb/sdk/wandb_settings.py
Fixes WB-14083
Azure blob storage has two authorization methods: Role-Based Access Control (RBAC) and access keys ([docs](https://learn.microsoft.com/en-us/azure/storage/blobs/authorize-data-operations-portal)). We currently support RBAC, this PR adds support for using access keys.
- Made sure default authorization works:
- Logged out of Azure with `$ az logout` and made sure authorization with access key works:
=> feat(artifacts): support access key for Azure references

tests/pytest_tests/unit_tests_old/utils/mock_server.py, tox.ini, wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_manifest_entry.py, wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Fixes WB-13972
Before:
- 32 threads downloading files 1 at a time; we query gorilla which does a bunch of MySQL queries, generates a download URL and redirects to it ([code](https://github.com/wandb/core/blob/13079312727145231965f133f9a46e4a150fdd88/services/gorilla/api/handler/artifacts.go#L140)).
After:
- 1 thread getting download URLs for files in 5k batches; waiting for download threads to catch up (at most 5k files in download queue) before fetching the next batch
- 64 threads downloading files 1 at a time using the URL fetched above, falling back to getting the URL using the old method
Benchmark: downloading a 1 million file artifact went down from 5h 38min to 1h 11min ([thread](https://weightsandbiases.slack.com/archives/C04MNBGJDBN/p1686304602511269)).
Depends on server-side …
=> perf(artifacts): get download URLs in batches

wandb/data_types.py, wandb/sdk/data_types/trace_tree.py
Fixes WB-13943
Exposed `WBTraceTree` as `data_types.WBTraceTree` so that we can generate docs for it automatically.
Tested in https://github.com/wandb/docugen/pull/32
=> docs(sdk): expose WBTraceTree as data_types.WBTraceTree

tests/pytest_tests/unit_tests/test_artifacts/test_storage.py, tests/pytest_tests/unit_tests/test_saved_model.py, tests/pytest_tests/unit_tests/tests_launch/test_job.py, wandb/apis/public.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_manifest_entry.py, wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py, wandb/sdk/wandb_run.py
Fixes WB-13943
There's no way to make a method public to the rest of the wandb package, but not outside of it. I made methods that should not be exposed to users private. This means that we need to be more careful when modifying private methods, because they might be called by other classes in the wandb package.
Tested in https://github.com/wandb/docodile/pull/314
=> refactor(artifacts): change artifact methods and attributes to private

wandb/sdk/artifacts/artifact.py
Fixes WB-13972
This fixes a bug introduced in https://github.com/wandb/wandb/pull/5692. I assumed `Artifact.files()` in GraphQL doesn't include references, but it does.
Downloaded an artifact with 500 references, made sure the counter correctly said 500 / 500:
=> fix(artifacts): fix handling of references when downloading

wandb/cli/cli.py, wandb/sdk/internal/internal_api.py
Prod defaults to the entity passed in, which in many cases is the team entity. Update viewer api call to get username, and use that if available.
=> fix(sweeps): correct launch sweep author to personal username

tests/pytest_tests/unit_tests/test_saved_model.py, tests/pytest_tests/unit_tests_old/utils/mock_server.py, tox.ini, wandb/sdk/artifacts/artifact.py
Fixes WB-14295
Each artifact has a different set of aliases in each collection it's a member of. We fetch aliases as (collection name, alias) pairs and filter to those where the collection name is the same as the one used to fetch the artifact. However, comparing by name is not enough, since there can be collections with the same name in different projects. We have to compare collections by their (entity, project, name).
Corresponding yea-wandb PR: https://github.com/wandb/yea-wandb/pull/116
In 0.15.4:
After an assert that there is exactly one vN alias was added in https://github.com/wandb/wandb/pull/5454:
After this PR:
=> fix(artifacts): fix collection filtering when getting aliases

.vscode/settings.json
Fixes WB-14418
flake8 config was removed in https://github.com/wandb/wandb/pull/5812. In this PR I've disabled it in Visual Studio Code.
Opened a Python file, made sure there are no more errors like
> line too long (85 > 79 characters) flake8(E501)
=> chore(sdk): disable flake8 in Visual Studio Code

tests/standalone_tests/artifact_object_reference_test.py
Fixes WB-14400
Since `imageio==2.28` ([changes](https://github.com/imageio/imageio/compare/v2.27.0...v2.28.0)), this code:
```
import wandb
wandb.Video(np.random.randint(0, high=255, size=(4, 1, 10, 10), dtype=np.uint8))
```
started giving an error:
```
File "/Users/szymon/wandb/wandb/sdk/data_types/video.py", line 128, in __init__
self.encode()
File "/Users/szymon/wandb/wandb/sdk/data_types/video.py", line 149, in encode
write_gif_with_image_io(clip, filename)
File "/Users/szymon/wandb/wandb/sdk/data_types/video.py", line 45, in write_gif_with_image_io
writer.append_data(frame)
File "/Users/szymon/.pyenv/versions/venv_dev/lib/python3.9/site-packages/imageio/v2.py", line 226, in append_data
return self.instance.write(im, …
```
=> test(artifacts): fix video fixture

wandb/sdk/artifacts/artifact.py
Fixes WB-14400
In https://github.com/wandb/wandb/pull/5533 we changed the behavior or `artifact.name` to return the name of the secondary (portfolio) collection instead of the name of the primary (sequence) collection. This changed the default download location as well. In this PR, I modified the default download location to use `artifact.source_name` to go back to the previous behavior.
- Modified `S3Handler.versioning_enabled` to `return False`; otherwise I was getting a permission error.
- Ran the tests:
```
$ cd empty_dir
$ python ~/wandb/tests/standalone_tests/artifact_object_reference_test.py
1/19 Complete
2/19 Complete
3/19 Complete
4/19 Complete
5/19 Complete
6/19 Complete
7/19 Complete
8/19 Complete
9/19 Complete
10/19 Complete
11/19 Complete
12/19 Complete
13/19 Complete
14/19 …
```
=> test(artifacts): fix broken tests

wandb/sdk/internal/sender.py
Fixes WB-14508
Protocol buffers don't support nulls. When we serialize an artifact to protocol buffer [here](https://github.com/wandb/wandb/blob/3d5b63e7e4b89e76d149b9bd2740a437dff1b29e/wandb/sdk/interface/interface.py#L376), `None` description becomes `""`.
When creating an artifact, we check if there is an existing artifact with the same digest. If there is, we don't create a new artifact and return the existing one instead. We also set the artifact properties (description, metadata, aliases) if they're specified. Because we were sending a `""` description when someone didn't set it, we were incorrectly removing the description of the existing artifact.
After this PR, we turn `""` back to `None` before sending the description to the server.
- Created an artifact with description, …
=> fix(artifacts): handle None description correctly

wandb/sdk/launch/agent/agent.py
delete the `sweep_id` from the launch_config, the run should already have it because we are resuming. Without the sweep_id the launch agent will let it run no matter what.
=> chore(launch): special handling for resumed sweep runs

tests/pytest_tests/system_tests/test_sweep/test_sweep_scheduler.py, wandb/cli/cli.py, wandb/sdk/launch/agent/agent.py, wandb/sdk/launch/sweeps/scheduler.py
Fixes
-----
https://weightsandbiases.slack.com/archives/C044BQJCB46/p1691003760557389?thread_ts=1690933174.850759&cid=C044BQJCB46
Description
-----------
Catch comm errors so that we return from the thread process on error, rather than entering infinite loop. Happens when set_sweep_state errors, commonly when the sweep is not found....
Also remove the cling api instantiation, replacing with `InternalApi`. The cling api pre-populates the singleton value, which results in replacing the `WANDB_RUN_ID` that the scheduler relies on when in the local process.
=> chore(sweeps): catch set state error and remove cling api

wandb/sdk/interface/interface.py
Bug where we call an incorrect metadata key, resulting in image jobs manually created NOT rerunning correctly. They run correcty the first time, but then upgrade from "partial" to a full job with **no** image key, resulting in failed job runs after v0. 
Current:
=> fix(launch): manually created image jobs can rerun correctly

wandb/sdk/artifacts/artifact_saver.py, wandb/sdk/internal/internal_api.py, wandb/sdk/launch/create_job.py
Fixes WB-15188
Removing some legacy code from artifact saver:
- labels: the implementation was never finished. I don't think we need labels in addition to aliases, metadata and tags. There are 1146 artifacts with labels with various formats:
- `null`
- `["manually-created"]`
- `{"env":["staging"]}`
- aliases with `collection:alias`: they are no longer allowed
- enable_digest_deduplication: always set to true
Created 3 artifacts. Made sure aliases were correctly set, and the third artifact reused the first artifact.
=> refactor(artifacts): simplify artifact saver

wandb/sdk/artifacts/artifact.py, wandb/sdk/wandb_run.py
https://wandb.atlassian.net/browse/WB-15226
Testing
-------
Ran locally and made sure the warning were showing up accordingly
```
artifact.ttl = None
artifact.link(...) # no warning since the artifact.ttl is disabled anyways
artifact2.ttl = timedelta(days=123)
artifact2.link(...) # warning
artifact3.ttl = wandb.ArtifactTTL.INHERIT
artifact3.link(...) # warning
artifact4.link(...) # warning
```
=> chore(artifacts): better check of when to warn user of ttl disabling after linking

nexus/pkg/artifacts/linker.go, nexus/pkg/artifacts/saver.go
Fixes WB-13717
Moved `ArtifactSaver` and `ArtifactLinker` into separate files.
Created an artifact, observed the artifact saver was correctly called (but failed as before, since it's not fully implemented):
=> refactor(artifacts): split file

wandb/sdk/wandb_run.py
Fixes
-----
https://wandb.atlassian.net/browse/WB-15585
Description
-----------
reduce ttl warning only when there is a ttl set, as opposed to warning pretty much everytime a model is being linked. This takes away potential warning if the TTL is inherited but we prioritize reducing logging clutter
Testing
-------
locally tested
=> chore(artifacts): reduce ttl link warning

wandb/apis/public.py
Fixes WB-15686
Runs can be moved to a different project ([docs](https://docs.wandb.ai/guides/app/features/runs-table#move-runs-between-projects)). When fetching input / output artifacts of a run, we should use the entity & project of the artifact, not the run.
- Created an artifact
- Moved its creator run to a different project
- Fetched the output artifacts of the run
Before:
After:
=> fix(artifacts): don't assume run and its i/o artifacts are in the same project

tests/pytest_tests/system_tests/test_core/test_public_api.py, tests/pytest_tests/unit_tests_old/test_public_api.py, wandb/apis/public.py, wandb/sdk/internal/internal_api.py
Fixes WB-15686
`wandb.Api().run(run_name).log_artifact(artifact)` has been broken since July 2021 ([blame](https://github.com/wandb/wandb/pull/2325/files#r1334892771)). I fixed it by making `clientID` optional in the GraphQL query.
Also:
- raise an error if the run and artifact are in different projects, instead of silent no-op
- use `.source_name` instead of `.name`
Before:
After:
Tried to log an artifact from a different project, made sure I get an error:
=> fix(artifacts): fix wandb.Api().run(run_name).log_artifact(artifact)

nexus/api/graphql/genqlient.yaml, nexus/internal/gql/gql_gen.go
Fixes WB-15188
Fixed GraphQL type mapping: `Int64` in GraphQL should be mapped to `int64` in Go.
Generated GraphQL code, made sure there are no build errors:
```
$ scripts/generate-graphql.sh
```
=> fix(sdk): fix graphql type mapping

nexus/internal/uploader/upload_manager.go, nexus/internal/uploader/upload_task.go, nexus/internal/uploader/uploader_default.go, nexus/pkg/artifacts/saver.go
Fixes WB-15188
There was no way to know whether an upload task succeeded or not. I made each task store the `error` (if any), and allow passing in a callback to execute when the task is finished (either succeeded or failed).
Tested in https://github.com/wandb/wandb/pull/6296
=> refactor(sdk): allow uploader to communicate errors back to the caller

wandb/sdk/lib/gitlib.py
Description
-----------
Spent a good while trying to figure out why clearing my `tmp_path` with `pytest tests/loggers/test_wandb_logger.py -x -s -o tmp_path_retention_policy=failed` errors out in the mosaicml [composer tests](https://github.com/mosaicml/composer/blob/9977bd60ea8f5e745b9b8f02eba0a3360900dd9c/tests/loggers/test_wandb_logger.py#L45-L46) whereas `pytest tests/loggers/test_wandb_logger.py -x -s -o tmp_path_retention_policy=all` passes. 
Here is the error log:
```
Thread HandlerThread:
File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
self._run()
File "/Users/chuck.tang/miniconda3/lib/python3.11/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run …
```
=> Improve error handling for gitlib for FileNotFoundErrors

nexus/pkg/server/resume.go, nexus/pkg/server/sender.go, nexus/pkg/utils/utils.go
Fixes WB-15188
Protocol buffers don't support null, so missing values are stored as zero. We often want to convert zero back to null. There was an existing `emptyAsNil` function for this. I generalized it to work for any type (instead of just string) and moved it to a reusable `pkg/utils` package.
Tested in https://github.com/wandb/wandb/pull/6296
=> refactor(sdk): create NilIfZero util

nexus/pkg/server/connection.go
Fixes WB-15188
- increased max message size passed to the background process from 64 MB to 2 GB
- added error handling (before we got stuck on errors)
- Created an artifact with ~120 MB manifest, made sure it got saved instead of getting stuck.
- Changed the max message size back to 64 MB and made sure we `panic`ed with an informative error message.
=> fix(sdk): increase max message size, handle errors

wandb/sdk/artifacts/storage_handlers/gcs_handler.py, wandb/sdk/artifacts/storage_handlers/s3_handler.py
Fixes WB-13717
Removing a function that was added in the [original artifacts PR](https://github.com/wandb/client-ng/pull/30) and never used.
Grepped for `_content_addressed_path`.
=> chore(artifacts): remove dead code

tests/pytest_tests/system_tests/conftest.py, tests/pytest_tests/system_tests/test_artifacts/test_misc2.py, tests/pytest_tests/system_tests/test_core/test_wandb_init.py, wandb/testing/relay.py
Fixes WB-13808
Artifacts tests in the `wandb` repo are a mess. As a result, we don't write tests and spend a lot of time keeping the existing ones up to date. I'm on a mission to clean this up in WB-13808.
First, I want to consolidate our tests into the [system_tests directory](https://github.com/wandb/wandb/tree/main/tests/pytest_tests/system_tests/test_artifacts) and move each test to a file corresponding to the code under test. This will solve a number of problems:
- when you look at a file, it will be clear where to look for its tests, and vice versa
- we will no longer use the mock server, which was a pain
- all tests will be run the same way
Note that terminology like "unit" vs "integration" vs "system" vs "functional" etc. is arbitrary, see …
=> test(artifacts): move tests from unit_tests_old to system_tests

wandb/sdk/data_types/image.py
, otherwise using matplotlibs`s pgf backend yields an error when reading with PIL.
Testing
-------
In my project, yes; otherwise no.
=> saving mlp figure to buffer and reading with PIL should specify format

wandb/apis/public.py
Description
-----------
Fix an error message suggesting to use the `wandb artifact put` command.  Was saying `artifacts`
Testing
-------
Error message fix, no impact on functionality.
=> docs(public-api): Fix suggested command for uploading artifacts

tests/pytest_tests/system_tests/test_artifacts/test_misc2.py, tests/pytest_tests/system_tests/test_artifacts/test_object_references.py, tests/pytest_tests/unit_tests/test_artifacts/test_storage.py, tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py, tests/pytest_tests/unit_tests_old/test_artifacts/test_artifact_public_api.py, tests/standalone_tests/dsviz_demo.py, wandb/data_types.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_manifest_entry.py, wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py, wandb/sdk/data_types/base_types/media.py, wandb/sdk/data_types/base_types/wb_value.py, wandb/sdk/data_types/helper_types/image_mask.py, wandb/sdk/data_types/html.py, wandb/sdk/data_types/image.py, wandb/sdk/data_types/saved_model.py, wandb/sdk/interface/interface.py
Fixes WB-16027
`Artifact.get_path(name)` returns an `ArtifactManifestEntry`, it should be called `get_entry(name)`.
=> refactor(artifacts): rename get_path() to get_entry()

wandb/sdk/launch/runner/kubernetes_runner.py
Description
-----------
I removed all env variables from the launch-queue config, and that resulted in the following spec:
```
spec:
template:
spec:
containers:
- env: null
resources:
requests:
cpu: 40000m
memory: 40Gi
```
Then, when I ran a job, I saw the following error:
```
123983 05:23:09pm wandb: ERROR launch: Error running job: Traceback (most recent call last):
123984 05:23:09pm wandb: ERROR   File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/agent/agent.py", line 534, in thread_run_job
123985 05:23:09pm wandb: ERROR     self._thread_run_job(
123986 05:23:09pm wandb: ERROR   File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/agent/agent.py", line 616, in _thread_run_job
123987 05:23:09pm wandb: ERROR     run = backend.run(project, image_uri)
123988 05:23:09pm …
```
=> chore(launch): Launch runner fails when env is null

core/pkg/artifacts/downloader.go, core/pkg/utils/files.go, core/pkg/utils/hash.go, tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py
Fixes WB-15159
Modified artifact downloader in Nexus to only skip files if their digest matches.
```
$ nox -s build-core install-core
$ pytest tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts_full.py::test_check_changed_artifact_then_download
```
=> fix(artifacts): only skip file download if digest matches

tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py, tests/pytest_tests/unit_tests/test_artifacts/conftest.py, tests/pytest_tests/unit_tests/test_artifacts/test_storage.py, tests/pytest_tests/unit_tests/test_artifacts/test_wandb_artifacts.py, wandb/cli/cli.py, wandb/sdk/artifacts/artifact.py, wandb/sdk/artifacts/artifact_file_cache.py, wandb/sdk/artifacts/artifact_instance_cache.py, wandb/sdk/artifacts/storage_handlers/azure_handler.py, wandb/sdk/artifacts/storage_handlers/gcs_handler.py, wandb/sdk/artifacts/storage_handlers/http_handler.py, wandb/sdk/artifacts/storage_handlers/local_file_handler.py, wandb/sdk/artifacts/storage_handlers/s3_handler.py, wandb/sdk/artifacts/storage_handlers/wb_artifact_handler.py, wandb/sdk/artifacts/storage_handlers/wb_local_artifact_handler.py, wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py
Fixes WB-13717
In https://github.com/wandb/wandb/pull/6171 we split artifacts cache into two modules: one for caching `Artifact` instances and one for caching artifact files. Here, I'm renaming the modules to make this more clear:
- "artifact cache" -> "artifact instance cache": caches `Artifact` instances
- "artifacts cache" -> "artifact file cache": caches artifact files
CI
=> refactor(artifacts): rename cache modules

wandb/apis/public/__init__.py, wandb/apis/public/api.py, wandb/apis/public/artifacts.py, wandb/apis/public/projects.py
Fixes WB-16676
- renamed `ProjectArtifactTypes` -> `ArtifactTypes`; removed unused `name` param
- renamed `ProjectArtifactCollections` -> `ArtifactCollections`
- renamed `ArtifactVersions` -> `Artifacts`
- reordered
- added `Api.artifacts()`, deprecated `Api.artifact_versions()`; changed to create `Artifacts` directly
- added `Api.artifact_collections()`, `Api.artifact_collection()`
=> refactor(artifacts): clean up public API

tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py, wandb/sdk/artifacts/storage_handlers/s3_handler.py
Description
-----------
- Fixes [WB-16491](https://wandb.atlassian.net/browse/WB-16491)
- Fixes https://github.com/wandb/wandb/pull/6759
Linked PR introduced a bug where `hasAttr(obj, 'e_tag')` throws an exception instead of returning the assumed boolean for s3's `ObjectVersion`. This PR removes the additional if-else block from `_etag_from_obj()`, and gets the etag for the ObjectVersion in place. 
Testing
-------
Same as https://github.com/wandb/wandb/pull/6759
[WB-16491]: https://wandb.atlassian.net/browse/WB-16491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(artifacts): revert #6759 and read object version etag in place 

wandb/integration/ultralytics/bbox_utils.py, wandb/integration/ultralytics/callback.py, wandb/integration/yolov8/yolov8.py
On ModuleNotFound exception from ultralytics.yolo.utils try from ultralytics.utils instead.
Description
-----------
- Fixes #6740
- Fixes #6566
A recent version of ultralytics refactored the module `ultralytics.yolo.utils` to `ultralytics.utils`. This PR imports from the latter if the former raises a ModuleNotFoundError.
Testing
-------
This function is already covered in https://github.com/wandb/wandb/blob/main/tests/functional_tests/t0_main/ultralytics/test_ultralytics_detection.py .
This PR should improve compatibility with ultralytics > 8.0.186
=> fix(integrations): Handle ultralytics utils import refactor

tests/pytest_tests/system_tests/test_launch/test_launch_kubernetes.py, tests/pytest_tests/unit_tests/test_launch/test_runner/test_kubernetes.py, wandb/sdk/launch/runner/kubernetes_monitor.py, wandb/sdk/launch/runner/kubernetes_runner.py
Description
-----------
- Fixes WB-16596
- Fixes #NNNN
This PR adds logic in the launch kubernetes monitor so that any job deleted while in a non terminal state will be recognized as failed. There is also a bad regression fixed in here and caused by https://github.com/wandb/wandb/pull/6730
Testing
-------
=> fix(launch): recognize deleted k8s jobs as failed

wandb/sdk/launch/runner/local_container.py
Description
-----------
- Fixes [WB-16970](https://wandb.atlassian.net/browse/WB-16970)
For non-image jobs using the local container runner, we ignore anything passed in through the `args` override since we assume the args have been built into the image's entrypoint in the build step. This is not the case, so the args should be included in the run step.
Testing
-------
- Start an agent polling a Docker queue with `builder: docker`
- Submit [this job](https://wandb.ai/tim-hays/debugging/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEzMDg2NzIyMQ==/runs/latest) to the queue, which prints the passed in command line args. Include overrides for args and entrypoint
- Confirm that the args are present
[WB-16970]: https://wandb.atlassian.net/browse/WB-16970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> fix(launch): Local container runner doesn't ignore override args

tests/pytest_tests/system_tests/test_core/test_sync_tb.py, tests/pytest_tests/unit_tests/test_library_public.py, tests/pytest_tests/unit_tests/test_wandb_config.py, wandb/sdk/lib/config_util.py, wandb/sdk/wandb_config.py, wandb/sdk/wandb_run.py
Description
-----------
- Fixes WB-16967
This PR ensures that wandb run configs generated by sweeps and launch runs are merge-updated into user provided configs, instead of updated at the top level only. This ensures that nested parameters are properly handled in sweep configs and fixes the following situation: 
--- 
Right now, if you init a run with config: 
```python
wandb.init(config={'path': {'to': {'overwrite': 'foo', 'keep': 'bar'}}})
```
Then if the config generated by your current iteration of a sweep looks like this: 
```
{'path': {'to': {'overwrite': 'baz'}}}
```
Then your final config will look like this: 
```
{'path': {'to': {'overwrite': 'baz'}}}
```
When instead it should look like this:
```
{'path': {'to': {'overwrite': 'baz', 'keep': 'bar'}}}
```
This …
=> fix(sdk): merge-update config with sweep/launch config

.circleci/config.yml, core/internal/data_types/data_types_test.go, noxfile.py, wandb/sdk/launch/runner/local_container.py
What does the PR do? Solves the following problem:
Problem: local-testcontainers are not published on docker hub and therefore recycled after a month due to our storage policy. But we still want to test the SDK against older versions.
Testing
-------
=> ci(sdk): store local-testcontainer's of local server releases
